public/components/eui-loader.js
public/controllers/management/management.js
public/controllers/management/monitoring.js
public/templates/management/monitoring/main.html
public/templates/management/monitoring/monitoring.html

Hi team!
This PR close https://github.com/wazuh/wazuh-kibana-app/issues/2538

Adds a message to the cluster view when the user does not have permission

---

scripts/generate-api-4.0-info/generate-api-4.0-info.js
util/api-request-list.json

Hi team,
- Fix generate script with missing body parameters without an exported `name` property
- Update API info

[4.0-7.9] Fix and update API info:

---

public/components/health-check/health-check.tsx
public/components/health-check/lib/check-kibana-settings.ts
public/components/health-check/lib/index.ts
public/react-services/index.ts
public/services/resolves/get-config.js
public/utils/config-equivalences.js
server/lib/initial-wazuh-config.js

Hi team, 
This PR adds a new task to check the value of Kibana's "metaField" setting and change its value.
close #2524

Added a new task to the health-check.

---

public/components/settings/configuration/components/bottom-bar.tsx
server/lib/update-configuration.js

Hello team,
-  Fix app configuration cache after updating it in WUI in:
- Frontend-side
- Server-side
close #2534

[4.0-7.9] Fix app configuration cache

---

public/less/common.less

Added css rule to truncate discover field details

---

public/react-services/generic-request.js
public/react-services/wz-request.js
public/utils/index.ts
public/utils/odfe-utils.ts

Reload the page when the session has expired

---

public/components/security/main.tsx
public/components/wz-menu/wz-menu-security.js
public/components/wz-menu/wz-menu.js
public/redux/actions/securityActions.js
public/redux/reducers/rootReducers.js
public/redux/reducers/securityReducers.js

Hello team, this PR resolves:
- Current section is not highlighted in the main Menu
closes [#2483](https://github.com/wazuh/wazuh-kibana-app/issues/2483)

[4.0-7.9] [#2483] Fix current selected security section is not highlighted in the menu

---

package.json

Hi team!
This PR close https://github.com/wazuh/wazuh-kibana-app/issues/2568

Adapt kibana version to v7.9.3

---

public/components/settings/configuration/components/categories/components/category/components/field-form.tsx

- Array editor looks bad on Settings/Editor with certain resolutions
Closes #2584

[4.0-7.9] [BUGFIX] Fixed missing width prop on array editor

---

public/components/agents/fim/inventory/fileDetail.tsx
public/components/common/util/index.ts
public/components/common/util/truncate-horizontal-components/truncate-horizontal-components.tsx

Hello team, this PR resolves: 
- Enhance render Windows file user permissions:
- Created TruncateHorizontalComponents component
- Removed no used variables component
- Refactorized how to transform the value of file details
closes #2514

[4.0-7.9] Enhance render Windows file permissions

---

public/components/common/modules/modules-helper.js

- Filter popup doesn't open after to pin the filter.
Closes #2581

[4.0-7.9] [BUGFIX] Fixed show popup after to pin a filter

---

public/components/overview/metrics/metrics.tsx

Reverts wazuh/wazuh-kibana-app#2587

Revert "[4.0-7.9] [BUGFIX] Removed unnecessary function call"

---

CHANGELOG.md
public/less/loader.js

Hi team, 
This PR close https://github.com/wazuh/wazuh-kibana-app/issues/2599

Change the method of importing css files

---

CHANGELOG.md
public/components/common/modules/events-enhance-discover-fields.ts

Fixed position icons on events view

---

public/components/security/users/components/users-table.tsx

Hi team! This resolves : 
- The username is undefined in the pop up to confirm delete an user.
Closes #2595

Fixed username undefined on delete user

---

CHANGELOG.md
public/components/visualize/wz-visualize.js
public/controllers/agent/agents-preview.js
public/controllers/agent/components/agents-preview.js
public/controllers/overview/overview.js
server/controllers/wazuh-api.js

- Remove all default agent subtraction from total and active 
Closes #2579

Removed agent substraction from code

---

CHANGELOG.md
public/components/visualize/agent-visualizations.js

- Missing tables on agents reports
Closes #2628

Added missing tables on agents reports

---

CHANGELOG.md
public/components/common/welcome/overview-welcome.js
public/controllers/overview/overview.js

Hi team! I have added a callout when there aren´t any agents that shows the view to add an agent.
This closes [#2564](https://github.com/wazuh/wazuh-kibana-app/issues/2564)

New callout when there aren´t agents available

---

CHANGELOG.md
public/components/visualize/agent-visualizations.js
public/components/visualize/visualizations.js
public/components/visualize/wz-visualize.js
public/templates/agents/visualizations.js
server/integration-files/visualizations/agents/agents-aws.js
server/integration-files/visualizations/agents/agents-gcp.js
server/integration-files/visualizations/agents/agents-mitre.js
server/integration-files/visualizations/agents/agents-virustotal.js
server/integration-files/visualizations/overview/overview-aws.js
server/integration-files/visualizations/overview/overview-gcp.js
server/integration-files/visualizations/overview/overview-mitre.js
server/integration-files/visualizations/overview/overview-virustotal.js

Hi team! This resolves: 
- Add Alerts summary table for PDF reports on all modules
Closes #2632

[FEATURE] [4.0-7.9] Alerts summary for all modules

---

CHANGELOG.md
public/controllers/management/components/management/configuration/utils/wz-fetch.js
public/controllers/management/components/management/status/utils/status-handler.js
public/services/config-handler.js

Hi team!
This PR close https://github.com/wazuh/wazuh-kibana-app/issues/2640

Removed the delay parameter from the restart request

---

CHANGELOG.md
public/components/security/roles-mapping/components/roles-mapping-edit.tsx
public/components/security/roles-mapping/components/roles-mapping-table.tsx
public/components/security/users/components/edit-user.tsx
public/components/security/users/components/users-table.tsx
public/react-services/wz-api-utils.ts
util/constants.js

Hi team, this PR resolves: 
- Created a method to check if an API entity is reserved (ID < 100)
closes #2643

feat(frontend): increase the API entities reserved IDs

---

CHANGELOG.md
public/react-services/saved-objects.js

Hi team! This resolves: 
- The index pattern title is overwritten with its id after refreshing its fields.
Closes #2577

Fixed overwriting index pattern with id

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

Hi team, this PR add the start option when you enroll a new Macos agent in Wazuh app.

Added start option to macos Agents

---

CHANGELOG.md
public/services/resolves/get-config.js
public/utils/config-equivalences.js
server/controllers/wazuh-elastic.js
server/lib/initial-wazuh-config.js
server/lib/update-configuration.js

- Define a prefix for sample alerts indices by a config.
Closes #2593

[FEATURE] Added config for sample alerts prefix

---

CHANGELOG.md
public/components/health-check/health-check.tsx

Hi team,
This PR resolves:
- Fix the check of API and APP version in the health check

fix(fronted): fixed the check of API and APP version in health check

---

CHANGELOG.md
server/monitoring.js

Hi team! This PR changes some logic using username instead user key for the host information.
Closes #2654

change user instances in monitoring.js

---

CHANGELOG.md
public/less/layout.less

- Fullscreen visualizations are overlayed.
Closes #2667

[FIX] Fullscreen visualizations overlayed

---

CHANGELOG.md
README.md
package.json
public/components/agents/fim/inventory/registry-table.tsx
public/components/common/welcome/components/fim_events_table/fim_events_table.tsx
public/components/overview/mitre/components/techniques/techniques.tsx
public/components/security/roles-mapping/components/roles-mapping-table.tsx
public/components/security/roles-mapping/roles-mapping.tsx
public/components/security/users/components/users-table.tsx
public/components/wz-search-bar/lib/q-interpreter.ts
public/controllers/agent/components/register-agent.js
public/controllers/dev-tools/dev-tools.js
public/controllers/management/components/management/ruleset/list-editor.js
public/kibana-integrations/kibana-discover.js
public/react-services/saved-objects.js
public/react-services/wz-user-permissions.test.ts
public/react-services/wz-user-permissions.ts
public/services/resolves/get-config.js
public/styles/component.scss
public/styles/layout.scss
server/controllers/wazuh-api.old.js
server/lib/initial-wazuh-config.js
server/monitoring.js

- Merge last changes of 4.0-7.9 into 4.0-7.10
Partially closes #2727

Merge 4.0-7.10 with 4.0-7.9

---

public/kibana-services.ts
public/plugin.ts
public/react-services/app-state.js

- Improved behavior when cookies cant be setted
Closes #2733

Improved behavior when cookies cant be setted

---

server/routes/wazuh-api.ts

Fixed endpoints that use Modules/All categories/ export formatted (csv)

Fixed endpoint csv

---

public/services/routes.js

Hi team,
This PR contains fixes of the Agents view.

Fix bughunt in agents

---

public/styles/common.scss
public/styles/layout.scss

Hi team, we fix the next steps:
- Removing ' from calcs of codemirror.scss and common.scss

Bugfixing Dev-Tools for 4.0-7.10

---

util/api-request-list.json

Hi team, we have run the generate-api-info script and it has modified api-request-list.json

Changes in api-request-list.json

---

public/components/common/welcome/components/requirement_vis/components/requitement_body/components/requirements_donnut/requirements_donnut.tsx
public/components/wz-menu/wz-menu.js
public/kibana-integrations/discover/application/angular/context/query/index.js
server/start/initialize.ts

- Fixed error with the menu when an Agent is unpinned
- Fixed log error on server when try to delete the index .wazuh-version 
- Fixed d3 error on agent preview

Fixed some bugs related to agent selection 

---

public/components/add-modules-data/sample-data.tsx
public/components/settings/api/add-api.js
public/components/settings/api/api-is-down.js
public/components/settings/configuration/components/header.tsx
public/components/settings/settings-logs/logs.js
public/services/routes.js

Fixed some minor bugs in settings. Closes #2735

Feature/settings 4.0-7.10

---

public/utils/components-os-support.js

Hi team, this PR solves a problem that affected solaris agent and the menu.

Added solaris agent (sunos)

---

kibana.json
public/components/security/roles-mapping/roles-mapping.tsx
public/controllers/management/components/management/configuration/utils/wz-fetch.js
server/controllers/wazuh-api.ts
server/controllers/wazuh-elastic.ts
server/lib/security-factory/factories/default-factory.ts
server/lib/security-factory/factories/opendistro-factory.ts
server/lib/security-factory/factories/xpack-factory.ts
server/lib/security-factory/security-factory.ts
server/start/initialize.ts
server/types.ts
util/constants.ts

Adapt the app to Open Distro for Elasticsearch 1.12.0.
- Fixed Open Distro for Elasticsearch plugin id of the optional plugin in kibana.json
- Adapted `SecurityObj` factory to new ODFE plugin id
- Improved the response of security plugin in `/elastic/current-platform`. Now each security client has a `platform` property with the name.
- Adapted frontend to the new response of `elastic/current-platform`
- Fixed in ODFE security backend client, the response for `getCurrentUser`
- Moved some variables of the initialize job to `contants.ts`.
Closes #2753

4.0-7.10 Adapt Open Distro 1.12

---

public/styles/layout.scss

- https://github.com/wazuh/wazuh-kibana-app/issues/2739#issuecomment-758185133

Fixed top style for fullscreen view

---

public/react-services/pattern-handler.js

Hi teams this PR solves a problem that was caused due to before to refresh the fields of the index pattern we used an endpoint that was removed.

Changed the way index pattern are refreshed

---

server/controllers/wazuh-api.ts

Hi team,
This PR contains fixes for all `PUT` request `content_type`.

Fixed content-type on header for request.

---

public/components/wz-menu/wz-menu.js
public/styles/common.scss

Hi team i change the style of the agent pinned in wz-menu.

Fixed Style of agent pinned in wz-menu

---

public/components/security/roles-mapping/components/rule-editor.tsx
public/components/settings/configuration/components/categories/components/category/components/field-form.tsx
public/components/tools/devtools/devToolsHistory.tsx
public/controllers/management/components/management/configuration/edit-configuration/edit-configuration.js
public/controllers/management/components/management/configuration/util-components/code-editor.js
public/controllers/management/components/management/groups/groups-editor.js
public/controllers/management/components/management/ruleset/ruleset-editor.js
public/services/routes.js

Hi team,
This PR contains fixes for EuiCodeEditor react component.
Affected views: 
- Rules
- Configurations
- Groups
- Decoders

Fix bughunt in Management

---

CHANGELOG.md
public/utils/components-os-support.js

Hi team this PR fixed the unsupported components of solaris agents.
Closes #2773

Fixed unsopported components of solaris

---

CHANGELOG.md
README.md

- Include revision 4015 and organize 4016 changes
- Fixed readme, and Elasticsearcn and Kibana versions
- Added new packages to the readme

4.0-7.10 - Fix changelog and readme.

---

kibana.json
public/plugin.ts
public/types.ts

Hi team this resolves 
- Remove Kibana alert for security https://github.com/wazuh/wazuh-kibana-app/issues/2801#issuecomment-764840354

[4.0-7.10] Removed kibana alert for security

---

public/components/agents/sca/inventory.tsx

- The pagination wasn't working in the SCA checks table. https://github.com/wazuh/wazuh-kibana-app/issues/2801#issuecomment-764838773 https://github.com/wazuh/wazuh-kibana-app/issues/2801#issuecomment-765443147
Closes #2835

4.0-7.10 Fix the pagination in SCA ckecks table

---

public/plugin.ts

- Fixed error when trying to navigate from discovery to Wazuh app.
Issue [#2831](https://github.com/wazuh/wazuh-kibana-app/issues/2831)

Fix discovery navigation

---

public/components/agents/sca/inventory.tsx

Fix the SCA table with a wrong behaviour using the refresh button:
- Removed the filters in the request. The filters are applied in the results of the request.
- Replaced filter in the search bar for not Not applicable result from an empty string to 'not applicable'
Closes: #2847

4.0-7.10 - Fix the SCA table with a wrong behaviour using the refresh button

---

public/components/agents/sca/main.tsx
public/components/common/welcome/components/sca_scan/sca_scan.tsx
server/lib/cache-api-user-has-run-as.ts
server/start/cron-scheduler/apiRequest.ts

- SCA information is not shown for authorized agents. 
Now we show a prompt with policies necessaries.:
Issue [#2842](https://github.com/wazuh/wazuh-kibana-app/issues/2842)

Fix 4.0 7.10 sca permissions

---

public/components/add-modules-data/sample-data.tsx
public/components/common/modules/main-overview.tsx
public/kibana-integrations/kibana-discover.js

-  Blank page on modules after pinning a filter, go agents and return.
Resolves [#2801 comment](https://github.com/wazuh/wazuh-kibana-app/issues/2801#issuecomment-769171853)

[4.0.4-7.10] Fixed filter pinned crash returning from agents

---

public/components/agents/fim/inventory/flyout.tsx
public/components/common/modules/module.scss
public/components/overview/compliance-table/components/requirement-flyout/requirement-flyout.tsx
public/components/overview/mitre/components/techniques/components/flyout-technique/flyout-technique.tsx
public/components/security/policies/edit-policy.tsx
public/components/security/policies/policies.tsx
public/components/security/roles-mapping/components/roles-mapping-create.tsx
public/components/security/roles-mapping/components/roles-mapping-edit.tsx
public/components/security/roles/create-role.tsx
public/components/security/roles/edit-role.tsx
public/components/security/users/components/create-user.tsx
public/components/security/users/components/edit-user.tsx
public/controllers/overview/components/select-agent.js
public/kibana-integrations/discover/application/components/top_nav/open_search_panel.js

Hi guys, we fixed css of layouts because of conflicts with kibana flyouts. We resolved it giving specific classNames to our flyouts.
Solved: https://github.com/wazuh/wazuh-kibana-app/issues/2801#issuecomment-769149895

Fixed css of layouts because of conflicts with kibana flyouts

---

public/controllers/management/components/management/configuration/utils/wz-fetch.js

Hi team,
This PR resolves the problem after restarting the cluster.
Changed the endpoint to check.

Changed method and request to check status of cluster

---

CHANGELOG.md
README.md
package.json

Hi team, 
this update the changelog and readme for revision 4017
Feel free to update the titles for easier reading

Prepare changelog readme for revision 4017

---

public/assets/custom-style.js

Hi Team, this fixes:
- Custom _home_ link wasn't always replaced by Wazuh _home_
- Discover help menu documentation link was being replaced unnecessarily

Feature/cloud/customization 7.10 - Wazuh Home link fix

---

server/controllers/wazuh-api.ts
server/plugin.ts

Hello team,
we have added that wz-user and wz-token show the tag secured in SSL / TLS session.
Closes: #2790

Set secure cookies in SSL/TLS sessions

---

CHANGELOG.md
public/components/wz-search-bar/lib/filters-to-object.ts

- Fix the complex searches using the Wazuh API query filter in the WzSearchBar component
Closes #2913

Fix complex searches in WzSearchBar for query filter

---

CHANGELOG.md
public/components/common/hooks/useUserPermissions.ts
public/redux/reducers/appStateReducers.js

Hi team,
This PR added a control before check permissions to render components and changed the initial state of userPermissions.
+ Applied prettier.
Closes #2919

Check user permissions before render

---

CHANGELOG.md
public/styles/common.scss

- Strange box shadow in Export popup panel
Closes #2886

Fixed wrong box shadow popup panel

---

CHANGELOG.md
server/controllers/wazuh-hosts.ts

- Wrong command on alert when data folder does not exist
Closes #2906

Fixed wrong command on alert when data folder does not exist

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

- This PR resolves wrong package name, missing l letter in name
Closes #2934

Fix wrong package name in deploy new agent

---

CHANGELOG.md
public/components/d3/pie.js

Hi team,
This PR fixed number of agents not shown on the status graph at first load.
Closes: #2890

Fix number agents not show on pie

---

CHANGELOG.md
public/utils/odfe-utils.ts

Hi team, this PR fix the error message that reported that statusCode was undefined.
Closes #2916 #2924

Fix statusCode error undefined

---

CHANGELOG.md
public/components/agents/sca/inventory.tsx

HI team, this PR resolves:
- Fixed stats in SCA policy stats when uses the Refresh button
- Fixed dates to use the TimeService
Closes: #2962

Stats in SCA policy stats didn't refresh

---

CHANGELOG.md
public/components/agents/fim/inventory/fileDetail.tsx
public/components/agents/fim/inventory/table.tsx
public/components/agents/sca/inventory.tsx

Fix date field format to the browser time zone in:
- FIM table, file, and registry detail. 
- SCA policies table and stat in policy detail
Closes: #2960

fix(frontend): Date format in FIM table and file/registry detail

---

public/components/agents/fim/main.tsx
public/components/agents/sca/main.tsx

Hi team,
This PR fixed the error when entering SCA it was loading the view (with a not selected agent).
1. Go to SCA view (with not Agent selected)
2. The view is constantly loading.

Fix SCA view with a not selected Agent

---

public/services/resolves/get-config.js
public/services/resolves/get-ip.js

Hi team, 
this resolves health-check runs after every refresh
1. Open Wazuh app for first time (with cache cleared) 
2. Health-check runs (OK)
3. Navigate to any section of the app
4. Press F5
5. Health-check runs (KO)

Fixed health check runs after every refresh

---

public/kibana-integrations/kibana-vis.js

Fixed kibana vis error id of undefined

---

CHANGELOG.md
public/app.js

Hi team,
This PR added an event on logout to remove the API token.
Closes: #2789

Bugfix logout remove token x pack

---

public/components/agents/fim/inventory/flyout.tsx
public/components/agents/fim/inventory/registryValues/registryValues.tsx

We resolve a bug that make that registry_values aren't not displayed for Windows agents
Closes: #3019

Registry_values aren't not displayed for Windows agents

---

CHANGELOG.md
public/controllers/management/components/management/groups/get-agents-filters-values.js

Hi team, this PR solves:
- Agents table show suggestions with managers info
Closes #2946

Fix manager is shown in suggestions

---

CHANGELOG.md
public/components/settings/api/add-api.js

HI team, this PR resolves:
- add `run_as` setting to Add new API view
Closes: #3017

Add run_as setting to Add new API view

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

Hi team, this PR solve:
- Bad variable declaration for macOS agent deployment
Closes #3058

Fix deployment command line macos agents

---

public/react-services/wz-authentication.ts

Fix infinite loading status while the user login in when the request fails and can't get the token
Screenshot:

fix(frontend): Fix infinite loading user logging in status

---

public/controllers/settings/settings.js

Hi team this PR improve the message when you select an API as default in Configuration
Related to #2948

Change api selected as default message

---

public/controllers/agent/components/agents-table.js

Hi guys,
We fix a bug that dont show cluster node in agents table

Fixed cluster node in Agents

---

server/integration-files/visualizations/cluster/statistics.ts

Reverts wazuh/wazuh-kibana-app#3098

Revert "fix tcp sessions visualizations"

---

public/react-services/filter-authorization-agents.ts
server/controllers/wazuh-elastic.ts
server/integration-files/visualizations/cluster/statistics.ts

- New agents filter is included in statistics views

Fixed agents filter in statistics views

---

public/app.js

Hi team,
This PR fixed the call to the remove token method in the logout for x-pack and ODFE.

Fixed remove token on logout

---

public/components/common/modules/discover/discover.tsx

Hi guys,
In this PR we fix some lines that we overwrite

Fixing overwriten lines

---

CHANGELOG.md
public/components/health-check/health-check.tsx

Hi team,
This PR fixed state of loader `wazuhNotReadyYet`

Fixed updateWazuhNotReady state

---

server/controllers/wazuh-elastic.ts

Hello guys, in this PR we solved an error that caused that when you had permission for all users in / Agents -> Most Active Agent nothing was shown

Fixing when most active agent doesn't apper

---

public/directives/wz-logtest/components/logtest.tsx

Hi team,
This PR fixed format to show on CodeBlock.

bugfix(logtest): Fixed format result of request.

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

Hi Team.
This PR resolves some bugs in deployment new agent autocompleted command.

add agent deployment variables 

---

CHANGELOG.md
public/directives/wz-logtest/components/logtest.tsx

Hi team,
This PR check if the parent value does not exist, does not show it.
Closes: #3150

 bugfix(logtest): Dont show parent if it doesn't exist.

---

public/components/common/welcome/agents-welcome.js

Hi team,
This PR fixed styles on agent overview (superposition).

bugfix(agents): Styles agent-overview and remove console.log

---

CHANGELOG.md
common/constants.ts
public/components/health-check/health-check.tsx
public/components/wz-menu/wz-menu.js
public/react-services/pattern-handler.js
public/react-services/saved-objects.js
public/services/resolves/get-ip.js

- Change the current index pattern from the Wazuh menu doesn't apply the selection.
Closes #3186
Related to #2985 and #3141
Testing: 
- Create a new index pattern (it should be by changing the default pattern setting, it should be set as default for Kibana too) 
- Change the pattern selection from the Wazuh menu to the new pattern.
- After refresh, the selection should be the new pattern.
- Change it again to another index pattern than the default.
- After refresh, the selection should be the pattern selected.
- The default pattern must be the same as previously configured.

Fixed change index pattern from menu doesnt work

---

public/directives/wz-logtest/components/logtest.tsx

Hi team,
This PR fixed format to show data result of logtest.
Closes  #3150 and #3193

bugfix(logtest): Fixed data to show + prettier

---

public/react-services/wz-user-permissions.test.ts

Hi team,
This PR just fix the unit test of user-permissions. 🧪

test(fix): Fix unit test actions and resources was changed.

---

.prettierrc

Hi team, 
This file has a configuration for [prettier](https://prettier.io/docs/en/index.html) 😃

feat(prettier): Added prettierrc config file.

---

public/components/agents/fim/inventory/fileDetail.tsx
public/components/agents/fim/inventory/filterBar.tsx
public/components/agents/fim/inventory/registry-table.tsx
public/components/agents/fim/inventory/registryValues/registryValues.tsx
public/components/common/welcome/agents-welcome.js

Hi team!
This PR removes SHA1 data from windows registry tab
Also, applies date format to every windows table with date
Closes #3182

Removed sha1 data and correct date format

---

CHANGELOG.md
public/controllers/management/management.js
public/styles/common.scss
public/templates/management/management.html

We have fixed a bug, which caused a flicker in the graph that is shown in Management / Cluser -> View Overview, we have added a Loader in the loading time, as there is in the Security Events visualizations.
To check its operation, simply enter where I have commented and configure Network in the Dev Tools of your browser to Fast 3g to be able to see it well.
Close #3060

Fixed screen flickers in Cluster Visualization

---

CHANGELOG.md
kibana.json
package.json
public/react-services/generic-request.js
public/react-services/pattern-handler.js
public/react-services/saved-objects.js

Hi team,
This PR fixed the problem when Index-pattern is not present on health-check.
Close: #3169

Bugfix default index patterns [Health-check]

---

CHANGELOG.md
public/components/add-modules-data/module-guide.js

Hi team, this PR change one tag to the Wazuh standard. Closes #2856

Rename config tag

---

CHANGELOG.md
public/styles/component.scss
public/utils/wz-logo-menu.js

Hi team,
this fixed wazuh main menu render issues in 7.12
Closes #3343 
To test try to resproduce the linked issue

Hide Wazuh breadcrumb label and Wazuh api selector css fix

---

public/react-services/error-orchestrator/error-orchestrator-base.ts
server/lib/base-logger.ts

Hi team this PR fix a problem related with the creation of the logs files (app and ui).

Fix creation of json file after a ui log

---

public/components/health-check/container/health-check.container.tsx

Hi team this PR implements the errorBoundary hoc to the new health-check.

Implement error boundary hoc in  health check

---

public/react-services/error-orchestrator/error-orchestrator-base.ts
public/react-services/error-orchestrator/error-orchestrator-ui.ts

Hi team,
This PR changes the logic for display errors depends on level Error and severity UI

Now for level.Error always displayError

---

CHANGELOG.md
public/components/settings/settings-logs/logs.js
server/lib/base-logger.ts
server/start/cron-scheduler/error-handler.ts

Hi team this is the cherry-pick of #3397 into 4.3-7.10

Cherry pick #3397 into 4.3 7.10

---

.github/workflows/cypress-automation-tests.yml

Hi Team,
This branch is generated as a test to be able to integrate a workflow that will execute the automatic tests of cypress.
Variables for the workflow:
WAZUH_MANAGER_IMAGE=wazuh_manager_filebeat_sources_cmake
WAZUH_AGENT_IMAGE=wazuh_agent_ubuntu_sources_cmake
WAZUH_VERSION=master
ELASTIC_VERSION=7.10.2

Create Cypress Workflow for 4.3-7.10

---

public/components/common/welcome/components/agent-sections.ts
public/components/common/welcome/components/menu-agent.js

Hi team,
This PR added on menu-agents.js mapDispatchToProps to dispatch updateCurrentAgentData.
Plus: Prettier applied

Fixed dispatch for updateCurrentAgentData

---

CHANGELOG.md
public/controllers/management/components/management/reporting/__snapshots__/reporting-main.test.tsx.snap
public/controllers/management/components/management/reporting/reporting-main.test.tsx
public/controllers/management/components/management/reporting/reporting-table.js
public/controllers/management/components/management/reporting/utils/actions-buttons-main.js
public/controllers/management/components/management/reporting/utils/reporting-handler.js

Hi team,
This PR implement our new error handling strategy on the Ruleset section
Close #3426

Added try-catch strategy in Reporting section

---

public/components/common/custom-search-bar/custom-search-bar.tsx
public/components/common/custom-search-bar/index.ts
public/components/overview/office-panel/search-bar-config.ts

add searchbar component

---

CHANGELOG.md
public/components/common/hocs/withKibanaContext.tsx
public/components/common/hooks/use-es-search.ts
public/components/common/hooks/use-filter-manager.ts
public/components/common/modules/panel/main-panel.tsx
public/components/visualize/components/security-alerts.tsx

Reverts wazuh/wazuh-kibana-app#3513

Revert "Moved filter subscription to useFilterManager"

---

public/controllers/management/components/management/configuration/office365/components/SubscriptionTab/SubscriptionTab.tsx
public/controllers/management/components/management/configuration/office365/components/api-auth-tab/api-auth-tab.tsx
public/controllers/management/components/management/configuration/office365/components/general-tab/general-tab.tsx

Hi guys,
With this PR we are resolving the adjustment of Office configuration in /Management/Configuration, involving the xml and json editor of general, credential, and subscriptions

Fixing height of Office configuration

---

public/components/common/custom-search-bar/components/multi-select.tsx
public/components/common/custom-search-bar/custom-search-bar.tsx
public/components/common/modules/panel/main-panel.tsx
public/components/overview/office-panel/office-panel.tsx

Hi team, this resolve:
- When you enter a specific drilldown, filter should be blocked to prevent you from choosing another option-

block filter when drilldown is open

---

CHANGELOG.md
server/controllers/wazuh-api.ts
server/lib/update-registry.ts
server/start/cron-scheduler/save-document.ts
server/start/index.ts
server/start/initialize/index.ts
server/start/monitoring/index.ts
server/start/tryCatchForIndexPermissionError.ts

Hi team!
This PR solves the logs errors when kibana has been deployed (even though as the first time)
related PRs:  #3260 
Closes: #3567 #3209

fix: remove logs after app starts

---

.github/ISSUE_TEMPLATE/bug_report.md

Updated the fields needed to generate a new bug, in order to better describe the bug behaviour found.

Update bug_report.md according to testing needs

---

CHANGELOG.md
public/controllers/dev-tools/dev-tools.ts

Hi team,
This PR fixed handler of an error on the Api console section.

Fix handler error on dev-tools

---

CHANGELOG.md
public/components/common/globalBreadcrumb/globalBreadcrumb.scss
public/components/common/globalBreadcrumb/globalBreadcrumb.tsx
public/components/common/modules/main-overview.tsx

Hi team,
This PR contains the changes applied in 4.2 to correct the visual style shown in 7.14+
Pick: #3668

Fixed styles of globalBreadcrumb for 7.14

---

public/controllers/management/components/management/ruleset/rule-info.js

This PR solves a problem when opening a rule file in rule detail information.
- Fix error when opening a rule file from the `Related rules`  in the rule detail information
No related issue

[FIX] Error opening rule file in Related rules of rule detail information

---

CHANGELOG.md
public/components/common/modules/events.tsx
public/components/health-check/services/check-index-pattern/check-index-pattern-object.service.ts
public/components/visualize/wz-visualize.js
public/react-services/saved-objects.js

Hi guys,
In this PR we fix the bug of index patterns in health-check due to bad copy of a PR.

Fixing the bug of index patterns in health-check due to bad copy of a PR

---

CHANGELOG.md
README.md
kibana.json
public/app.js
public/controllers/settings/settings.js
public/plugin.ts
public/react-services/saved-objects.js
public/react-services/wz-authentication.ts
public/types.ts

Hello Team in the PR I integrate the last changes made for version 4.2.5 to version 4.3

Feature/integrate changes 4.2.5

---

CHANGELOG.md
kibana.json
public/app.js
public/components/health-check/services/check-index-pattern/check-index-pattern-object.service.ts
public/controllers/settings/settings.js
public/plugin.ts
public/react-services/saved-objects.js
public/react-services/wz-authentication.ts
public/types.ts

Hi team,
This pull request is to backport all new changes to cloud.

Cloud 4.2.5 7.10.2 backport

---

CHANGELOG.md
public/controllers/management/components/management/configuration/global-configuration/global-configuration-global.js

This PR fixes some settings that are not visible in `Management/Configuration/Global configuration/Global/Main settings`.
- The settings related to `archives` and other settings should be visible in `Main settings`
Closes #3735

[FIX] Missing settings in `Management/Configuration/Global configuration/Global/Main settings`

---

CHANGELOG.md
public/components/agents/fim/inventory/flyout.tsx
public/components/agents/fim/inventory/registry-table.tsx
public/components/agents/fim/inventory/table.tsx
public/components/agents/vuls/inventory/table.tsx
public/components/common/flyouts/index.ts
public/components/common/flyouts/wz-flyout.tsx
public/components/common/modules/discover/discover.tsx
public/components/common/modules/events.tsx
public/components/common/welcome/components/fim_events_table/fim_events_table.tsx
public/components/common/welcome/components/mitre_top/mitre_top.tsx
public/components/overview/compliance-table/components/requirement-flyout/requirement-flyout.tsx
public/components/overview/compliance-table/components/subrequirements/subrequirements.tsx
public/components/overview/mitre/components/techniques/components/flyout-technique/flyout-technique.tsx
public/components/overview/mitre/components/techniques/techniques.tsx
public/components/overview/mitre_attack_intelligence/resource_detail_flyout.tsx
public/components/security/policies/create-policy.tsx
public/components/security/policies/edit-policy.tsx
public/components/security/roles-mapping/components/roles-mapping-create.tsx
public/components/security/roles-mapping/components/roles-mapping-edit.tsx
public/components/security/roles/create-role.tsx
public/components/security/roles/edit-role.tsx
public/components/security/users/components/create-user.tsx
public/components/security/users/components/edit-user.tsx
public/directives/wz-logtest/components/logtest.tsx

Fixing error in the flyout, that when clicking inside them, the flyout was closed due to an unintended behavior of EuiOutsideClickDetector. Fixed changing this Eui component to a prop in all EuiFlyouts.
To test it, you would need to go to all the flyouts of the app and check that they work correctly.

Fixing Flyouts in Kibana 7.14.2

---

.github/workflows/create-wazuh-packages.yml
CHANGELOG.md

Hi team in this PR i added a new workflow for create wazuh packages.

Added workflow wazuh package

---

CHANGELOG.md
public/controllers/agent/components/agents-preview.js
public/styles/common.scss

Change of styles so that it has the same height as the other cards and the same length when it has this one the screen is small
**Issues Resolved**
The height of the evolution card is smaller than the other cards. [#3786](https://github.com/wazuh/wazuh-kibana-app/issues/3786)
**Test**
1. Navigate to the agent's page
2. Look at the evolution card
**Check List**
[x] The evolution card is the same size as the other cards

Fixed the styles on the evolution card

---

public/components/agents/stats/table.test.tsx
public/components/common/util/markdown/markdown.test.tsx
public/components/health-check/container/__snapshots__/health-check.container.test.tsx.snap
public/components/health-check/container/health-check.container.test.tsx
public/controllers/management/components/management/configuration/office365/components/SubscriptionTab/SubscriptionTab.test.tsx
public/controllers/management/components/management/ruleset/__snapshots__/main-ruleset.test.tsx.snap
public/controllers/management/components/management/ruleset/main-ruleset.test.tsx
public/controllers/management/components/management/status/__snapshots__/status-main.test.tsx.snap
public/controllers/management/components/management/status/status-main.test.tsx

This PR fixes and update the tests
- The tests with jest should pass
```bash
yarn test:jest
```

[TESTS] Fix and update the tests

---

CHANGELOG.md
public/components/wz-kibana-vis/wz-kibana-vis.tsx
public/controllers/agent/components/agents-preview.js
public/kibana-integrations/kibana-vis.js
server/controllers/wazuh-elastic.ts
server/routes/wazuh-elastic.ts

Hi Team,
This PR resolves the agent evolution card permanently loading when vis index pattern doesn't exist.
Closes #3830

Fixed agents evolutions card

---

CHANGELOG.md
public/controllers/agent/components/agents-preview.js
public/styles/common.scss

Hi Team, 
This PR resolve a wrong mobile style in agents details card.
Close #3859

Fixed agents link mobile style in Agents details card

---

CHANGELOG.md
public/components/health-check/services/check-index-pattern/check-index-pattern-object.service.ts

Hi team,
this PR fixes the [BUG] [HEALTH CHECK] undefined is not an object (evaluating indexPatternToSelect.id).
https://github.com/wazuh/wazuh-kibana-app/issues/3862

fix: bug-health-check

---

CHANGELOG.md
public/components/overview/office-panel/views/office-stats.tsx
public/controllers/management/components/management/configuration/office365/components/general-tab/general-tab.tsx

Hi team,
this PR improves Office365 configuration description to avoid confusion.
Closes #3951

Changed office365 config description

---

CHANGELOG.md
public/components/overview/mitre_attack_intelligence/resource.tsx

Now in the widget you can choose between 10, 15, 25, 50 or 100 rows.

Modules-> Mitre-> Widget: Rows per page

---

CHANGELOG.md
public/components/agents/fim/inventory/flyout.tsx
public/components/agents/vuls/inventory/flyout.tsx

Hi Team,
This PR resolves the toast error when FIM file in FIM details layout not exists.
Closes #4104

Fixed not found FIM file toast error

---

CHANGELOG.md
public/controllers/management/components/management/status/status-agent-info.js

**Correction of field and value in the section: last registered agent**
**Preconditions**
1. A registered agent must exist
**Steps to reproduce**
1. Navigate to Management -> Status
**As you can see in the image in the section: 'last registered agent' there is a field that says "Date add" and it should say "Date added", you can also see that the value of the Status field is "active" and it should be "Active"**
In this image you can see the corrected errors

4044 grammatical error and absence of capitalization in the state field

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

Modified the download agent command for windows.
This change resolves #4085.

Fix windows command for agent installation

---

CHANGELOG.md
public/kibana-integrations/kibana-vis.js

* Update CHANGELOG.md
* Update kibana-vis.js
Co-authored-by: Álex <alejandro.ruiz.becerra@wazuh.com>
(cherry picked from commit 7536c05a7986d55a4435eb42bfbd8a8b39733984)

Fix type error on the Agents main view (#4233)

---

CHANGELOG.md
common/api-info/endpoints.json
scripts/generate-api-4.0-info/generate-api-4.0-info.js
server/lib/api-interceptor.ts
server/lib/api-request-list.json

* Use POST method when requesting the API login endpoint
* changelog: add PR entry
Co-authored-by: Matias Ezequiel Moreno <matiasmoreno876@gmail.com>
Co-authored-by: Álex <alex-r-b@hotmail.com>
Co-authored-by: Antonio David Gutiérrez <antonio.gutierrez@wazuh.com>
(cherry picked from commit 3977e45c6ffdc06926edfd12355f0f20dd2f9d84)

Use POST method when requesting the API login endpoint (#4103)

---

public/components/wz-search-bar/components/wz-search-badges/wz-search-badges.tsx
public/components/wz-search-bar/lib/filters-to-object.test.ts
public/components/wz-search-bar/lib/filters-to-object.ts
public/components/wz-search-bar/lib/q-interpreter.test-cases.ts
public/components/wz-search-bar/lib/q-interpreter.test.ts
public/components/wz-search-bar/lib/q-interpreter.ts
public/components/wz-search-bar/lib/suggest-handler.ts
public/components/wz-search-bar/wz-search-bar.test-cases.ts
public/components/wz-search-bar/wz-search-bar.test.tsx

Hi Team,
This PR resolves some issues related to `WzSearchBar`, `QInterpreter`, and `filterToObject` method.
All used on Wazuh UI SearchBar.
Closes #4088

Added feature searchbar conjuntion parser

---

public/controllers/management/components/management/reporting/reporting-table.js
public/react-services/reporting.js
server/controllers/wazuh-reporting-security-endpoint-handler.test.ts
server/controllers/wazuh-reporting-security-endpoint-parameters-validation.test.ts
server/controllers/wazuh-reporting.ts
server/lib/error-response.ts
server/lib/security-factory/factories/default-factory.ts
server/lib/security-factory/factories/opendistro-factory.ts
server/lib/security-factory/factories/opensearch-dashboards-security-factory.ts
server/lib/security-factory/factories/xpack-factory.ts
server/plugin.ts
server/routes/wazuh-reporting.ts
server/start/index.ts
server/start/migration-tasks/index.ts
server/start/migration-tasks/reports_directory_name.test.ts
server/start/migration-tasks/reports_directory_name.ts

Backport 3c1e51cbc8d4c269d08df90f855d1f07e4897fd6 from #4330.

[Backport 4.3-1.2-wzd] Sanitize report's inputs and usernames

---

README.md
kibana.json
package.json

This PR bumps the Wazuh version from 4.3.5 to 4.3.6

Support for Wazuh 4.3.6

---

CHANGELOG.md
common/csv-key-equivalence.ts
public/utils/monitoring-fields.ts
server/controllers/wazuh-reporting.ts
server/integration-files/monitoring-known-fields.ts

Backport from https://github.com/wazuh/wazuh-kibana-app/pull/4350

[Backport 4.3-1.2-wzd] Fixed errors in group reports

---

CHANGELOG.md
public/plugin.ts

* Solve TypeError
* Add CHANGELOG
* Change request service
* Fix request's response structure
(cherry picked from commit 44a43cbe28cf92824da60627b38ff50800474e07)

TypeError resolved (#4362)

---

CHANGELOG.md
common/constants.ts
public/services/resolves/get-config.js
public/utils/config-equivalences.js
server/controllers/wazuh-hosts.ts
server/lib/initial-wazuh-config.ts
server/lib/manage-hosts.ts
server/lib/update-registry.ts

* Review Wazuh.yml documentation
Remove unused settings. Centralize documentation. Add missing settings. Programmatic file generation.
* Add Changelog
* Fix indentation for hosts in the wazuh.yml
Also fixes some TS warnings
* Deep copy the WAZUH_DEFAULT_APP_CONFIG object
(cherry picked from commit 1d441096398ed5e34e98048077520c78687788c0)

Fix wazuh.yml link and in-file documentation (#4378)

---

test/performance/modules/vulnerabilities-events-modules.js
test/performance/modules/vulnerabilities-inventory-modules.js

adding performance scripts for the **Vulnerabilities** module, this script includes _Inventory_ and _Events_ tabs
Report:
<details>
</details>

Add performance scripts for the Vulnerabilities module

---

CHANGELOG.md
public/components/health-check/services/check-index-pattern/check-index-pattern-object.service.ts
public/components/health-check/services/check-pattern-support.service.ts
public/react-services/saved-objects.js
server/start/initialize/index.ts

* fix: Fixed a routes loop when reinstalling Wazuh indexer
* fix: replaced the display error in the plugin loop
* changelog: add PR entry
* fix import variable
Co-authored-by: Matias Ezequiel Moreno <matiasmoreno876@gmail.com>
(cherry picked from commit be7654a2912eec72ec37f942857067a611441b1e)

Fixed a routes loop when reinstalling Wazuh indexer (#4373)

---

CHANGELOG.md
public/controllers/agent/agents-preview.js
public/controllers/agent/components/agents-preview.js
public/controllers/agent/components/agents-preview.scss
public/controllers/agent/components/agents-table.js
public/controllers/agent/components/register-agent.js
public/kibana-integrations/kibana-vis.js
public/templates/agents-prev/agents-prev.html

* Requests improvements
* Fix Agent wizard close state
* Independent loading cards
* Updated wazuh version
* Added changelog
* Added agentsSynced initial value
* Added flex-wrap to KPIs
(cherry picked from commit 4f710c1c1aefa1395a24c82e8a5d1ff673a47ee6)

Agents section performance improvements (#4363)

---

CHANGELOG.md
README.md
kibana.json
package.json

Add support for Wazuh 4.3.8
Related issue: https://github.com/wazuh/wazuh-kibana-app/issues/4462

Bump 4.3.8

---

test/cypress/cypress/integration/pageobjects/basic/wazuh-menu/rules.page.js
test/cypress/cypress/integration/pageobjects/odfe/wazuh-menu/rules.page.js
test/cypress/cypress/integration/pageobjects/wzd/wazuh-menu/rules.page.js
test/cypress/cypress/integration/pageobjects/xpack/wazuh-menu/rules.page.js

This PR Implements a fix to edit rules test.
Closes: https://github.com/wazuh/wazuh-kibana-app/issues/4513
Before: 
After:

Editing selectors to solved duplicated calls

---

CHANGELOG.md
README.md
package.json

This PR adds support for Wazuh v3.13.6.

Add support for Wazuh 3.13.6

---

CHANGELOG.md
public/plugin.ts
server/controllers/wazuh-api.ts
server/routes/wazuh-api.ts

* Create get-logos endpoint and initialize custom logos
* Update endpoint name
* Add Changelog
Co-authored-by: Alex Ruiz Becerra <alejandro.ruiz.becerra@wazuh.com>
(cherry picked from commit b9f7cf3cc4d4a24bfc4f8995a8096226533dfad1)

Initialize Wazuh plugin with custom logos (#4539)

---

test/cypress/cypress/fixtures/configuration.panel.text.json

Issue #4560 
This PR includes the correction of the configuration module, these are changes in the text of the descriptions of the modules.
Test 
<details>
<summary>Test execution</summary>
</details>

fix for kibana-xpack cofiguration texts

---

CHANGELOG.md
common/constants.ts
public/components/health-check/container/health-check.container.tsx
public/components/health-check/services/check-setup.service.ts

Solve backport conflict from [#4529](https://github.com/wazuh/wazuh-kibana-app/pull/4529)

[Backport 4.4-7.16] Change message for API version mismatch in Kibana

---

.github/workflows/backport.yml
.github/workflows/create-wazuh-packages.yml
.github/workflows/cypress-automation-tests.yml
.github/workflows/cypress-basic.yml
.github/workflows/cypress-odfe.yml
.github/workflows/cypress-wzd.yml
.github/workflows/cypress-xpack.yml
.github/workflows/wazuh-build-push-docker-action.yml
.github/workflows/wazuh-unit-test.yml

Closes #4575
Hi team, in this PR I add new workflows for Github actions, these workflows were added in version [4.4 in this PR](https://github.com/wazuh/wazuh-kibana-app/pull/4344), the idea is to be able to work directly in the master branch with the workflows and update the version of the runners to 'ubuntu-latest'.

Add new 'workflows for Github actions'.

---

.github/workflows/backport.yml
.github/workflows/create-wazuh-packages.yml
.github/workflows/cypress-basic.yml
.github/workflows/cypress-odfe.yml
.github/workflows/cypress-wzd.yml
.github/workflows/cypress-xpack.yml
.github/workflows/wazuh-build-push-docker-action.yml
.github/workflows/wazuh-unit-test.yml

Backport b1bb8ae94abdf00bd37aa43cb4068ba144599570 from #4574.

[Backport 4.4-7.16] Add new 'workflows for Github actions

---

.github/workflows/backport.yml
.github/workflows/create-wazuh-packages.yml
.github/workflows/cypress-basic.yml
.github/workflows/cypress-odfe.yml
.github/workflows/cypress-wzd.yml
.github/workflows/cypress-xpack.yml
.github/workflows/wazuh-build-push-docker-action.yml
.github/workflows/wazuh-unit-test.yml

Backport b1bb8ae94abdf00bd37aa43cb4068ba144599570 from #4574.

[Backport 4.4-1.2-wzd] Add new 'workflows for Github actions

---

.github/workflows/backport.yml
.github/workflows/create-wazuh-packages.yml
.github/workflows/cypress-basic.yml
.github/workflows/cypress-odfe.yml
.github/workflows/cypress-wzd.yml
.github/workflows/cypress-xpack.yml
.github/workflows/wazuh-build-push-docker-action.yml
.github/workflows/wazuh-unit-test.yml

Backport b1bb8ae94abdf00bd37aa43cb4068ba144599570 from #4574.

[Backport 4.4-7.10] Add new 'workflows for Github actions 

---

test/cypress/images/ubuntu-cypress/Dockerfile

hello team in this pr I solve the relative path to the cypress folder in the dockerfile file 
- Closes #4603

Fix path to cypress folder

---

test/cypress/CODEOWNERS
test/cypress/cypress/integration/features/management/rules/should-list-rules-by-level.feature
test/cypress/cypress/integration/pageobjects/basic/wazuh-menu/rules.page.js
test/cypress/cypress/integration/pageobjects/odfe/wazuh-menu/rules.page.js
test/cypress/cypress/integration/pageobjects/wzd/wazuh-menu/rules.page.js
test/cypress/cypress/integration/pageobjects/xpack/wazuh-menu/rules.page.js
test/cypress/cypress/integration/step-definitions/management/rules/the-filter-label-is-displayed.then.js
test/cypress/cypress/integration/step-definitions/management/rules/the-user-can-see-the-rule-then.js
test/cypress/cypress/integration/step-definitions/management/rules/the-user-clicks-the-refresh-button-when.js
test/cypress/cypress/integration/step-definitions/management/rules/the-user-clicks-the-search-bar-when.js

Added Feature to increase coverage for Rule module. This feature checks the rules result displayed filtered by a user per level
#4613 
<details>
<summary> code </summary>
</details>
<details>
<summary> test executed </summary>
</details>

Add test feature: list rules filtered by level

---

CHANGELOG.md
README.md
opensearch_dashboards.json
package.json

(cherry picked from commit 5d385c5b17842c0dd86a21910b5f9387788b0f81)

Backport 4655 to 4.3 1.2 wzd

---

CHANGELOG.md
README.md
kibana.json
package.json

(cherry picked from commit 5d385c5b17842c0dd86a21910b5f9387788b0f81)

Bump 4.3.9 (#4655)

---

.github/ISSUE_TEMPLATE/revision-manual_test.md

Added template file to have the same way to report manual test review.

Add template files for revision manual test

---

CHANGELOG.md
README.md
kibana.json
package.json

Backport https://github.com/wazuh/wazuh-kibana-app/commit/589dae5a20a9b5a738fae5ad782eb1d10dcee0c8 from https://github.com/wazuh/wazuh-kibana-app/pull/4669.

[Backport 4.3-7.16] Merge 4.3-7.10 into 4.3-7.16

---

test/cypress/cypress/integration/step-definitions/management/rules/the-rule-page-is-available.then.js
test/cypress/cypress/integration/step-definitions/management/rules/the-user-clicks-the-refresh-button-when.js
test/cypress/cypress/integration/step-definitions/management/rules/the-user-see-that-the-rule-list-is-paginated.then.js
test/cypress/cypress/integration/step-definitions/settings/api-configuration/check-api-connection-from-instructions-modal.when.js

This PR fixed the test case of the validation paginator in the Rule page that failed when we executed the test suite. 
#4687 
<details>
</details>

Fix feature after test suite execution on WZD - 4687 

---

public/components/agents/stats/__snapshots__/table.test.tsx.snap
public/components/common/error-boundary/__snapshots__/error-boundary.test.tsx.snap
public/components/common/hocs/error-boundary/__snapshots__/with-error-boundary.test.tsx.snap
public/components/common/tables/__snapshots__/table-default.test.tsx.snap
public/components/common/tables/__snapshots__/table-with-search-bar.test.tsx.snap
public/components/common/tables/__snapshots__/table-wz-api.test.tsx.snap
public/components/common/tables/components/__snapshots__/export-table-csv.test.tsx.snap
public/components/health-check/components/__snapshots__/check-result.test.tsx.snap
public/components/overview/mitre_attack_intelligence/__snapshots__/intelligence.test.tsx.snap
public/controllers/management/components/management/configuration/office365/components/SubscriptionTab/__snapshots__/SubscriptionTab.test.tsx.snap
public/controllers/management/components/management/configuration/office365/components/api-auth-tab/__snapshots__/api-auth-tab.test.tsx.snap
public/controllers/management/components/management/configuration/office365/components/general-tab/__snapshots__/general-tab.test.tsx.snap
public/controllers/management/components/management/decoders/__snapshots__/main-decoders.test.tsx.snap
public/controllers/management/components/management/ruleset/__snapshots__/main-ruleset.test.tsx.snap
public/controllers/management/components/management/status/__snapshots__/status-main.test.tsx.snap
public/controllers/overview/components/__snapshots__/stats.test.tsx.snap
scripts/jest.js
server/controllers/wazuh-reporting-security-endpoint-parameters-validation.test.ts
test/jest/config.js

This PRs fixes the unit tests for the plugin compatible with Kibana 7.16.x-7.17.x
Closes https://github.com/wazuh/wazuh-kibana-app/issues/4712

Fix the unit tests on Kibana 7.16.x-7.17.x

---

public/components/agents/stats/__snapshots__/table.test.tsx.snap
public/components/common/error-boundary/__snapshots__/error-boundary.test.tsx.snap
public/components/common/hocs/error-boundary/__snapshots__/with-error-boundary.test.tsx.snap
public/components/common/tables/__snapshots__/table-default.test.tsx.snap
public/components/common/tables/__snapshots__/table-with-search-bar.test.tsx.snap
public/components/common/tables/__snapshots__/table-wz-api.test.tsx.snap
public/components/common/tables/components/__snapshots__/export-table-csv.test.tsx.snap
public/components/health-check/components/__snapshots__/check-result.test.tsx.snap
public/components/health-check/container/__snapshots__/health-check.container.test.tsx.snap
public/components/overview/mitre_attack_intelligence/__snapshots__/intelligence.test.tsx.snap
public/controllers/management/components/management/configuration/alerts/__snapshots__/alerts-configurations.test.tsx.snap
public/controllers/management/components/management/configuration/office365/__snapshots__/office365.test.tsx.snap
public/controllers/management/components/management/configuration/office365/components/SubscriptionTab/__snapshots__/SubscriptionTab.test.tsx.snap
public/controllers/management/components/management/configuration/office365/components/api-auth-tab/__snapshots__/api-auth-tab.test.tsx.snap
public/controllers/management/components/management/configuration/office365/components/general-tab/__snapshots__/general-tab.test.tsx.snap
public/controllers/management/components/management/decoders/__snapshots__/main-decoders.test.tsx.snap
public/controllers/management/components/management/groups/__snapshots__/groups-main.test.tsx.snap
public/controllers/management/components/management/ruleset/__snapshots__/main-ruleset.test.tsx.snap
public/controllers/management/components/management/status/__snapshots__/status-main.test.tsx.snap
public/controllers/overview/components/__snapshots__/stats.test.tsx.snap
server/controllers/wazuh-reporting-security-endpoint-parameters-validation.test.ts
server/start/cron-scheduler/save-document.test.ts
server/start/initialize/index.test.ts
test/jest/config.js

This PRs fixes the unit tests for the plugin compatible with the Wazuh dashboard.
Closes #4714 

Fix the unit tests on Wazuh dashboard 4.4

---

CHANGELOG.md
public/components/agents/sca/inventory.tsx
public/components/agents/sca/inventory/checks-table.tsx
public/components/agents/sca/inventory/index.ts
public/components/agents/sca/inventory/lib/api-request.ts
public/components/agents/sca/inventory/lib/index.ts
public/components/agents/vuls/inventory.tsx
public/components/common/tables/table-default.tsx
public/components/common/tables/table-wz-api.tsx
public/components/wz-search-bar/lib/base-handler.ts

Backport https://github.com/wazuh/wazuh-kibana-app/commit/8ec037c685d5d5747920dd36c2d0d8052ea294d0 from https://github.com/wazuh/wazuh-kibana-app/pull/4653.

[Backport 4.4-7.16] Added pagination to SCA table

---

test/cypress/cypress/support/index.js

Hello team, this PR is created to fix problems whit github actions.
In this way, we are going to implement solutions for kibana integration

Fix problems in the integration of Cypress and GitHub Actions

---

test/cypress/cypress/integration/utils/driver.js

this PR fix the timeout error on Github Actions execution.
#4547 
<details>
</details>

fix for tiemeout error on the github actions executon

---

CHANGELOG.md
common/constants.ts
common/plugin-settings.test.ts
common/services/settings-validator.ts
public/components/common/form/__snapshots__/index.test.tsx.snap
public/components/common/form/hooks.test.tsx
public/components/common/form/hooks.tsx
public/components/common/form/index.test.tsx
public/components/settings/configuration/components/bottom-bar.tsx
public/components/settings/configuration/components/categories/components/category/category.tsx
server/routes/wazuh-utils/wazuh-utils.test.ts
server/routes/wazuh-utils/wazuh-utils.ts

Backport 5c0c413f7357afe7388af748007fec62c25dd9a0 from #4503.

[Backport 4.4-2.3-wzd] Add validation to the plugin settings

---

test/cypress/cypress/integration/step-definitions/settings/The-wazuh-admin-user-is-logged.given.js
test/cypress/cypress/support/index.js

Hello team, this PR integrate some changes on the login method for WZD and solves problems integrated on the last QA PR

Fixing login method for WZD

---

.github/workflows/dependency-review.yml
.github/workflows/eslint.yml

This PR adds workflows to run ESLint and a [vulnerability scanner for project's dependencies](https://github.com/actions/dependency-review-action)
Closes #4681

Add GitHub Actions for Code Analysis

---

CHANGELOG.md
common/constants.ts
common/plugin-settings.test.ts
common/services/settings.test.ts
common/services/settings.ts
public/components/common/form/index.tsx
public/components/common/hocs/withUserLogged.tsx
public/components/health-check/container/health-check.container.tsx
public/components/settings/configuration/components/categories/components/category/category.tsx
public/components/settings/configuration/configuration.tsx
public/components/wz-menu/wz-menu.js
public/plugin.ts
server/controllers/wazuh-api.ts
server/lib/reporting/printer.ts
server/lib/reporting/summary-table.ts
server/routes/wazuh-reporting.test.ts
server/routes/wazuh-utils/wazuh-utils.test.ts

Backport https://github.com/wazuh/wazuh-kibana-app/commit/c1c39b359148f788985da17c2ff2b8b0530c19e9 from https://github.com/wazuh/wazuh-kibana-app/pull/4507.

[Backport 4.4-2.3-wzd] Add switch to toggle the use of custom branding

---

test/cypress/cypress/integration/features/filters/remove-filter-from-agent-module-dashboard.feature
test/cypress/cypress/integration/step-definitions/filters/the-user-removes-applied-filter-on-agent.when.js

Hello team ! I create this PR to add a new automated test case.
The goal of the test is to check if the remove filter functionality it's working.
So in the development of this test we consider the creation and deletion of a particular filter on all the modules available for a particular agent.
I'll add more information on this PR a soon I have the test result data.

Adding remove filters from agent module

---

test/cypress/cypress/integration/features/filters/remove-filter-from-agent-module-events.feature

Hi team, I create this PR to implement the remove filter functionality for agent events dashboards multimodule.
The test it's working on WZD

Adding a new test

---

CHANGELOG.md
README.md
kibana.json
package.json

Adds support for Wazuh 4.3.10
#4836 
Not needed
Not needed

Add support for Wazuh 4.3.10 - 7.16

---

CHANGELOG.md
README.md
opensearch_dashboards.json
package.json

Adds support for Wazuh 4.3.10
#4836 
Not needed
Not needed
- [] Update [CHANGELOG.md](./../CHANGELOG.md)
- [] Commits are signed per the DCO using --signoff

Add support for Wazuh 4.3.10 - 1.2-wzd

---

CHANGELOG.md

This PR fixes the Wazuh version of the SAML fix PR.

Fixed 4.3.10 changelog

---

test/cypress/cypress/integration/features/filters/remove-filter-from-agent-module-dashboard.feature
test/cypress/cypress/integration/features/filters/remove-filter-from-agent-module-events.feature
test/cypress/cypress/integration/features/filters/remove-pinned-filter-from-agent-dashboard.feature
test/cypress/cypress/integration/features/filters/unpinned-filter-from-agent-dashboard.feature
test/cypress/cypress/integration/pageobjects/wzd/filters/filters.page.js
test/cypress/cypress/integration/step-definitions/filters/the-user-unppined-the-selected-filter-when.js

Hi team ! I create this PR to add a new test case to cover the unpin functionality from the agent module dashboard.
I'm working on reusing some existing functionality. I'll add more info as soon I advance with the development

Unpinned a selected filter from agent dashboard

---

CHANGELOG.md
public/controllers/agent/components/register-agent-service.test.ts
public/controllers/agent/components/register-agent-service.ts

Backport https://github.com/wazuh/wazuh-kibana-app/commit/ee0b61817cc1aff1e9e35d1481787179b9fec9a3 from https://github.com/wazuh/wazuh-kibana-app/pull/4849

[Backport 4.4-7.16] Fixed WAZUH_PROTOCOL param suggestion

---

CHANGELOG.md
public/components/security/policies/create-policy.tsx

Added new data-test-subj in Create policy section
Closes #4872

Added data-test-subj create policy

---

CHANGELOG.md
public/components/security/policies/create-policy.tsx

Backport https://github.com/wazuh/wazuh-kibana-app/commit/b9c464565a2273fce38743a36b7c652680419efc from https://github.com/wazuh/wazuh-kibana-app/pull/4873.

[Backport 4.4-2.3-wzd] Added data-test-subj create policy (#4873)

---

CHANGELOG.md
public/components/security/policies/create-policy.tsx

Backport https://github.com/wazuh/wazuh-kibana-app/commit/b9c464565a2273fce38743a36b7c652680419efc from https://github.com/wazuh/wazuh-kibana-app/pull/4873.

[Backport 4.4-7.16] Added data-test-subj create policy

---

public/plugin.ts
public/services/request-handler.js

This PR is to add missing changes to https://github.com/wazuh/wazuh-kibana-app/pull/4831 on branch 7.10
The solution should be tested in the next scenarios:
Environments:
We should test at least with the highlighted cases (in bold).

[4.4-7.10] Add missing changes of centralized request service

---

CHANGELOG.md

Backport https://github.com/wazuh/wazuh-kibana-app/commit/d0c9e91e1c7ac139b3073247938ec2a69aade946 from https://github.com/wazuh/wazuh-kibana-app/pull/4879.

[Backport 4.4-2.3-wzd] Post-release v4.3.10

---

CHANGELOG.md

Fixes the changelog.
Closes #4887 
--
--

Fix Changelog for 7.10

---

CHANGELOG.md

Fixes the changelog.
Closes #4887 
--
--

Fix Changelog for 7.16

---

CHANGELOG.md

Fixes the changelog.
Closes #4887 
--
--

Fix Changelog for WzD

---

.github/workflows/eslint.yml
.github/workflows/unit-test.yml

Updates the patterns to match 4.5 branches
--
--
--

Update patterns to match branches

---

CHANGELOG.md
public/components/agents/fim/inventory/filterBar.tsx
public/components/agents/prompts/prompt-agent-feature-version.tsx
public/components/agents/sca/inventory.tsx
public/components/common/hocs/withButtonOpenOnClick.tsx
public/components/common/hocs/withGlobalBreadcrumb.tsx
public/components/common/hocs/with_module_tab_loader.tsx
public/components/common/modules/panel/main-panel.tsx
public/components/common/welcome/components/sca_scan/sca_scan.tsx
public/components/health-check/components/check-result.tsx
public/components/overview/mitre_attack_intelligence/all_resources_search_results.tsx
public/components/overview/mitre_attack_intelligence/resources.tsx
public/components/security/roles/edit-role-table.tsx
public/components/wz-search-bar/wz-search-badges.tsx
public/components/wz-search-bar/wz-search-bar.test.tsx
public/controllers/management/components/management/configuration/office365/components/SubscriptionTab/__snapshots__/SubscriptionTab.test.tsx.snap
public/controllers/management/components/management/configuration/office365/components/api-auth-tab/__snapshots__/api-auth-tab.test.tsx.snap
public/controllers/management/components/management/configuration/office365/components/general-tab/__snapshots__/general-tab.test.tsx.snap

> Ported from https://github.com/wazuh/wazuh-kibana-app/pull/4688
> Thanks, @jctello 
This PR addresses many typos observed in `tsx` files. Some typos were visible in the UI, others were part of the module description and others of comments in the code.

Typo correction (#4688)

---

CHANGELOG.md
public/components/overview/compliance-table/compliance-table.tsx
public/react-services/generic-request.js

[Describe what this change achieves]
[List any issues this PR will resolve]

[Backport 4.5] 4711 error not caught and wrong error message in pci module 

---

docker/imposter/agents/summary_status.json
docker/imposter/wazuh-config.yml

This PR adds a valid response to the [/agents/summary/status](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.get_agent_summary_status) endpoint on imposter for the development environments.
https://github.com/wazuh/wazuh-kibana-app/issues/4388

Add endpoint response

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

Backport from https://github.com/wazuh/wazuh-kibana-app/pull/5021

[Backport 4.4-7.16] Add validation to agent name

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

Backport from https://github.com/wazuh/wazuh-kibana-app/pull/5021

[Backport 4.4-2.4-wzd] Add validation to agent name

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

[Backport 4.4-7.16] Add length validation to agent name

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js
public/controllers/agent/wazuh-config/index.ts

Backport https://github.com/wazuh/wazuh-kibana-app/commit/17936a9f5c62ff93553654413faa3550b11be55b from https://github.com/wazuh/wazuh-kibana-app/pull/5045.

[Backport 4.4-2.4-wzd] Fix section deploy new agent

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js
public/controllers/agent/wazuh-config/index.ts

Backport https://github.com/wazuh/wazuh-kibana-app/commit/17936a9f5c62ff93553654413faa3550b11be55b from https://github.com/wazuh/wazuh-kibana-app/pull/5045.

[Backport 4.4-7.16] Fix section deploy new agent

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js
public/controllers/agent/register-agent/__snapshots__/register-agent-button-group.test.tsx.snap
public/controllers/agent/register-agent/register-agent-button-group.test.tsx
public/controllers/agent/register-agent/register-agent-button-group.tsx
public/controllers/agent/wazuh-config/index.ts

Backport https://github.com/wazuh/wazuh-kibana-app/commit/e71b344b598c77a0af6ea414abb721666118353c from #5063

Added default selected options in Deploy Agent page (#5063)

---

CHANGELOG.md
common/api-info/endpoints.json
common/api-info/security-actions.json
common/constants.ts
public/components/agents/sca/inventory.tsx
public/components/agents/sca/inventory/checks-table.tsx
public/components/common/welcome/components/sca_scan/sca_scan.tsx

Backport bf7fbb47528c53e726edb9ab0c19770992b89d3f from https://github.com/wazuh/wazuh-kibana-app/pull/5031.

[backport 4.4-7.16] Fix filtering of `not applicable` SCA checks using `result` filter

---

CHANGELOG.md
public/components/visualize/visualizations.js
server/integration-files/visualizations/overview/overview-nist.ts

Replace 'Requiments' by 'Requirements'
Closes #5099
Check the title has changed and is correct.

Fix mispeliing in NIST module

---

CHANGELOG.md
public/components/visualize/visualizations.js
server/integration-files/visualizations/overview/overview-nist.ts

Backport https://github.com/wazuh/wazuh-kibana-app/commit/afd754a4efc6a8fa6f9b2669cd0e3ef606cf2897 from https://github.com/wazuh/wazuh-kibana-app/pull/5107.

[Backport 4.4-7.10] Fix mispeliing in NIST module

---

CHANGELOG.md
server/controllers/wazuh-reporting.ts
server/lib/reporting/audit-request.ts
server/lib/reporting/base-query.ts
server/lib/reporting/extended-information.ts
server/lib/reporting/gdpr-request.ts
server/lib/reporting/overview-request.ts
server/lib/reporting/pci-request.ts
server/lib/reporting/rootcheck-request.ts
server/lib/reporting/summary-table.ts
server/lib/reporting/syscheck-request.ts
server/lib/reporting/tsc-request.ts
server/lib/reporting/vulnerability-request.ts

Backport c54058037361a724126d6bf8b7a6f6254e0a6670 from https://github.com/wazuh/wazuh-kibana-app/pull/5131.

[Backport 4.4-7.10] Fix Alerts Summary table truncated results

---

CHANGELOG.md
server/controllers/wazuh-reporting.ts
server/lib/reporting/audit-request.ts
server/lib/reporting/base-query.ts
server/lib/reporting/extended-information.ts
server/lib/reporting/gdpr-request.ts
server/lib/reporting/overview-request.ts
server/lib/reporting/pci-request.ts
server/lib/reporting/rootcheck-request.ts
server/lib/reporting/summary-table.ts
server/lib/reporting/syscheck-request.ts
server/lib/reporting/tsc-request.ts
server/lib/reporting/vulnerability-request.ts

Backport c54058037361a724126d6bf8b7a6f6254e0a6670 from https://github.com/wazuh/wazuh-kibana-app/pull/5131.

[Backport 4.4-7.16] Fix Alerts Summary table truncated results

---

CHANGELOG.md
server/start/cron-scheduler/save-document.ts

Backport 6a6ea1f8af52fa63b30a39fb7589ccf4847e71b3 from https://github.com/wazuh/wazuh-kibana-app/pull/5150

[Backport 4.4-7.16] Serialize cronjob doc and remove type property

---

CHANGELOG.md
public/controllers/agent/components/register-agent-service.ts
public/controllers/agent/components/register-agent.js
public/controllers/agent/register-agent/steps/wz-manager-address.tsx

Backport b167d6c4bc65b1b42029ddbab13c99c99cd43428 from #5166.

[Backport 4.4-2.4-wzd] Added server address and wazuh protocol definition in Deploy agent section

---

CHANGELOG.md
public/styles/common.scss

Backport 018a22501c79c118a6820018176615ffde943b19 from #5177.

[Backport 4.4-7.10] Agents table action buttons style fix

---

CHANGELOG.md
public/kibana-integrations/discover/application/angular/doc_table/components/table_row/_open.scss
public/kibana-integrations/discover/application/angular/doc_table/components/table_row/open.html

Backport https://github.com/wazuh/wazuh-kibana-app/commit/57f0e9fab6fa9dbfb8f0b396f8a7d1ae52317607 from https://github.com/wazuh/wazuh-kibana-app/pull/5137.

[Backport 4.4-7.16] Fix button styling in event view

---

CHANGELOG.md
public/components/agents/vuls/inventory/detail.tsx
public/components/agents/vuls/inventory/table.tsx

Backport 08fc532046f0148840d583383117a9d0dedf2bf6 from https://github.com/wazuh/wazuh-kibana-app/pull/5200.

[Backport 4.4-7.10] Fix a crash in the vulnerability details flyout

---

CHANGELOG.md
public/components/agents/vuls/inventory/detail.tsx
public/components/agents/vuls/inventory/table.tsx

Backport 08fc532046f0148840d583383117a9d0dedf2bf6 from https://github.com/wazuh/wazuh-kibana-app/pull/5200.

[Backport 4.4-7.16] Fix a crash in the vulnerability details flyout

---

CHANGELOG.md
public/components/agents/syscollector/inventory.tsx
public/components/common/modules/discover/row-details.tsx
public/components/common/welcome/agents-welcome.js
public/controllers/agent/components/register-agent.js
public/controllers/management/components/management/configuration/configuration-no-agent.js
public/controllers/management/components/management/ruleset/views/rule-info.tsx
public/utils/check-plugin-version.tsx

Backport https://github.com/wazuh/wazuh-kibana-app/commit/39d75a7f0d9cb87ad7677148ca1269fdbe70b69b from https://github.com/wazuh/wazuh-kibana-app/pull/5197.

[Backport 4.5-7.10] Add `rel="noopener noreferrer"` in documentation links 

---

CHANGELOG.md
public/components/agents/syscollector/inventory.tsx
public/components/common/modules/discover/row-details.tsx
public/components/common/welcome/agents-welcome.js
public/controllers/agent/components/register-agent.js
public/controllers/management/components/management/configuration/configuration-no-agent.js
public/controllers/management/components/management/ruleset/views/rule-info.tsx
public/utils/check-plugin-version.tsx

Backport https://github.com/wazuh/wazuh-kibana-app/commit/39d75a7f0d9cb87ad7677148ca1269fdbe70b69b from https://github.com/wazuh/wazuh-kibana-app/pull/5197.

[Backport 4.5-7.16] Add `rel="noopener noreferrer"` in documentation links (#5197)

---

CHANGELOG.md
public/components/common/hooks/use-kbn-loading-indicator.ts

Reverts wazuh/wazuh-kibana-app#5217

Revert "[Backport 4.5] Fix cannot read null properties bug in settings section"

---

CHANGELOG.md
public/components/common/hooks/use-kbn-loading-indicator.ts

Backport https://github.com/wazuh/wazuh-kibana-app/commit/4c113f7f613e0c52d1e070721f64056c2b38d7e2 from https://github.com/wazuh/wazuh-kibana-app/pull/5135.

[Backport 4.5] Fix cannot read null properties bug in settings section

---

CHANGELOG.md
public/components/add-modules-data/module-guide.js
public/components/agents/fim/inventory.tsx
public/components/common/util/markdown/markdown.test.tsx
public/components/common/util/markdown/markdown.tsx
public/components/health-check/container/health-check.container.tsx
public/components/management/cluster/cluster-disabled.js
public/components/security/roles-mapping/components/rule-editor.tsx
public/components/settings/configuration/components/categories/components/category/category.tsx
public/components/settings/configuration/components/header.tsx
public/components/wz-blank-screen/wz-blank-screen.js
public/controllers/agent/components/register-agent.js
public/controllers/management/components/management/configuration/util-components/help-button-popover.js
public/kibana-integrations/discover/application/angular/directives/no_results.js
public/react-services/saved-objects.js

the rel="noopener noreferrer" attribute is added to external links
- #5038

Add noopener noreferrer to externals links

---

CHANGELOG.md
public/components/add-modules-data/module-guide.js
public/components/agents/fim/inventory.tsx
public/components/common/util/markdown/markdown.test.tsx
public/components/common/util/markdown/markdown.tsx
public/components/health-check/container/health-check.container.tsx
public/components/management/cluster/cluster-disabled.js
public/components/security/roles-mapping/components/rule-editor.tsx
public/components/settings/configuration/components/categories/components/category/category.tsx
public/components/settings/configuration/components/header.tsx
public/components/wz-blank-screen/wz-blank-screen.js
public/controllers/agent/components/register-agent.js
public/controllers/management/components/management/configuration/util-components/help-button-popover.js
public/kibana-integrations/discover/application/angular/directives/no_results.js
public/react-services/saved-objects.js

Backport https://github.com/wazuh/wazuh-kibana-app/commit/c1db0b28925be2231fc49980ad8b1ff4b99d41dc from [#5274](https://github.com/wazuh/wazuh-kibana-app/pull/5274).

[Backport 4.5-7.16] Add noopener noreferrer to externals links (#5274)

---

CHANGELOG.md
public/components/add-modules-data/module-guide.js
public/components/agents/fim/inventory.tsx
public/components/common/util/markdown/markdown.test.tsx
public/components/common/util/markdown/markdown.tsx
public/components/health-check/container/health-check.container.tsx
public/components/management/cluster/cluster-disabled.js
public/components/security/roles-mapping/components/rule-editor.tsx
public/components/settings/configuration/components/categories/components/category/category.tsx
public/components/settings/configuration/components/header.tsx
public/components/wz-blank-screen/wz-blank-screen.js
public/controllers/agent/components/register-agent.js
public/controllers/management/components/management/configuration/util-components/help-button-popover.js
public/kibana-integrations/discover/application/angular/directives/no_results.js
public/react-services/saved-objects.js

Backport https://github.com/wazuh/wazuh-kibana-app/commit/c1db0b28925be2231fc49980ad8b1ff4b99d41dc from https://github.com/wazuh/wazuh-kibana-app/pull/5274.

[Backport 4.5-7.10] Add noopener noreferrer to externals links (#5274)

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

backport https://github.com/wazuh/wazuh-kibana-app/commit/7140b80b6433a858509c0ece826dd171a0f3e3d6 from #5285

[Backport 4.4-7.10] Fixed Deploy Agent wrong use of connection secure property (#5285)

---

docker/runner/docker-compose.yml
package.json
scripts/manifest.js
scripts/runner.js

Backport https://github.com/wazuh/wazuh-kibana-app/commit/c7d97f2d71fbe772541918953e79310d196dce50 from #5305.

[Backport #5305 to 4.5-7.16] Add dockerized yarn runner

---

docker/runner/docker-compose.yml
package.json
scripts/manifest.js
scripts/runner.js

Backport https://github.com/wazuh/wazuh-kibana-app/commit/c7d97f2d71fbe772541918953e79310d196dce50 from #5305.

[Backport #5305 to 4.5-7.10] Add dockerized yarn runner

---

README.md
common/api-info/security-actions.json
scripts/tag.py

Backport https://github.com/wazuh/wazuh-kibana-app/commit/d69d840c0fbc2c1c76a8f0e18b73a0c2f919ac96 to 4.4-7.16

[Backport 4.4-7.16] Bump Wazuh and platform versions for v4.4.1

---

CHANGELOG.md
Makefile
scripts/tag.py

[Backport 7.16]Add the tag generation script to the 4.3-x branch (#5391)

---

CHANGELOG.md
Makefile
scripts/tag.py

[Backport 7.10]Add the tag generation script to the 4.3-x branch (#5391)

---

CHANGELOG.md
README.md
opensearch_dashboards.json
package.json
scripts/tag.py

This pull request prepares the app for Wazuh 4.4.2.
- #5405

Bump Wazuh and platform versions for v4.4.2

---

CHANGELOG.md
README.md
kibana.json
package.json
scripts/tag.py

[Backport 4.4-7.16]Bump Wazuh and platform versions for v4.4.2 (#5406)

---

CHANGELOG.md
README.md
kibana.json
package.json
scripts/tag.py

[Backport 4.4-7.10]Bump Wazuh and platform versions for v4.4.2 (#5406)

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

Changed the title and added a description to step 3 of the deploy a new agent section. This step is now optional.
#5415 
Verify that the title of step 3 and the description below it look like in the following image:

Changed the title and added a description to step 3 of the deploy a new agent section

---

CHANGELOG.md
public/controllers/management/components/management/groups/groups-editor.js

Backport 56e156fffc21e16685fbe1425e29ac4bc86ee0c7 from https://github.com/wazuh/wazuh-kibana-app/pull/5423

[Backport 4.5-7.10] Fix error when using invalid group configuration

---

CHANGELOG.md
public/controllers/management/components/management/groups/groups-editor.js

Backport 56e156fffc21e16685fbe1425e29ac4bc86ee0c7 from https://github.com/wazuh/wazuh-kibana-app/pull/5423

[Backport 4.5-7.16] Fix error when using invalid group configuration

---

CHANGELOG.md
scripts/tag.py

Update of the revision for the new CR
[List any issues this PR will resolve]

Update revision and tag_suffix

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

**Changed the title of step 3 of the deploy a new agent section:** 
"Optionally, assign a name and a group to the agent"
**by:** 
"Optional settings"
----
**Added a title to the agent name input of the deploy a new agent section:**
"Assign an agent name"
----
**Changed the description of step 3 of the deploy a new agent section:** 
"The agent name is set as the name of the host where it is deployed. You can set your own name in the field below. Note that the agent name cannot be changed once registered."
**by:** 
"The deployment sets the endpoint hostname as the agent name by default. Optionally, you can set the agent name below."
----
**Changed the placeholder of the agent name input of the deploy a new agent section:**
"Name agent"
**to:**
"Agent name"
----
**Added callout below the …

 Changed step 3 in the "Deploy a new agent" section.

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

Backport https://github.com/wazuh/wazuh-kibana-app/commit/fc10c84a77e9834ff0875de43389c5a1c517f219 from #5470

[Backport 4.5-7.16] Fix macos apple install command

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

Backpor b38ed8983ed3cdec7e4a873c56e4274b169f09de from  #5470

[Backport 4.5-7.10] Fix macos apple install command

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

Backport commit 3200cc9e50d78bc934786edf02625f3ee2a2cdd0 from #5481

[Backport 4.4-7.10] Change macOS register agent installation script (#5481)

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

Backport commit 3200cc9e50d78bc934786edf02625f3ee2a2cdd0 from #5481

[Backport 4.4-7.16] Change macOS register agent installation script (#5481)

---

public/components/common/form/hooks.test.tsx
public/components/common/form/hooks.tsx
public/components/common/form/index.tsx
public/components/common/form/types.ts

Adapting the common form component to reuse in the Register agent section
Closes #5441

[Redesign add agent] Register agent reuse common/form component (Settings > Configuration)

---

CHANGELOG.md
public/components/common/welcome/agents-welcome.js
public/controllers/agent/agents.js

Backport https://github.com/wazuh/wazuh-kibana-app/commit/522d3cdfbc81cb6a50ed423ba93f9f081d06e43f from https://github.com/wazuh/wazuh-kibana-app/pull/5451.

[Backport 4.5-7.10]Remove deprecated code (#5451)

---

CHANGELOG.md
public/components/common/welcome/agents-welcome.js
public/controllers/agent/agents.js

Backport https://github.com/wazuh/wazuh-kibana-app/commit/522d3cdfbc81cb6a50ed423ba93f9f081d06e43f from https://github.com/wazuh/wazuh-kibana-app/pull/5451.

[Backport 4.5-7.16]Remove deprecated code (#5451)

---

CHANGELOG.md
public/components/common/welcome/agents-welcome.js
public/controllers/agent/agents.js
public/controllers/management/components/management/configuration/configuration-switch.js

Backport https://github.com/wazuh/wazuh-kibana-app/commit/f5be86d213db79fb42c8af9098660c961a3e1732 from https://github.com/wazuh/wazuh-kibana-app/pull/5460.

[Backport 4.5-7.16] Removes unnecessary requests in config, inventory data or statistics

---

.gitignore
CHANGELOG.md
public/controllers/agent/components/register-agent.js

Backport https://github.com/wazuh/wazuh-kibana-app/commit/be80961d640d623f2ae37e81e118d74222a00bea from https://github.com/wazuh/wazuh-kibana-app/pull/5416.

[Backport 4.4-7.10] Changed step 3 in the "Deploy a new agent" section.

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

Fix macos command. This problem arose when merging changes
#5415

fix macos command

---

CHANGELOG.md
README.md
kibana.json
package.json
scripts/tag.py

Backport https://github.com/wazuh/wazuh-kibana-app/commit/cb8a8bee7f7217031ce94e6241893e611288a146 from https://github.com/wazuh/wazuh-kibana-app/pull/5524.

[Backport 4.4-7.16] Bump Wazuh and platform versions for v4.4.4 (#5524)

---

CHANGELOG.md
README.md
kibana.json
package.json
scripts/tag.py

Backport https://github.com/wazuh/wazuh-kibana-app/commit/cb8a8bee7f7217031ce94e6241893e611288a146 from https://github.com/wazuh/wazuh-kibana-app/pull/5524.

[Backport 4.4-7.10] Bump Wazuh and platform versions for v4.4.4 (#5524)

---

CHANGELOG.md
public/controllers/dev-tools/dev-tools.ts

This pull request fixed an error in the request body parameter suggestions in API Console.
#5520
[wka-pr-5521-tests.md](https://github.com/wazuh/wazuh-kibana-app/files/11650330/wka-pr-5521-tests.md)

Fix error of request body parameter suggestions in API Console

---

CHANGELOG.md
scripts/tag.py

The changelog has been improved, as the information in 4.4.4 was a bit redundant. Also added the changes for the next RC.
- #5543
View changelog change

Improved changelog

---

CHANGELOG.md
scripts/tag.py

Backport https://github.com/wazuh/wazuh-kibana-app/commit/0e7201ff8b7fb6a76de789160b94e665c0af41e1 from https://github.com/wazuh/wazuh-kibana-app/pull/5544.

[Backport 4.4-7.16] Improved changelog (#5544)

---

CHANGELOG.md
scripts/tag.py

Backport https://github.com/wazuh/wazuh-kibana-app/commit/0e7201ff8b7fb6a76de789160b94e665c0af41e1 from https://github.com/wazuh/wazuh-kibana-app/pull/5544.

[Backport 4.4-7.10] Improved changelog (#5544)

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

This pull request fixes windows agent service name **"WazuhSvc"** to **"Wazuh"** in the deploy new agent wizard.
#5531 
- Go to Agents menu.
- Click on **Deploy new agent**
- Select **Windows** operating system option.
- Complete other fields.
- In step 7, check that the command is `NET START Wazuh`

Change windows agent service name

---

CHANGELOG.md
public/components/common/welcome/agents-welcome.js

This pull request removes the agent name in the agent info ribbon
https://github.com/wazuh/wazuh-kibana-app/issues/5496
Legend:
| Ensure the agent name is not displayed in the agent info ribbon | :black_circle: | :black_circle: | :black_circle: |
**Details**
<details>
<summary>:black_circle: Ensure the agent name is not displayed in the agent info ribbon</summary>
</details>

Remove agent name in agent info ribbon

---

CHANGELOG.md
docker/imposter/agents/agent.json
docker/imposter/agents/agents.json
docker/imposter/agents/group.json
docker/imposter/cluster/cluster_node_info.json
docker/imposter/syscollector/netaddr.js
docker/imposter/syscollector/ports.js
docker/imposter/wazuh-config.yml
public/components/agents/syscollector/components/syscollector-table.tsx
public/components/common/welcome/agents-info.js
public/components/management/cluster/node-list.tsx
public/controllers/agent/components/agents-table.js
public/controllers/management/components/management/configuration/client/client.js
public/controllers/management/components/management/configuration/global-configuration/global-configuration-remote.js
public/controllers/management/components/management/groups/group-agents-table.js

Backport 1153509927073082167fb61f3aecc87536d8a3f3 from https://github.com/wazuh/wazuh-kibana-app/pull/5471

[Backport 4.4-7.16] Fix IPV6 visualizations

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

Backport 2bc89843ce5c0bd5ce61ffcd18f0f8c29b9fa34e from https://github.com/wazuh/wazuh-kibana-app/pull/5538

[Backport 4.4-7.16] Change windows agent service name

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

Backport 2bc89843ce5c0bd5ce61ffcd18f0f8c29b9fa34e from https://github.com/wazuh/wazuh-kibana-app/pull/5538

[Backport 4.4-7.10] Change windows agent service name

---

CHANGELOG.md
public/components/common/welcome/agents-welcome.js

Backport 858205f706394a236a11ac73ed43abef45ef4146 from https://github.com/wazuh/wazuh-kibana-app/pull/5497

[Backport 4.4-7.16] Remove agent name in agent info ribbon

---

CHANGELOG.md
public/components/common/welcome/agents-welcome.js

Backport 858205f706394a236a11ac73ed43abef45ef4146 from https://github.com/wazuh/wazuh-kibana-app/pull/5497

[Backport 4.4-7.10] Remove agent name in agent info ribbon

---

.github/workflows/eslint.yml
.github/workflows/unit-test.yml
common/api-info/endpoints.json
common/services/web_documentation.test.ts
docker/wazuh-4.4-wz/pre.sh
docker/wazuh-4.4-wz/rel.sh
docker/wazuh-4.x-es/pre.sh
docker/wazuh-4.x-es/rel.sh
public/controllers/management/components/management/configuration/office365/components/SubscriptionTab/__snapshots__/SubscriptionTab.test.tsx.snap
public/controllers/management/components/management/configuration/office365/components/api-auth-tab/__snapshots__/api-auth-tab.test.tsx.snap
public/controllers/management/components/management/configuration/office365/components/general-tab/__snapshots__/general-tab.test.tsx.snap

Backport https://github.com/wazuh/wazuh-kibana-app/commit/1ae5f19a9edc967187b2d946aad6e8d8f0afff14 from #5601

[Backport 4.5.1-7.10] Update test snapshots for 4.5

---

.github/workflows/eslint.yml
.github/workflows/unit-test.yml
common/api-info/endpoints.json
common/services/web_documentation.test.ts
docker/wazuh-4.4-wz/pre.sh
docker/wazuh-4.4-wz/rel.sh
docker/wazuh-4.x-es/pre.sh
docker/wazuh-4.x-es/rel.sh
public/controllers/management/components/management/configuration/office365/components/SubscriptionTab/__snapshots__/SubscriptionTab.test.tsx.snap
public/controllers/management/components/management/configuration/office365/components/api-auth-tab/__snapshots__/api-auth-tab.test.tsx.snap
public/controllers/management/components/management/configuration/office365/components/general-tab/__snapshots__/general-tab.test.tsx.snap

Backport https://github.com/wazuh/wazuh-kibana-app/commit/1ae5f19a9edc967187b2d946aad6e8d8f0afff14 from https://github.com/wazuh/wazuh-kibana-app/pull/5601

[Backport 4.5.1] Update test snapshots for 4.5

---

CHANGELOG.md
public/controllers/agent/agents-preview.js
public/controllers/agent/components/agents-preview.js

Backport 53bf022cefa20db57aa854edad240ce1a98d51e9 from #5490

[Backport 4.5.1-7.16] Fix agents active coverage stat as NaN

---

CHANGELOG.md
public/controllers/agent/agents-preview.js
public/controllers/agent/components/agents-preview.js

Backport 53bf022cefa20db57aa854edad240ce1a98d51e9 from #5490

[Backport 4.5.1-7.10] Fix agents active coverage stat as NaN

---

plugins/main/common/api-info/endpoints.json
plugins/main/scripts/generate-api-data.js

Backport f33281701a6a3255b500527acf07d255f29bc921 from #5611

[Backport 4.6.0-7.16] Fix API endpoint documentation link in static file

---

CHANGELOG.md
docker/imposter/security/security-actions.json
docker/imposter/security/security-me-policies.js
docker/imposter/security/security-policies.json
docker/imposter/security/security-roles.json
docker/imposter/security/security-rules.json
docker/imposter/security/users.json
docker/imposter/wazuh-config.yml
plugins/main/common/constants.ts
plugins/main/public/components/security/main.tsx
plugins/main/public/components/security/policies/create-policy.tsx
plugins/main/public/components/security/policies/edit-policy.tsx
plugins/main/public/components/security/policies/policies-table.tsx
plugins/main/public/components/security/policies/policies.tsx
plugins/main/public/components/security/roles-mapping/components/roles-mapping-create.tsx
plugins/main/public/components/security/roles-mapping/components/roles-mapping-edit.tsx
plugins/main/public/components/security/roles-mapping/components/roles-mapping-table.tsx
plugins/main/public/components/security/roles-mapping/components/rule-editor.tsx
plugins/main/public/components/security/roles-mapping/roles-mapping.tsx
plugins/main/public/components/security/roles/create-role.tsx
plugins/main/public/components/security/roles/edit-role-table.tsx
plugins/main/public/components/security/roles/edit-role.tsx
plugins/main/public/components/security/roles/roles-table.tsx
plugins/main/public/components/security/roles/roles.tsx
plugins/main/public/components/security/users/components/create-user.tsx
plugins/main/public/components/security/users/components/edit-user.tsx
plugins/main/public/components/security/users/components/users-table.tsx
plugins/main/public/components/security/users/users.tsx

Backport 252822a4036a17580e7c5f2c848f45e45f3cedae from #5551

[Backport 4.6.0-7.16] Add specific RBAC permissions to Security section

---

docker/images/kbn-7.17.11-dev.Dockerfile
docker/kbn-dev/dev.sh

This PR adds compatibility with Kibana 7.17.11
#5623 
In the issue
Test the environment

Add kbn-dev 7.17.11

---

CHANGELOG.md
README.md
opensearch_dashboards.json
package.json
scripts/tag.py

This pull request prepares the app for Wazuh 4.4.5.
- #5638

Bump Wazuh and platform versions for v4.4.5

---

CHANGELOG.md
README.md
kibana.json
package.json
scripts/tag.py

Backport https://github.com/wazuh/wazuh-kibana-app/commit/b33c4a5dfcc4349dd0c4635f8b242f5208f17722 from https://github.com/wazuh/wazuh-kibana-app/pull/5639.

[Backport 4.4.5-7.10] Bump Wazuh and platform versions for v4.4.5 (#5639)

---

scripts/tag.py

This PR prepares the taggiing script for 
#5637 
-
-

Prepare tag.py for v4.4.5-rc1

---

scripts/tag.py

Backport https://github.com/wazuh/wazuh-kibana-app/commit/c10eb4eef3cec095d1c9db8e2e927bcf53e5345c from https://github.com/wazuh/wazuh-kibana-app/pull/5645.

[Backport 4.4.5-7.10] Prepare tag.py for v4.4.5-rc1 

---

scripts/tag.py

Add support for Wazuh 4.4.5-rc2
#5658

Add support for Wazuh 4.4.5-rc2

---

plugins/main/public/components/common/welcome/agents-welcome.js

When the branch synchronization conflicts were solved, a variable that should have been there was removed, this PR adds it back and deletes things that were added and are not being used. 
- #5681

Fixes redirection problem to inventory data, stats and configuration in an agent

---

CHANGELOG.md

Removed changelog entries in 4.6.0. These changes are from 4.4.4.
- #5690

Fix 4.6.0 changelog merge errors

---

CHANGELOG.md
docker/imposter/agents/configuration.js
docker/imposter/agents/configuration/agent_labels.json
docker/imposter/agents/configuration/default.json
docker/imposter/cluster/configuration/agent_labels.json
docker/imposter/manager/configuration.js
docker/imposter/manager/configuration/agent_labels.json
docker/imposter/manager/configuration/default.json
docker/imposter/manager/configuration/monitor_reports.json
docker/imposter/wazuh-config.yml
public/controllers/management/components/management/configuration/alerts/alerts-labels.js
public/controllers/management/components/management/configuration/alerts/alerts.js

Backport 6a181729b7ce6fa6f2f05f986379c9a1d4785ce4 from #5687.

[Backport 4.5.1-7.16] Fix API request to get the manager labels and broken documentation link

---

CHANGELOG.md
docker/imposter/agents/configuration.js
docker/imposter/agents/configuration/agent_labels.json
docker/imposter/agents/configuration/default.json
docker/imposter/cluster/configuration/agent_labels.json
docker/imposter/manager/configuration.js
docker/imposter/manager/configuration/agent_labels.json
docker/imposter/manager/configuration/default.json
docker/imposter/manager/configuration/monitor_reports.json
docker/imposter/wazuh-config.yml
public/controllers/management/components/management/configuration/alerts/alerts-labels.js
public/controllers/management/components/management/configuration/alerts/alerts.js

Backport 6a181729b7ce6fa6f2f05f986379c9a1d4785ce4 from #5687.

[Backport 4.5.1-7.10] Fix API request to get the manager labels and broken documentation link

---

CHANGELOG.md
public/react-services/reporting.js
server/controllers/wazuh-reporting.ts
server/lib/reporting/base-query.ts
server/lib/reporting/extended-information.ts
server/lib/reporting/gdpr-request.ts
server/lib/reporting/pci-request.ts
server/lib/reporting/rootcheck-request.ts
server/lib/reporting/tsc-request.ts
server/routes/wazuh-reporting.test.ts
server/routes/wazuh-reporting.ts

Backport from #5714 to 4.5.1-7.16

[Backport 4.5.1-7.16] Fix server side query in pdf report filter

---

CHANGELOG.md
common/constants.ts
common/services/settings.test.ts
server/routes/wazuh-reporting.test.ts

Backport https://github.com/wazuh/wazuh-kibana-app/commit/a997dcf1ae7006b0b1a4675777382ac63822a23a from https://github.com/wazuh/wazuh-kibana-app/pull/5766.

[Backport 4.6.0-7.10] Fix outdated year in PDF report footer

---

CHANGELOG.md

Merge 4.5-7.10 into 4.5.1-7.10

Merge 4.5-7.10 into 4.5.1-7.10

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

Backport b4fa960b0e65fe75ff5f1b27317d0b35fc598c1b from #5764

[Backport 4.5.2-7.16] Update step 7 in deployment of Oracle Linux 6+

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

Backport https://github.com/wazuh/wazuh-kibana-app/commit/b4fa960b0e65fe75ff5f1b27317d0b35fc598c1b from https://github.com/wazuh/wazuh-kibana-app/pull/5764

[Backport 4.5.2-7.10] Update step 7 in deployment of Oracle Linux 6+

---

CHANGELOG.md
opensearch_dashboards.json

Merge 4.5.1 into 4.5.2

---

CHANGELOG.md
plugins/main/package.json
plugins/main/scripts/release/tag.js

This PR aims to change the OpenSerarch version to 2.8.0 
#5831

Modify opensearch version in 4.6.0

---

CHANGELOG.md
kibana.json
package.json

Backport 2664730673a3e2777ad6ac1bc770c87c6247f77e from #5844.

[Backport 4.5.2-7.16] Bump revision to 02 (4.5.2)

---

CHANGELOG.md
kibana.json
package.json

Backport 2664730673a3e2777ad6ac1bc770c87c6247f77e from #5844.

[Backport 4.5.2-7.10] Bump revision to 02 (4.5.2)

---

docker/README.md
docker/wazuh-4.5-wz/README.md
docker/wazuh-4.5-wz/config/certs/ca.json
docker/wazuh-4.5-wz/config/certs/cfssl.json
docker/wazuh-4.5-wz/config/certs/host.json
docker/wazuh-4.5-wz/config/filebeat/filebeat.yml
docker/wazuh-4.5-wz/config/imposter/api_info.json
docker/wazuh-4.5-wz/config/imposter/login.js
docker/wazuh-4.5-wz/config/imposter/wazuh-config.yml
docker/wazuh-4.5-wz/config/wazuh_cluster/wazuh_manager.conf
docker/wazuh-4.5-wz/config/wazuh_dashboard/wazuh.yml
docker/wazuh-4.5-wz/config/wazuh_dashboard/wazuh_dashboard.yml
docker/wazuh-4.5-wz/config/wazuh_dashboard/wazuh_dashboard_saml.yml
docker/wazuh-4.5-wz/config/wazuh_indexer/config-saml.yml
docker/wazuh-4.5-wz/config/wazuh_indexer/config.yml
docker/wazuh-4.5-wz/config/wazuh_indexer/internal_users.yml
docker/wazuh-4.5-wz/config/wazuh_indexer/opensearch.yml
docker/wazuh-4.5-wz/config/wazuh_indexer/roles.yml
docker/wazuh-4.5-wz/config/wazuh_indexer/roles_mapping.yml
docker/wazuh-4.5-wz/config/wazuh_indexer/wazuh.indexer.yml
docker/wazuh-4.5-wz/enable_saml.sh
docker/wazuh-4.5-wz/pre.sh
docker/wazuh-4.5-wz/pre.yml
docker/wazuh-4.5-wz/rel.sh
docker/wazuh-4.5-wz/rel.yml

Backport 622f346ecbfdec2edd43326cdfd9bc01ec0cccd7 from #5797.

[Backport 4.5.2-7.10]Add environments for 4.5 (#5797)

---

plugins/main/common/constants.ts

Updates OpenSearch's documentation link to version 2.8.
#5883

Update OpenSearch's documentation link

---

CHANGELOG.md
docker/imposter/api-info/api_info.json
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/main/public/components/common/tables/__snapshots__/table-with-search-bar.test.tsx.snap

Bump Wazuh version 4.7.1
- #5904

Bump Wazuh v4.7.1

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json

Bump v4.6.0 beta1

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json

Bump revision for 4.6.0

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

Backport b697a28ecd0d4eea54694f19e3e3c22676475290 from #5925

[Backport 4.5.3-7.10] Fix install agent command on SUSE

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

Backport b697a28ecd0d4eea54694f19e3e3c22676475290 from #5925

[Backport 4.5.3-7.16] Fix install agent command on SUSE

---

CHANGELOG.md
opensearch_dashboards.json
package.json

Bump 4.5.3 revision 02 - RC2

---

CHANGELOG.md
kibana.json
package.json

Bump 4.5.3-7.10 revision 02 - RC2

---

CHANGELOG.md
kibana.json
package.json

Bump 4.5.3-7.16 revision 02 - RC2

---

CHANGELOG.md
opensearch_dashboards.json
package.json

Bump 4.5.3 revision 01 - RC2

---

CHANGELOG.md
kibana.json
package.json

Bump 4.5.3 - 7.10 revision 01 - RC2

---

CHANGELOG.md
kibana.json
package.json

Bump 4.5.3 - 7.16 revision 01 - RC2

---

plugins/main/public/controllers/agent/components/agents-table.js

Fixes redirection to an agent from the agent table
- #5900

Fix redirection

---

CHANGELOG.md
opensearch_dashboards.json
package.json

Bump 4.5.3 revision 02 - RC3

---

CHANGELOG.md
kibana.json
package.json

Bump 4.5.3 - 7.10 revision 02 - RC3

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json

Bump 4.6.0 - Revision 02 - RC1

---

CHANGELOG.md
kibana.json
package.json

Add support for Wazuh 4.5.4
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6008

Bump 4.5.4-7.16 revision 00

---

CHANGELOG.md
kibana.json
package.json

Add support for Wazuh 4.5.4
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6008

Bump 4.5.4-7.10 revision 00

---

CHANGELOG.md
opensearch_dashboards.json
package.json

Add support for Wazuh 4.5.4
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6008

Bump 4.5.4-2.6.0 revision 00

---

CHANGELOG.md
opensearch_dashboards.json
package.json

Bump revision for new Alpha 1 stage for 4.5.4
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6024

Bump revision 4.5.4 2.6.0 Alpha1

---

CHANGELOG.md
kibana.json
package.json

Bump revision for new Alpha 1 stage for 4.5.4
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6024

Bump revision 4.5.4 7.16.x Alpha1

---

CHANGELOG.md
kibana.json
package.json

Bump revision for new Alpha 1 stage for 4.5.4
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6024

Bump revision 4.5.4 7.10.2 Alpha1

---

.github/ISSUE_TEMPLATE/new_release.md
CHANGELOG.md
CONTRIBUTING.md
README.md
docker/README.md
docker/kbn-dev/README.md
docker/osd-dev/README.md
plugins/main/package.json
plugins/main/public/components/health-check/services/check-index-pattern/check-index-pattern-object.service.ts
plugins/main/public/components/health-check/services/check-pattern-support.service.ts
plugins/main/public/components/visualize/wz-visualize.js
plugins/main/public/kibana-integrations/kibana-vis.js
plugins/main/public/react-services/error-management/docs/README.md
plugins/main/public/react-services/saved-objects.js
plugins/main/public/templates/settings/settings.html
plugins/main/server/lib/initial-wazuh-config.ts

Merge 4.6.0 into 4.7.0
> IMPORTANT: Merge PR strategy: Create a merge commit

Merge 4.6.0 into 4.7.0

---

.github/ISSUE_TEMPLATE/new_release.md
CHANGELOG.md
CONTRIBUTING.md
README.md
docker/README.md
docker/kbn-dev/README.md
docker/osd-dev/README.md
plugins/main/common/api-info/endpoints.json
plugins/main/common/api-info/security-actions.json
plugins/main/package.json
plugins/main/public/components/health-check/services/check-index-pattern/check-index-pattern-object.service.ts
plugins/main/public/components/health-check/services/check-pattern-support.service.ts
plugins/main/public/components/visualize/wz-visualize.js
plugins/main/public/kibana-integrations/kibana-vis.js
plugins/main/public/react-services/error-management/docs/README.md
plugins/main/public/react-services/saved-objects.js
plugins/main/public/styles/theme/dark/index.dark.scss
plugins/main/public/templates/settings/settings.html
plugins/main/server/lib/initial-wazuh-config.ts

Merge 4.8.0 into master
> IMPORTANT: Merge PR strategy: Create a merge commit

Merge 4.8.0 into master

---

CHANGELOG.md

This pull request fixes an error in the URL of a changelog entry.
#4718

Fix URL on changelog entry

---

plugins/main/yarn.lock

Backport https://github.com/wazuh/wazuh-dashboard-plugins/pull/6069/commits/7a9d907b36da096db845860563f7c08030311bff from https://github.com/wazuh/wazuh-dashboard-plugins/pull/6062

[Backport 4.8.0] Upgrade project dependencies

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json

Bump revision for Alpha2 to 02

Bump 4.7.0 - Revision 02 - Alpha2

---

CHANGELOG.md
plugins/main/common/api-info/endpoints.json
plugins/main/common/api-info/security-actions.json
plugins/main/opensearch_dashboards.json
plugins/main/package.json

Bump revision 03 for 4.7.0-RC1

Bump revision 03 for 4.7.0-RC1

---

plugins/main/package.json

Backport https://github.com/wazuh/wazuh-dashboard-plugins/commit/2d4f2a08d79e05cf2f9bb1d7d306cc60a81f5739 from https://github.com/wazuh/wazuh-dashboard-plugins/pull/6121

[Backport 4.7.0] Fix tests to run sequentially by default

---

plugins/main/package.json

Backport https://github.com/wazuh/wazuh-dashboard-plugins/commit/2d4f2a08d79e05cf2f9bb1d7d306cc60a81f5739 from #6121

[Backport 4.7.1] Fix tests to run sequentially by default

---

plugins/main/package.json

Revert changes of PR #6122

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json

Bump revision 04 for 4.7.0-RC2
- #6143

Bump revision 04 for 4.7.0-RC2

---

.github/workflows/wazuh-build-push-docker-action.yml
CHANGELOG.md
RELEASING.md
docker/kbn-dev/dev.yml
docker/osd-dev/dev.yml
docker/wazuh-4.2-es/pre.yml
docker/wazuh-4.3-wz/pre.yml
docker/wazuh-4.4-wz/pre.yml
docker/wazuh-4.5-wz/pre.yml
docker/wazuh-4.x-es/pre.yml
plugins/main/opensearch_dashboards.json
plugins/main/test/cypress/images/wazuh_manager_filebeat_sources_cmake/Dockerfile
scripts/release/tag.js

Merge 4.7.1 into 4.8.0
> IMPORTANT: Merge PR strategy: Create a merge commit

Merge 4.7.1 into 4.8.0

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json

This pull request bumps the plugin to 4.7.2 revision 00
#6180

Bump 4.7.2 revision 00

---

CHANGELOG.md
plugins/main/common/api-info/endpoints.json
plugins/main/common/api-info/security-actions.json
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

Bump 4.8.0 version revision to 01. 
Closes #6192

Bump revision to 01

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json

Bump revision 02 for 4.7.1-RC2

Bump revision 02 for 4.7.1-RC2

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json

Bump revision 03 for 4.7.1-RC3

  Bump revision 03 for 4.7.1-RC3

---

.github/workflows/wazuh-build-push-docker-action.yml
docker/kbn-dev/dev.yml
docker/osd-dev/dev.yml
docker/wazuh-4.2-es/pre.yml
docker/wazuh-4.3-wz/pre.yml
docker/wazuh-4.4-wz/pre.yml
docker/wazuh-4.5-wz/pre.yml
docker/wazuh-4.x-es/pre.yml
plugins/main/test/cypress/images/wazuh_manager_filebeat_sources_cmake/Dockerfile

Changes filebeat enviroment version
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6238
| Test |  |
| --- |  --- |
| Filebeat version it must be 0.4 | :black_circle: | :black_circle: | :black_circle: |
**Details**
<details>
<summary>:black_circle: Filebeat version it must be 0.4</summary>
</details>

Ugrade filebeat version to 0.4

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json

This pull request bumps the revision to 01 for Wazuh 4.7.2.
#6247

Bump revision to 01 for Wazuh 4.7.2

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps Wazuh version to 4.8.2 revision 00 to add support to the new version. 
```
node scripts/release/bump.js --manifest-changelog ./CHANGELOG.md --manifest-package ./plugins/main/package.json --platform-version 2.10.0 --plugin-main-generate-api-data-spec https://raw.githubusercontent.com/wazuh/wazuh/4.8.1/api/api/spec/spec.yaml --plugins-directory ./plugins --revision 00 --version 4.8.2
```
#6261

Bump version 4.8.2 rev 00

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json

This pull request bumps the revision to 02 for Wazuh 4.7.2.
Parent issue https://github.com/wazuh/wazuh-dashboard-plugins/issues/6270

Bump revision to 02 for Wazuh 4.7.2

---

CHANGELOG.md
plugins/main/common/api-info/endpoints.json
plugins/main/common/api-info/security-actions.json
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

Bump 4.8.0 version revision to 02. 
Closes #6283

Bump revision to 02 for 4.8.0 version

---

CHANGELOG.md
plugins/main/common/api-info/endpoints.json
plugins/main/common/api-info/security-actions.json

Merge 4.8.0 into 4.8.1
> [!CAUTION]

Merge 4.8.0 into 4.8.1

---

CHANGELOG.md
plugins/main/common/api-info/endpoints.json
plugins/main/common/api-info/security-actions.json

Merge 4.8.1 into 4.8.2
> [!CAUTION]

Merge 4.8.1 into 4.8.2

---

CHANGELOG.md
plugins/main/common/api-info/endpoints.json
plugins/main/common/api-info/security-actions.json

Merge 4.8.2 into master
> [!CAUTION]

Merge 4.8.2 into master

---

CHANGELOG.md
plugins/main/common/api-info/endpoints.json
plugins/main/common/api-info/security-actions.json
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/main/public/components/common/tables/__snapshots__/table-with-search-bar.test.tsx.snap
plugins/main/public/controllers/management/components/management/configuration/office365/components/SubscriptionTab/__snapshots__/SubscriptionTab.test.tsx.snap
plugins/main/public/controllers/management/components/management/configuration/office365/components/api-auth-tab/__snapshots__/api-auth-tab.test.tsx.snap
plugins/main/public/controllers/management/components/management/configuration/office365/components/general-tab/__snapshots__/general-tab.test.tsx.snap
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json
plugins/wazuh-endpoints/opensearch_dashboards.json
plugins/wazuh-endpoints/package.json

This pull request bumps the version to 5.0.0.
#6401

Bump 5.0.0

---

docker/imposter/manager/configuration.js
scripts/vulnerabilities-events-injector/DIS_Template.json
scripts/vulnerabilities-events-injector/dataInjectScript.py

This pull request adapts the vulnerabilities events generator to match the latest changes in the vulnerabilities template. It also adds a minor fix to an imposter endpoint.
Closes #6425 
- Go to the folder `/scripts/vulnerabilities-events-injector`
- Run `python3 dataInjectScript.py` script
- Check it created events in the vulnerabilities index-pattern
-

Update the vulnerabilities events injector script

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json

This pull request bumps Wazuh version to 4.7.3 revision 00 to add support to the new version. 
```
node scripts/release/bump.js --manifest-changelog ./CHANGELOG.md --manifest-package ./plugins/main/package.json --platform-version 2.8.0 --plugin-main-generate-api-data-spec https://raw.githubusercontent.com/wazuh/wazuh/v4.7.2/api/api/spec/spec.yaml --plugins-directory ./plugins --revision 00 --version 4.7.3
```
#6427

Bump version 4.7.3

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json

Bump revision 01 for 4.7.3
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6436

Bump revision 01 for 4.7.3 RC1

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json

This pull request bumps the revision to 02 for Wazuh 4.7.3
Closes #6449

Bump revision 02 for 4.7.3 RC2

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps Wazuh version to 4.8.0 revision 05.
```
node scripts/release/bump.js --manifest-changelog ./CHANGELOG.md --manifest-package ./plugins/main/package.json --platform-version 2.10.0 --plugin-main-generate-api-data-spec https://raw.githubusercontent.com/wazuh/wazuh/4.8.0/api/api/spec/spec.yaml --plugins-directory ./plugins --revision 05 --version 4.8.0
```
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6467

Bump revision 05 for 4.8.0 Beta 3

---

CHANGELOG.md
plugins/main/common/constants.ts
plugins/main/public/components/common/welcome/overview-welcome.js
plugins/main/public/components/common/welcome/welcome.scss
plugins/main/public/components/overview/vulnerabilities/dashboards/overview/dashboard.tsx
plugins/main/public/components/overview/vulnerabilities/dashboards/overview/dashboard_panels.ts
plugins/main/public/components/overview/vulnerabilities/dashboards/overview/dashboard_panels_filters.ts
plugins/main/public/components/overview/vulnerabilities/dashboards/overview/dashboard_panels_kpis.ts
plugins/main/public/components/visualize/visualizations.js
plugins/main/public/controllers/management/components/management/ruleset/views/rule-info.tsx
plugins/main/public/styles/common.scss
plugins/main/public/styles/theme/dark/index.dark.scss
plugins/main/public/utils/applications.ts
plugins/main/server/integration-files/visualizations/overview/overview-pm.ts
scripts/vulnerabilities-events-injector/DIS_Template.json
scripts/vulnerabilities-events-injector/dataInjectScript.py

Merge 4.8.2 into 4.9.0
> [!CAUTION]

Merge 4.8.2 into 4.9.0

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps Wazuh version to 4.8.0 revision 07.
```
node scripts/release/bump.js --plugins-directory ./plugins --manifest-changelog ./CHANGELOG.md --plugin-main-generate-api-data-spec https://raw.githubusercontent.com/wazuh/wazuh/4.8.0/api/api/spec/spec.yaml --manifest-package ./plugins/main/package.json --revision 07
```
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6574

Bump revision to 07

---

CHANGELOG.md
plugins/main/public/components/common/modules/main-agent.tsx
plugins/main/public/components/common/modules/module.scss
plugins/main/public/controllers/management/components/management/ruleset/components/columns.tsx
plugins/main/public/controllers/management/components/management/ruleset/views/rule-info.tsx
plugins/main/public/styles/common.scss
plugins/main/public/styles/component.scss
plugins/main/public/styles/layout.scss
plugins/main/public/styles/theme/dark/index.dark.scss
plugins/main/public/styles/typography.scss
plugins/main/public/templates/management/management.html

This pull request removes hardcoded colors and implements OUI styles.
Closes #6585 
**It's recommended to test it with a real Wazuh manager to be able to filter rules**
- Go to Server management -> Rules
- Filter rule ID 19004 in the rules table
- Click on the rule ID 19004 row
- Verify all call to actions have the OUI primary color
- Go to Endpoint summary section
- Select an active agent in the table
- Go to Stats or Inventory
- Verify the title with the agent name has the OUI primary color
- Go to Cluster section
- Verify all the call to actions use the OUI primary color

Remove hardcoded colors and implement OUI styles

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json

This pull request bumps Wazuh version to 4.7.3 revision 00 to add support to the new version. 
```
node scripts/release/bump.js --manifest-changelog ./CHANGELOG.md --manifest-package ./plugins/main/package.json --platform-version 2.8.0 --plugin-main-generate-api-data-spec https://raw.githubusercontent.com/wazuh/wazuh/v4.7.3/api/api/spec/spec.yaml --plugins-directory ./plugins --revision 00 --version 4.7.4
```
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6598

Bump version to 4.7.4

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps Wazuh version to 4.8.0 revision 08.
```
node scripts/release/bump.js --plugins-directory ./plugins --manifest-changelog ./CHANGELOG.md --plugin-main-generate-api-data-spec https://raw.githubusercontent.com/wazuh/wazuh/4.8.0/api/api/spec/spec.yaml --manifest-package ./plugins/main/package.json --revision 08
```
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6603

Bump revision to 08 beta6

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json

This pull request bumps the revision to 01.
#6610

Bump revision to 01 for 4.7.4 RC1

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json

This pull request bumps the revision to 02 for 4.7.4
#6619

Bump 4.7.4 revision 02

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps the revision to 09 for 4.8.0.
#6637

Bump revision to 09 for 4.8.0

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps Wazuh version to 4.8.0 revision 10.
```
node scripts/release/bump.js --plugins-directory ./plugins --manifest-changelog ./CHANGELOG.md --plugin-main-generate-api-data-spec https://raw.githubusercontent.com/wazuh/wazuh/4.8.0/api/api/spec/spec.yaml --manifest-package ./plugins/main/package.json --revision 10
```
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6665

Bump revision 10 for 4.8.0-rc2

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json

This pull request bumps Wazuh version to 4.7.5 revision 00 to add support to the new version. 
```
node scripts/release/bump.js --manifest-changelog ./CHANGELOG.md --manifest-package ./plugins/main/package.json --platform-version 2.8.0 --plugin-main-generate-api-data-spec https://raw.githubusercontent.com/wazuh/wazuh/v4.7.4/api/api/spec/spec.yaml --plugins-directory ./plugins --revision 00 --version 4.7.5
```
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6670

Bump version to 4.7.5

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json

This pull request bumps the revision to 01 for 4.7.5
#6694

Bump 4.7.5 revision 01

---

CHANGELOG.md
plugins/main/package.json
plugins/main/server/controllers/wazuh-utils/wazuh-utils.ts
plugins/main/server/lib/sanitizer/index.ts
plugins/main/server/lib/sanitizer/sanitizer.test.ts
plugins/main/server/lib/sanitizer/sanitizer.ts
plugins/main/server/plugin.ts
plugins/main/server/start/index.ts
plugins/main/server/start/sanitize-uploaded-files/__mocks__/malicious.customization.logo.app.svg.ts
plugins/main/server/start/sanitize-uploaded-files/__mocks__/sanitized.customization.logo.app.svg.ts
plugins/main/server/start/sanitize-uploaded-files/index.ts
plugins/main/server/start/sanitize-uploaded-files/sanitize-svg.test.ts
plugins/main/server/start/sanitize-uploaded-files/sanitize-svg.ts
plugins/main/yarn.lock

Merge 4.7.5 into 4.8.0
> [!CAUTION]

Merge 4.7.5 into 4.8.0

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps the revision to 11
```console
node scripts/release/bump.js --plugins-directory ./plugins --manifest-changelog ./CHANGELOG.md --plugin-main-generate-api-data-spec https://raw.githubusercontent.com/wazuh/wazuh/4.8.0/api/api/spec/spec.yaml --manifest-package ./plugins/main/package.json --revision 11
```
Side changes:
- Replace references to IT Hygiene application by agent view
#6705

Bump revision 11 for 4.8.0-rc3

---

plugins/main/public/kibana-integrations/discover/application/angular/doc_table/components/table_row.ts

This PR fixes surrounding document link.

Fix surrounding document link

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json

This pull request bumps the revision to 02 for 4.7.5
#6719

Bump 4.7.5 revision 02

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps the revision to 4.8.0 rev12
#6750

Bump revision 12 for 4.8.0-rc4

---

CHANGELOG.md
docker/imposter/api-info/api_info.json
plugins/main/common/api-info/endpoints.json
plugins/main/common/api-info/security-actions.json
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/main/public/components/common/tables/__snapshots__/table-with-search-bar.test.tsx.snap
plugins/main/public/controllers/management/components/management/configuration/office365/components/SubscriptionTab/__snapshots__/SubscriptionTab.test.tsx.snap
plugins/main/public/controllers/management/components/management/configuration/office365/components/api-auth-tab/__snapshots__/api-auth-tab.test.tsx.snap
plugins/main/public/controllers/management/components/management/configuration/office365/components/general-tab/__snapshots__/general-tab.test.tsx.snap
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps Wazuh version to 4.10.0 revision 00 to add support to the new version. 
```
node scripts/release/bump.js --plugins-directory ./plugins --manifest-changelog ./CHANGELOG.md --plugin-main-generate-api-data-spec https://raw.githubusercontent.com/wazuh/wazuh/4.10.0/api/api/spec/spec.yaml --manifest-package ./plugins/main/package.json --version 4.10.0 --revision 00
```
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6780

Bump version to 4.10.0

---

CHANGELOG.md
plugins/main/common/api-info/endpoints.json
plugins/main/common/api-info/security-actions.json
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

Bump 4.9.0 version revision to 01. 
Closes #6786

Bump 4.9.0 to revision 01

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps the revision to 02 for 4.9.0
#6819

Bump 4.9.0 to revision 02

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps Wazuh version to 4.9.0 revision 03.
```
node scripts/release/bump.js --plugins-directory ./plugins --manifest-changelog ./CHANGELOG.md --plugin-main-generate-api-data-spec https://raw.githubusercontent.com/wazuh/wazuh/4.9.0/api/api/spec/spec.yaml --manifest-package ./plugins/main/package.json --version 4.9.0 --revision 03
```
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6849

Bump revision 03 for 4.9.0 Alpha3

---

CHANGELOG.md
docker/imposter/api-info/api_info.json
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps Wazuh version to 4.9.1 revision 00 to add support to the new version.
#6863

Bump version 4.9.1 rev 00

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps 4.9.0 rev 04
#6894

Bump 4.9.0 rev 04

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps to 4.9.0 rev 05
#6903

Bump 4.9.0 rev 05

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps to 4.8.2 rev 00.
#6910

Bump version to 4.8.2

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps Wazuh version to 4.8.2 revision 01.
```
node scripts/release/bump.js --plugins-directory ./plugins --manifest-changelog ./CHANGELOG.md --plugin-main-generate-api-data-spec https://raw.githubusercontent.com/wazuh/wazuh/4.8.2/api/api/spec/spec.yaml --manifest-package ./plugins/main/package.json --version 4.8.2 --revision 01
```
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6914

Bump revision 01 for 4.8.2 RC1

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps Wazuh version to 4.9.2 revision 00 to add support to the new version.
#6970

Bump Wazuh 4.9.2 rev 00

---

SECURITY.md

This PR updates the repository security policy.
#6994

Update repository security update

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This PR bumps the revision to 01 for 4.9.1 RC1
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/7002

Bump 4.9.1 revision 01 RC1

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps the version to 4.10.1 and the revision to 00.
#7010

Support Wazuh 4.10.1 rev 00

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps to 4.9.1 revision 02.
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/7024

Bump revision 4.9.1 02

---

CHANGELOG.md
plugins/main/common/wazuh-modules.ts
plugins/main/public/utils/applications.ts
plugins/main/server/routes/wazuh-reporting.test.ts

Malware feature: We want to change its current description by Check indicators of compromise triggered by malware infections or cyberattacks.
https://github.com/wazuh/wazuh-dashboard-plugins/issues/7027
Navigate to the overview page and review the description of Malware Detection.

Update malware feature description

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps to Wazuh 4.10.2 revision 00.
#7061

Support Wazuh 4.10.2 rev 00

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps Wazuh 4.9.1 revision to 03
https://github.com/wazuh/wazuh-dashboard-plugins/issues/7066

Bump Wazuh 4.9.1 revision to 03

---

CHANGELOG.md
plugins/main/common/api-info/security-actions.json
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps Wazuh 4.10.0 revision to 02.
- #7095

Support 4.10.0 alpha2

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This PR bumps the revision to 4.9.1-04 to support RC4.
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/7097

Bump revision to 04

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps 4.10.0 rev 03.
#7109

Bump 4.10.0 rev 03

---

.github/workflows/dev-environment.yml
plugins/wazuh-engine/package.json
plugins/wazuh-fleet/package.json

This pull request adds the plugins Fleet and Engine to the build workflow.

Add Fleet and Engine plugins to build workflow

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps 4.9.2 revision 01.
#7132

Bump 4.9.2 rev01

---

CHANGELOG.md
scripts/release/bump.js
scripts/release/lib/update-imposter.js

Merge 4.9.2 into 4.10.0
> [!CAUTION]

Merge 4.9.2 into 4.10.0

---

CHANGELOG.md

This pull request removes a changelog entry was included in a previous version. See 4.9.2 changelog.
#7137

Remove duplicated entry was included in a previous version

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps 4.10.0 to rev 05.
#7168

Bump 4.10.0 rev 05

---

CHANGELOG.md

This pull request fixes the number refecen in a changelog entry.
#7148

Fix pull request number

---

CHANGELOG.md
docker/imposter/wazuh-config.yml
plugins/main/common/api-info/security-actions.json
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps the version to Wazuh 4.10.3.
#7209

Bump version to 4.10.3

---

CHANGELOG.md
docker/imposter/api-info/api_info.json
docker/imposter/wazuh-config.yml
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps to Wazuh 4.11.0 revision 00.
#7215

Support Wazuh 4.11.0 rev 00

---

CHANGELOG.md
docker/imposter/api-info/api_info.json
docker/imposter/wazuh-config.yml
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps to Wazuh 4.11.0 revision 00.
#7216

Support Wazuh 4.12.0 rev 00 

---

CHANGELOG.md
plugins/main/public/components/common/tables/__snapshots__/table-with-search-bar.test.tsx.snap
plugins/main/public/controllers/management/components/management/configuration/office365/components/SubscriptionTab/__snapshots__/SubscriptionTab.test.tsx.snap
plugins/main/public/controllers/management/components/management/configuration/office365/components/api-auth-tab/__snapshots__/api-auth-tab.test.tsx.snap
plugins/main/public/controllers/management/components/management/configuration/office365/components/general-tab/__snapshots__/general-tab.test.tsx.snap
plugins/wazuh-check-updates/server/plugin-services.ts
plugins/wazuh-check-updates/server/services/updates/get-updates.test.ts
plugins/wazuh-check-updates/server/services/updates/get-updates.ts
plugins/wazuh-core/server/services/manage-hosts.ts

Merge 4.11.0 into 4.12.0
> [!CAUTION]

Merge 4.11.0 into 4.12.0

---

CHANGELOG.md
docker/osd-dev/dev.yml
plugins/main/public/components/common/data-grid/use-data-grid.tsx
plugins/main/public/components/common/wazuh-data-grid/wz-data-grid.tsx
plugins/main/public/components/common/wazuh-discover/components/data-grid-additional-controls.tsx
plugins/main/public/components/common/wazuh-discover/components/visible-columns-selector.tsx
plugins/main/public/components/common/wazuh-discover/wz-discover.tsx
plugins/main/public/components/overview/vulnerabilities/dashboards/inventory/inventory.tsx
plugins/main/public/styles/layout.scss

This pull request enhances the performance of data grid component used in `Events` tab and `Vulnerability Detection` > `Inventory`.
Changes:
- Remove to the Columns button the ability to set the columns visibility
- Create an Available fields button as additional control of data grid
that manages the fields visibility similar to the render of Columns
button when this ability was enabled
Side changes:
- Change the color of Export formatted button of data grid to text to
match the color of the of buttons
#7223
- Vulnerabilities Detection > Inventory
- Module > Events
Legend:
| Go to module > Events and use the …

Enhance the performance of data grid with many fields

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps 4.10.1 to revision 01.
#7239

Bump 4.10.1 rev 01

---

CHANGELOG.md
plugins/main/public/components/common/charts/visualizations/legend.tsx
plugins/main/public/components/common/data-grid/use-data-grid.tsx
plugins/main/public/components/common/tables/table-wz-api.tsx
plugins/main/public/components/common/wazuh-data-grid/wz-data-grid.tsx
plugins/main/public/components/common/wazuh-discover/components/data-grid-additional-controls.tsx
plugins/main/public/components/common/wazuh-discover/components/visible-columns-selector.tsx
plugins/main/public/components/common/wazuh-discover/wz-discover.tsx
plugins/main/public/components/common/welcome/components/vuls_panel/vuls_welcome_panel.tsx
plugins/main/public/components/management/cluster/components/overview_cards.tsx
plugins/main/public/components/overview/vulnerabilities/dashboards/inventory/inventory.tsx
plugins/main/public/components/settings/api/api-table.js
plugins/main/public/controllers/overview/components/last-alerts-stat/last-alerts-stat.tsx
plugins/main/public/react-services/format-number.ts
plugins/main/public/styles/layout.scss

Merge 4.10.2 into 4.11.0
> [!CAUTION]

Merge 4.10.2 into 4.11.0

---

CHANGELOG.md
plugins/main/public/components/wz-menu/wz-menu.js

This pull request reduces the duplicated request to get the list of index pattterns valid of alerts in the menu component. These requests could cause problems with 429 errors on Wazuh dashbaord.
#7254
Requests on fresh load (reload page):
Navigate from home links to Threat Hunting:
Navigate to Threat Hunting from Wazuh dashboard sidebar menu:
Legend:
| With alerts data, go to Threat Hunting > Dashboard, open the  browser dev tools, reload the page and ensure the requests to get the list of valid index pattern has a low count of request (filter by 9999 in the Network tab). Depending on the visible section you …

Fix duplicate request index patterns list on menu

---

plugins/main/yarn.lock
plugins/wazuh-check-updates/yarn.lock
plugins/wazuh-core/yarn.lock

This PR upgrades the `axios` version
#7271

Upgrade axios

---

CHANGELOG.md

This PR fixes a changelog entry that accidentally set incorrectly in https://github.com/wazuh/wazuh-dashboard-plugins/pull/7274
#7274

Fix incorrect changelog entry 

---

CHANGELOG.md
docker/imposter/wazuh-config.yml
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps to Wazuh 4.11.1 revision 00.
#7279

Support wazuh 4.11.1 rev 00

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps to 4.11.0 rev 02.
#7281

Bump revision to 4.11.0-02 beta1

---

.github/workflows/dev-environment.yml
.github/workflows/manual-build.yml
.github/workflows/playground.yml
.github/workflows/unit-test.yml
plugins/main/public/directives/wz-logtest/components/logtest.tsx
plugins/main/scripts/generate-api-data.js
scripts/indices-fields-mapping-to-index-pattern-fields/README.md
scripts/indices-fields-mapping-to-index-pattern-fields/build-static-files/README.md
scripts/indices-fields-mapping-to-index-pattern-fields/build-static-files/build-static-files-get-from-wildcard.js
scripts/indices-fields-mapping-to-index-pattern-fields/build-static-files/build-static-files-transform-templates.js

This pull request changes the `master` branch name references to `main`
#7277

Change master branch references to main

---

CHANGELOG.md
plugins/main/public/components/common/data-grid/data-grid-service.ts
plugins/main/public/components/common/wazuh-discover/wz-discover.tsx

This PR fixes the csv export, as it was not taking into account the specified time range in the table.
#7295
| Test | Result |
| --- |  --- |
| Configure different relative timeframes and verify that the exported file meets them | :black_circle: |
| Configure different absolute timeframes and verify that the exported file meets them | :black_circle: |

Fix CSV export not filtering by timerange

---

VERSION.json

As part of the standardization process, all XDR-SIEM repositories will use a consistent identification method. Each repository will include a standardized `VERSION.json` file containing necessary data to identify the origin branch and release stage. This file should be included in the installer's installation directory and indicate the short commit used to create it.
<details><summary>GitHub</summary>
1. Each repository must include a `VERSION.json` file in the root directory.
2. The file must be named `VERSION.json`.
3. It should follow the specified `JSON` format (with required keys).
4. The `version` key value must follow the `MAJOR.MINOR.PATCH` format.
5. The `stage` key value must indicate the `release stage`, using lowercase and no spaces.
6. Numeric revisions (e.g., `41200`) should …

Version file standardization

---

.github/workflows/dev-environment.yml
.github/workflows/manual-build.yml
.github/workflows/playground.yml
.github/workflows/unit-test.yml
CHANGELOG.md
plugins/main/public/directives/wz-logtest/components/logtest.tsx
plugins/main/scripts/generate-api-data.js

Merge 4.11.0 into 4.11.1
> [!CAUTION]

Merge 4.11.0 into 4.11.1

---

CHANGELOG.md
docker/osd-dev/dev.yml
plugins/main/package.json
plugins/main/public/components/agents/stats/__snapshots__/table.test.tsx.snap
plugins/main/public/components/common/form/__snapshots__/index.test.tsx.snap
plugins/main/public/components/common/tables/__snapshots__/table-default.test.tsx.snap
plugins/main/public/components/common/tables/__snapshots__/table-with-search-bar.test.tsx.snap
plugins/main/public/components/common/tables/__snapshots__/table-wz-api.test.tsx.snap
plugins/main/public/components/common/tables/components/__snapshots__/export-table-csv.test.tsx.snap
plugins/main/public/controllers/management/components/management/configuration/office365/components/SubscriptionTab/__snapshots__/SubscriptionTab.test.tsx.snap
plugins/main/public/controllers/management/components/management/configuration/office365/components/api-auth-tab/__snapshots__/api-auth-tab.test.tsx.snap
plugins/main/public/controllers/management/components/management/configuration/office365/components/general-tab/__snapshots__/general-tab.test.tsx.snap
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/package.json

This pull request adds the compatibility with OpenSearch Dashboards 2.19.0.
#7302

Compatibility with opensearch 2.19.0

---

CHANGELOG.md

Update CHANGELOG to remove redundant entry for known fields test added in https://github.com/wazuh/wazuh-dashboard-plugins/pull/7268/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR11
https://github.com/wazuh/wazuh-dashboard-plugins/issues/7266

Update CHANGELOG to remove redundant entry for known fields test

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull requests bumps the 4.11.1 to rev 01.
Additional changes:
- Rephrase changelog entry
#7326

Bump 4.11.1 rev 01

---

VERSION.json

Update version stage from alpha1 to alpha0
#7293

Update version stage from alpha1 to alpha0

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull requests bumps the 4.11.1 to rev 02.
#7338

Bump revision 02

---

CHANGELOG.md
docker/osd-dev/dev.yml
plugins/main/package.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/package.json

This pull request adds the compatibility with OpenSearch Dashboards 2.19.1.
#7331

Compatibility with opensearch 2.19.1

---

CHANGELOG.md
plugins/main/package.json
plugins/wazuh-analysis/package.json
plugins/wazuh-core/package.json
plugins/wazuh-engine/package.json
plugins/wazuh-fleet/package.json

This pull request adds the compatibility with OpenSearch Dashboards 2.19.1.
#7316

Update Opensearch Dashboard version to 2.19.1 (5.0.0)

---

CHANGELOG.md
VERSION.json
docker/imposter/api-info/api_info.json
docker/imposter/wazuh-config.yml
docker/osd-dev/dev.yml
plugins/main/common/api-info/endpoints.json
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/main/public/components/common/tables/__snapshots__/table-with-search-bar.test.tsx.snap
plugins/main/public/controllers/management/components/management/configuration/office365/components/SubscriptionTab/__snapshots__/SubscriptionTab.test.tsx.snap
plugins/main/public/controllers/management/components/management/configuration/office365/components/api-auth-tab/__snapshots__/api-auth-tab.test.tsx.snap
plugins/main/public/controllers/management/components/management/configuration/office365/components/general-tab/__snapshots__/general-tab.test.tsx.snap
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull requests bumps the version to 4.13.0
#7340

Bump version 4.13.0

---

plugins/wazuh-check-updates/package.json

This PR upgrades wazuh-check-updates to OSD 2.19.1.
https://github.com/wazuh/wazuh-dashboard-plugins/issues/7316

Upgrade check-updates to 2.19.1

---

CHANGELOG.md
plugins/main/common/constants.ts
plugins/main/public/components/management/cluster/cluster-disabled.js
plugins/main/public/controllers/management/components/management/configuration/alerts/alerts-email-alerts.js
plugins/main/public/controllers/management/components/management/configuration/alerts/alerts-reports.js
plugins/main/public/controllers/management/components/management/configuration/alerts/alerts-syslog-output.js
plugins/main/public/controllers/management/components/management/configuration/cis-cat/help-links.js
plugins/main/public/controllers/management/components/management/configuration/client-buffer/client-buffer.js
plugins/main/public/controllers/management/components/management/configuration/cluster/cluster.js
plugins/main/public/controllers/management/components/management/configuration/integrations/integrations.js
plugins/main/public/controllers/management/components/management/configuration/log-collection/log-collection-sockets.js
plugins/main/public/controllers/management/components/management/configuration/open-scap/help-links.js
plugins/main/public/controllers/management/components/management/configuration/osquery/osquery.js
plugins/main/public/controllers/management/components/management/configuration/policy-monitoring/help-links.js
plugins/main/public/utils/check-plugin-version.tsx
plugins/main/server/lib/generate-alerts/sample-data/ciscat.js
plugins/main/server/lib/reporting/agent-configuration.ts
plugins/wazuh-core/common/constants.ts
plugins/wazuh-core/server/services/configuration-store.ts

This pull request fixes broken documentation links.
https://github.com/wazuh/wazuh-dashboard-plugins/issues/7328
Broken: https://documentation.wazuh.com/4.11/user-manual/wazuh-dashboard/config-file.html
Fixed: https://documentation.wazuh.com/4.11/user-manual/wazuh-dashboard/settings.html
<details>
</details>
<hr/>
Broken: https://documentation.wazuh.com/4.11/user-manual/manager/manual-email-report/index.html
Fixed: https://documentation.wazuh.com/4.11/user-manual/manager/alert-management.html#configuring-email-alerts
<details>
</details>
<hr/>
Broken: https://documentation.wazuh.com/4.11/user-manual/manager/manual-email-report/smtp-authentication.html
Fixed: https://documentation.wazuh.com/4.11/user-manual/manager/alert-management.html#smtp-server-with-authentication
<details>
</details> …

Fix documentation links

---

CHANGELOG.md
docker/imposter/wazuh-config.yml
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull requests bumps the version to 4.11.2
#762

Bump version 4.11.2

---

CHANGELOG.md
plugins/main/common/constants.ts
plugins/main/public/components/management/cluster/cluster-disabled.js
plugins/main/public/controllers/management/components/management/configuration/alerts/alerts-email-alerts.js
plugins/main/public/controllers/management/components/management/configuration/alerts/alerts-reports.js
plugins/main/public/controllers/management/components/management/configuration/alerts/alerts-syslog-output.js
plugins/main/public/controllers/management/components/management/configuration/cis-cat/help-links.js
plugins/main/public/controllers/management/components/management/configuration/client-buffer/client-buffer.js
plugins/main/public/controllers/management/components/management/configuration/cluster/cluster.js
plugins/main/public/controllers/management/components/management/configuration/integrations/integrations.js
plugins/main/public/controllers/management/components/management/configuration/log-collection/log-collection-sockets.js
plugins/main/public/controllers/management/components/management/configuration/open-scap/help-links.js
plugins/main/public/controllers/management/components/management/configuration/osquery/osquery.js
plugins/main/public/controllers/management/components/management/configuration/policy-monitoring/help-links.js
plugins/main/public/utils/check-plugin-version.tsx
plugins/main/server/lib/generate-alerts/sample-data/ciscat.js
plugins/main/server/lib/reporting/agent-configuration.ts
plugins/wazuh-core/common/constants.ts
plugins/wazuh-core/server/services/configuration-store.ts

This pull request fixes broken documentation links. This fix was originally intended for Wazuh 4.12.0, but it will be applied in Wazuh 4.11.2.
https://github.com/wazuh/wazuh-dashboard-plugins/issues/7328
Broken: https://documentation.wazuh.com/4.11/user-manual/wazuh-dashboard/config-file.html
Fixed: https://documentation.wazuh.com/4.11/user-manual/wazuh-dashboard/settings.html
<details>
</details>
<hr/>
Broken: https://documentation.wazuh.com/4.11/user-manual/manager/manual-email-report/index.html
Fixed: https://documentation.wazuh.com/4.11/user-manual/manager/alert-management.html#configuring-email-alerts
<details>
</details>
<hr/>
Broken: https://documentation.wazuh.com/4.11/user-manual/manager/manual-email-report/smtp-authentication.html
Fixed: …

Fix broken documentation links for 4.11.2

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps 4.11.2 to revision 02.
#7375

Bump 4.11.2 rev 02

---

CHANGELOG.md
VERSION.json
docker/imposter/wazuh-config.yml
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps Wazuh version to 4.12.1.
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/7391

Bump version to 4.12.1

---

CHANGELOG.md
plugins/main/public/components/settings/about/__snapshots__/appInfo.test.tsx.snap
plugins/main/public/components/settings/about/appInfo.test.tsx
plugins/main/public/components/settings/about/appInfo.tsx
plugins/main/public/components/settings/about/index.tsx
plugins/main/public/components/settings/settings.tsx
plugins/main/public/components/settings/types.ts

Merge 4.12.0 into 4.12.1
#7395

Merge 4.12.0 into 4.12.1

---

CHANGELOG.md
VERSION.json
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps the version 4.12.0 to revision 03.
#7409

Bump 4.12.0 rev 03

---

CHANGELOG.md
VERSION.json
docker/imposter/wazuh-config.yml
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps the version to 4.12.2 to support a new Wazuh version.
#7414

Support wazuh 4.12.2

---

CHANGELOG.md
plugins/main/public/styles/layout.scss
plugins/main/server/start/monitoring/index.ts

Merge 4.12.2 into 4.13.0
> [!CAUTION]

Merge 4.12.2 into 4.13.0

---

CHANGELOG.md
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps the version 4.10.2 rev 01.
#7444

Bump 4.10.2 rev 01

---

CHANGELOG.md
VERSION.json
docker/imposter/api-info/api_info.json
docker/imposter/wazuh-config.yml
plugins/main/common/api-info/endpoints.json
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/main/public/components/common/tables/__snapshots__/table-with-search-bar.test.tsx.snap
plugins/main/public/controllers/management/components/management/configuration/office365/components/SubscriptionTab/__snapshots__/SubscriptionTab.test.tsx.snap
plugins/main/public/controllers/management/components/management/configuration/office365/components/api-auth-tab/__snapshots__/api-auth-tab.test.tsx.snap
plugins/main/public/controllers/management/components/management/configuration/office365/components/general-tab/__snapshots__/general-tab.test.tsx.snap
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json
tools/repository_bumper.sh

This pull request bumps the version to 4.14.0 to support a new Wazuh version.
#7447

Support wazuh 4.14.0

---

.github/ISSUE_TEMPLATE/compatibility_request.md
CHANGELOG.md
docker/imposter/manager/info.json
docker/imposter/wazuh-config.yml
plugins/main/package.json
plugins/main/public/components/endpoints-summary/register-agent/services/register-agent-os-commands-services.test.ts
plugins/main/public/components/endpoints-summary/register-agent/services/register-agent-os-commands-services.tsx
plugins/main/public/components/overview/vulnerabilities/dashboards/overview/dashboard_panels.ts
plugins/main/public/components/settings/api/api-table.js
plugins/main/server/controllers/wazuh-api.ts
plugins/main/yarn.lock
plugins/wazuh-check-updates/package.json
plugins/wazuh-check-updates/yarn.lock
plugins/wazuh-core/package.json
plugins/wazuh-core/yarn.lock

Merge 4.12.1 into 4.12.2
> [!CAUTION]

Merge 4.12.1 into 4.12.2

---

CHANGELOG.md

Remove 4.12.2 references
#7478

Remove 4.12.2 references

---

CHANGELOG.md
VERSION.json
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

Issue: https://github.com/wazuh/wazuh-dashboard-plugin/issues/2392

Bump enhancement/wqa2392-bump-test/7492-bumper-script-workflow-bump-stage-test-to-4.13.0-alpha1 branch to 4.13.0-alpha1

---

CHANGELOG.md
VERSION.json
docker/imposter/wazuh-config.yml
plugins/main/common/api-info/endpoints.json
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

Issue: https://github.com/wazuh/wazuh-dashboard-plugin/issues/2392

Bump enhancement/wqa2392-bump-test/7492-bumper-script-workflow-bump-stage-test-to-4.14.0-alpha0 branch to 4.14.0-alpha0

---

CHANGELOG.md
VERSION.json
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

Issue: https://github.com/wazuh/wazuh-dashboard-plugin/issues/2392

Bump test/7492-bumper-script-workflow-bump-stage-test branch

---

CHANGELOG.md
VERSION.json
docker/imposter/wazuh-config.yml
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

This pull request bumps Wazuh version to 4.13.0-00
#7523

Bump version to 4.13.1-00

---

.github/workflows/build.yml
.github/workflows/manual-build.yml

This pull request fixes a PR write permission in the package building workflow.

Add PR write permission

---

.github/workflows/6_bumper_repository.yml
tools/.gitignore
tools/README.md
tools/repository_bumper.sh

This pull request adds the repository bumper script to the 6.0.0 branch.
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/7546
<details><summary>Only the revision and stage should be changed</summary>
<p>
```console
./repository_bumper.sh --version 6.0.0 --stage alpha2
[2025-06-25 17:46:45] Starting repository bump process
[2025-06-25 17:46:45] Repository path: /Users/ianyenienserrano/wazuh/wazuh-dashboard-plugins
[2025-06-25 17:46:45] Version: 6.0.0
[2025-06-25 17:46:45] Stage: alpha2
[2025-06-25 17:46:45] Attempting to extract current version from /Users/ianyenienserrano/wazuh/wazuh-dashboard-plugins/VERSION.json using sed...
[2025-06-25 17:46:45] Successfully extracted version using sed: 6.0.0
[2025-06-25 17:46:45] Current version detected in VERSION.json: 6.0.0
[2025-06-25 …
```

Add repository bumper

---

.github/workflows/5_bumper_repository.yml
.github/workflows/6_bumper_repository.yml
tools/repository_bumper.sh

This pull request adds the repository bumper workflows in the main branch.
- #7546 
<details><summary>Only the revision and stage should be changed</summary>
<p>
```console
./repository_bumper.sh --version 5.0.0 --stage alpha1
[2025-06-25 16:40:04] Starting repository bump process
[2025-06-25 16:40:04] Repository path: /Users/ianyenienserrano/wazuh/wazuh-dashboard-plugins
[2025-06-25 16:40:04] Version: 5.0.0
[2025-06-25 16:40:04] Stage: alpha1
[2025-06-25 16:40:04] Attempting to extract current version from /Users/ianyenienserrano/wazuh/wazuh-dashboard-plugins/VERSION.json using sed...
[2025-06-25 16:40:04] Successfully extracted version using sed: 5.0.0
[2025-06-25 16:40:04] Current version detected in VERSION.json: 5.0.0
[2025-06-25 16:40:04] Current major.minor: 5.0
[2025-06-25 …
```

Add bumper repository workflows

---

CHANGELOG.md
plugins/main/public/components/common/dashboards/inventory.tsx
plugins/main/public/components/endpoints-summary/register-agent/services/register-agent-os-commands-services.test.ts
plugins/main/public/components/endpoints-summary/register-agent/services/register-agent-os-commands-services.tsx

Merge 4.13.0 into 4.13.1
> [!CAUTION]

Merge 4.13.0 into 4.13.1

---

CHANGELOG.md
VERSION.json
docker/imposter/wazuh-config.yml
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

Issue: https://github.com/wazuh/wazuh-qa-automation/issues/2625

Bump test/554-test branch

---

docker/imposter/wazuh-config.yml

This pull request changes the branch references to 4.13.0.
#7574

Change branch references

---

CHANGELOG.md
plugins/main/public/components/overview/it-hygiene/dashboards/dashboard-kpi.ts
plugins/main/public/components/overview/it-hygiene/dashboards/dashboard-panels.ts

Fix some bugs related to It hygiene visalizations
- Updated the visualization function to use getVisStateTable for better data representation.
- Fixed a typo in the label from 'TPC connection status' to 'TCP connection status' in multiple dashboard panels.
#7580 
- Check if you changed kpi Operating system families to table
- Check text 'TPC connection status' change to 'TCP connection status on visualization

Fix IT hygiene dashboard visualizations

---

CHANGELOG.md
docker/osd-dev/config/2.x/os/opensearch.yml
plugins/main/package.json
plugins/main/public/components/common/tables/__snapshots__/table-with-search-bar.test.tsx.snap
plugins/main/yarn.lock
plugins/wazuh-check-updates/package.json
plugins/wazuh-check-updates/yarn.lock
plugins/wazuh-core/package.json
plugins/wazuh-core/yarn.lock

Update Opensearch version of the plugins
- #7560

Updates OpenSearch Dashboards version to 3.1.0

---

CHANGELOG.md
VERSION.json
docker/imposter/wazuh-config.yml
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

Issue: https://github.com/wazuh/wazuh-qa-automation/issues/2745

Bump 4.13.0 branch

---

plugins/main/public/components/overview/vulnerabilities/dashboards/inventory/inventory.tsx
plugins/main/public/controllers/management/components/management/common/actions-buttons.tsx

Revert some changes of the branch sync mentioned in this pull request https://github.com/wazuh/wazuh-dashboard-plugins/pull/7616

Revert some changes of the branch sync

---

docker/imposter/api-info/api_info.json
plugins/main/opensearch_dashboards.json

Fix the `opensearch_dashboards.json` and update the imposter `api_info` version.

Remove duplicate version

---

CHANGELOG.md
VERSION.json
docker/imposter/wazuh-config.yml
plugins/main/opensearch_dashboards.json
plugins/main/package.json
plugins/wazuh-check-updates/opensearch_dashboards.json
plugins/wazuh-check-updates/package.json
plugins/wazuh-core/opensearch_dashboards.json
plugins/wazuh-core/package.json

Issue: https://github.com/wazuh/wazuh-qa-automation/issues/3035

Bump 4.14.1 branch

---

CHANGELOG.md

Update 4.14.1 changelog

---

.github/workflows/4_builderpackage_plugins.yml
.github/workflows/4_builderprecompiled_base-dev-environment.yml
.github/workflows/4_codelinter_prettier.yml
.github/workflows/4_testunit_jest.yml

Add build dashboard and dashboard_core actions for 5.x and 4.x versions according to major_prefix_target nomenclature
https://github.com/yenienserrano/wazuh-dashboard/actions/runs/17138016173

Adds version-specific dashboard build workflows (4.10.4)

---

docker/imposter/wazuh-config.yml

Change tag reference to 4.13.0 in imposter `wazuh-config.yml`

Change tag reference to 4.13.0

---

CHANGELOG.md
plugins/main/public/components/overview/mitre/framework/components/techniques/components/flyout-technique/flyout-technique.tsx

This pull request fixes the navigation method of the Mitre att&ck framework flyout.
#7687 

Fix mitre framework flyout navigation

---

plugins/main/common/constants.ts
plugins/main/public/components/overview/sca/docs/sca-readme.md
plugins/main/public/react-services/navigation-service.test.ts

Adapt the name of the related `wazuh-states` index patterns accordingly.
https://github.com/wazuh/wazuh-dashboard-plugins/issues/7726
<details><summary>screenshoots</summary>
<p>
</p>
</details> 
CR: 🟢 
Test: 🟢 
Legend:
| Go to any dashboard that requires the `wazuh-states` index pattern (with no indices stored) and verify that the error message refers to the index pattern **without** the `-*` suffix  | :white_circle: | :white_circle: | :white_circle: |
| Add sample data and verify that the dashboard loads and works correctly | :white_circle: | :white_circle: | :white_circle: |
**Details**
<details> …

Remove cluster name from states index patterns

---

docker/imposter/wazuh-config.yml

Issue: https://github.com/wazuh/wazuh-qa-automation/issues/3996

Bump 4.13.1 branch

---

CHANGELOG.md
plugins/main/public/components/common/reload-cluster-manager-callout.tsx
plugins/main/public/components/overview/it-hygiene/packages/inventories/packages/dashboard.ts

Merge 4.13.1 into 4.14.0

---

CHANGELOG.md
plugins/main/public/components/common/reload-cluster-manager-callout.tsx
plugins/main/public/components/overview/it-hygiene/networks/inventory.tsx
plugins/main/public/components/overview/it-hygiene/packages/inventories/packages/dashboard.ts

Merge 4.14.0 into 4.14.1

---

docker/imposter/wazuh-config.yml

This pull request changes the tag reference.
#7778

Change tag references
