- CHANGELOG.md
- public/components/common/tables/__snapshots__/table-wz-api.test.tsx.snap
- public/components/common/tables/table-default.tsx
- public/components/common/tables/table-with-search-bar.tsx
- public/components/common/tables/table-wz-api.tsx
This PRs fixes that the table in `Modules/Vulnerabilities/Inventory` doesn't refresh when changing the selected agent.
- Added `endpoint` property as dependency and parameter to redo the request. The `endpoint` property contains the agent ID.
- Requirements:
- 2 agents at least
- Vulnerability module is enabled and at least one scan should be done.
- Checks
- Go to `Modules/Vulnerabilities/Inventory` and select one agent, change the selected agent and the data of table should change
> [FIX] [Vulnerabilities/Inventory] Table not reload when changing the selected agent

- CHANGELOG.md
- public/components/agents/vuls/inventory/detail.tsx
- public/components/common/modules/discover/discover.tsx
- public/components/common/modules/discover/row-details.tsx
Hi team,
this PR show all available fields in Discover Details Flyout table. Also fixes the open row icon width in the first column when the table has few columns.
Related PR #3893 
To test it:
- Have some vulnerability alerts
- Go to Vulnerabilities / Inventory
- Select a row in the table which has events
- Open the row to see the details and verify it show all available fields for that event
> Enhance rework vulnerabilities inventory flyout

- CHANGELOG.md
- public/utils/known-fields.js
This PR adds some fields to the known fields for the index pattern of alerts. These fields are used as the default fields when creating the index pattern of alerts and there are no related indices.
We extract the fields used in the visualizations and check if they were defined in the know fields file.
Related to #3918
- With an environment without indices related to Wazuh alerts, access to the Wazuh plugin for Kibana. The health check should run and create the index pattern for the Wazuh alerts with the fields used in the visualizations of all current modules. Access to each module in the two modes (with and without the selected agent) and should appear the toast that says `The index pattern was refreshed successfully.
> [Known fields] Add fields to the know fields for the index pattern of alerts

- CHANGELOG.md
- public/components/common/modules/events.tsx
- public/components/visualize/wz-visualize.js
Hi team,
this pull request solves an asynchronism issue when multiple fields are missing in the Events view rows details. Once this PR is applied **only 1 toast should pop** informing the index pattern was updated.
Closes #3923
To test it try to reproduce the linked issue.
> Fixed async problem when checking for unknown fields

- CHANGELOG.md
- public/kibana-integrations/kibana-vis.js
Hi team,
this PR fixes a miscalculation when the map gets its position relative to the map wrapper and the visualization is in a loading state. 
Closes #3919 
To test it, check all visualizations in all dashboards render properly.
> Map visualization render problem

- CHANGELOG.md
- public/controllers/dev-tools/dev-tools.ts
This PR fixes when the `#` character is used not at the beginning of the line. This solves a parse error when using the character in the `password` field to create a new user.
- Go to `Tools/API Console` and set the next query:
```
POST /security/users
{
"username": "wazuh_test_user",
"password": "Abcdef1#"
}
```
The query shouldn't display the parse error.
Closes #3810
> [BUG][Tools/Api Console] Parse error when using  character on the line start

- CHANGELOG.md
- public/components/common/modules/panel/components/module_configuration.scss
- public/components/common/modules/panel/components/module_configuration.tsx
Hi team,
this fixed the github and office 365  configuration panels overflow when a field was very long.
Closes #3938 
To test it generate a very long field to show in the panel, like the github auth token and check it renders properly.
> GitHub configuration panel text overflow

- CHANGELOG.md
- public/app.js
- public/controllers/management/components/management/configuration/office365/components/general-tab/__snapshots__/general-tab.test.tsx.snap
The basePath was changed to take the kibana subpath
**Issues Resolved:**
Logout doesn't work with yarn start command [#3953](https://github.com/wazuh/wazuh-kibana-app/issues/3953)
**Test:**
1. Start kibana with the `yarn start` command
2. Navigate to `wazuh`
3. Click on `logout`
4. See that logout works
5. Start kibana with the `yarn start --no-base-path` command
6. Navigate to `wazuh`
7. Click on `logout`
8. See that logout works
> Change logout path

- CHANGELOG.md
- server/start/cron-scheduler/scheduler-job.ts
This PR prevents Wazuh throwing an unhandled promise rejection error, which caused Kibana to crash node.options was not set up to only throw a warning after an unhandled promise rejection.
Closes #3887 
To test it:
- Start up / login in Kibana 
- Take down Wazuh API
- Wait for Wazuh to start cron-jobs
- Kibana should not exit on fatal exception and the promise rejection is handled
> [Fix] Unhandled promise error when Wazuh API

- .github/workflows/create-wazuh-packages.yml
This PR adds the support to build a package of plugin for OpenSearch Dashboards thank you for the added process to the `wazuh-packages` repository in its branch 4.3. https://github.com/wazuh/wazuh-packages/tree/4.3
Note that other branches of wazuh-packages could have no the process to build package for OpenSearch Dashboards
- Replaced the default `wazuh-packages` branch to `4.3`
- Replaced some logs
- Added logic to check if the branch is a package for Kibana or OpenSearch Dashboards
> [Feat][GitHub Actions] Support for creating package of OpenSearch Dashboards

- CHANGELOG.md
- public/utils/codemirror/codemirror.scss
Changed the z-index so that the background of the selected text is below the text
**Issue:** 
- #4051 
**Test:**
1. Navigate to `Tools>API Console`
2. Select text
3. See text
4. Scroll to the right 
5. The text shouldn't overflow the line numbers.
**Screenshots:**
Light Mode
Dark Mode
> The selected text is visible in API Console

- CHANGELOG.md
- public/components/common/globalBreadcrumb/globalBreadcrumb.tsx
- public/components/common/modules/agents-current-section.tsx
- public/components/common/modules/main-overview.tsx
This PR a `main-overview.tsx` leftover code. When `globalBreadcrumb.tsx` was refactored to centralize the agent routing, **_main-overview_** should have been modified to just send the agent information, so **_globalBreadcrumb_** creates the routing object.
Closes #4093 
- Go to Agents > Name of the agent > System auditing
- Return to the agent summary menu 
- See the undefined router error in the console
The class **_WzCurrentAgentsSection_** also has deprecated code and doesn't seem to be used by the application. I suggest creating an issue to clean code and remove deprecated classes, commented code, functions not being used, etc
> Changed breadcrumb agent push

- CHANGELOG.md
- common/constants.ts
- public/services/resolves/get-config.js
- server/lib/initial-wazuh-config.ts
- server/start/cron-scheduler/save-document.ts
- server/start/monitoring/index.ts
This PR modifies the default `shards` configuration for the `statistics` indices.
- configuration:
- shards: 1
- replicas: 0
- affected:
- configuration in the creation of indices
- initial default plugin configuration
- `getWzConfig` route resolver
- constant with the default configuration
- The initial configuration should display the settings as:
- `cron.statistics.shards`: `1`
- `cron.statistics.replicas`: `0`
- The new `statistics` indices should be created with the new `shards` and `replicas` settings if there is no other configuration.
Closes #4053
> [Jobs] Change the `shards` configuration for the `statistics` indices

- public/controllers/agent/components/register-agent.js
The Red Hat options were added since only those of CentOS appeared. 
**Issue:**
Improve message for OS selection in agent installation walkthrough [#4038](https://github.com/wazuh/wazuh-kibana-app/issues/4038)
**Test:**
1. Navigate to `Agents`
2. Click on `Deploy a new agent`
3. Click on `Red Hat / CentOS`
> OS selection in agent installation

- CHANGELOG.md
- public/controllers/agent/components/register-agent.js
Changes were made to the messages in the agent installation guide.
- From `You can predefine the Wazuh server address with the enrollment.dns setting` to `This is the address the agent uses to communicate with the Wazuh server. It can be an IP address or a fully qualified domain name (FQDN).`
- From `Running this command on a host with an agent already installed upgrades the agent package without enrolling the agent. To enroll it, see the Wazuh documentation` to `If the installer finds another Wazuh agent in the system, it will upgrade it preserving the configuration.`
**Test:**
1. Navigate to `Agents`
2. Click on `Deploy a new agent`
3. Look at the changes
**Issues:**
Improve messages on agent installation walkthrough …
> Improve messages in the agent installation

- CHANGELOG.md
- public/controllers/management/components/management/mg-logs/logs.js
Closes #4089 
- Go to the Manager logs section.
- No error should appear on start.
> Fix the `Missing parameters` error on the Manager Logs view

- public/components/common/modules/modules-helper.js
Changes in the function where it checks if the filter is from the modules view or if it is an added filter, since currently the filters that can be added, such as the negation of the filters of each module, cannot be removed, and ideally they are have to be able to remove all custom filters.
**issue:**
- #4045
**Test:**
You should always be able to remove the filter
1. Navigate to any module, for example, Security Events
2. Add filter `NOT cluster.name: wazuh` 
3. Pin filter
4. Unpin filter
> Can remove custom filter

- CHANGELOG.md
- public/components/common/modules/discover/discover.tsx
Hi team, in this PR we were able to solve the problem reported in the following issue #4052 In it we have performed a `dataParse()` on the selection date.
Many thanks to @asteriscos  and @yenienserrano  for participating in the solution of the problem.
Closes #4052
> Fix error when selecting date range in discover

- CHANGELOG.md
- public/controllers/management/components/management/mg-logs/logs.js
- public/controllers/management/components/management/ruleset/actions-buttons.js
The spinner is added when the Export formatted button is clicked on all views of Management since it was clicked and did not show anything to the user who was making the request
**Issue:**
- #4060 
**Test:**
1. Navigate to `Management/(Rules | Decoders | etc.)`
2. Click on 'Export formatted'
3. See spinner when requesting
https://user-images.githubusercontent.com/63758389/165907441-6ce80c86-7940-4cda-bc90-7474538fab39.mp4
> Add the spinner when exporting a table

- CHANGELOG.md
- public/components/wz-search-bar/lib/suggest-handler.ts
- public/components/wz-search-bar/wz-search-bar.tsx
**This is a workaround for the issue #4105** 
The ruleset view and the rule files view share the same input, so the reference of the input does not trigger the useEffect and is lost. To fix this I added a possible pre-existing reference to the constructor of the suggestion component. 
This base issue also causes another problem, because changing the view doesn't reset the input and keeps the previous search. When a previous field has a query it fails on the new view. 
E.g.
> Fixed searchbar suggest handler undefined input ref

- CHANGELOG.md
- public/directives/wz-logtest/components/logtest.tsx
This PR enhances the output of the `Ruleset Test` utility by replicating the output of the `wazuh-logtest` utility.
Unique log:
Multiple logs:
Log no match a decoder:
- Remove the logging of the specific fields
- Replicate the output of the `wazuh-logtest` utility:
- Add tabulations
- Fix phase text
- Wrap the values in single quotes
- Displays the fields that are defined
Go to `Tools/Ruleset Test` and check the next cases are working as expected:
- Unique log that matches a decoder and rule
> For example:
> ```
> Jul 06 22:00:22 linux-agent sshd[29205]: Invalid user blimey from 1.3.1.3 port 48928
> ```
- Multiple logs (match or not)
> For example:
> ```
> Jul 06 22:00:22 linux-agent sshd[29205]: Invalid user blimey from 1.3.1.3 port 48928
> Jul 06 22:00:22 linux-agent custom[10215]: …
```
> [Logtest] Enhance the output of Ruleset Test

- CHANGELOG.md
- public/controllers/agent/components/register-agent.js
This PR adds a warning about the PowerShell version requirement in the agent installation wizard. 
Related with: #4085
> Add powershell version warning

- CHANGELOG.md
- public/components/common/modules/modules-helper.js
This PR fixes the possibility to remove the implicit filters in the modules.
- Restored the change from `match` to `match_phrase` when seeing the filters in the search bar.
- Restored the use of `.meta.value()` for Kibana 7.16.x-7.17.x.
These changes were introduced previously in:
- https://github.com/wazuh/wazuh-kibana-app/commit/b7f63d04c208e367bab9f7b8e1ef6b79aa532e39
- https://github.com/wazuh/wazuh-kibana-app/pull/3777/commits/e860353325d9015212004a85f73d5c9a2b7ee53b
Closes #4144
> [FIX] Avoid to remove the implicit filters in the modules

- CHANGELOG.md
- public/components/agents/vuls/inventory.tsx
This PR replaces as the full and partial scan dates are displayed in the `Details` panel in `Vulnerabilities/Inventory`
- Use the same component that renders data in the agent overview
- Generate vulnerabilities for an agent and go to `Vulnerabilities/Inventory and see the `Details` panel, the dates should be rendered as expected
Closes #4049
> [UI] Replaced as the full and partial scan dates are displayed in the Details panel in Vulnerabilites/Inventory

- CHANGELOG.md
- public/controllers/management/components/management/ruleset/actions-buttons.js
- public/controllers/management/components/upload-files.js
- public/styles/common.scss
When trying to upload a file with the same name it overwrote it and did not warn you that a file existed. What I did is to recover a functionality that was lost that tells you which files were uploaded or not if any were not uploaded, and add a checkbox for the option to overwrite or not.
**Test:**
1. Go to "Management/Rules or Decoders"
2. Click on "Manage rules files" or "Manage decoders files"
3. Click on "Import files"
4. import files with or without the overwrite option
**Issue:** 
- #4056 
https://user-images.githubusercontent.com/63758389/171361459-6071fe7b-e894-4167-8429-90d6ac85d27e.mp4
> Overwriting files in rules and decoders

- CHANGELOG.md
- public/controllers/agent/components/agents-preview.js
- public/kibana-integrations/kibana-vis.js
This PR fixes an error when building the core visualizations for the plugins for Kibana 7.16.x and 7.17.x.
- fix an error when building the core visualizations
- fix error in the `Agents` section caused by a not defined class.
- Navigate to any section which has a core visualization. This should be displayed.
> [FIX][Kibana][7.16.x-7.17.x] Fix error when building the visualizations

- CHANGELOG.md
- public/components/common/charts/charts/donut.tsx
The background of the tooltips of the agent module is fixed because the background was not appearing.
**Test:**
1. Navigate to Agents
2. Hover in the status chart
Screenshot:
Closes https://github.com/wazuh/wazuh-kibana-app/issues/4201
> Agents tooltip background

- CHANGELOG.md
- public/kibana-integrations/kibana-vis.js
This PR fixes an error that appears in the production package when building the visualizations. The problem doesn't appear in development mode as they are rendered correctly.
- Revert how the visualization is built
- Add logic to apply the params and uiStateJSON properties of the visualization that due a bung in KIbana 7.10.2 these are not working.
- The visualizations should be visible in development mode and in a production package without the mentioned error.
- Moreover, the visualizations should renders as expected related to the UI properties.
- Use case: with data related to the monitoring job of the plugin (agent status), review that the `Evolution` visualization of `Agents` section is displayed with the expected colors for the status labels.
- Review each visualization is visible …
> [FIX] Visualizations are not built due a Types was not set error in a production package

- CHANGELOG.md
- public/components/common/modules/modules-helper.js
A validation is added to a section of the filter code, since sometimes `moduleFilter.meta.value` is a function and sometimes a string.
When it was a string it lost the check to be able to eliminate or not the filter.
For example in the Mitre Attack module
**Issue:**
- #4218 
**Test:**
1. Navigate  to 'Mitre Attack module'
2. Look at the module filters can''t be removed.
3. View the console without error
> String or function validation

- CHANGELOG.md
- public/controllers/agent/components/register-agent.js
Changed the word `Manager` to `Wazuh server` from the phrases that appeared in "Deploy a new agent". 
**Issue:**
- #4210 
**Test:**
1. Navigate to `Agents`
2. Click on 'Deploy new agent'
3. Complete everything and at the end Wazuh server appears.
> Changed phrase "Wazuh server"

- CHANGELOG.md
- public/kibana-integrations/kibana-vis.js
**Steps to reproduce**
1- Navigate to an Agent's view.
2- Resize your browser's window.
3 - Open the browser's console.
4 - Navigate to the Inventory Data section.
5 - See the error.
**Video where you see the error solved:**
https://user-images.githubusercontent.com/99441266/172658878-3eb21f0c-61d8-410a-a6f3-862d96fdf923.mp4
Closes #4158
> Fix type error on the Agents main view

- CHANGELOG.md
- public/components/common/modules/discover/discover.tsx
This PR fixes a plugin crash when searching with a query with syntax errors in `Modules/Security events`.
Screenshot
Closes https://github.com/wazuh/wazuh-kibana-app/issues/4168
- Go to `Modules/Security events` and search with a query with syntax errors, by example:
```test()```
The plugin UI should not crash and should display toast messages with the errors.
> [BUG] Plugin crash when searching with a query with syntax errors in Modules/Security events

- CHANGELOG.md
- public/directives/wz-logtest/components/logtest.tsx
When a user goes to test a new rule in Tools -> Ruleset Test, we were getting API messages that were not displayed. Now if there are messages they are displayed on the screen.
**Issue:**
- #4111 
**Test:**
1. Navigate to 'Tools -> Ruleset Test'
2. Run test
3. Check that the messages appear, if there are no messages see that the request does not return messages
https://user-images.githubusercontent.com/63758389/173323330-c9800dab-f63f-4d89-9bbc-2f88a094460a.mp4
> Ruleset test messages

- CHANGELOG.md
- server/start/cron-scheduler/save-document.ts
This PR removes the logging when there is an error checking or creating the index.
If the error is not related to creating an existent index, this is thrown, caught, and logged in another method.
More information in:
- https://github.com/wazuh/wazuh-kibana-app/issues/4203#issuecomment-1147273268
The plugin logs, it should look similar to the screenshot when is initiated:
compare to the error seen in:
Closes https://github.com/wazuh/wazuh-kibana-app/issues/4203
- It should not be logged an error related to `resource_already_exists_exception` when creating the index of `statistics` job.
Requirements:
- Secure that depending on the `statistics` job configuration, a new index should be created when the job runs.
- Give to the internal Kibana user, permissions to create and index data in the …
> [Statistics] Remove logged error related to the creation of an existent index

- CHANGELOG.md
- public/components/overview/mitre_attack_intelligence/__snapshots__/intelligence.test.tsx.snap
- public/components/overview/mitre_attack_intelligence/intelligence.test.tsx
- public/components/overview/mitre_attack_intelligence/intelligence.tsx
Hi Team,
This PR add the AuthorizationPrompt in Mitre Intelligence section
Closes #4243
> Added authorization prompt in Mitre > Intelligence

- CHANGELOG.md
- public/components/settings/settings-logs/logs.js
- public/controllers/management/components/management/mg-logs/logs.js
Hi Team,
This PR fixes a Management > Logs layout to ensure that the "Load more logs" show correctly.
Closes #4206
> Fixed code editor component height in logs layout (Management and Settings)

- CHANGELOG.md
- public/components/security/policies/create-policy.tsx
- public/components/visualize/components/sample-data-warning.js
- public/controllers/management/components/management/configuration/edit-configuration/edit-configuration.js
- public/controllers/management/components/management/configuration/utils/wz-fetch.js
- public/controllers/management/components/management/reporting/utils/reporting-handler.js
- public/react-services/wz-request.ts
Added the waiting time to see if the manager is active again since it was not waiting for anything and in other ways of restarting it waits for 15000ms
**Issue:**
- #4181 
**Preconditions:**
1. Wazuh manager environments
**Test:**
1. Navigate to 'Management>Configuration'
2. Click on 'Edit configuration'
3. Change vulnerability-detector to enabled or disabled
4. Click save
5. Click restart manager button
6. Wait for it to restart
https://user-images.githubusercontent.com/63758389/173820553-64317ce5-a3cd-413d-99b0-9b879c52c5bb.mp4
> Timeout change in the restart manager in the configuration

- CHANGELOG.md
- public/controllers/dev-tools/dev-tools.test.tsx
- public/controllers/dev-tools/dev-tools.ts
This PR fixes a string error handling generated when Wazuh API's request has failed in _Wazuh Dev Tools_. 
Closes https://github.com/wazuh/wazuh-kibana-app/issues/4260
To test it:
- Go to Wazuh devtools
- Add agents running this request 
```
POST /agents
{
"name": "NewAgent3"
}
```
- Once agents were added, try to delete them with the request:
`DELETE /agents?agents_list=002&status=all`
- Verify the error can be seen properly in the right textarea _(API output)_
Other test cases:
- Inexistent endpoint
- Wazuh API is down
> Fixed parsedError string handling

- CHANGELOG.md
- common/api-info/endpoints.json
- public/controllers/management/components/management/mg-logs/logs.js
This PR removes the filtered tags of Wazuh manager logs, so they can appear in the tag selector of Management/Logs. This change is required because the API endpoint will be modified to accept any tag.
Issue: https://github.com/wazuh/wazuh/issues/13841
Pull request: https://github.com/wazuh/wazuh/pull/13867
The API changes should be integrated in the branch `4.3`. Use a manager with that version or secure the change is included in the manager you are using.
Related to https://github.com/wazuh/wazuh-kibana-app/issues/4242
> Remove the filtered tags of manager logs

- CHANGELOG.md
- public/services/resolves/get-ip.js
This PR adds a more descriptive message when finding the index patterns and the user has no permission to do it.
Closes  #4216
The proposed fix goes against the last work in frontend error management. We should consider if we want to include it or we should redefine how the errors are being managed to let this case.
Using OpenDistro for Elasticsearch or Wazuh dashboard:
1. create a new user without mapping any permissions
2. enable the `run_as` in the Wazuh API host entry of the Wazuh plugin. Restart Kibana/Wazuh dashboard to be sure the configuration is taken.
3. login using the created user, using `security_tenant=global` in the URL. For example: `https://localhost/5601/app/wazuh?security_tenant=global`
4. after the plugin loaded, it should redirect to the `blank-screen` and it should …
> Display a message related to missing user permissions when finding index patterns in a route resolver

- public/controllers/management/components/management/reporting/reporting-table.js
- public/react-services/reporting.js
- server/controllers/wazuh-reporting-security-endpoint-handler.test.ts
- server/controllers/wazuh-reporting-security-endpoint-parameters-validation.test.ts
- server/controllers/wazuh-reporting.ts
- server/lib/error-response.ts
- server/lib/security-factory/factories/default-factory.ts
- server/lib/security-factory/factories/opendistro-factory.ts
- server/lib/security-factory/factories/xpack-factory.ts
- server/plugin.ts
- server/routes/wazuh-reporting.ts
- server/start/index.ts
- server/start/migration-tasks/index.ts
- server/start/migration-tasks/reports_directory_name.test.ts
- server/start/migration-tasks/reports_directory_name.ts
Closes #4329
- Check the reports' folder for a user `$WAZUH_APP_HOME/downloads/reports/<username>` has been automatically renamed to `$WAZUH_APP_HOME/downloads/reports/hash(<username>)`, and that their reports are still inside the new folder.
- Check no report from other users can be obtained.
- Check there are no collisions between files in read/write operations.
- Check the report name is no longer sent from the frontend (check the request using the dev tools).
- Check that usernames with UTF-8 characters gets encoded by the MD5 hash function.
> Sanitize report's inputs and usernames

- CHANGELOG.md
- public/controllers/management/components/management/groups/utils/columns-main.js
Added the option to sort by agents in the group table.
**Issue:**
- #3950
**Preconditions:**
Have more than 1 group with different numbers of agents
**Test:**
1. Navigate to "Management/Groups"
2. Click on "Agents"
3. See that they are sorted by number of agents 
> Sorting by agents in the table groups

- package.json
This PR adds the MD5 node module dependency, as it is needed by the plugin.
> Fix MD5 dependency

- CHANGELOG.md
- common/constants.ts
- public/components/health-check/container/__snapshots__/health-check.container.test.tsx.snap
- public/utils/config-equivalences.js
- server/lib/initial-wazuh-config.ts
A new constant has been created in the `common/constants.ts` file and used in all necessary places
> Fixed path in logo customization section

- CHANGELOG.md
- common/constants.ts
- server/lib/security-factory/factories/default-factory.ts
- server/lib/security-factory/factories/xpack-factory.ts
This PR fixes when x-pack is detected with no `authContext` available and no `hashUsername` is provided. Therefore in this kind of context, creating PDF reports fails.
> Fix creating PDF reports in x-pack without authentication context 

- public/components/agents/sca/inventory.tsx
- public/components/wz-search-bar/lib/suggest-handler.ts
Hi Team, 
This PR resolves an issue occurring on the SCA Inventory Table Searchbar when we select a field of the suggestion list that doesn't exist in the table data rendered.
I added validations for the suggestions list item. Now the suggestion fields always will exist in the table preventing the current error. 
Closes #4347 
- Do the same steps to reproduce the error (Described in issue comments).
- Expects the error doesn't appear.
> Fixed searchbar error on SCA Inventory table

- CHANGELOG.md
- common/csv-key-equivalence.ts
- public/utils/monitoring-fields.ts
- server/controllers/wazuh-reporting.ts
- server/integration-files/monitoring-known-fields.ts
This PRs fixes some problems when generating a group reports:
- Error due to accessing to a property of undefined
- The agent in group table doesn't display all the agents in the group.
Closes #4348
- Fixed an error due to accessing to a property of undefined when the API request to get the group configuration failed due to token expiration or another error.
- Changed styles of `Agents in groups` title
- Fixed a problem with missing agents in the table for a group report.
Now it gets all the agents.
- Removed unnecessary API request
- Optimized API requests to get the agent information required to print
the agents in group's table
- Removed `manager_host` deprecated field ([more information](https://github.com/wazuh/wazuh-kibana-app/commit/320825de99791fc76fb826712f4bb37d557672db#diff-9808 …
> Fixed errors in group reports

- CHANGELOG.md
- server/start/initialize/index.test.ts
- server/start/initialize/index.ts
This PR fixes that the host extension configuration was lost when changing the installed plugin (changed version or revision) because the registry file was rebuilt with an empty configuration for the `hosts` field. Now, the `hosts` configuration is kept and migrates the extension configuration when changing the installed plugin.
Extension configuration migration:
- Keep the supported and existing extension with the configured value.
- Add the supported and missing extensions in the previous configuration
- Remove not supported extensions by the installed plugin
- Migrated the existing host configuration in the registry file when changing the
plugin version or revision, instead of removing it when it was rebuilt.
- Removed not necessary return statements
- Removed not necessary try/catch …
> Fix modules settings persistence between updates

- CHANGELOG.md
- server/start/initialize/index.test.ts
- server/start/initialize/index.ts
Backport from https://github.com/wazuh/wazuh-kibana-app/pull/4359.
> [Backport 4.3-1.2-wzd] Fix modules settings persistence between updates

- CHANGELOG.md
- public/plugin.ts
In `public/plugin.ts` a Get request is done with a Kibana resource `core.http.get(/api/check-wazuh)`.
That resource fails in Chrome and Firefox browsers.
The Kibana core get resource is set up to catch the error with an `HttpFetchError` class that is a child of the Node Error class. Which is compatible only with browsers with V8 engine.
For this reason in Chrome it shows the error in the console as a debug and in Firefox it shows it in the console as an unrecognized error.
In the `http_fetch_errors.ts` and `globals.d.ts` files, kibana mentions V8 compatibility and that it will only work in browsers that use it. Attached screenshots
https://github.com/v8/v8/wiki/Stack%20Trace%20API#customizing-stack-traces
Change the Get request that was made with a Kibana core.http.get(/api/check-wazuh) …
> TypeError resolved

- CHANGELOG.md
- common/constants.ts
- public/services/resolves/get-config.js
- public/utils/config-equivalences.js
- server/controllers/wazuh-hosts.ts
- server/lib/initial-wazuh-config.ts
- server/lib/manage-hosts.ts
- server/lib/update-registry.ts
This PR solves the issue noted in the issue https://github.com/wazuh/wazuh-kibana-app/issues/4349#issuecomment-1204050742.
```yml
---
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#-------------------------------- Wazuh hosts ----------------------------------
#
#
hosts:
- default:
url: https://localhost
port: 55000
username: wazuh-wui
password: wazuh-wui
run_as: false
```
- The `wazuh.yml` file is created without errors.
- The link to the web documentation is right: https://documentation.wazuh.com/4.3/user-manual/wazuh-dashboard/config-file.html
- The in-file documentation is understandable and free of errors (of any kind).
- The in-file documentation is consistent with the UI and web …
> Fix wazuh.yml link and in-file documentation

- CHANGELOG.md
- README.md
- package.json
- public/react-services/reporting.js
- public/services/reporting.js
- server/controllers/wazuh-reporting.js
- server/routes/wazuh-reporting-enpoint-parameters-validation.test.ts
- server/routes/wazuh-reporting.js
- test/jest/jest.config.js
- test/jest/jest.js
This PR adds parameter validation to the report's endpoints.
Closes https://github.com/wazuh/wazuh-kibana-app/issues/4329
- Add parameter validation to the reporting endpoints.
- Removed some parameters in the reporting endpoints.
- Build the report name in the backend.
- Add testing with Jest.
- Add tests with invalid parameters in the reporting endpoints.
- Do requests to the reports endpoints with unexpected / forbidden parameters using some tools such as cURL or Postman.
- Check that each kind of report can be generated as expected:
- Modules (with an agent selected, without an agent selected, changing the type of selected time range, etc...)
- Group
- Agent configuration
- Agent inventory
> Sanitize report's inputs and usernames - 3.13.x

- CHANGELOG.md
- common/config-equivalences.js
- public/components/settings/configuration/components/header.tsx
- public/components/settings/configuration/configuration.tsx
- server/lib/initial-wazuh-config.ts
changed the config-equivalences file folder to make it available for the entire application
**Issue:**
- #4378
> Moved the file config-equivalences to common

- CHANGELOG.md
- public/components/common/modules/discover/discover.tsx
- public/components/overview/metrics/metrics.tsx
- public/components/overview/mitre/lib/elastic-helpers.ts
In the dashboards, nested fields were not properly identified and because of this, the query results didn't work as expected. To fix it we added the index pattern information to the query building methods, so the field information can be retrieved and analyzed to structure the query object.
Closes https://github.com/wazuh/wazuh-kibana-app/issues/4430
> Fixed dashboard nested fields filtering

- CHANGELOG.md
- public/components/common/modules/discover/discover.scss
- public/components/common/modules/discover/discover.tsx
- public/components/common/modules/discover/row-details.tsx
This PR fixes the issue where the **Dashboard** / **Security Alerts** table was not prepared to render an array of objects as a field value. It implements the components used in **Modules** / **Events** table to analyze and render possible nested fields.
Closes https://github.com/wazuh/wazuh-kibana-app/issues/4429
<details>
<summary>Screenshot</summary>
***
***
</details>
> Render nested field rows in security alerts table

- test/cypress/cypress/integration/pageobjects/xpack/wazuh-menu/decoders.page.js
- test/cypress/cypress/integration/step-definitions/management/decoders/the-user-selects-a-custom-decoder-when.js
After executing a complete execution of the automated test suite, it was detected a few errors on Kibana 7.16.3 with the Xpack plugin, so this PR is to solve the detected problem.
Closes: https://github.com/wazuh/wazuh-kibana-app/issues/4460
Executed Test:
This PR covers the solution to the edit-decoder-without-saving test.
After checking the existing selector, I saw that it was two web elements with the same selector, which was causing the problem.
Modify the selector and the problem is solved, test both xpack and wzd
Changed selector
> Updating XML selector for decoder file

- CHANGELOG.md
- public/components/common/modules/discover/discover.scss
- public/components/common/modules/discover/discover.tsx
- public/components/common/modules/discover/row-details.tsx
Backport https://github.com/wazuh/wazuh-kibana-app/commit/b2a6c10b5ae284bb25210e5c696750ec25efacdc from https://github.com/wazuh/wazuh-kibana-app/pull/4428.
* Evaluate nested fields and render object array
* Removed text color style
* Added changelog
(cherry picked from commit b2a6c10b5ae284bb25210e5c696750ec25efacdc)
> [Backport 4.4-1.2-wzd] Render nested field rows in security alerts table

- test/cypress/cypress/integration/step-definitions/management/decoders/the-user-creates-a-new-decoder-when.js
- test/cypress/cypress/integration/step-definitions/management/rules/the-user-writes-a-new-rule-when.js
- test/cypress/cypress/integration/utils/driver.js
|Related issue|
|---|
|closes #4494   |
Description:
This PR implements a fix to Create new decoder/rule test for Wazuh Dashboard.
The main problem is related to the decoder name, the new decoder needs to have a unique name
Solution: 
The proposed solution is to use a random name for the new decoders based on the timestamp. I add this code in a new function in the controller so we can implement it in other test cases as well.
<details>
</details>
> Test Fixed, change decoder/rule tittle for correct execution

- public/components/overview/metrics/metrics.tsx
This PR fixes an issue with the main Office 365 dashboard, in which the Max Rule Level was not showing the correct value. 
- Modified the file  `public/components/overview/metrics/metrics.tsx` for the office Max Rule Level to use the field rule.level instead of timestamp.  
Closes #4355 
**Screenshots**
- Before the changes:
- After the changes:
Scenario: Open the main Office 365 dashboard
Given the alerts on the specified timeframe 
When the maximum alert level is defined
Then the Max Rule Level should show the correct value and match with the value shown in the `Events by severity over time` graphic
> Changed terms of Office Max Rule Level

- test/cypress/cypress/integration/features/filters/remove-filter-from-module-dashboard.feature
Issue #4527 
This PR includes the fix for the feature "remove filter from modules dashboard"
We decided to delete some modules because on wzd these modules are disabled by default
Modules:
- GDPR
- HIPAA
the feature remains:
```
Scenario Outline: The user remove an added filter - Module - Dashboard <Module Name>
When The user goes to <Module Name>
And The user adds a new filter
And The user checks filter label is added
And The user removes the applied filter
Then The user checks filter label is not added
Examples:
| Module Name          |
| Security Events      |
| Integrity Monitoring |
| System Auditing      |
| Mitre & Attack       |
| NIST                 |
| TSC                  |
| Policy Monitoring    |
| PCIDSS               |
```
<details>
<summary> Feature</summary>
</details> …
> fix for #4527- remove filter from modules dashboard

- test/cypress/cypress/integration/step-definitions/settings/configuration/valida-configuration.when.js
Issue #4530 
This PR includes the fix for the feature "configuration to the module", this includes changes of the texts description on the setting/configuration page.
one example of the change including
```
(Cypress.env('type') == 'wzd') ? elementTextIncludes(LogosCustomizationPanelLogoReportDescription, 'Set the name of the reports logo (.png) stored at /plugins/wazuh/public/assets/') : elementTextIncludes(LogosCustomizationPanelLogoReportDescription, texts.Panel[4].items[3].subTitle);
```
<details>
<summary> Feature</summary>
</details>
> fix for configuration feature

- test/cypress/cypress/integration/features/management/settings/sample-data.feature
- test/cypress/cypress/integration/pageobjects/wzd/settings/api-configuration.page.js
- test/cypress/cypress/integration/pageobjects/wzd/settings/logs.page.js
- test/cypress/cypress/integration/step-definitions/filters/the-user-adds-a-new-filter.when.js
- test/cypress/cypress/integration/step-definitions/settings/navigate-to-settings.when.js
- test/cypress/cypress/integration/step-definitions/settings/sample-data/add-remove-sample-data.when.js
- test/cypress/cypress/integration/step-definitions/settings/wazuh-logs/reload-logs.when.js
Issue #4545  
This PR includes the fix for both features add sample data and About.
fix for About feature:
it was decided to add a wait for the web elements.
Fix for Add Sample Data:
It was decided to add a step to the function, this step fixes the state of the button in the sample data page when the state of the buttons does not have the expected state.
```
And All buttons have add status
```
```
And All buttons have remove status
```
<details>
<summary> Feature</summary>
</details>
<details>
<summary> Test execution</summary>
</details>
> 4545-fix for "add sample data" and "About" features

- test/cypress/cypress/integration/step-definitions/settings/navigate-to-settings.when.js
Issue #4550 
This PR includes the fix for enabling Virus Total Module.
It includes an if statement logical block for WZD
before:
```
cy.wait(1000);
elementIsVisible(getSelector(menuOption, SETTINGS_MENU_LINKS)).click();
```
After:
```
if (Cypress.env('type') == 'wzd') {
cy.wait(1000);
elementIsVisible(getSelector(menuOption, SETTINGS_MENU_LINKS)).click()
} else {
elementIsVisible(getSelector(menuOption, SETTINGS_MENU_LINKS));
clickElement(getSelector(menuOption, SETTINGS_MENU_LINKS));
};
```
Test 
<details>
<summary>Test execution</summary>
</details>
> 4550-feature/fix for enable modules Virus Total in Xpack

- test/cypress/cypress/integration/pageobjects/xpack/wazuh-menu/wazuh-menu.page.js
- test/cypress/cypress/integration/step-definitions/management/decoders/the-confirm-modal-is-displayed-then.js
- test/cypress/cypress/integration/step-definitions/management/groups/the-confirm-modal-is-displayed-then.js
- test/cypress/cypress/integration/step-definitions/management/rules/the-confirm-modal-is-displayed-then.js
- test/cypress/cypress/integration/step-definitions/settings/sample-data/add-remove-sample-data.when.js
- test/cypress/cypress/integration/utils/driver.js
Issue #4568 
This PR includes the fix for the "add new filter "feature and other fixes for conditional on the When step "All buttons have..."
It includes:
- increase the timeout on the getElement function
- a new closure in the if statement logical block for Xpack
Test 
<details>
<summary>Test execution</summary>
</details>
> fix for timeout and change the if conditional

- CHANGELOG.md
- common/constants.ts
- public/components/health-check/container/health-check.container.tsx
- public/components/health-check/services/check-setup.service.ts
Solves #4299 
On PR https://github.com/wazuh/wazuh-kibana-app/pull/4103, a method was changed to request the API endpoint. Only for testing purposes of this particular issue, it is possible to replace line 50 of `server/lib/api-interceptor.ts` with the following: `method: !!authContext ? 'POST' : 'GET',` to avoid getting an error due to a not allowed method and trigger the desired error.
- Modified the message displayed when there is a version mismatch between the Wazuh API and the Wazuh App, to make it easier to understand.
- Removed the \<a\> tags on the message. 
- Added `PLUGIN_APP_NAME` constant to make the message match the same structure as in Wazuh Dashboard, for easier modifications in the future. 
- Added `addTagsToUrl` function on `health-check-container.tsx` and modified the …
> Change message for API version mismatch in Kibana

- .github/workflows/cypress-basic.yml
- .github/workflows/cypress-odfe.yml
- .github/workflows/cypress-wzd.yml
- .github/workflows/cypress-xpack.yml
Hello team in this PR I remove one of the commands that copies the reports from cypress to send them to slack. These reports are not necessary to send them to slack, since we can access them from the actions.
- Closes #4603
> Delete CP command for reports on Cypress

- server/controllers/wazuh-api.ts
Hi team, this PR fixes a typo in `getAppLogos` endpoint controller. This will avoid mis-interpreting an error in case an exception is logged.
Related to [#4539](https://github.com/wazuh/wazuh-kibana-app/pull/4539/files#diff-b5c6c40e187d24bd680f9885b7ec2a1d09d7faaf1e32e6954c78a03efb6d5306R1100)
> Fix typo in API getAppLogos endpoint catch log

- test/cypress/cypress/integration/features/management/rules/filter-rules-si-displayed-after-refresh.feature
- test/cypress/cypress/integration/step-definitions/management/rules/the-filtered-label-is-still-visible-then.js
- test/cypress/cypress/integration/step-definitions/management/rules/the-user-clicks-the-refresh-button-when.js
Added Feature to increase coverage for Rule module. This feature checks the rules result displayed filtered by a user per level
#4636 
<details>
<summary> test execution</summary>
</details>
> Add test feature: rules are displayed after refreshing the page using a filtered label

- CHANGELOG.md
- README.md
- kibana.json
- package.json
Add support for Wazuh 4.3.9
Closes https://github.com/wazuh/wazuh-kibana-app/issues/4654
> Bump 4.3.9

- .github/pull_request_template.md
- CHANGELOG.md
- README.md
- kibana.json
- package.json
Sync branches for release 4.3.9
#4582
> Merge 4.3-7.10 into master

- test/cypress/cypress/integration/features/management/rules/validate-paginator.feature
- test/cypress/cypress/integration/step-definitions/management/rules/a-new-set-of-rules-displayed.when.js
Some Features are failing on the test suite execution because of misspellings on steps features.
<details>
<summary>tes case fail</summary>
</details>
#4648 
<details>
</details>
> fix for misspelling on features 4648

- CHANGELOG.md
- public/app.js
When SAML is enabled, the logout button inside the Wazuh plugin didn't work properly. That was because there is a function to remove the token before redirecting to logout, and the logout URL is different when SAML is enabled. 
The solucion provided is to get the logout URL programatically from the logout anchor. That way, the issue is resolved and there is no need to modify anything in case that the logout URL changes in the future.
https://github.com/wazuh/wazuh-kibana-app/issues/4595
Trying to logout from the Wazuh plugin before the changes: 
Trying to logout from the Wazuh plugin after the changes (the user is correctly redirected to the idp login page): 
Scenario: have an environment with xPack
When the user opens the Wazuh plugin and clicks on log out 
Then the session should be …
> Fix logout from Wazuh when SAML is enabled

- test/cypress/cypress/integration/features/filters/Search-by-parameters.feature
- test/cypress/cypress/integration/features/filters/pin-filter-from-dashboard-to-events.feature
- test/cypress/cypress/integration/pageobjects/wzd/filters/filters.page.js
- test/cypress/cypress/integration/step-definitions/filters/The-user-types-particular-search.when.js
- test/cypress/cypress/integration/step-definitions/filters/the-query-is-accepted.then.js
- test/cypress/cypress/integration/step-definitions/settings/The-wazuh-admin-user-is-logged.given.js
- test/cypress/cypress/integration/utils/driver.js
this PR adds a feature to increase coverage in some modules for search by filter with parameters AND, OR
Feature
```
Feature: Search by parameters
As a Wazuh user
I want to pin a filter
in order to aplly it across the modules
Background:
Given The wazuh admin user is logged
And The sample data is loaded
Scenario Outline: Search by parameters with AND
When The user goes to <Module Name>
And The user types a particular search <key> on the search bar
Then The query is accepted and the results should be displayed
Examples:
| Module Name          | key                                              |
| Security Events      | cluster.name : "wazuh" and rule.level : "3"      |
| Integrity Monitoring | cluster.name : "wazuh" and agent.id : "001"      |
| NIST                 | cluster.name : …
```
> feature search by parameters And , Or

- CHANGELOG.md
- server/controllers/wazuh-api.ts
- server/routes/wazuh-api-http-status.test.ts
Team, this PR fixes typos and error codes that shouldn't be replaced in the pull request _[Replace generic HTTP status codes in the API controller #4710](https://github.com/wazuh/wazuh-kibana-app/pull/4710)_
- All jest tests should work.
- Testing the previous PR [#4710](https://github.com/wazuh/wazuh-kibana-app/pull/4710) should work
> Fix typos and errors code status replacement in wazuh-api controller

- test/cypress/cypress/integration/features/management/reporting/add-report-from-modules-agent.feature
- test/cypress/cypress/integration/features/management/reporting/add-report-from-modules.feature
Hello team.
This PR includes a fixed for a problem that was related to generate report test. The problem was related to cases when sample data was not added, so after the work of @mauceballos we can made a function to call and add sample data with API calls.
So I added the call for the function that @mauceballos implemented and with this the problem was solved.
<details>
The error displayed it's related to a reported bug: https://github.com/wazuh/wazuh-kibana-app/issues/4621
</details>
> Adding sample data call on test definition

- test/cypress/cypress/integration/step-definitions/settings/The-wazuh-admin-user-is-logged.given.js
Hello team, we create this PR to integrate functionality that checks the environment where the test suite execution it's been executing.
This functionality fixes some problems that we have with the previous test suite execution.
<details>
</details>
> Add an environment validation to check the request

- server/routes/wazuh-api-http-status.test.ts
Team, this PR fixes the unit test server configuration. It adds the cors and shutTimeout options.
Run the unit test in Kibana 7.16
> Fix HTTP status error unit test for Kibana 7.16

- CHANGELOG.md
- common/constants.ts
- common/plugin-settings.test.ts
- common/services/settings-validator.ts
- public/components/common/form/__snapshots__/index.test.tsx.snap
- public/components/common/form/index.test.tsx
- public/components/common/form/index.tsx
- public/components/common/form/input_text_area.tsx
- public/components/settings/configuration/components/categories/components/category/category.tsx
- public/components/settings/configuration/configuration.tsx
- server/controllers/wazuh-reporting.ts
- server/lib/reporting/printer.ts
- server/routes/wazuh-reporting.test.ts
- server/routes/wazuh-utils/wazuh-utils.test.ts
Backport ce29034e17045a808b43390f314b44fbf2c7c8e2 from #4505.
> [Backport 4.4-7.16] Add header and footer report customization #4505

- CHANGELOG.md
- common/constants.ts
- common/services/settings-validator.ts
- common/services/settings.ts
- tsconfig.json
Team,
this PR adds the wazuh.yml multiline settings validations to the configuration description. The goal is to warn the user about the text area validations to prevent errors.
Related issue #4446
> Add multi-line validation parameters in config description

- public/components/common/form/input_text_area.tsx
This PR fixes the rows limit of the textarea input
#4426 
Check that the text areas' height is limited.
> Fix the rows limit in the textarea input

- CHANGELOG.md
- common/constants.ts
- common/plugin-settings.test.ts
- server/lib/reporting/printer.ts
- server/routes/wazuh-utils/wazuh-utils.test.ts
Hi team,
this PR increases the maximum character length of the header and footer PDF report customization. 
- Go to Settings / Configuration
- Customize a header and check the maximum character length is 40
- Customize a footer and check the maximum character length is 50
> Fix PDF header and footer input max row length

- CHANGELOG.md
- public/app.js
When SAML is enabled, the logout button inside the Wazuh plugin didn't work properly. That was because there is a function to remove the token before redirecting to logout, and the logout URL is different when SAML is enabled.
The solucion provided is to get the logout URL programatically from the logout anchor. That way, the issue is resolved and there is no need to modify anything in case that the logout URL changes in the future.
https://github.com/wazuh/wazuh-kibana-app/issues/4595
Trying to log out from the Wazuh plugin before the changes:
Trying to log out from the Wazuh plugin after the changes (the user is correctly redirected to the idp login page):
Scenario: have an environment with xPack
When the user opens the Wazuh plugin and clicks on log out
Then the session should be …
> change function to get the path programatically

- CHANGELOG.md
- public/controllers/agent/components/register-agent.js
- public/styles/component.scss
In Wazuh info, in the 'Deploy new agent' section, the OS and versions were not displayed correctly.
This is what Wazuh Info used to look like:
This is what it looks like now: 
*Verify that the styles are displayed correctly.
> Fix styles in deploy new agent section

- CHANGELOG.md
- public/controllers/agent/components/register-agent.js
In the Wazuh information, in the 'Deploy new agent' section, the redhat7 version lacked the powerPC architecture.
Before:
Now: 
*Click the 'Deploy new agent' button.
*Verify that redhat7 supports i386, x86_64, armhf, aarch64 and powerPC architectures.
> redhat7 version powerPC

- CHANGELOG.md
- README.md
- kibana.json
- package.json
Adds support for Wazuh 4.3.10
#4836 
Not needed
Not needed
> Add support for Wazuh 4.3.10 - 7.10.2

- CHANGELOG.md
- public/controllers/agent/components/register-agent-service.test.ts
- public/controllers/agent/components/register-agent-service.ts
Fixed wrong WAZUH_PROTOCOL suggestion when the user has `enrollment.DNS configuration and set a custom IP typing in the server Address Combobox
Closes #4318
> Fixed WAZUH_PROTOCOL param suggestion

- CHANGELOG.md
- public/controllers/agent/wazuh-config/index.ts
We want to unify the names displayed in operating system versions, as for example in SUSE versions only the number is displayed and on Ubuntu the number plus the OS name is displayed.
https://github.com/wazuh/wazuh-kibana-app/issues/4850
*Verify that each version shows the OS name plus the number.
> Show name and number in OS version

- CHANGELOG.md
- public/controllers/agent/wazuh-config/index.ts
We want to unify the names displayed in operating system versions, as for example in SUSE versions only the number is displayed and on Ubuntu the number plus the OS name is displayed.
https://github.com/wazuh/wazuh-kibana-app/issues/4850
*Verify that each version shows the OS name plus the number.
> Backport 4851 to 4.4 7.16

- CHANGELOG.md
- public/controllers/agent/components/register-agent-service.test.ts
- public/controllers/agent/components/register-agent-service.ts
- public/controllers/agent/components/register-agent.js
- public/controllers/agent/register-agent/steps/__snapshots__/server-address.test.tsx.snap
- public/controllers/agent/register-agent/steps/index.ts
- public/controllers/agent/register-agent/steps/server-address.test.tsx
- public/controllers/agent/register-agent/steps/server-address.tsx
Backport https://github.com/wazuh/wazuh-kibana-app/commit/d1787527a1879b399a39b907a74e9f6d28f8db97 from https://github.com/wazuh/wazuh-kibana-app/pull/4776
> [Backport 4.4-7.16] Add cluster's IP and protocol as suggestions in the agent deployment wizard

- CHANGELOG.md
- public/controllers/agent/components/register-agent.js
- public/controllers/agent/wazuh-config/index.ts
Add macOS version to wizard deploy agent
[#4204][#4178]
*Verify that the macOS Ventura version is displayed.
> Fix add mac os version

- CHANGELOG.md
- public/controllers/agent/components/register-agent.js
- public/controllers/agent/wazuh-config/index.ts
Add macOS version to wizard deploy agent
Backport c64a0775badac71185baf2f36267e5cb8f0f8d9f from #4867.
[#4204][#4178]
*Verify that the macOS Ventura version is displayed.
> [Backport 4.4 7.16] Fix add mac os version

- CHANGELOG.md
- public/controllers/agent/components/register-agent.js
Raspbian OS, Ubuntu, Amazon Linux and Amazon Linux 2 commands in the wizard deploy agent now change when selecting a different architecture.
[#4204]
[[Provide screenshots or videos to prove this PR solves the issues]](https://user-images.githubusercontent.com/99441266/202254679-c0ddce9a-cc7c-44ad-a4ad-c4db5f52b2cc.mov)
*Verify that when changing architecture the OS Raspbian, Ubuntu, Amazon Linux and Amazon Linux 2 show the commands according to the selected architecture.
> Fix architecture link in the deploy agent wizard

- CHANGELOG.md
- public/controllers/management/components/management/configuration/utils/utils.js
Backport https://github.com/wazuh/wazuh-kibana-app/commit/5dba6f44b6ae0a5b6d3fd528dbfc805db21daa39 from https://github.com/wazuh/wazuh-kibana-app/pull/4917.
> Fix display of remote protocols when there are more than one (#4917)

- CHANGELOG.md
- public/controllers/management/components/management/mg-logs/logs.js
This PR adds a validation in the "Export formatted" button when the logs are empty.
Closes #4948 
- When the logs are empty the "Export formatted" button must be disabled.
https://user-images.githubusercontent.com/6089438/206191509-1141916e-2eb3-44b1-b0a6-4a56daf47fb3.mp4
> Added export logs validation when is empty

- CHANGELOG.md
- public/components/agents/vuls/inventory.tsx
- public/components/agents/vuls/inventory/detail.tsx
- public/components/agents/vuls/inventory/lib/index.ts
- public/components/agents/vuls/inventory/lib/utils.ts
Hi team,
this PR changes de default last scan date parser to be able to catch dates returned by Wazuh API when no vulnerabilities scan has been made. It prepares the parser to format any date string starting with `1970` _(default last scan date in the API response)_.
Default last scan response example:
```
{
"data": {
"affected_items": [
{
"last_full_scan": "1970-01-01T00:00:00+00:00",
"last_partial_scan": "1970-01-01T00:00:00+00:00"
}
],
"total_affected_items": 1,
"total_failed_items": 0,
"failed_items": []
},
"message": "Last vulnerability scans of the agent were returned",
"error": 0
}
```
Closes https://github.com/wazuh/wazuh-kibana-app/issues/4959
- Set up a new environment without any vulnerabilities scan
- Go to Vulnerabilities / Inventory
- See the default dates as `-`
> [Backport 7.16] Fix default last scan date formatter

- CHANGELOG.md
- public/controllers/management/components/management/common/file-editor.tsx
This PR adds validations in the File Editor.
Closes #4946 
- When the editor hasn't changed the initial content or is empty the "Save" button is disabled
https://user-images.githubusercontent.com/6089438/206179577-c56db1f9-a38b-44f5-a2bb-14f4836b790e.mp4
- When the editor has a valid XML  the "Save" button is enabled.
https://user-images.githubusercontent.com/6089438/206179804-272887db-35c0-496c-9642-1034823d769a.mp4
>  Added file saving conditions in File Editor

- CHANGELOG.md
- public/controllers/agent/components/register-agent.js
This PR fixes the agent installation command for macOS
This pull request is going to be merged into the main branch used for this epic [#4931](https://github.com/wazuh/wazuh-kibana-app/pull/4933)
[4.4-2.3-wzd](https://github.com/wazuh/wazuh-kibana-app/pull/4982)
[4.4-7.16 ](https://github.com/wazuh/wazuh-kibana-app/pull/4983)
#4953 
* Click on agents
* Click deploy new agent
* Follow the steps to deploy a new macOS agent
* In the step 'Install and enroll agent' the variables WAZUH_MANAGER, WAZUH_AGENT_GROUP and WAZUH_AGENT_NAME *should not contain a '=' sign.
> Fix the agent installation command for macOS

- CHANGELOG.md
- public/components/agents/sca/inventory.tsx
- public/components/agents/sca/inventory/checks-table.tsx
Hi Team, This PR fixes the behavior when the Inventory Stat is clicked.
Closes #4952 
- When the Inventory Stat is clicked the Check table must be filtered
https://user-images.githubusercontent.com/6089438/207654344-f8e73ffa-25fa-4881-ab8b-bd0317d80ebb.mp4
1. **Scenario** The user can add a filter by clicking on the result count indicator (Pass) of the Security configuration assessment
policy checks
**Given** SCA data is available
**When** the user is seeing the table of checks of a Security configuration assessment
policy
**And** the user clicks on any result count indicator
**Then** a filter must be added to the search bar
**And** the table should be filtered by the added filter
2. **Scenario** The user can add a filter by clicking on the result count indicator (Fail) of the Security …
> Fixed Inventory checks table filters by stats

- CHANGELOG.md
- public/components/common/modules/discover/discover.tsx
- public/components/common/modules/discover/row-details.tsx
- public/kibana-integrations/lib/format_hit.ts
The Security Alerts table is unable to parse and render properly nested fields. It displays an array of objects as a single line array string without interpreting the object.
Related issue https://github.com/wazuh/wazuh-kibana-app/issues/4429
Related PR for Kibana 7.10 https://github.com/wazuh/wazuh-kibana-app/pull/4428
Closes https://github.com/wazuh/wazuh-kibana-app/issues/4906 issue found in 7.16.x tests
- Load AWS alerts with nested fields
- Go to Security Events / Events
- Search for an alert with nested fields
- Open the row details in the table and check the field is shown properly
- Go to Security Events / Dashboard
- Search for an alert with nested fields
- Open the row details in the Alerts table and check the field is shown properly
> Nested fields error in Security Alerts table and Events tab row details

- CHANGELOG.md
- package.json
- public/app.js
- public/get_inner_angular.ts
- public/kibana-integrations/kibana-discover.js
This pull request fixes some problems related to dependency vulnerabilities:
- Removed `angular-chart.js` dependency and unused code
- Upgrade `winston` to `3.5.1`
Closes #4956
1. **Scenario** Plugin logs should be generated without problems
**Given** a new environment without plugin logs stored in the filesystem
**When** the plugin starts
**Then** it should exist the plugin logs files with some logs
> Fix vulnerabilities in dependencies

- CHANGELOG.md
- package.json
- public/app.js
- public/get_inner_angular.ts
- public/kibana-integrations/kibana-discover.js
- server/routes/wazuh-reporting.test.ts
This pull request fixes some problems related to dependency vulnerabilities:
- Remove `angular-chart.js` dependency and unused code
- Upgrade `winston` to `3.5.1`
- Upgrade `pdfmake` to `0.2.6`
Closes #4956
1. **Scenario** Plugin logs should be generated without problems
**Given** a new environment without plugin logs stored in the filesystem
**When** the plugin starts
**Then** it should exist the plugin logs files with some logs
2. **Scenario** The PDF reports can be generated correctly - Modules without selected agent
**When** the user exports to PDF a Dashboard. For example, `Security events` and no agent is selected
**Then** the PDF should be generated correctly.
**And** the logo should appear
**And** the default …
> [Backport 4.4-7.16] Fix vulnerabilities in dependencies

- CHANGELOG.md
- public/components/agents/sca/inventory.tsx
This pull request removes unneeded buttons in the SCA inventory section.
The affected buttons are:
- Export formatted
- Refresh
that were displayed on the top of the panel.
With the work in a previous pull request (https://github.com/wazuh/wazuh-kibana-app/pull/4653), these actions are included in the reusable component, but the previous buttons were not removed so they were duplicated.
Closes #5011 
The buttons were placed in the highlighted section.
**Scenario 1**: `Export formatted` button should not be duplicated
**Given** data related to Security configuration assessment scan
**When** When the user goes to `Modules/Security configuration assessment`
**And** Select a policy
**Then** the button should be duplicated. It should appear above the table.
**Scenario 2**: `Refresh` button …
> Remove duplicated buttons in SCA inventory

- CHANGELOG.md
- public/controllers/agent/components/register-agent.js
This PR aims to add a validation to the agent name, in order to avoid entering incorrect names that may cause errors in different places of the app.
https://github.com/wazuh/wazuh-kibana-app/issues/4927
**Scenario:** have a Wazuh environment and navigate to agents/deploy new agent
**When** the users enter a name with [invalid characters](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#agent-name)
**Then** it should show an error telling that, and not show the deploy commands
> Add validation to agent name

- CHANGELOG.md
- public/controllers/agent/components/register-agent.js
Backport from https://github.com/wazuh/wazuh-kibana-app/pull/5028
> [Backport 4.4-2.4-wzd] Add length validation to agent name

- CHANGELOG.md
- public/controllers/agent/components/register-agent.js
This PR aims to add length validation to the agent name, in order to avoid entering incorrect names that may cause errors in different places of the app.
https://github.com/wazuh/wazuh-kibana-app/issues/4927
Scenario: have a Wazuh environment and navigate to agents/deploy new agent
When the users enter a name shorter than 2 characters
Then it should show an error telling that, and not show the deploy commands
Scenario: have a Wazuh environment and navigate to agents/deploy new agent
When the users doesn't enter any name 
Then it should not show any errors and should show the deploy commands.
> Add length validation to agent name

- CHANGELOG.md
- public/controllers/agent/components/register-agent.js
A solaris command has been fixed
> fix solaris command

- docker/osd-dev/config/2.x/osd/opensearch_dashboards.yml
- public/components/wz-menu/wz-menu.scss
This pull requests disables the expanded header (black top bar) by adding this configuration to the `opensearch_dashboards.yml` file
```
opensearchDashboards.branding:
useExpandedHeader: false
```
With `useExpandedHeader: false`
Without `useExpandedHeader: false`
Start environments and see that the black header has disappeared.
> Disable expanded header in Wazuh Dashboard

- CHANGELOG.md
- public/controllers/agent/components/register-agent.js
- public/controllers/agent/wazuh-config/index.ts
Fixed commands: Aix, OpenSUSE, Alpine, Suse11, Fedora, HP, Oracle Linux 5, Amazon Linux 2, Centos5
Changed the word 'or higher' in buttons to '+'.
Fixed validations for Hp, Solaris, and Alpine.
The enroll message for hp, solaris and Alpine os has been moved. The message now appears below the install and enroll section.
#5042 
https://user-images.githubusercontent.com/99441266/209834280-cd31db31-602f-4061-99c5-d765ec6921aa.mov
- Verify commands for Aix, OpenSUSE, Alpine, Suse11, Fedora, HP, Oracle Linux 5, Amazon Linux 2, Centos5. You can verify them [here](https://github.com/wazuh/wazuh-packages/issues/1625#issuecomment-1365838810)
- Verified that the buttons have changed the word 'or higher' to '+'.
- Alpine, Hp or Solaris do not allow configuring wazuh server, agentName and agentGroup. …
> Fix section deploy new agent

- CHANGELOG.md
- public/controllers/agent/components/register-agent.js
- public/controllers/agent/register-agent/__snapshots__/register-agent-button-group.test.tsx.snap
- public/controllers/agent/register-agent/register-agent-button-group.test.tsx
- public/controllers/agent/register-agent/register-agent-button-group.tsx
- public/controllers/agent/wazuh-config/index.ts
Added default selected options in Deploy Agent Page 
Closes #5061 
1. Go to Deploy agent 
2. Select any OS 
3. Check the auto-selected options when OS has only one option for architecture or version
1. Go to Deploy agent 
2. Select any OS 
3. Check the auto-selected options for version and architecture
4. Repeat for every OS
> Added default selected options in Deploy Agent page

- Makefile
- package.json
- public/package.test.ts
- scripts/tag.py
Some of the `package.json` settings were changed, 
for example: 
- `version`: untouched. Follows the major.minor.patch pattern
- `revision`: represents the build number. It is a number of 2 digits, starting at 00 and increased by one each time a package for the same version is built. This value is reset only when the version changes.
- `stage`: replaces the code property which has no actual use. With this property, we'll represent the stage of development at which the package has been built at: pre-alpha (development), alpha, beta, release-candidate or stable (production).
- `commit`: we'll also include the short SHA of the latest commit included in the package (can also be the SHA of the commit used to tag). With this, we'll be able to have a clear reference of what was included in the …
> Implement new versioning methodology

- CHANGELOG.md
- common/api-info/endpoints.json
- common/api-info/security-actions.json
- common/constants.ts
- public/components/agents/sca/inventory.tsx
- public/components/agents/sca/inventory/checks-table.tsx
- public/components/common/welcome/components/sca_scan/sca_scan.tsx
Backport bf7fbb47528c53e726edb9ab0c19770992b89d3f from https://github.com/wazuh/wazuh-kibana-app/pull/5031.
> [backport 4.4-7.10]Fix filtering of `not applicable` SCA checks using `result` filter

- CHANGELOG.md
- public/components/common/flyouts/wz-flyout.tsx
This pull request fixes a problem when closing the flyouts using the Firefox browser.
Previously, we checked if the elements of the `event.path` contains the HTML classes related to the flyouts. The `event.path` is undefined for recent versions of Firefox browser, while others browsers could be defined and work the logic to close the flyout.
The solution removes the EuiOutsideClickDetector component wrapping to EuiFlyout. Now it uses the outsideClickCloses property of EuiFlyout.
The solution must work in all the browsers.
Closes #5043
**For each browser (Google Chrome, Firefox, Safari)**
Tests result template: [pr_5046_template_result_tests.md](https://github.com/wazuh/wazuh-kibana-app/files/10314383/pr_5046_template_result …
> Fix errors on closing flyouts in Firefox

- CHANGELOG.md
- public/controllers/agent/components/agents-table.js
Team,
this PR adds os.uname and os.version fields to the required /agents request for the agents overview table. With this information the table can render the agent OS icon and the agent OS version in the OS column
Closes #5073 
Related to https://github.com/wazuh/wazuh-kibana-app/pull/4363
Register Linux / Windows agents in the manager
Check the agent OS icon and version are shown
> Add `os.uname` and `os.version` fields to agents table

- CHANGELOG.md
- public/controllers/agent/components/agents-table.js
Team,
this PR adds os.uname and os.version fields to the required /agents request for the agents overview table. With this information the table can render the agent OS icon and the agent OS version in the OS column
Closes #5073 
Related to https://github.com/wazuh/wazuh-kibana-app/pull/4363
Register Linux / Windows agents in the manager
Check the agent OS icon and version are shown
> [Backport 7.16] Add `os.uname` and `os.version` fields to agents table

- CHANGELOG.md
- public/controllers/agent/components/agents-table.js
Team,
this PR adds os.uname and os.version fields to the required /agents request for the agents overview table. With this information the table can render the agent OS icon and the agent OS version in the OS column
Closes #5073 
Related to https://github.com/wazuh/wazuh-kibana-app/pull/4363
Register Linux / Windows agents in the manager
Check the agent OS icon and version are shown
> [Backport 2.4] Add `os.uname` and `os.version` fields to agents table

- CHANGELOG.md
- public/components/visualize/agent-visualizations.js
- server/integration-files/visualizations/agents/agents-github.ts
Team,
this PR fixes an exception when selecting an agent or removing a pinned agent and later generating a PDF report in the dashboard.
The problem was that the agents visualizations had exactly the same HTML ID as the overview visualizations, therefore when angularJS updated the state it didn't create a new instance of the visualization component.
Closes #5065 
**Scenario**: Loading Github dashboard for the first time and generating a PDF report should not produce any errors
**When** The user loads Github dashboard
**And** The user clicks Generate report
**Then** a toast with a report successful message should pop up
**Scenario**: Loading Github dashboard then changing the pinned agent state and generating a PDF report should not produce any errors
**When** The user loads Github …
> [Backport 2.4] Fix github agents visualizations id

- CHANGELOG.md
- public/components/management/groups/multiple-agent-selector.tsx
This pull request fixes a console error displayed when clicking in the multiple agent selector to manage the agents in a group
Closes #5091
**Scenario 1** Clicking on the multiple selector (Available agents) of the group agents management doesn't display any error in the console of the browser dev tools
**Given** a group without agents
**When** the user goes to Manage agents
**And** clicking on selector of the Available agentsCurrent agents in the group panel
**Then** it should not appear an error in the console of the browser dev tools
**Scenario 2** Clicking on the multiple selector (Current agents in the group) of the group agents management doesn't display any error in the console of the browser dev tools
**Given** a …
> [Backport 4.4-7.10] Fix error when clicking on the multiple agent selector

- CHANGELOG.md
- public/kibana-integrations/discover/application/angular/doc_table/components/table_row/_open.scss
- public/kibana-integrations/discover/application/angular/doc_table/components/table_row/open.html
Changed the styles of the button that shows more information of each row of the table in events so that it has the same styles as the button that appears in discover.
- #5136
**Scenario 1** The button should have the same appearance as the button that appears in Discover when the information is not displayed.
**When** the user navigates to a module/events
**Then** should see the button like the one shown in Discover
**Scenario 2** The button should have the same appearance as the button that appears in Discover when after clicking to see the information.
**When** the user navigates to a module/events and click to see the information
**Then** should see the button like the one shown in Discover
> Fix button styling in event view 

- CHANGELOG.md
- server/start/cron-scheduler/save-document.ts
Hi team,
this PR fixes the statistics cronjob request body to fix the `"mapper_parsing_exception"`. It seems the opensearch dependency that executes the bulk doc insert has changed.
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1.2.0/package.json#L121
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/2.4.1/package.json#L133
Closes https://github.com/wazuh/wazuh-automation/issues/1020
- Verify the Statistics information is indexed in Cluster mode ON and OFF
| Cluster Mode ON | Cluster Mode OFF |
| --- |  --- |
|:black_circle:|:black_circle:|
> Serialize cronjob doc and remove type property

- CHANGELOG.md
- server/controllers/wazuh-reporting.ts
- server/lib/reporting/audit-request.ts
- server/lib/reporting/base-query.ts
- server/lib/reporting/extended-information.ts
- server/lib/reporting/gdpr-request.ts
- server/lib/reporting/overview-request.ts
- server/lib/reporting/pci-request.ts
- server/lib/reporting/rootcheck-request.ts
- server/lib/reporting/summary-table.ts
- server/lib/reporting/syscheck-request.ts
- server/lib/reporting/tsc-request.ts
- server/lib/reporting/vulnerability-request.ts
Team,
this PR fixes the query result of the PDF report _Alerts Summary Table_ to avoid truncating the number of rows. The parsing algorithm wasn't iterating all the bucket combinations, therefore it returned only the first combination of buckets. Now it iterates al possible combinations of the aggregation buckets and returns all possible results.
Note: We also found server-side functions truncate and sort indexer queries. The issue is described in the issue https://github.com/wazuh/wazuh-kibana-app/issues/5134
Closes #5130 
- Generate a report of each module with and without a pinned agent.
- The rendered Alerts Summary table should be consistent with the rest of the visualizations and the available alerts in the reported Module Dashboard
- Setup the Allow agents restriction filter and …
> Fix Alerts Summary table truncated results

- CHANGELOG.md
- public/components/common/modules/panel/components/module-side-panel.tsx
Hi team,
This PR fixes GitHub office365 panel information tab by removing the euiCollapsibleNavbar custom styles and using newer eui v34.6.0 component properties to display the close button inside the container and to remove the overlay.
This fix is for Opensearch 2.4.0 and above. Elasticsearch 7.10.x and 7.16.x branches don't require it.
Closes #5164 
- Navigate to Modules -> Github / Office365
- Click on the `Panel` tab
- Click on the laft tab with the _`i`_ icon
- Check it opens the drawer
> Fix GitHub office365 panel information tab

- CHANGELOG.md
- common/compliance-requirements/pci-requirements.ts
- common/csv-key-equivalence.ts
- public/components/agents/syscollector/components/syscollector-metrics.tsx
- public/components/common/welcome/agents-info.js
- public/components/management/cluster/node-list.tsx
- public/components/overview/office-panel/config/drilldown-operations-config.tsx
- public/components/overview/office-panel/config/drilldown-rules-config.tsx
- public/components/overview/office-panel/config/drilldown-user-config.tsx
- public/components/overview/office-panel/config/main-view-config.tsx
- public/components/overview/office-panel/config/module-config.tsx
- public/components/visualize/visualizations.js
- public/components/wz-search-bar/wz-search-bar.test.tsx
- public/controllers/agent/components/agents-preview.js
- public/controllers/agent/components/agents-preview.scss
- public/controllers/agent/components/agents-table.js
- public/controllers/management/components/management/configuration/configuration-settings.js
- public/controllers/management/components/management/configuration/global-configuration/global-configuration-remote.js
- public/controllers/management/components/management/configuration/integrations/integrations.js
- public/controllers/management/components/management/groups/group-agents-table.js
- public/controllers/management/components/management/status/status-agent-info.js
- public/controllers/management/components/management/status/status-stats.js
- public/controllers/overview/components/overview-actions/agents-selection-table.js
- public/controllers/overview/components/select-agent.js
- public/styles/common.scss
- public/templates/management/management.html
- server/controllers/wazuh-reporting.ts
- server/integration-files/visualizations/overview/overview-office.ts
- server/lib/reporting/agent-configuration.ts
- server/lib/reporting/extended-information.ts
Hi team,
This PR: 
- Disables by default the `Synced` - `Registration Date` - `Last Keep Alive` fields of the Agents table and removes the metric on the top of the view. Even though it is disabled, it still can be enabled by checking the field in the table settings.
- It also changes the text `IP` and the text `OS` to `IP address` and to `Operating system` throughout the app. 
- Improves the Agents table dynamic layout
- Fixes Windows and MacOs operating system icons in the agents table
Closes #5141 
- Register agents in the manager
- Go to Agents overview
- Check the table does not include the `synced` field
- Check the top metrics don't include the `Synced` percentage
- Check the synced field can be enabled in the Agents table
- Go to an Agent inventory data
- Generate PDF report
- Go …
> Disable synced by default

- CHANGELOG.md
- public/controllers/agent/components/register-agent-service.ts
- public/controllers/agent/components/register-agent.js
- public/controllers/agent/register-agent/steps/wz-manager-address.tsx
- tsconfig.json
This PR, adds a new WzServerAddress component for the Deploy Agent section.
The component is a free input.
Closes #5138 #5140
1. When the only available Protocol is `UDP`, the `WAZUH_PROTOCOL` param in the command will show `UDP`.
- On Manager and Cluster mode.
2. When the Protocol available exists `TCP`,   the `WAZUH_PROTOCOL` param in the command will be `TCP` (the param is hidden, and TCP is the default value)
- On Manager and Cluster mode.
1. When the user has filled the `enrollment.dns` field in `Management > Configuration`. The server address input must be filled by default with this value.
> ### Annotation
> The protocol and server address input are independent.
> The command protocol param defined depends on only the remote configuration defined in the ossec.conf file.
1. Check …
> Added server address and wazuh protocol definition in Deploy agent section

- CHANGELOG.md
- server/start/cron-scheduler/save-document.ts
Backport 6a6ea1f8af52fa63b30a39fb7589ccf4847e71b3 from https://github.com/wazuh/wazuh-kibana-app/pull/5150
> [Backport 4.4-7.10] Serialize cronjob doc and remove type property

- CHANGELOG.md
- public/controllers/agent/components/agents-table.js
- public/styles/common.scss
Hi team,
This PR removes the flex-wrap style from the action buttons of the Agents table. This is to avoid the buttons wrapping unnecessarily in firefox.
Related to https://github.com/wazuh/wazuh-kibana-app/issues/5141
- Go to Agents Overview
- Change the screen size to see the buttons horizontally and vertically
| Chrome | Firefox | Safari |
| --- | --- | --- |
| :black_circle:  | :black_circle:  | :black_circle:  |
> Agents table action buttons style fix

- public/kibana-integrations/discover/application/angular/doc_table/components/table_row/open.html
Team,
this PR changes the color of the `>` button in the `Security events` / `Events` rows. The button style should match the Kibana Discover plugin.
**Important:** This must only be applied to the 7.16.x dev branch.
Related Pull request #5184 
**Security events**
**Discover**
- Verify the color of the `>` button in the `Security events` / `Events` rows. 
- Check it matches the Kibana Discover plugin row button style.
> Fix backport 5137 to 4.4 7.16 - change button text color

- CHANGELOG.md
- public/components/agents/vuls/inventory/detail.tsx
- public/components/agents/vuls/inventory/table.tsx
This pull request fixes a UI crash when opening the details of a vulnerability that has no the `external_references` field.
The changes ensure the field is defined and is an array.
If there is data related to external references, then a `-` will be displayed
#5199
| Test |
| --- |
| See the References of a vulnerability that has one or more references, it should display the accordion with the references. |
| See the References of a vulnerability that has no references, it should display a `-`. |
| See the References of a vulnerability that the references are not defined, it should display a `-`. |
[crash-vulnerability-data-no-external-references.md](https://github.com/wazuh/wazuh-kibana-app/files/10677157/crash-vulnerability-data-no-external-references.md)
Imposter patch that adds some …
> Fix a crash in the vulnerability details flyout

- CHANGELOG.md
- public/components/common/hooks/use-kbn-loading-indicator.ts
Fixed the 2 errors that appeared in console in Settings>Configuration section.
#4772 
https://user-images.githubusercontent.com/99441266/212919623-c28a2d46-e47d-4c5c-a2fb-d76318240953.mov
**Case 1:**
In the Wazuh menu click on Settings>Configuration
Then go to any part of the application and check that no error is displayed in console
**Case 2:**
In the Wazuh menu click on Settings>Configuration
Change some configuration and when you click on save a loading should appear next to the kibana logo. 
https://user-images.githubusercontent.com/99441266/212922249-c5b1cb0a-c774-4d12-9176-35e4a5762020.mov
In opensearch the loading appears in this icon <img width="50" alt="image" src="https://user-images.githubusercontent.com/99441266/212921006-642ef5ed-83ad-4883-b7b0-e5c47a6a339d.png">
> Fix cannot read null properties bug in settings section

- CHANGELOG.md
- public/react-services/wz-user-permissions.ts
Regular expression change to detect if you have permission to perform actions, In some cases it was checked if it was a literal string and in others it was not. Now if the required permission has the character "*" verify that it has some value. 
- #5037
Case 1
Run test `yarn run test:jest wz-user`
Case 2
Log in with a user with full permissions and see if the application works as expected.
Caso 3
Log in with a user with reduced permissions and check if the application works as expected.
> Change RexExp

- public/components/agents/vuls/main.tsx
This PR fixes a typo that is shown when accessing the Vulnerabilities dashboard without having an agent selected. 
Currently it incorrectly has the `it's` contraction where the `its` possessive should be used instead.
This is a trivial PR that should not require a long review period.
> Fix possessive 'it's' in the Vulnerability dashboard

- CHANGELOG.md
- public/kibana-integrations/discover/application/angular/directives/no_results.js
This change is only for "OpenSearch dashboards", it changes code that was related to Elasticsearch in the OpenSearch Dashboards branch.
- #5284 
Navigate to 'Security events'
Click on 'Syntax options from search bar'
Change 'OpenSearch Dashboards Query Language' to 'off'
Test 1
Click on Events without data
The view "no results" has to be rendered 
Test 2
Click on Events with data
The table has to be rendered 
Test 1
Click on Events and do a search
The table has to be rendered with the search data.
> Fix events view when search bar language is lucene

- CHANGELOG.md
- public/controllers/agent/components/register-agent.js
This PR, fixes an undefined property use.
Closes #5283
> Fixed Deploy Agent wrong use of connection secure property

- CHANGELOG.md
- public/components/common/modules/module.scss
- public/components/common/welcome/agents-welcome.js
Removed an unnecessary div and changed a style for components that have the 2 classes together (.wz-agent-empty-item.euiFlexItem).
- #5290
1. Navigate to 'an agent'
2. View header in different width sizes
> Header in agent view is rendered correctly

- CHANGELOG.md
- public/controllers/agent/components/register-agent-service.ts
- public/controllers/agent/components/register-agent.js
This PR has refactored code when the connection is secure or not.
Closes #5283
> Fixed deploy new agent refactor secure connection conditions

- docker/wazuh-4.3-es/pre.sh
- docker/wazuh-4.3-es/pre.yml
- docker/wazuh-4.3-es/rel.sh
- docker/wazuh-4.3-es/rel.yml
The pre-release environments in Kibana 7.10.2 were not working. Because of a file permissions problem that caused the container where Kibana was located to stop working.
Try to use the pre-release environment and install wazuh on version 7.10.2 and 7.16.x or 7.17.x.
> Fix pre-release environments for kibana 7.10.2

- CHANGELOG.md
- public/controllers/management/components/management/configuration/policy-monitoring/help-links.js
Anomaly and malware detection link changed to malware detection link. Due to documentation changes in this [PR](https://github.com/wazuh/wazuh-documentation/pull/5944)
- #5318
1. Navigate to management/configuration/policy monitoring/system audit
2. Click on image ![image](https://user-images.githubusercontent.com/63758389/227267718-afe190b4-05ac-4d8e-b3d8-3480de25e135.png)
3. The button is now called `Malware detection` and the href has to be `user-manual/capabilities/malware-detection/index`.
> Change link to Malware detection documentation

- CHANGELOG.md
- public/controllers/management/components/management/configuration/policy-monitoring/help-links.js
Backport https://github.com/wazuh/wazuh-kibana-app/commit/ed9e44e87f092b2965b46ce988aa00d92d701b43 from https://github.com/wazuh/wazuh-kibana-app/pull/5329.
> [Backport 7.16]Change link to Malware detection documentation

- CHANGELOG.md
- public/controllers/management/components/management/configuration/policy-monitoring/help-links.js
Backport https://github.com/wazuh/wazuh-kibana-app/commit/ed9e44e87f092b2965b46ce988aa00d92d701b43 from https://github.com/wazuh/wazuh-kibana-app/pull/5329.
> [Backport 7.10]Change link to Malware detection documentation

- CHANGELOG.md
- public/components/agents/syscollector/components/syscollector-table.tsx
Backport https://github.com/wazuh/wazuh-kibana-app/commit/4fadc4e0f6311f86b0f4adfdc0d0b00bc72337fe from https://github.com/wazuh/wazuh-kibana-app/pull/5196.
> [Backport 5196 to 4.4 7.16] Fix the search in the agent inventory data tables

- docker/imposter/wazuh-config.yml
- docker/wazuh-4.x-es/config/imposter/wazuh-config.yml
This pull request adds a mocked endpoint `GET /security/user/authenticate` for the user authentication in the imposter used by plugins 4.3.x.
- Added mock endpoint to root imposter
- Added mock endpoint for `wazuh-4.x-es`
[List any issues this PR will resolve]
> Mock auhentication endpoint for 4.3.x in Docker environments

- public/controllers/management/components/management/configuration/utils/wz-fetch.js
- public/react-services/error-handler.ts
- public/services/error-handler.js
- test/server/wazuh-api.js
Removes obsolete logic and tests that were left after deleting the GET `/api/agents-unique` endpoint.
- #4916 
See in the code that there is nothing left related to the endpoint `/api/agents-unique`
> Removed logic related to deprecated endpoint GET /api/agents-unique/{api}

- CHANGELOG.md
- server/lib/get-configuration.ts
This pull request fixes a problem accessing to an object property in the `getConfiguration` backend service.
#5427 
> Fix accessing property in getConfiguration backend service

- CHANGELOG.md
- public/controllers/agent/components/register-agent.js
> Fix macos apple install command

- CHANGELOG.md
- public/controllers/agent/components/register-agent.js
Hi team,
this pull request changes the register agent installation script for macOS. It sets de environment variables to the `/tmp/wazuh_envs`
Closes #5466 
- Go to the register agents wizard
- Select macOS
- With empty fields you should **NOT** see the `echo -e ""  > /tmp/wazuh_envs`
- With any filled input you **should** see `echo -e ""  > /tmp/wazuh_envs` with environmental variables like this:
```
curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.4.3-1.pkg && echo -e "WAZUH_MANAGER='192.168.0.1'\nWAZUH_AGENT_GROUP='default'\nWAZUH_AGENT_NAME='new-agent'\n" > /tmp/wazuh_envs && sudo installer -pkg ./wazuh-agent.pkg -target /
```
> Change macOS register agent installation script

- CHANGELOG.md
- public/controllers/agent/components/register-agent.js
Hi team, 
this PR changes the agent installation command for macOS.
Closes #5466 
Related to #5481 
- Go to Agents
- Click on "Deploy new agent"
- On step 1 select `macOS`
- With Password
- Check the password is shown by default with the correct value
- Fill in the rest of the configuration and check the double quotes `"` are escaped `\"`
- Check the environment variables are separated by `&&`
- Without password
- When all inputs are empty the `echo` section of the script should not appear
- Fill in the rest of the configuration and check the double quotes `"` are escaped `\"`
- Check the environment variables are separated by `&&`
> Change macOS register agent installation command

- CHANGELOG.md
- public/controllers/agent/components/register-agent.js
Hi team, 
this PR changes the agent installation command for macOS.
Closes #5466 
Base pull request #5484  
- Go to Agents
- Click on "Deploy new agent"
- On step 1 select `macOS`
- With Password
- Check the password is shown by default with the correct value
- Fill in the rest of the configuration and check the double quotes `"` are escaped `\"`
- Check the environment variables are separated by `&&`
- Without password
- When all inputs are empty the `echo` section of the script should not appear
- Fill in the rest of the configuration and check the double quotes `"` are escaped `\"`
- Check the environment variables are separated by `&&`
> [Backport 4.4-7.16] Change macOS register agent installation command

- CHANGELOG.md
- public/controllers/agent/components/register-agent.js
Hi team, 
this PR changes the agent installation command for macOS.
Closes #5466 
Base pull request #5484  
- Go to Agents
- Click on "Deploy new agent"
- On step 1 select `macOS`
- With Password
- Check the password is shown by default with the correct value
- Fill in the rest of the configuration and check the double quotes `"` are escaped `\"`
- Check the environment variables are separated by `&&`
- Without password
- When all inputs are empty the `echo` section of the script should not appear
- Fill in the rest of the configuration and check the double quotes `"` are escaped `\"`
- Check the environment variables are separated by `&&`
> [Backport 4.4-7.10] Change macOS register agent installation command

- CHANGELOG.md
- public/controllers/agent/agents-preview.js
- public/controllers/overview/overview.js
- public/templates/visualize/dashboards.html
Backport https://github.com/wazuh/wazuh-kibana-app/commit/7d409b0a8f72a7d2269492ddbe53f441e9a7bd28 from https://github.com/wazuh/wazuh-kibana-app/pull/5453.
> [Backport 4.5-7.16]Remove unnecessary dashboard queries (#5453)

- .gitignore
- CHANGELOG.md
- public/controllers/agent/components/register-agent.js
"Optionally, assign a name and a group to the agent"
"Optional settings"
"Assign an agent name"
"The agent name is set as the name of the host where it is deployed. You can set your own name in the field below. Note that the agent name cannot be changed once registered."
"The deployment sets the endpoint hostname as the agent name by default. Optionally, you can set the agent name below."
"Name agent"
"Agent name"
#5415 
"Optionally, assign a name and a group to the agent"
"Optional settings"
"Assign an agent name"
"The agent name is set as the name of the host where it is deployed. You can set your own name in the field below. Note that the agent name cannot be changed once registered."
"The deployment sets the endpoint hostname as the agent name by default. Optionally, you can set the …
>  Changed step 3 in the "Deploy a new agent" section.

- README.md
Hi team,
this PR changes the installation URL of the README.md file to a generic label, so the user can replace the command label with the desired Wazuh package link from the compatibility matrix.
Closes #4291
> Update installation guide in README.md

- CHANGELOG.md
- docker/imposter/overview/agents.json
- docker/imposter/wazuh-config.yml
- public/controllers/management/components/management/status/actions-buttons-main.js
- public/controllers/management/components/management/status/status-overview.js
Unnecessary requests have been eliminated
- #5243 
Before
After
Legend:
| Navigate to management status and do not see the request `GET /agents/summary/status` | :black_circle: | :black_circle: | :black_circle: |
| Navigate to management status and do not see the request `GET /agents" with parameters {"limit": "1", "sort": "-dateAdd", "q": "id!=000"}` | :black_circle: | :black_circle: | :black_circle: |
| In cluster mode do not see the request `GET /manager/info`  | :black_circle: | :black_circle: | :black_circle: |
| In manager mode see the request `GET /manager/info`  | :black_circle: | :black_circle: | …
> Wazuh api usage magement/status

- CHANGELOG.md
- public/controllers/management/components/management/cdblists/components/cdblists-table.tsx
- public/controllers/management/components/management/cdblists/main-cdblists.tsx
- public/controllers/management/components/management/cdblists/views/cdblists-overview.tsx
- public/controllers/management/components/management/common/actions-buttons.tsx
- public/controllers/management/components/management/configuration/configuration-switch.js
- public/controllers/management/components/management/decoders/__snapshots__/main-decoders.test.tsx.snap
- public/controllers/management/components/management/decoders/components/decoders-table.tsx
- public/controllers/management/components/management/decoders/main-decoders.tsx
- public/controllers/management/components/management/decoders/views/decoders-overview.tsx
- public/controllers/management/components/management/groups/__snapshots__/groups-main.test.tsx.snap
- public/controllers/management/components/management/groups/groups-main.test.tsx
- public/controllers/management/components/management/management-main.js
- public/controllers/management/components/management/ruleset/__snapshots__/main-ruleset.test.tsx.snap
- public/controllers/management/components/management/ruleset/components/ruleset-table.tsx
- public/controllers/management/components/management/ruleset/main-ruleset.tsx
- public/controllers/management/components/management/ruleset/views/ruleset-overview.tsx
- public/controllers/management/management.js
- public/redux/actions/appStateActions.js
- public/redux/reducers/appStateReducers.js
Backport https://github.com/wazuh/wazuh-kibana-app/commit/13984520d84bdb07cb0d86f1f315cec4aa39dd84 from https://github.com/wazuh/wazuh-kibana-app/pull/5485.
> [Backport 5485 to 4.5 7.10] Remove deprecated code and request in Management

- CHANGELOG.md
- public/controllers/agent/components/register-agent.js
- public/controllers/agent/wazuh-config/index.ts
Hi team,
this pull request adds a new button with the Apple Silicon architecture to the **Register Agents** wizard.
Closes #5202 
To test the PR we need to check both macOS architecture work properly:
- Go to Agents
- Press the `Deploy new agent` button
- Press the macOS in option 1
- Select MacOS Sierra in the 2nd step
- Select each of the available architectures and verify the installation script is correct, the package name should be like `wazuh-agent-${VERSION}-${REVISION}.${ARCH}.pkg:`
<details>
<summary>Intel script</summary>
</details>
<details>
<summary>Apple Silicon script</summary>
</details>
> Add Apple Silicon architecture to the register Agent wizard

- opensearch_dashboards.json
- package.json
As 4.4.4 has been cancelled and replaces by 4.5.1, we revert the 4.4 branch to the latest 4.4.x patch, which is 4.4.4.
The 4.5.1 branch has been already created from 4.4, containing the merged changes which were supposed to be included in 4.4.5.
None
```$ git log
commit 9f99758e119e47d85913af2dcfa962c3931a8f86 (HEAD -> revert-to-v4.4.4, tag: v4.4.4-2.6.0, origin/revert-to-v4.4.4)
Author: yenienserrano <ian.serrano@wazuh.com>
Date:   Thu Jun 8 13:09:10 2023 +0200
Bump v4.4.4-2.6.0-rc2
commit 0e7201ff8b7fb6a76de789160b94e665c0af41e1
Author: Ian Yenien Serrano <63758389+yenienserrano@users.noreply.github.com>
Date:   Thu Jun 8 12:54:18 2023 +0200
Improved changelog (#5544)
* Update changelog
* Update revision for RC2
commit cb8a8bee7f7217031ce94e6241893e611288a146
Author: Ian Yenien Serrano …
```
> Revert 4.4 to v4.4.4

- public/controllers/register-agent/components/command-output/command-output.tsx
- public/controllers/register-agent/containers/register-agent/register-agent.tsx
- public/controllers/register-agent/containers/steps/steps.tsx
- public/controllers/register-agent/core/config/os-commands-definitions.ts
- public/controllers/register-agent/core/register-commands/types.ts
- public/controllers/register-agent/services/register-agent-os-commands-services.tsx
- public/controllers/register-agent/services/register-agent-services.tsx
- public/controllers/register-agent/services/register-agent-steps-status-services.tsx
This PR, adds the register commands with parameters.
The commands are defined in https://github.com/wazuh/wazuh-kibana-app/issues/5594#issuecomment-1610017559
Closes #5594
- Mentioned in the issue comment https://github.com/wazuh/wazuh-kibana-app/issues/5594#issuecomment-1611906176
> [Redesign add agent] Add and validate register agent commands

- plugins/main/common/api-info/endpoints.json
- plugins/main/scripts/generate-api-data.js
Backport f33281701a6a3255b500527acf07d255f29bc921 from #5611
> [Backport 4.6.0-7.10] Fix API endpoint documentation link in static file

- CHANGELOG.md
- plugins/main/common/api-info/endpoints.json
- plugins/main/common/services/web_documentation.test.ts
- plugins/main/opensearch_dashboards.json
- plugins/main/package.json
- plugins/main/public/controllers/management/components/management/configuration/office365/components/SubscriptionTab/__snapshots__/SubscriptionTab.test.tsx.snap
- plugins/main/public/controllers/management/components/management/configuration/office365/components/api-auth-tab/__snapshots__/api-auth-tab.test.tsx.snap
- plugins/main/public/controllers/management/components/management/configuration/office365/components/general-tab/__snapshots__/general-tab.test.tsx.snap
- plugins/main/scripts/tag.py
This pull request prepares the app for Wazuh 4.7.0.
- #5630
> Bump 4.7.0

- CHANGELOG.md
- docker/imposter/security/security-actions.json
- docker/imposter/security/security-me-policies.js
- docker/imposter/security/security-policies.json
- docker/imposter/security/security-roles.json
- docker/imposter/security/security-rules.json
- docker/imposter/security/users.json
- docker/imposter/wazuh-config.yml
- plugins/main/common/constants.ts
- plugins/main/public/components/security/main.tsx
- plugins/main/public/components/security/policies/create-policy.tsx
- plugins/main/public/components/security/policies/edit-policy.tsx
- plugins/main/public/components/security/policies/policies-table.tsx
- plugins/main/public/components/security/policies/policies.tsx
- plugins/main/public/components/security/roles-mapping/components/roles-mapping-create.tsx
- plugins/main/public/components/security/roles-mapping/components/roles-mapping-edit.tsx
- plugins/main/public/components/security/roles-mapping/components/roles-mapping-table.tsx
- plugins/main/public/components/security/roles-mapping/components/rule-editor.tsx
- plugins/main/public/components/security/roles-mapping/roles-mapping.tsx
- plugins/main/public/components/security/roles/create-role.tsx
- plugins/main/public/components/security/roles/edit-role-table.tsx
- plugins/main/public/components/security/roles/edit-role.tsx
- plugins/main/public/components/security/roles/roles-table.tsx
- plugins/main/public/components/security/roles/roles.tsx
- plugins/main/public/components/security/users/components/create-user.tsx
- plugins/main/public/components/security/users/components/edit-user.tsx
- plugins/main/public/components/security/users/components/users-table.tsx
- plugins/main/public/components/security/users/users.tsx
Backport 252822a4036a17580e7c5f2c848f45e45f3cedae from #5551
> [Backport 4.6.0-7.10] Add specific RBAC permissions to Security section

- docker/images/kbn-7.17.11-dev.Dockerfile
- docker/kbn-dev/dev.sh
We have upgraded Elasticsearch and Kibana to version 7.17.11, and the changes are reflected in issue #5623
#5623
Up the environment and check that it works.
> Add kbn-dev 7.17.11

- CHANGELOG.md
- README.md
- kibana.json
- package.json
- scripts/tag.py
Backport https://github.com/wazuh/wazuh-kibana-app/commit/b33c4a5dfcc4349dd0c4635f8b242f5208f17722 from https://github.com/wazuh/wazuh-kibana-app/pull/5639.
> [Backport 4.4.5-7.16] Bump Wazuh and platform versions for v4.4.5 (#5639)

- CHANGELOG.md
- docker/imposter/agents/configuration.js
- docker/imposter/agents/configuration/agent_labels.json
- docker/imposter/agents/configuration/default.json
- docker/imposter/cluster/configuration/agent_labels.json
- docker/imposter/manager/configuration.js
- docker/imposter/manager/configuration/agent_labels.json
- docker/imposter/manager/configuration/default.json
- docker/imposter/manager/configuration/monitor_reports.json
- docker/imposter/wazuh-config.yml
- public/controllers/management/components/management/configuration/alerts/alerts-labels.js
- public/controllers/management/components/management/configuration/alerts/alerts.js
Changes:
- API request to get the manager labels
Fixed:
- Broken documentation link to the agent labels
#5565
Check changes in https://github.com/wazuh/wazuh/issues/17610.
I installed from sources a Wazuh manager based in the current `4.5.1` version.
```json
{"data": {"title": "Wazuh API REST", "api_version": "4.5.1", "revision": 40501, "license_name": "GPL 2.0", "license_url": "https://github.com/wazuh/wazuh/blob/v4.5.1/LICENSE", "hostname": "wazuh-manager-master-7102", "timestamp": "2023-07-18T11:10:11Z"}, "error": 0}
```
Review changes in https://github.com/wazuh/wazuh/issues/17610
- Manager
Adapting the API request and managing the response:
- Cluster
Adapting the API request and managing the response:
- API request
- UI
- Cluster node
- Manager node
- UI
Legend: …
> Fix API request to get the manager labels and broken documentation link

- CHANGELOG.md
- public/react-services/reporting.js
- server/controllers/wazuh-reporting.ts
- server/lib/reporting/base-query.ts
- server/lib/reporting/extended-information.ts
- server/lib/reporting/gdpr-request.ts
- server/lib/reporting/pci-request.ts
- server/lib/reporting/rootcheck-request.ts
- server/lib/reporting/tsc-request.ts
- server/routes/wazuh-reporting.test.ts
- server/routes/wazuh-reporting.ts
Backport from #5714 to 4.5.1-7.10
> [Backport 4.5.1-7.10] Fix server side query in pdf report filter

- docker/images/wzd-dev.Dockerfile
- docker/osd-dev/dev.sh
Upgrade environments to 4.6 and 4.7
> Upgrade environments to 4.6 and 4.7

- server/routes/wazuh-reporting.test.ts
This pull request fixes a unit test that evaluates the md5 value of a PDF report. The value of the copyright footer was changed in the pull request https://github.com/wazuh/wazuh-kibana-app/pull/5768/files#diff-a820f3796afb20894571d3f482ecb5ad3671c48bb62594f8ff4706a415d3638fR207-R212 , but the test md5 was not updated in the **Kibana 7.10 branch**.
The PDF md5 test must pass
> Update PDF md5 expected values in unit test

- CHANGELOG.md
- plugins/main/public/controllers/register-agent/core/config/os-commands-definitions.ts
- plugins/main/public/controllers/register-agent/services/register-agent-os-commands-services.tsx
Fix package URLs in aarch64 commands
Closes #5870 
Check all the LINUX commands
1. Select one-by-one Linux Distros
2. Check if the package URL works (copy and paste in a new browser tab) 
- **Important:** Use `package-dev` and `/pre-release/` instead /4.x/
3. Check in the command if the package name and package downloaded have the same name
4. If you have the same distro, check the agent package installation
```bash
curl -o wazuh-agent-4.6.0-1.x86_64.rpm https://packages.wazuh.com/4.x/yum/wazuh-agent-4.6.0-1.x86_64.rpm && sudo WAZUH_MANAGER='0.0.0.0' rpm -ihv wazuh-agent-4.6.0-1.x86_64.rpm
```
> Annotation: 
> In this case, the `amd64.rpm` package doesn't exist because of that we use the `x86_64.rpm`
```bash
wget https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.6.0- …
```
> [Register Agent ] Fixed package URLs in aarch64 commands

- plugins/main/public/controllers/register-agent/components/server-address/server-address.tsx
This pull request fixes the documenation link to the manager address.
#5865
Legend:
| Ensure the Server address documentation link is pointing to https://documentation.wazuh.com/4.6/user-manual/reference/ossec-conf/client.html#manager-address | :black_circle: | :black_circle: | :black_circle: |
**Details**
<details>
<summary>:black_circle: Ensure the Server address documentation link is pointing to https://documentation.wazuh.com/4.6/user-manual/reference/ossec-conf/client.html#manager-address</summary>
</details>
> Fix documentation link of manager address in the Deploy new agent guide

- plugins/main/public/components/add-modules-data/module-guide.js
- plugins/main/public/controllers/management/components/management/configuration/utils/utils.js
- plugins/main/public/utils/config-handler.js
This pull request fixes a problem parsing the XML configuration in Management > Configuration
#5868
Legend:
| Go to Management > Configuration > Any section and open the XML viewer, it should not throw any error and the configuration should be visible. | :black_circle: | :black_circle: | :black_circle: |
**Details**
<details>
<summary>:black_circle: Go to Management > Configuration > Any section and open the XML viewer, it should not throw any error and the configuration should be visible.</summary>
</details>
> Fix error parsing manager configuration to XML

- plugins/main/public/controllers/dev-tools/dev-tools.ts
This pull request fixes a syntax error when typing the request payload.
#5880
Legend:
| Go to Tools > API Console and type an API request that contains the following payload: {\n  "\n } (\n is a newline). There should not appear any error in the console. | :black_circle: | :black_circle: | :black_circle: |
**Details**
<details>
<summary>:black_circle: Go to Tools > API Console and type an API request that contains the following payload: {\n  "\n } (\n is a newline). There should not appear any error in the console.
</summary>
</details>
> Fix syntax error on API Console

- CHANGELOG.md
- plugins/main/public/controllers/register-agent/core/register-commands/optional-parameters-manager/optional-parameters-manager.ts
- plugins/main/public/controllers/register-agent/services/register-agent-os-commands-services.tsx
Fix the macOS installation command
Closes #5886
```bash
curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.6.0-1.intel64.pkg && echo "WAZUH_MANAGER='0.0.0.0' && WAZUH_AGENT_NAME='agent-name'" > /tmp/wazuh_envs && sudo installer -pkg ./wazuh-agent.pkg -target /
```
```bash
curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.6.0-1.arm64.pkg && echo "WAZUH_MANAGER='0.0.0.0' && WAZUH_AGENT_NAME='agent-name'" > /tmp/wazuh_envs && sudo installer -pkg ./wazuh-agent.pkg -target /
```
1. Go to Agents section
2. Click Deploy new agent button
3. Select macOS operting system and complete the form
4. Check the installation and start commands
> Fixed install macOS agent commands

- plugins/main/public/components/common/tables/__snapshots__/table-with-search-bar.test.tsx.snap
- plugins/main/public/components/search-bar/query-language/wql.tsx
This pull request fixes the link to the WQL documentation. It redirects to the official documentation instead of repository documenation.
#5867
Legend:
| Ensure the WQL documentation link is pointing to the official documentation and the link would be valid. | :black_circle: | :black_circle: | :black_circle: |
**Details**
<details>
<summary>:black_circle: Ensure the WQL documentation link is pointing to the official documentation and the link would be valid.</summary>
</details>
> Fix WQL documentation link

- CHANGELOG.md
- public/controllers/agent/components/register-agent.js
This pull request fixes the command to install the agent on SUSE.
#5924
Legend:
| Go to deploy new agent guide and select SUSE, the command to install the agent should use zypper package manager | :black_circle: | :black_circle: | :black_circle: |
| Go to deploy new agent guide and select SUSE, add agent name or group and the command to install the agent should use zypper package manager and display the defined setting in environment variables | :black_circle: | :black_circle: | :black_circle: |
**Details**
<details>
<summary>:black_circle: Go to deploy new agent guide and select SUSE, the command to install …
> Fix install agent command on SUSE

- plugins/main/public/app.js
- plugins/main/public/components/index.js
- plugins/main/public/components/wz-updates-notification/__snapshots__/index.test.tsx.snap
- plugins/main/public/components/wz-updates-notification/index.test.tsx
- plugins/main/public/components/wz-updates-notification/index.tsx
- plugins/wazuh-check-updates/public/components/updates-notification.tsx
Notify user when a new update is available
https://github.com/wazuh/wazuh-dashboard/issues/97
If the notification doen't appear, you have to go to the About page and click "Check updates" button. Then reload the page or open it in other tab. The notification should appear on all Wazuh pages until you dismiss it.
> Notify user when a new update is available

- plugins/main/public/components/security/roles/edit-role-table.tsx
The name of the onclick function parameter was changed because it was called the same as the render function parameter and was using the wrong one.
- #5935
1. Navigate to 'Security/Roles'
2. Click on 'a custom role'
3. Try to remove any policy
4. If you use a real manager, the policy has to be removed. If you use the imposter, make sure that in the delete request you have policy_ids
> Fix remove policy from roles

- plugins/main/public/components/overview/vulnerabilities/dashboards/hooks/use-dashboard-configuration.test.ts
- plugins/main/public/components/overview/vulnerabilities/dashboards/hooks/use-dashboard-configuration.tsx
This PR adds the useDashboardConfiguration hook for configuring vulnerability dashboards.
- #5946 
- Check code
- Run `use-dashboard-configuration.test.ts`
> Add useDashboardConfiguration hook for configuring vulnerability dashboards

- plugins/main/public/components/overview/vulnerabilities/searchbar/use-search-bar-configuration.tsx
This PR, 
solves the wrong agent.id filters in the search bar using the hook.
Closes #5969 
- Use the useSearchBarConfiguration hook 
- Check that the auto-loaded agent.id filter is not shown
- Navigate between dashboards and check that the filters have been preserved
> [Vulnerabilities dashboards] Fix wrong agent.id filters loaded in search bar by default

- plugins/main/public/components/common/welcome/overview-welcome.js
- plugins/main/public/plugin.ts
- plugins/main/public/utils/applications.ts
Updated menu to the expected result and overview app.
#5893
> Update sidebar menu and overview app

- .github/ISSUE_TEMPLATE/new_release.md
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- docker/README.md
- docker/kbn-dev/README.md
- docker/osd-dev/README.md
- plugins/main/package.json
- plugins/main/public/components/health-check/services/check-index-pattern/check-index-pattern-object.service.ts
- plugins/main/public/components/health-check/services/check-pattern-support.service.ts
- plugins/main/public/components/visualize/wz-visualize.js
- plugins/main/public/kibana-integrations/kibana-vis.js
- plugins/main/public/react-services/error-management/docs/README.md
- plugins/main/public/react-services/saved-objects.js
- plugins/main/public/templates/settings/settings.html
- plugins/main/server/lib/initial-wazuh-config.ts
This PR updates the links to the repository after its renaming. The old links are still working, but we want to update them just in case.
`wazuh-kibana-app --> wazuh-dashboard-plugins`
https://github.com/wazuh/internal-devel-requests/issues/318
> Update links to repo after its renaming

- CHANGELOG.md
- plugins/main/public/styles/theme/dark/index.dark.scss
This PR aims to fix an issue detected in #6000 regarding the color of the agent's name text in the group selector while using dark mode
#6016 
1. Enable dark mode in Stack Management
2. Navigate to management/groups
3. Select a group and go to Manage Agents
4. Verify that the text is clearly visible
> Fix agent name text in dark mode

- plugins/main/public/components/common/modules/main-agent.tsx
- plugins/main/public/components/common/modules/module.scss
- plugins/main/public/components/common/welcome/agents-welcome.js
- plugins/main/public/components/common/welcome/components/menu-agent.js
- plugins/main/public/styles/common.scss
- plugins/main/public/templates/agents/dashboards.html
- plugins/main/public/utils/applications.ts
This pull request adapts the agent menu to display the applications related to agents.
Changes: 
- Refactor agent menu to use the applications and categories
- Simplify the data saved in the local storage to keep the pinned applications
- Remove the usage of extensions configuration
- Change the data schema of the pinned applications
- Rename the session storage key to `wz-menu-agent-apps-pinned` where the pinned applications are stored
- Fix a problem with the agent menu header when the side menu is docked
#5893 
Legend:
| Test | Chrome |
| --- |  --- |
| With a fresh browser, ensure the Threat hunting, File integrity monitoring, Configuration assessment, Vulnerability …
> Rename applications on agent menu

- plugins/main/public/components/wz-menu/wz-menu.js
- plugins/main/public/react-services/app-state.js
- plugins/main/public/utils/applications.ts
Fixes the problem that when changing api and switching applications, many repeated requests were made.
- #5900 
Have a productive environment up and running and 2 connected apis
1. Change the selected api.
2. Navigate to another plugin.
3. It should redirect correctly without further delay.
4. Repeat at least 2 more times.
> Fix change APIs

- plugins/main/public/components/common/modules/modules-defaults.js
- plugins/main/public/components/overview/vulnerabilities/common/components/loading_spinner.scss
- plugins/main/public/components/overview/vulnerabilities/common/components/loading_spinner.tsx
- plugins/main/public/components/overview/vulnerabilities/common/components/no_results.tsx
- plugins/main/public/components/overview/vulnerabilities/common/constants.ts
- plugins/main/public/components/overview/vulnerabilities/dashboards/inventory/config/index.ts
- plugins/main/public/components/overview/vulnerabilities/dashboards/inventory/inventory.scss
- plugins/main/public/components/overview/vulnerabilities/dashboards/inventory/inventory.tsx
- plugins/main/public/components/overview/vulnerabilities/data_grid/use_data_grid.ts
- plugins/main/public/components/overview/vulnerabilities/doc_viewer/doc_viewer.tsx
- plugins/main/public/components/overview/vulnerabilities/doc_viewer/use_doc_viewer.ts
This PR changes the inventory table.
Closes #5895
> Change new vulnerabilities inventory table

- CHANGELOG.md
- plugins/main/public/components/agents/sca/main.tsx
- plugins/main/public/components/common/modules/modules-defaults.js
- plugins/main/public/components/wz-menu/wz-menu-overview.js
Change the display order of tabs in all modules
#6066 
Compruebe que en todos los modulos que tengan las pestañas de Inventory, Dashboard y Events aparezcan ordenadas de la siguiente manera:
Dashboard | Inventory | Events
Y que en el resto de los modulos siempre aparezca primero el tab de dashboard
> Change the display order of tabs in all modules

- CHANGELOG.md
- plugins/main/server/controllers/wazuh-api.ts
This PR aims to solve an issue detected when the Dashboard username contains chinese characters. 
#6068 
Using an environment with a real manager:
- Create an internal user with chinese characters. For example `Test 证明`. Assign admin permissions
- Map the internal user with the admin role in the Wazuh Plugin
- Log in with the new user
- Navigate in the app and verify that no errors are shown and the app works as expected
> Fix error when using chinese characters in username

- CHANGELOG.md
- plugins/main/public/controllers/management/components/management/configuration/registration-service/registration-service.js
Hi team,
this PR adds `ssl_agent_ca` to _Management -> Configuration -> Registration service_ with the label **_"Path to the CA certificate used to verify clients"_**.
Also, it changes the previous label from _""_ to _"Verify host when a CA certificate is specified"_
- Add the **_ssl_agent_ca_** entry to the `ossec.conf` file and restart the manager.
- Verify this configuration entry is included in the _Management -> Configuration -> Registration service_
```xml
<auth>
<disabled>no</disabled>
<port>1515</port>
<use_source_ip>no</use_source_ip>
<purge>yes</purge>
<use_password>no</use_password>
<ciphers>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ciphers>
<ssl_agent_ca>etc/sslmanager.cert</ssl_agent_ca>
<ssl_verify_host>no</ssl_verify_host> …
```
> Add ssl agent ca configuration entry

- .github/workflows/dev-environment.yml
- plugins/wazuh-check-updates/scripts/manifest.js
- plugins/wazuh-check-updates/scripts/runner.js
Add the GitHub Actions to run tests for the Wazuh Check Updates plugin when pushing changes to a PR.
https://github.com/wazuh/wazuh-dashboard/issues/111
One way to test the changes is to fork the repository, make a commit with some modifications, and create a PR. Once the tests are run and automatic comments are generated, you should make another commit and push it to test that new comments are generated and the previous ones are removed.
> Add Github actions to run wazuh check updates plugin tests

- CHANGELOG.md
- plugins/main/public/components/common/hooks/use-query.ts
- plugins/main/public/components/visualize/components/security-alerts.tsx
Hi team,
this pull request deprecates the `useQuery` hook which uses the method `getDiscoverScope()` of the legacy Discover. It replaces its implementation with the `useQueryManager` hook that makes use of the Data plugin to handle the query state. 
Closes #6042 
- Go to Security Events
- Click in the input Query bar
- Type a value, like 553 (_a rule ID_) and press "enter"
- See the change apply to the visualizations and the table
- Delete the value from the input Query bar and press enter
- Check the values in the visualizations and the Security alerts table are correct
> Fix Security Events table query filter

- CHANGELOG.md
- plugins/main/public/controllers/register-agent/utils/validations.test.tsx
- plugins/main/public/controllers/register-agent/utils/validations.tsx
This PR aims to fix an incorrect validation of the agent name in the `Deploy new agent` window, that prevents the use of numeric characters.
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6029
- Navigate to the `Deploy new agent` section and verify that the agent name is correctly validated. It must allow `A-Z`, `a-z`, `0-9`, `.`,`-`,`_`.
> Fix agent name validation

- CHANGELOG.md
- plugins/main/public/controllers/management/components/management/configuration/log-collection/log-collection.js
- plugins/main/public/controllers/management/components/management/configuration/util-components/tab-selector.js
This pull request fix UI cash on retrieving log collection configuration for macOS agent. The issue occurs when you go to the settings of a macOS agent and navigate to the Log Collection section. The reason for this error is described in [this comment](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6088#issuecomment-1790625859).
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6088
1. To be able to reproduce the context you must have an agent on macOS or you can modify the imposter to emulate the response.
<details>
<summary>
Emulate agent response on macOS with the imposter
</summary>
You must go to the file `~/docker/imposter/agents/configuration/logcollector-localfile.json` and change the default response to the following and restart the imposter:
```json
{
"data": { …
```
> Fix UI crash on retrieving log collection configuration for macos agent

- CHANGELOG.md
- plugins/main/package.json
- plugins/main/yarn.lock
- plugins/wazuh-check-updates/package.json
- plugins/wazuh-check-updates/server/routes/updates/get-updates.test.ts
- plugins/wazuh-check-updates/server/routes/user-preferences/get-user-preferences.test.ts
- plugins/wazuh-check-updates/server/routes/user-preferences/update-user-preferences.test.ts
- plugins/wazuh-check-updates/yarn.lock
- plugins/wazuh-core/package.json
- plugins/wazuh-core/yarn.lock
This pull request upgrades the version of  `axios` dependency.
Side changes:
- Fix a problem with tests using `axios`. Use `supertest` instead.
#6113
> Upgrade version axios

- plugins/main/package.json
- plugins/wazuh-check-updates/package.json
- plugins/wazuh-core/package.json
This PR aims to configure the tests to be ran sequentially by default. This is due to some tests failing when they are executed after a commit, causing the need to re run several times them. 
#6107
> Fix tests to run sequentially by default

- .github/workflows/wazuh-build-push-docker-action.yml
- docker/kbn-dev/dev.yml
- docker/osd-dev/dev.yml
- docker/wazuh-4.2-es/pre.yml
- docker/wazuh-4.3-wz/pre.yml
- docker/wazuh-4.4-wz/pre.yml
- docker/wazuh-4.5-wz/pre.yml
- docker/wazuh-4.x-es/pre.yml
- plugins/main/test/cypress/images/wazuh_manager_filebeat_sources_cmake/Dockerfile
This PR updates the Filebeat module located in the dev environments so that we can maintain a version of it according to the product and avoid outdated files.
#6124
> Update Filebeat module to 0.3 version

- CHANGELOG.md
- plugins/main/common/api-info/endpoints.json
- plugins/main/common/api-info/security-actions.json
- plugins/main/opensearch_dashboards.json
- plugins/main/package.json
- plugins/wazuh-check-updates/opensearch_dashboards.json
- plugins/wazuh-check-updates/package.json
- plugins/wazuh-core/opensearch_dashboards.json
- plugins/wazuh-core/package.json
This pull request bumps Wazuh version to 4.8.1 revision 00 to add support to the new version.
This change was made running this command:
```console
$ node scripts/release/bump.js --plugins-directory ./plugins --manifest-changelog ./CHANGELOG.md --plugin-main-generate-api-data-spec https://raw.githubusercontent.com/wazuh/wazuh/4.8.0/api/api/spec/spec.yaml --manifest-package ./plugins/main/package.json --revision 00 --version 4.8.1
```
Closes #6139
> Bump version 4.8.1 rev 00

- .github/workflows/dev-environment.yml
- docker/osd-dev/dev.yml
- plugins/main/opensearch_dashboards.json
- plugins/main/public/types.ts
- plugins/wazuh-endpoints/.i18nrc.json
- plugins/wazuh-endpoints/common/constants.ts
- plugins/wazuh-endpoints/opensearch_dashboards.json
- plugins/wazuh-endpoints/package.json
- plugins/wazuh-endpoints/public/index.ts
- plugins/wazuh-endpoints/public/plugin.ts
- plugins/wazuh-endpoints/public/types.ts
- plugins/wazuh-endpoints/scripts/jest.js
- plugins/wazuh-endpoints/scripts/manifest.js
- plugins/wazuh-endpoints/scripts/runner.js
- plugins/wazuh-endpoints/server/index.ts
- plugins/wazuh-endpoints/server/plugin.ts
- plugins/wazuh-endpoints/server/types.ts
- plugins/wazuh-endpoints/test/jest/config.js
- plugins/wazuh-endpoints/translations/en-US.json
- plugins/wazuh-endpoints/tsconfig.json
Create new plugin wazuh-endpoints to manage the endpoint fleet page components.
This issue is only for the plugin creation without any functionality.
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6141
- Check if there is a new `wazuh-endpoints` plugin inside the `plugins` folder in the osd docker container.
- Check if the dashboard load ok
> Create new plugin wazuh-endpoints

- docker/imposter/manager/version/check.json
- plugins/main/public/components/settings/api/api-table.js
- plugins/wazuh-check-updates/server/services/updates/get-updates.test.ts
- plugins/wazuh-check-updates/server/services/updates/get-updates.ts
- Ignore uuid field in GET /manager/version/check response to return the available updates from the service
- Fix copy error on `Updates status` column.
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6156
Test with an imposter or a real service with the endpoint `manager/version/check` and make sure that the `endpoint` returns `uuid` field.
- Go to the file `docker/imposter/wazuh-config.yml`
- Replace line 3 with: `specFile: https://raw.githubusercontent.com/wazuh/wazuh/dev-14153-vulndet-refactor/api/api/spec/spec.yaml`
- Restart imposter
Go to the server APIs page, look for a column `Updates status` and a manager with and error. Click on the (?) icon. Check if the clipboard content match with the error.
> Ignore uuid field in GET /manager/version/check response

- plugins/wazuh-check-updates/server/services/updates/get-updates.ts
This PR solves the error that produces the API endpoint `manager/version/check` response when the check updates service is disabled and the field `last_check_date` is an empty string.
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6168
1. Go to the file `docker/imposter/wazuh-config.yml`
2. Replace line 3 with: `specFile: https://raw.githubusercontent.com/wazuh/wazuh/dev-14153-vulndet-refactor/api/api/spec/spec.yaml`
3. Go to the file `docker/imposter/manager/version/check.json` and replace content with:
```console
{
"data": {
"last_check_date": "",
"current_version": "4.8.0",
"update_check": false,
"last_available_major": {},
"last_available_minor": {},
"last_available_patch": {}
},
"error": 0
}
```
5. Restart imposter
> Fix last_check_date mapping when check updates service is disabled

- CHANGELOG.md
- plugins/main/public/components/overview/vulnerabilities/dashboards/inventory/inventory_service.ts
- plugins/main/public/components/overview/vulnerabilities/data_grid/use_data_grid.ts
This PR, 
solves an error when clicking on the `show all` button from the inventory columns selector.
The error was triggered when the column didn't have a value (empty value) to show.
Solves #6164 
- Go to the Vulnerabilities `Inventory` tab
- Open the columns selector
- Click on the `show all` button
- Check if all the columns are shown and not throw error
### Before
https://github.com/wazuh/wazuh-dashboard-plugins/assets/6089438/d56f0c69-3541-4d1b-ba22-6778588b10ee
> Fix error when a column with no value is selected to show in the vulnerabilities inventory table

- scripts/vulnerabilities-events-injector/dataInjectScript.py
This PR Solves an issue with the user settings in the vulnerabilities injection script
Having a Wazuh instance:
- Run the script and try to save the events
- Run the script and try to inject the events to the Indexer using a non existing index. Store the Indexer information for future use. It should create it using the `DIS_Template.json` template.
- Run the script and try to inject again. It should use the stored settings
- Modify the `DIS_Settings.json` file and rename one of the fields (i.e. `password` to `pw`) and run the script to inject again. It should say that there's an error in the file and ask for the Indexer information again.
> Fix errors in vulnerabilities injection script

- .github/workflows/dev-environment.yml
- .github/workflows/manual-build.yml
Update the GitHub action for package creation and change the package name to the convention name.
- #6194 
- Run a manual build workflow through dispatching the action
> Update Build manual Github action

- CHANGELOG.md
- plugins/main/public/components/agents/syscollector/__snapshots__/inventory.test.tsx.snap
- plugins/main/public/components/agents/syscollector/components/syscollector-metrics.tsx
**Agent > Inventory** shows hostname and board serial fields
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6190
> Add hostname board serial fields to agent inventory

- CHANGELOG.md
- plugins/main/public/components/security/policies/create-policy.tsx
- plugins/main/public/components/security/policies/edit-policy.tsx
- plugins/main/public/components/security/policies/policies-table.tsx
- plugins/main/public/controllers/register-agent/containers/register-agent/register-agent.tsx
- plugins/main/public/controllers/register-agent/services/register-agent-services.tsx
This pull request aims to use a manager or cluster endpoint to get the authentication configuration of the Wazuh server. Previously it used the agent endpoint filtered by the manager ID `000`, which may cause RBAC issues.
It also fixes the order of the RBAC options in the create/edit policies view, so they appear in alphabetical order.
Closes #6203 
- Check the manager auth configuration request uses either the manager or cluster endpoint:
https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.cluster_controller.get_node_config
- Configure a password in the manager and check the register agent wizard sets the password properly in the script:
- Check the actions SuperSelect options are in alphabetical order:
> Change the endpoint to get Wazuh manager auth configuration

- CHANGELOG.md
- plugins/main/public/controllers/agent/components/agents-preview.scss
- plugins/main/public/controllers/register-agent/components/command-output/command-output.tsx
- plugins/main/public/controllers/register-agent/components/command-output/os-warning.tsx
- plugins/main/public/controllers/register-agent/components/group-input/group-input.tsx
- plugins/main/public/controllers/register-agent/components/optionals-inputs/optionals-inputs.tsx
- plugins/main/public/controllers/register-agent/components/server-address/server-address.tsx
- plugins/main/public/controllers/register-agent/containers/steps/steps.scss
- plugins/main/public/controllers/register-agent/containers/steps/steps.tsx
- plugins/main/public/controllers/register-agent/utils/register-agent-data.tsx
- Add colons `:` at the end of wizard titles
- Add colons `:` to input labels
- Add an info callout specifying if the script is in Powershell (Windows) or shell bash (Linux). It should also mention when administrator permissions are needed.
- Change the description of the optional setting
- Remove the word Wazuh each time an agent is mentioned
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6202
> Standardize titles and subtitles in the register agent wizard

- CHANGELOG.md
- plugins/main/public/controllers/register-agent/services/register-agent-services.tsx
This pull request fixes the conditional in the register agent service to determine if the app is in cluster mode or not.
This is part of the issue #6203 
The requests made to get the node configuration must match the cluster or manager configuration.
- Configure the app in cluster mode
- Go to modules > Overview and check no error toasts pop up
- Go to Agents and check no error toasts pop up
- Configure the app in manager mode
- Go to modules > Overview and check no error toasts pop up
- Go to Agents and check no error toasts pop up
> Fix the register agent selected cluster/manager config endpoint 

- CHANGELOG.md
- plugins/main/public/controllers/agent/components/agents-preview.js
This PR aims to solve a problem with the agents. When a user access an agent information clicking on `Most active agent` or `Last registered agent`, after navigating to another site on the app it can't return with the browser's `back` button. 
This doesn't happen when the agent is accessed through the agents table
#6211 
https://github.com/wazuh/wazuh-dashboard-plugins/assets/42900763/530adda1-0169-4aae-90b0-5d5a1e68b91a
1. Have an environment with a real manager and an agent registered
2. Navigate to `Wazuh/Agents` and click on the `Last registered agent`
3. Navigate to `Wazuh/Tools/Api console` and run any query
4. Click the browser's back button. It should return to the agent detail. 
5. Repeat steps 2 to 4, clicking on the `Most active agent` instead of last registered
6. Repeat steps …
> Fix error navigating back to agent

- CHANGELOG.md
- plugins/main/public/controllers/agent/components/agents-table.js
- plugins/main/public/controllers/settings/settings.js
- plugins/main/public/react-services/time-service.js
- plugins/wazuh-core/public/utils/time.ts
This PR fixes a few redundant date formats. This was caused by some components trying to format dates already formatted.
It also improves the validation of the date parameter in the `formatUIDate` service.
> [!IMPORTANT]  
> The issue can only be replicated in Firefox. Nevertheless, it should be tested in all browsers with a real manager.
Closes #6207 #6212 #6220 
- Go to _About_ page and check the date renders properly
- Register an agent in a Wazuh server
- Go to Endpoints Summart and check the date values are rendered properly
- Select an agent in the table and verify `Registration date` and `Last keep alive` values render a valid date
> Fix invalid date format

- CHANGELOG.md
- plugins/main/public/controllers/agent/components/agents-preview.js
Fix the links of the last registered agent and the most active agent.
- https://github.com/wazuh/wazuh-dashboard/issues/94
1. Navigate to `summary endpoints`
2. Test the links of the last registered agent and the most active agent, if you don't have agents in those fields it should not be a link. (the application to which you are redirected should be it hygiene)
> Fix links las registered agent and agent most active

- CHANGELOG.md
- plugins/main/public/components/overview/vulnerabilities/dashboards/overview/dashboard.tsx
- plugins/main/public/components/overview/vulnerabilities/dashboards/overview/vulnerability_detector_filters.scss
Starting at breakpoint 767px, there is an overlap of the vulnerability dashboard panels.
The solution found to avoid overlapping panels is to add styles starting from the breakpoint where the overlap occurred (767px).
- #6245 
Before remember to create the mapping of port `9200:9200` in `osd1` in the `dev.yml`
- Create the index (wazuh-states-vulnerabilities) in the manager and insert data and mapping (using [comment](https://github.com/wazuh/wazuh-dashboard-plugins/issues/5763#issuecomment-1779564103)). 
- Navigate to `Threat Hunting` -> `Vulnerability Detection` and Reduce window to less than 768px.
- The panels must be arranged one below the order..
> Fix responsive view on vulnerability dashboard

- CHANGELOG.md
- plugins/main/public/components/agents/sca/events/configuration-assessment-columns.tsx
- plugins/main/public/components/common/modules/modules-defaults.js
This PR, replaces the events tab on the Configuration assessment module
- #6276 
| Apply filters using search bar input | :black_circle: | :black_circle: | :black_circle: |
| Apply filters using the search bar `add filter` feature | :black_circle: | :black_circle: | :black_circle: |
| Apply filters using the date picker | :black_circle: | :black_circle: | :black_circle: |
| Apply filters with no results (Check the `No results match your search criteria` message)| :black_circle: | :black_circle: | :black_circle: |
| Use the `saved queries` feature (Check saved queries CRUD) | :black_circle: | :black_circle: | :black_circle: |
- Apply filters using search bar input
<details>
</details>
- Apply filters using the search bar `add …
> Replace discover Configuration assessment

- CHANGELOG.md
- plugins/main/public/components/common/modules/modules-defaults.js
- plugins/main/public/components/overview/fim/events/file-integrity-monitoring-columns.tsx
This PR, replaces the events tab on the File integrity monitoringmodule
- #6277 
| Apply filters using search bar input | :black_circle: | :black_circle: | :black_circle: |
| Apply filters using the search bar `add filter` feature | :black_circle: | :black_circle: | :black_circle: |
| Apply filters using the date picker | :black_circle: | :black_circle: | :black_circle: |
| Apply filters with no results (Check the `No results match your search criteria` message)| :black_circle: | :black_circle: | :black_circle: |
| Use the `saved queries` feature (Check saved queries CRUD) | :black_circle: | :black_circle: | :black_circle: |
- Apply filters using search bar input
<details>
</details>
- Apply filters using the search bar `add …
> Replace discover file integrity monitoring

- CHANGELOG.md
- plugins/main/public/components/common/modules/modules-defaults.js
- plugins/main/public/components/common/wazuh-discover/wz-discover.tsx
- plugins/main/public/components/overview/vulnerabilities/events/vulnerabilities-columns.tsx
This PR, replaces the events tab on the Vulnerability module
- #6273
| Apply filters using search bar input | :black_circle: | :black_circle: | :black_circle: |
| Apply filters using the search bar `add filter` feature | :black_circle: | :black_circle: | :black_circle: |
| Apply filters using the date picker | :black_circle: | :black_circle: | :black_circle: |
| Apply filters with no results (Check the `No results match your search criteria` message)| :black_circle: | :black_circle: | :black_circle: |
| Use the `saved queries` feature (Check saved queries CRUD) | :black_circle: | :black_circle: | :black_circle: |
- Apply filters using search bar input
<details>
</details>
- Apply filters using the search bar `add filter` …
> Replace discover Vulnerability

- CHANGELOG.md
- plugins/main/public/controllers/register-agent/components/command-output/command-output.tsx
- plugins/main/public/controllers/register-agent/services/register-agent-os-commands-services.test.ts
- plugins/main/public/controllers/register-agent/services/register-agent-os-commands-services.tsx
when using the password to install agents in macos, the installation script was generated incorrectly without space or &&
- #6294
You need a real manage
1. Set the [password for deploy agent](https://documentation.wazuh.com/current/user-manual/agent-enrollment/security-options/using-password-authentication.html#using-password-authentication)
2. See that the macOS install command is rendered correctly
> Script for installing agents on macOS

- CHANGELOG.md
- plugins/main/public/controllers/register-agent/utils/validations.test.tsx
- plugins/main/public/controllers/register-agent/utils/validations.tsx
This PR aims to fix an error on which the `Deploy New Agent` section did not allow to specify a hostname as server address
#6311
- Deploy a new environment
- Navigate to Endpoints Summary/Deploy new agent
- Verify that it allows all the possible options for Server Address, and shows errors on any non valid address. 
The allowed options are: 
- Hostname from 1 to 63 alphanumeric characters
- Domains up to 255 characters (up to 63 per label)
- IPv4 
- Uncompressed IPv6
**Note**: A non valid IPv4 (i.e. 280.240.1.300) should be considered valid, as it matches the rules to be a domain (alphanumeric labels with 1-63 characters)
> Fix deploy new agent filters

- CHANGELOG.md
- plugins/main/public/controllers/register-agent/utils/register-agent-data.tsx
In the instructions to perform an agent deployment, the nomenclature FDQN has been changed to FQDN
[Incorrect abbreviation for Fully Qualified Domain Name](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6310)
| In the instructions to perform an agent deployment, the nomenclature should be FQDN | :black_circle: | :black_circle: | :black_circle: |
- In the instructions to perform an agent deployment, the nomenclature should be FQDN
<details>
</details>
> Fix abbreviation for Fully Qualified Domain Name

- plugins/main/public/components/overview/vulnerabilities/dashboards/overview/vulnerability_detector_filters.scss
- plugins/main/public/styles/common.scss
This pull request fix maximize in embeddable dashboards panels.
`dshLayout-isMaximizedPanel` is a specific class that adds OSD to the ResponsiveGrid component when a panel is expanded.
Since this fix is needed in more than one embedded dashboard, it was decided to apply the CSS at the highest possible level but within the context of Wazuh.
- #6322 
[Evidence.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/ac1d3ce0-e223-462c-9456-a30d3396b92d)
> [!NOTE]
> This test requires data to be inserted into the vulnerability index via the dataInjectScript.py script located in scripts/vulnerabilities-events-injector
- Go to vulnerability module.
- Go to panel actions of a panel ("···" button)
- Select maximize panel.
- The panel occupy the entire space of the module.
- Check …
> Fix maximize in embeddable vulnerability panel

- CHANGELOG.md
- plugins/main/public/plugin.ts
The Discover deprecation warning is hidden.
- #6314 
1. Navigate to the Discover plugin
2. The Discover deprecation warning should not appear.
> Hide discover deprecation notice

- CHANGELOG.md
- plugins/main/public/components/overview/vulnerabilities/dashboards/inventory/inventory.tsx
- plugins/main/public/styles/common.scss
In the Inventory tab of the Vulnerabilities module, when the table is maximized and the left main navigation menu is docked, the table is rendered by adjusting its width accordingly.
- #6323
https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/6d8cc7a7-65dd-469e-916b-59ee742be304
1. Dock the main left navigation menu
2. Navigate to Vulnerabilities / Inventory
3. Click on the maximize button of the table
> Fix inventory data table full screen side menu dock

- CHANGELOG.md
- plugins/main/server/integration-files/visualizations/cluster/statistics.ts
This PR fixes the `Queue Usage` stat. It was picking the max value instead of the current value in the visualization on the stats page.
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6340
1. Navigate to Server management -> Statistics -> Analysis Engine tab
2. Examine the Queue usage visualization
> Fix server stat Archives queue usage is picking the wrong value

- CHANGELOG.md
- plugins/main/public/components/overview/vulnerabilities/dashboards/inventory/inventory.scss
Fixes the unnecessary scrolling that occurs when you search for something that results in 1 page and then return to a multi-page result.
#6324 
https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/776cd9c6-8d09-4949-a100-3630f470fad2
1. Navigate to 'Vunerability/Inventory'
2. Filter table to have 1 page of results
3. Remove filter to have more than 1 page of results
4. Should not be able to scroll the page
> Fix unnecessary scroll in Vulnerability inventory

- CHANGELOG.md
- plugins/main/public/controllers/register-agent/services/register-agent-os-commands-services.tsx
This PR removes `WAZUH_REGISTRATION_SERVER` from the windows agent installation command. This is because the address in this variable is the same as the `WAZUH_MANAGER` therefore it's redundant.
#6348 
<details>
</details>
Verify the installation script for windows doesn't include WAZUH_REGISTRATION_SERVER:
Eg.
```
Invoke-WebRequest -Uri https://packages.wazuh.com/4.x/windows/wazuh-agent-4.8.0-1.msi -OutFile ${env.tmp}\wazuh-agent; msiexec.exe /i ${env.tmp}\wazuh-agent /q WAZUH_MANAGER='server.com' WAZUH_AGENT_GROUP='windows' WAZUH_AGENT_NAME='new-agent'
```
> Remove WAZUH_REGISTRATION_SERVER from the windows command

- CHANGELOG.md
- plugins/main/public/controllers/agent/components/agents-preview.js
The label of the last registered agent is changed to the Last enrolled agent
An information icon with a tooltip is added to the most active agent
- #6358
1. Navigate to Endpoint summary
2. Look at the label change 
3. Look at the icon and the tooltip
> Add tooltip to most active agent label

- CHANGELOG.md
- plugins/main/public/controllers/management/components/management/status/status-node-info.js
This pull request  removes all uses of the `compilation_date` field, because these API endpoints will no longer contain the field:
> GET /cluster/{node_id}/info
> GET /manager/info
Closes #6365 
- Check the **_Compilation Date_** is no longer present in the Status view.
- Check the compilation_date field is not used anywhere in the app
> Remove compilation date from dashboard

- CHANGELOG.md
- plugins/main/public/components/settings/api/api-table.js
A - is added when the run as is disabled, and a tooltip with information is added
- #6351
1. Navigate to Indexer/Dashboard Management -> Server API
2. Review the column "Run as"
> Add - when run as is disable

- plugins/main/public/components/settings/api/api-table.js
- plugins/wazuh-check-updates/README.md
- plugins/wazuh-check-updates/public/services/available-updates.ts
- plugins/wazuh-check-updates/public/types.ts
- plugins/wazuh-check-updates/server/routes/updates/get-updates.test.ts
- plugins/wazuh-check-updates/server/routes/updates/get-updates.ts
- plugins/wazuh-check-updates/server/services/updates/get-updates.ts
This PR prevents checking for updates with the force_query parameter set to true upon user login. Consequently, the Wazuh API will now return available updates without querying the CTI Service.
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6308
`query_api`: Determines whether the Check Updates plugin retrieves data from the Wazuh API or from a saved object.
`force_query`: When `query_api` is set to true, it determines whether the Wazuh API internally obtains the data or fetches it from the CTI Service.
1. Open brower inspectos to see network requests.
2. Logins and check the request: `/api/wazuh-check-updates/updates?query_api=true&force_query=false`
3. Navigate to `Indexer/dashboard management -> Server APIs` and check de request: …
> Avoid force check updates when user logins

- CHANGELOG.md
- plugins/main/public/controllers/overview/components/__snapshots__/stats.test.tsx.snap
- plugins/main/public/controllers/overview/components/last-alerts-stat/index.ts
- plugins/main/public/controllers/overview/components/last-alerts-stat/last-alerts-query.ts
- plugins/main/public/controllers/overview/components/last-alerts-stat/last-alerts-service.ts
- plugins/main/public/controllers/overview/components/last-alerts-stat/last-alerts-stat.tsx
- plugins/main/public/controllers/overview/components/stats.js
- plugins/main/public/controllers/overview/components/stats.test.tsx
This pull request removes the pending and never connected agents KPIs from the home view and also adds a new last 24 hours alerts KPI.
The last 24 hours alerts KPI is a call to action that redirects to the Discover plugin with the predefined filters.
- #6367 
- Go to Home -> Overview
- Check the only KPIs that exist are: `Active agents`, `Disconnected agents`, `Last 24 hours alerts`
- Check the `Last 24 hours alerts` is also a link to the Discover plugin
- The Discover plugin must have the `cluster.name` or `manager.name` pre-filtered (whether the cluster mode is enabled or not)
- The Discover plugin must be filtered by the last 24 hours
- The Discover plugin must use `wazuh-alerts-*` index pattern
- The results of the Discover plugin must match the _Last 24 hours alerts_ KPI count number …
> Add overview home last 24 hours KPI

- CHANGELOG.md
- plugins/main/public/controllers/overview/components/__snapshots__/stats.test.tsx.snap
- plugins/main/public/controllers/overview/components/last-alerts-stat/last-alerts-stat.tsx
- plugins/main/public/controllers/overview/components/stats.js
Fixes styling and redirection problem in home page KPIs 
- #6406 
Safari
Chrome
1. Check of the Home view KPIs must have the same font size and font-weight
2. check that the KPIs Active Agents and Disconnected Agents redirect to the endpoint summary with the selected filter in the table
> Fix home view kpis styles

- CHANGELOG.md
- plugins/main/public/controllers/agent/components/agents-preview.js
This pull request changes the Most active agent tooltip located in Endpoints summary to "Highest alert count agent in the last 24 hours"
Closes #6418 
- Go to Endpoints summary
- Hover over the Most active agent icon
- Validate the text
> Change text in endpoint summary most active agent tooltip

- CHANGELOG.md
- plugins/main/public/utils/applications.ts
This pull request adds the Vulnerabilities Detection application to the menu in Endpoint summary.
#6417
Legend:
| Go to Endpoints summary application, select some agent and ensure the menu contains a link to the Vulnerabilities Detection application | :black_circle: | :black_circle: | :black_circle: |
**Details**
<details>
<summary>:black_circle: Go to Endpoints summary application, select some agent and ensure the menu contains a link to the Vulnerabilities Detection application</summary>
</details>
> Add the Vulnerabilities Detection application to the menu in Endpoints summary view

- docker/osd-dev/dev.yml
Filebeat correction in development environments
- #6432 
- Run the environment without any real manager, only the imposter, filebeat should continue to run and the healtcheck should pass.
> Fixed filebeat in development environments

- CHANGELOG.md
- plugins/main/public/controllers/management/components/management/common/resources-handler.ts
This PR removes the `relative_dirname` when using CDB lists endpoints.
Closes #6455
- Go to Management -> CDB List 
- Click Import file button
- Select a file to import
- Refresh the table and check it was imported
- Edit the imported file
- Delete the imported file
> Remove relative_dirname from CDB List

- CHANGELOG.md
- plugins/main/public/controllers/management/components/management/common/resources-handler.ts
Merge 4.7.3 into 4.8.0
Issue:
- https://github.com/wazuh/wazuh-dashboard/issues/150
> [!CAUTION]
> Merge 4.7.3 into 4.8.0

- CHANGELOG.md
- plugins/main/public/styles/common.scss
- plugins/main/public/styles/theme/dark/index.dark.scss
This pull request fixes the style of the euiPage component background color and overview icons for both light and dark theme.
- #6483 
- Check the Overview page looks like the images provided.
- The euiPage component shouldn't have the native grey color in the light theme.
> Minor style fixes in light and dark mode

- CHANGELOG.md
- plugins/main/common/constants.ts
- plugins/main/common/services/settings.test.ts
- plugins/main/server/routes/wazuh-reporting.test.ts
This PR changes PDF report year number to 2024.
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6491
- Verify the PDF reports have 2024 as the year number
> Change PDF report year number to 2024

- CHANGELOG.md
- plugins/main/public/components/settings/api/api-table.js
This pull request fixes a problem with the initial value when editing the API connection.
#6201
Run as disabled as initial value:
Run as enabled as initial value:
Legend:
| With a API connection with run_as disabled, click on the edit button, the Run as should display as false. | :black_circle: | :black_circle: | :black_circle: |
| With a API connection with run_as enabled, click on the edit button, the Run as should display as true. | :black_circle: | :black_circle: | :black_circle: |
**Details**
<details>
<summary>:black_circle: With a API connection with run_as disabled, click on the edit button, the Run as …
> Fix wrong initial value editing an API connection

- CHANGELOG.md
- plugins/main/public/components/common/welcome/overview-welcome.js
- plugins/main/public/components/common/welcome/welcome.scss
This PR adds a class to the RedirectAppLinks component in the Home cards link to make the height even in each row.
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6509
- Go to the Home page
- Check each card's height is even in the category rows
> Fix height of Home overview cards

- CHANGELOG.md
- plugins/main/public/controllers/management/components/management/ruleset/views/rule-info.tsx
This pull request fixes the path of the **_"View alerts of this rule"_** so it pre-filters the rule ID in the Threat hunting view.
Closes https://github.com/wazuh/wazuh-dashboard-plugins/issues/6551
Link:
Applied filter:
- Go to Server management -> Rules
- Click on a rule row to display de details flyout
- Click on the top right link **_"View alerts of this rule"_**
- Check it opens a new tab in Threat hunting with the rule ID pre-applied filter
> Fix view rule alert link

- plugins/main/public/components/overview/vulnerabilities/dashboards/overview/dashboard.tsx
- plugins/main/public/components/overview/vulnerabilities/dashboards/overview/dashboard_panels.ts
- plugins/main/public/components/overview/vulnerabilities/dashboards/overview/dashboard_panels_filters.ts
- plugins/main/public/components/overview/vulnerabilities/dashboards/overview/dashboard_panels_kpis.ts
- scripts/vulnerabilities-events-injector/DIS_Template.json
- scripts/vulnerabilities-events-injector/dataInjectScript.py
This pull request makes additional changes to the Vulnerabilities dashboard as part of another refinement iteration.
Closes #6533 
- The severity KPIs must be placed in the first row of the dashboard
- The filter tables must be placed in the second row of the dashboard
- The filter tables order must be: Top 5 vulnerabilities, Top 5 OS, Top 5 agents, Top 5 packages
- The Top 5 OS, Top 5 agents tables must be wider than the Top 5 vulnerabilities, Top 5 packages tables
- We have to remove the word alerts and hyphens from the KPIs
- We must change the @timestamp field used in the Accumulation of the most detected vulnerabilities visualization for the new field published_at
> Change vulnerabilities dashboard

- plugins/main/public/components/visualize/visualizations.js
- plugins/main/server/integration-files/visualizations/overview/overview-pm.ts
This pull request changes the top left visualization label from **Emotet malware activity** to **Malware activity** and removes the fields `rule.mitre.tactic` and `rule.mitre.id` in the lower table.
It also adds an enhancement with custom widths for columns with a known short data length: Time; Rule level; Rule ID; Count
Closes #6552 
- Go to Malware detection
- Check the top left visualization label says "Malware activity"
- Check the bottom table doesn't have any `rule.mitre` field
> Refine malware detection dashboard

- CHANGELOG.md
- plugins/main/public/controllers/management/components/management/configuration/configuration-switch.js
- plugins/main/public/controllers/management/components/management/configuration/integrity-monitoring/integrity-monitoring.js
- plugins/main/public/controllers/management/components/management/configuration/log-collection/log-collection.js
This pull request fixes a disconnected agent exception when accessing the agent `log collection` or `integrity monitoring` configuration.
Changes made:
- Handle log collector and integrity monitoring falsy values
- Add HOC guard validating the agent is active for the configuration view
Closes https://github.com/wazuh/wazuh-dashboard-plugins/issues/6615
- Register a real agent and wait until it is active
- Disconnect the agent
- Go to Endpoints Summary
- Select the disconnected agent
- Go to Configuration
- Verify the view can only be used with active agents
> Add only active agents guard for configuration

- CHANGELOG.md
- plugins/main/public/components/common/welcome/overview-welcome.js
- plugins/main/public/controllers/overview/components/last-alerts-stat/last-alerts-stat.tsx
This PR reduces the size of the overview home page.
Closes #6624 
- Go to overview home
- Verify:
- KPI's title font size is 17.5px
- KPI's description font size is 12px
- Modules Card title is 16px
- Modules Card content is 12px
> Reduce overview welcome font size

- CHANGELOG.md
- plugins/main/public/components/endpoints-summary/services/upgrade-agent.tsx
- plugins/main/public/components/endpoints-summary/table/actions/edit-groups-modal.tsx
- plugins/main/public/components/endpoints-summary/table/actions/upgrade-agent-modal.test.tsx
- plugins/main/public/components/endpoints-summary/table/actions/upgrade-agent-modal.tsx
- plugins/main/public/components/endpoints-summary/table/agents-table.tsx
When upgrade an individual agent, in case that the OS is **`Linux`** and the platform is not one of these:
- `debian`
- `ubuntu`
- `amzn`
- `centos`
- `fedora`
- `ol`
- `opensuse`
- `opensuse-leap`
- `opensuse-tumbleweed`
- `rhel`
- `sles`
- `suse`
The confirm modal asks for the package type (RPM or DEB).
> [!NOTE]  
> The multiple upgrade action was not modified
https://github.com/wazuh/internal-devel-requests/issues/1102
The request was made **without** `package_type` and `force` parameters
The request was made **with** `package_type` and `force` parameters
Legend:
> [!IMPORTANT]  
> Test with a **real manager** from this branch: …
> Select package type to upgrade

- plugins/main/public/components/overview/vulnerabilities/dashboards/inventory/inventory.tsx
Hi team, this pull request changes the vulnerabilities inventory flyout title to `Vulnerability details`.
Closes #6661 
- Check the _**Vulnerabilities / Inventory**_ Open details buttons tooltip say `Inspect vulnerability details`
- Check the _**Vulnerabilities / Inventory**_ flyout title says `Vulnerability details`
> Change flyout title to Vulnerability details

- plugins/main/public/utils/applications.ts
Add to the url of the overview the parameter agentId to keep the agent pinned
- #6672 
1. Navigate to some dashboard
2. Pin some agent
3. Navigate to overview
4. Navigate to another dashboard
5. The previously pinned agent must remain pinned.
> Add to the url of overview the parameter agentId

- CHANGELOG.md
- plugins/main/public/components/agents/sca/dashboard/dashboard.tsx
A `localStorage.clear` is modified so that it does not delete the state responsible for hiding the discover message.
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6683
Before:
After:
> Hide discover callout warning message

- plugins/main/public/components/common/data-source/pattern/alerts/alerts-data-source.ts
- plugins/main/public/components/common/data-source/pattern/alerts/aws/aws-data-source.ts
- plugins/main/public/components/common/data-source/pattern/alerts/cluster/cluster-data-source.ts
- plugins/main/public/components/common/data-source/pattern/alerts/configuration-assessment/configuration-assessment-data-source.ts
- plugins/main/public/components/common/data-source/pattern/alerts/docker/docker-data-source.ts
- plugins/main/public/components/common/data-source/pattern/alerts/fim/fim-data-source.ts
- plugins/main/public/components/common/data-source/pattern/alerts/gdpr/gdpr-data-source.ts
- plugins/main/public/components/common/data-source/pattern/alerts/github/github-data-source.ts
- plugins/main/public/components/common/data-source/pattern/alerts/google-cloud/google-cloud-data-source.ts
- plugins/main/public/components/common/data-source/pattern/alerts/hipaa/hipaa-data-source.ts
- plugins/main/public/components/common/data-source/pattern/alerts/index.ts
- plugins/main/public/components/common/data-source/pattern/alerts/malware-detection/malware-detection-data-source.ts
- plugins/main/public/components/common/data-source/pattern/alerts/mitre-attack/mitre-attack-data-source.ts
- plugins/main/public/components/common/data-source/pattern/alerts/nist-800-53/nist-800-53-data-source.ts
- plugins/main/public/components/common/data-source/pattern/alerts/office-365/office-365-data-source.ts
- plugins/main/public/components/common/data-source/pattern/alerts/pci-dss/pci-dss-data-source.ts
- plugins/main/public/components/common/data-source/pattern/alerts/threat-hunting/index.ts
- plugins/main/public/components/common/data-source/pattern/alerts/threat-hunting/threat-hunting-data-source.ts
- plugins/main/public/components/common/data-source/pattern/alerts/tsc/tsc-data-souce.ts
- plugins/main/public/components/common/data-source/pattern/alerts/virustotal/virustotal-data-source.ts
- plugins/main/public/components/common/data-source/pattern/alerts/vulnerabilities/vulnerabilities-data-source.ts
- plugins/main/public/components/common/modules/modules-defaults.tsx
- plugins/main/public/components/overview/threat-hunting/dashboard/dashboard.tsx
Change the order of the filters to: `(cluster||manager).name`, `rule.groups` and `agent.id
` 
- #6672 
- navigate to different dashboards and events, the order of the filters must be `(cluster||manager).name`, `rule.groups` and `agent.id`
> Change the order of filters

- CHANGELOG.md
- plugins/main/public/components/wz-menu/wz-menu.js
- plugins/main/public/controllers/dev-tools/dev-tools.ts
- plugins/main/public/styles/common.scss
- plugins/main/public/styles/typography.scss
This pull request changes: 
- Removes bold font-weight from Endpoints summary KPIs `Last enrolled agent` and `Most active agent`
- Changes index pattern and APIs selectors font sizes to 14.5 px
- Changes the default console columns width of the Dev tools view
- Left column 45%
- Right column 55%
Closes #6699 
- Check the font-weight from Endpoints summary KPIs `Last enrolled agent` and `Most active agent` is `normal`
- Check the index pattern and APIs selectors font sizes are 14.5 px
- Check the default console columns width of the Dev tools view are:
- Left column 45%
- Right column 55%
> Change endpoints summary KPIs and index pattern and APIs selects font sizes

- plugins/main/public/components/common/modules/events-selected-fields.js
- plugins/main/public/components/overview/vulnerabilities/dashboards/inventory/config/index.ts
This pull request changes the default vulnerabilities tables columns fields.
Closes #6700 
- Check the default fields in Vulnerabilities / Inventory table are:
- agent.name
- package.name
- package.version
- vulnerability.description (bigger than the others)
- vulnerability.id
- vulneravility.severity
- Check the Vulnerabilities / Events table default fields and order are:
- time
- agent.name
- data.vulnerability.severity
- data.vulnerability.cve
- data.vulnerability.package.name
> Change default vulnerabilities tables columns fields

- plugins/main/public/components/overview/mitre/framework/mitre.tsx
This PR fixes the console warning : "**Failed prop type: Invalid prop children of type array supplied to I18nProvider, expected a single ReactElement**"
#6693 
Go to the Framework tab of the MITRE ATT&CK module and check that the following warning message does not appear in the console:
> Fix invalid prop children of type array supplied to I18nProvider

- CHANGELOG.md
- plugins/main/public/controllers/register-agent/components/command-output/command-output.tsx
- plugins/main/public/controllers/register-agent/services/register-agent-os-commands-services.test.ts
- plugins/main/public/controllers/register-agent/services/register-agent-os-commands-services.tsx
Hi team,
this pull request adds a space to the macOS agent register command when a password is required. Also, it adds a gap after the `Show password` switch to create a space before the info callout.
Closes #6717
```shell
curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.7.5-1.arm64.pkg && echo "WAZUH_MANAGER='1.1.1.1' && WAZUH_AGENT_GROUP='default,test-group' && WAZUH_AGENT_NAME='new-agent' && WAZUH_REGISTRATION_PASSWORD='Password123'\n" > /tmp/wazuh_envs && sudo installer -pkg ./wazuh-agent.pkg -target /
```
<details>
<summary>Screenshot</summary>
</details>
> Add space to macOS command with password

- CHANGELOG.md
- plugins/main/server/lib/parse-cron.ts
This pull request fixes the maximum allowed seconds validation of the cronjobs configuration.
The correct value is 24 * 3600 = `86400`
Closes #6688
> Fix cronjob max seconds interval

- plugins/main/public/components/common/form/input_select.tsx
- plugins/main/public/components/common/form/types.ts
Remove attributes in unused in select input to remove console errors
- #6693
https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/89698e30-eeec-4b7c-85e5-13134a5f28a1
1. Navigate to Dashboard management > App settings
2. Check that these errors do not appear in the console
`React does not recognize the isClearable prop on a DOM element.`
`React does not recognize the isDisabled prop on a DOM element.`
`React does not recognize the selectedOptions prop on a DOM element.`
> Remove attributes in unused in select input 

- plugins/main/public/controllers/management/components/management/status/actions-buttons-main.js
Removes an error in the console when navigating to Status with a manager without the cluster enabled or when switching from a manager with the cluster enabled to a manager without the cluster enabled in the Status view.
- #6693 
https://github.com/wazuh/wazuh-dashboard-plugins/assets/63758389/24ab9a28-d3e7-46a7-8669-9a3b55ae4504
1. Navigate to Server Management > Status
2. Check that the error does not appear in the console
`Failed prop type: Invalid prop value supplied to EuiSelect, expected one of type [string, number] `
3. Change manager with cluster enable to manager with cluster disabled
4.  Check that the error does not appear in the console
`Failed prop type: Invalid prop value supplied to EuiSelect, expected one of type [string, number] `
> Fix warning type error in status view

- CHANGELOG.md
- plugins/main/public/components/common/data-source/pattern/vulnerabilities/vulnerabilities-data-source.ts
- plugins/main/public/components/common/welcome/agents-welcome.js
- plugins/main/public/components/endpoints-summary/dashboard/endpoints-summary-dashboard.tsx
- plugins/main/public/components/endpoints-summary/endpoints-summary.scss
- plugins/main/public/components/endpoints-summary/endpoints-summary.tsx
- plugins/main/public/components/endpoints-summary/services/get-outdated-agents.ts
- plugins/main/public/components/endpoints-summary/services/index.tsx
- plugins/main/public/components/endpoints-summary/table/__snapshots__/agents-table.test.tsx.snap
- plugins/main/public/components/endpoints-summary/table/agents-table.tsx
- plugins/main/public/components/endpoints-summary/table/upgrades-in-progress/__snapshots__/upgrades-in-progress.test.tsx.snap
- plugins/main/public/components/endpoints-summary/table/upgrades-in-progress/upgrades-in-progress.tsx
This PR addresses the following changes:
1. Removed outdated agents' statistic from the Endpoints Summary page:
- The outdated agents' statistic has been removed to streamline the information displayed on the Endpoints Summary page.
2. Moved state management to table component:
- The state management for the total number of outdated agents has been shifted from the Endpoints Summary page to the table component. This ensures that the table component independently manages and reflects the accurate count of outdated agents.
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6736
> [!IMPORTANT]  
> Test with a real 4.9.0 manager and at least one outdated agent.
Legend:
| …
> Remove total outdated agents statistic from Endpoint Summary

- CHANGELOG.md
- plugins/main/public/components/common/search-bar/search-bar.tsx
- plugins/main/public/components/common/wazuh-discover/wz-flyout-discover.tsx
This PR replaces `SearchBar` with `WzSearchBar` in flyout component. Also, add an attribute (`hideFixedFilters`) to `WzSearchBar` so that it hides the fixed filters if necessary.
- #6711 
- **Check Flyout**
- Go to some screen that uses SearchBar in the flyout, for example, Inventory FIM.
- Make the necessary interaction to open the Flyout.
- Check that the SearchBar does not show the filters set as shown in the evidence.
- **Check SearchBar on non-Flyout screens**
- Go to a screen that uses the SearchBar other than Flyout
- Check, if applicable, that it shows the set filters.
> Replaced SearchBar with WzSearchBar in flyout component

- CHANGELOG.md
- plugins/main/public/components/overview/overview.tsx
- plugins/main/public/components/wz-agent-selector/wz-agent-selector-service.ts
- plugins/main/public/react-services/navigation-service.tsx
This PR fixes rendering when changing the API in Configuration Assessment when you have an agent pinned.
- #6763 
[evidence.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/aa08f375-d8ad-4572-a39f-6fd13362cbab)
- Navigate to Configuration Assessment.
- Pin an agent.
- Go to Home -> Overview
- Go to Configuration Assessment.
- Change the API.
- Check that the agent selection screen appears in Configuration Assessment.
> Fixed behavior in Configuration Assessment when changing API

- .github/workflows/prettier.yml
This pull request adds the Prettier and ESLint checks on the changed files for the pull requests workflow.
#6761
We could test it creating a pull request with changes on the files that do not pass the code format of prettier and eslint. To test, you could use a fork to create the pull request and review the check result for the code formatting (prettier and linter).
Currently, the ESLint check is disabled for this repository, so we could ignore the test of this check.
> GHA: add prettier and eslint checks on the changed files for the pull request

- CHANGELOG.md
- plugins/main/public/components/common/data-source/hooks/use-data-source.ts
- plugins/main/public/components/common/hooks/use-is-mounted.test.tsx
- plugins/main/public/components/common/hooks/use-is-mounted.ts
This PR fixes the disappearance of fixed filters when changing tabs quickly in vulnerabilities, between the dashboard/inventory and events tabs.
- #6764 
[evidence.webm](https://github.com/wazuh/wazuh-dashboard-plugins/assets/43619595/dd806cf3-82cc-41b5-ba15-467e30eef6ac)
> [!NOTE]  
> Data must be injected with dataInjectScript.py located in scripts/vulnerabilities-events-injector.
**Step to test:**
- Go to vulnerability detection module.
- Try change tabs quickly between the dashboard/inventory and events tabs.
- Check that the set filters do not disappear.
> Fix quick switch between tabs vulnerabilities gives a filter error

- CHANGELOG.md
- plugins/main/public/controllers/overview/components/last-alerts-stat/last-alerts-service.ts
- plugins/main/public/controllers/overview/components/last-alerts-stat/last-alerts-stat.tsx
- plugins/main/public/controllers/overview/components/stats.test.tsx
This pull request fixes the hardcoded value of index pattern on the filters of home KPI links.
Side changes:
- Fix a problem in the home KPI links when using a index pattern with different title and id.
#6776
Legend:
| With an index pattern with the same title and ID, go to Home > Overview, the KPI links should display and redirect correctly to the Discover app and the filters should be applied without errors | :black_circle: | :black_circle: | :black_circle: |
| With an index pattern with a different title and ID, go to Home > Overview, the KPI links should display and redirect correctly to the Discover app …
> Index pattern on the filters of home KPI links

- CHANGELOG.md
- plugins/main/server/controllers/wazuh-api.ts
This pull request removes the unexpected `delay` parameter on the server API request.
#6605
```
2024/06/18 11:38:30 INFO: wazuh-wui (c09a55c48149cb4a49111deba1f87c0e) 172.18.0.9 "PUT /cluster/restart" with parameters {} and body {} done in 0.031s: 200
```
Legend:
| Go to Rules and create or edit a rule file. Then restart the cluster. Ensure the API request to restart the cluster does not receive the `delay` parameter regarding the API logs | :black_circle: | :black_circle: | :black_circle: |
**Details**
<details>
<summary>:black_circle: Go to Rules and create or edit a rule file. Then restart the cluster. …
> Remove unexpected delay parameter on server API requests

- RELEASING.md
- scripts/release/README.md
- scripts/release/tag.js
This pull request move the sign and annotation of tag created by the releasing tool to optional.
This causes the default tag is not signed or  annotated to solve a problem with incompatibility of signed or annotated tags with the building process of Wazuh dashboard using a reusable workflow of plugins repository.
#6795
```console
[INFO][tag]: Run command: git tag v4.9.0-test-removeme
[INFO][tag]: Created tag: v4.9.0-test-removeme
[INFO][tag]: Run command: git push origin v4.9.0-test-removeme
remote: This repository moved. Please use the new location:        
remote:   https://github.com/wazuh/wazuh-dashboard-plugins.git        
To https://github.com/wazuh/wazuh-kibana-app.git
* [new tag]             v4.9.0-test-removeme -> v4.9.0-test-removeme
[INFO][tag]: Pushed tag v4.9.0-test-removeme …
```
> Remove sign and annotate tag from releasing tools

- CHANGELOG.md
- plugins/main/public/components/agents/fim/inventory/registry-table.tsx
- plugins/main/public/components/agents/fim/inventory/table.tsx
- plugins/main/public/components/health-check/container/health-check.container.tsx
- plugins/main/public/components/overview/mitre/intelligence/resource.tsx
- plugins/main/public/components/overview/overview.tsx
- plugins/main/public/controllers/management/components/management/groups/groups-main.js
- plugins/main/public/controllers/management/components/management/ruleset/views/rule-info.tsx
- plugins/main/public/react-services/navigation-service.tsx
Fix the url encoding.
#6773 
https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/f2978066-12f6-4dbe-9897-03a215bee836
https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/18d2cd59-74d0-4c1b-ad07-51a021ee81a0
https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/b26c3cf3-c660-457a-9d02-a666451c67bf
https://github.com/wazuh/wazuh-dashboard-plugins/assets/99441266/f9a81a49-48c4-4f06-b3b7-315841e3aa01
Verify that in the parts shown in the video evidence the url is not encoded, update and remove the url parameters if necessary.
> Fix switching tabs in the same module encodes the url

- CHANGELOG.md
- plugins/main/public/components/overview/vulnerabilities/dashboards/overview/dashboard.tsx
- plugins/main/public/components/overview/vulnerabilities/dashboards/overview/dashboard_panels.ts
- plugins/main/public/components/overview/vulnerabilities/dashboards/overview/dashboard_panels_kpis.ts
- plugins/main/public/components/overview/vulnerabilities/dashboards/overview/vulnerability_detector_filters.scss
This pull request defines the colors related to vulnerability severity levels on the dashboard of Vulnerability Detection application.
#6779
Legend:
| With vulnerabilities states data, go to Vulnerability Detection > Dashboard and ensure the metrics related to severity levels are sharing the colors with the Vulnerabilities by year of publication visualization | :black_circle: | :black_circle: | :black_circle: |
| The color of metric visualization of High and Medium should have interchanged. Final result: High (orange/yellow tone), Medium (blue tone) | :black_circle: | :black_circle: | :black_circle: | …
> Match colors related to severity levels on the vulnerabilities detection dashboard

- CHANGELOG.md
- plugins/main/opensearch_dashboards.json
- plugins/main/package.json
- plugins/wazuh-check-updates/opensearch_dashboards.json
- plugins/wazuh-check-updates/package.json
- plugins/wazuh-core/opensearch_dashboards.json
- plugins/wazuh-core/package.json
This pull request bumps Wazuh version to 4.8.1 revision 04.
```
node scripts/release/bump.js --plugins-directory ./plugins --manifest-changelog ./CHANGELOG.md --plugin-main-generate-api-data-spec https://raw.githubusercontent.com/wazuh/wazuh/4.8.1/api/api/spec/spec.yaml --manifest-package ./plugins/main/package.json --version 4.8.1 --revision 04
```
https://github.com/wazuh/wazuh-dashboard-plugins/issues/6835
> Bump revision 04 for 4.8.1 RC 4

- CHANGELOG.md
- plugins/main/public/components/common/search-bar/search-bar.scss
- plugins/main/public/components/common/search-bar/search-bar.tsx
Add the save query button to the search bar of the dashboards.
- #6829 
- Navigate to the different dashboards and events. 
- See that the Saved queries button appears and saves the filters external to the dashboard.
> Add saved queries button to search bar

- CHANGELOG.md
- plugins/main/public/components/overview/virustotal/events/virustotal-columns.tsx
This PR fixes `data.virustotal.permalink` column of the table in Events tab in Virustotal module. Para ello se cambia el render de ese campo usando un `EuiLink` con atributos de URL externo.
- #6838 
- Go to Virustotal module
- Go to Events tab
- Check  `data.virustotal.permalink` column shows links
- Chequear el correcto funcionamiento de los enlaces
> Fix permalink field in Events tab in Virustotal

- CHANGELOG.md
- plugins/main/public/components/common/charts/visualizations/legend.scss
- plugins/main/public/components/endpoints-summary/dashboard/components/donut-card.tsx
This PR fixes the legend of the donut-card component to adjust the available space the legend has, allowing more text to be rendered.
- https://github.com/wazuh/wazuh-dashboard/issues/244
- Go to `Server management -> Endpoints Summary`
- Check that the legends of the donut cards, especially those of Agents by status, are complete.
> Fixed donut card legend

- plugins/main/public/components/common/wazuh-discover/render-columns.tsx
- plugins/main/public/components/overview/threat-hunting/events/threat-hunting-columns.tsx
Remove `rule.mitre_techniques` column from the Threat Hunting
#6830 
- Go to the `Threat Hunting` module and verify that the field `rule.mitre_techniques` does not appear in the table on the `Dashboard` tab.
> Remove `rule.mitre_techniques` column from the Threat Hunting

- CHANGELOG.md
- plugins/main/public/components/agents/fim/inventory.tsx
Solution to change tab from Windows registry to Files when you have an agent pinned with windows and you switch to a non-windows agent.
- #6879 
https://github.com/user-attachments/assets/2b457a7c-5e44-4834-9bb6-cbfbdb135acf
Have 2 agents 1 windows and 1 from another operating system connected
1. Navigate to 'FIM > Inventory > Windows registry'
2. Change the pinned agent to the one of the other operating system
3. Windows registry tab should be changed for Files
> Checking the internal tab when changing agent on FIM > Inventory > Windows registry

- CHANGELOG.md
This pull request adds missing entries on the changelog related to the replacement of logging system.
> Add missing entries on the changelog related to logging system replacement

- CHANGELOG.md
- plugins/main/public/components/endpoints-summary/table/actions/actions.tsx
Hi team,
this pull request fixes the navigation method of the endpoint summary table action buttons, so the buttons use an in-module navigation method.
Closes #6892 
1. Go to Endpoints summary
2. Click on the :eye: button of an agent row to navigate to the agent details. Then go back in the browser history.
3. Click on the `...` button of an agent row to expand the actions, then click on `View agent details` to test the navigation.
4. Click on the `...` button of an agent row to expand the actions, then click on `Agent configuration` to navigate to the agent configuration.
> Fix endpoints summary agent action buttons navigation

- CHANGELOG.md
- plugins/main/public/controllers/management/components/management/configuration/active-response/active-response-active-response.js
- plugins/main/public/controllers/management/components/management/configuration/configuration-settings.js
The disabled render was removed and the description of Active response > Active response was changed.
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6801
> Fixed always disabled property from Active response

- CHANGELOG.md
- plugins/main/public/components/endpoints-summary/register-agent/services/register-agent-os-commands-services.test.ts
- plugins/main/public/components/endpoints-summary/register-agent/services/register-agent-os-commands-services.tsx
The windows-agent-deployment command uses `${env.tmp}` instead of `$env:tmp`. Then the pull changes the command.
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6518
```powershell
Invoke-WebRequest -Uri https://packages.wazuh.com/4.x/windows/wazuh-agent-4.9.1-1.msi -OutFile $env:tmp\wazuh-agent; msiexec.exe /i $env:tmp\wazuh-agent /q WAZUH_MANAGER='0' 
```
Go to Endpoints summary > Deploy new agent. Mark Windows deployment and check that the command in step 4 uses `$env:tmp` instead of `${env.tmp}`
> Changed windows-agent-deployment command

- CHANGELOG.md
- plugins/main/server/controllers/wazuh-api.ts
This pull request fixes a problem sending payload parameters as arrays on the Dev Tools application.
#6899
Legend:
| Go to Server management > Dev Tools and run the following request POST /events {"events": ["Test"]} and should not give an error. Use a real manager | :black_circle: | :black_circle: | :black_circle: |
**Details**
<details>
<summary>:black_circle: Go to Server management > Dev Tools and run the following request POST /events {"events": ["Test"]} and should not give an error. Use a real manager</summary>
</details>
> Fixed an error sending payload parameters as arrays on the Dev Tools application

- CHANGELOG.md
- plugins/main/public/components/endpoints-summary/register-agent/services/register-agent-os-commands-services.test.ts
- plugins/main/public/components/endpoints-summary/register-agent/services/register-agent-os-commands-services.tsx
Mac deployment-agent-command adds `\n` into the end of the `WAZUH_REGISTRATION_PASSWORD` variable. This PR removes the new line.
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6906
> To test this PR it must be tested with a real manager.
1. In manager files > Go to /var/ossec/etc/ossec.conf
2. Add (in auth section) <use_password>yes</use_password>
3. Create (in /var/ossec/etc/) authd.pass file
`echo "<CUSTOM_PASSWORD>" > /var/ossec/etc/authd.pass`
4. Restart manager
5. (In dashboard) Go to Endpoints summary > Deploy new agent. Select a mac os agent deployment.
6. Check that '\n' doesn't show in the `WAZUH_REGISTRATION_PASSWORD` variable in the deployment command.
> Repair mac deployment-agent-command

- CHANGELOG.md
- plugins/main/public/utils/applications.ts
In opensearch 2.16.0 compatibility they add the option to have a new menu, and because of this change new plugins were registered that conflict with ours so we had to change the settings id. 
- #6920 
Using OSD 2.16.0 it should work as expected.
the url of Server management> Settings should be /app/dashboards-settings
> Change the registration id of the setting application

- plugins/main/public/components/overview/overview.tsx
- plugins/main/public/utils/migrate_legacy_query.ts
This pull request fixes a problem with the filters are not kept when refreshing the page.
> This pull request does not contain an entry in the changelog because the entry was added to the entry of https://github.com/wazuh/wazuh-dashboard-plugins/issues/6120 that includes multiple pull requests
#6937
> Keep the appState filters on refreshing page

- CHANGELOG.md
- plugins/main/public/components/overview/mitre/intelligence/resource_detail_flyout.tsx
The description in the MITRE ATT&CK -> Intelligence -> details flyout get darker
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6951
> Improve intelligence flyout details readability

- CHANGELOG.md
- plugins/main/public/components/common/data-source/pattern/alerts/malware-detection/malware-detection-data-source.ts
- plugins/main/public/components/common/data-source/pattern/pattern-data-source-filter-manager.ts
Change the Endpoint security > Malware detection module filters to "rule.groups is one of rootcheck,virustotal,yara"
#6963 
1. Click on "Menu"
2. Expand "Endpoint security"
3. Click on "Malware Detection"
4. Select "Events" tab
5. Click on "«number» columns hidden"
6. Activate column "rule.groups"
7. See the result
> refactor: Update malware detection group values in data sources

- CHANGELOG.md
- plugins/main/public/components/agents/export-configuration.js
- plugins/main/public/controllers/management/components/management/configuration/configuration-settings.js
- plugins/main/public/utils/applications.ts
- plugins/main/public/utils/components-os-support.js
This pull request adds the Vulnerabilities detection and Office 365 links to the agent menu on the Endpoints summary application and fixes a problem of missing options depending on the agent operating system in the agent configuration report.
Side changes:
- Enhance the definition and management of unsupported modules by the agent operating system
#6972
Legend:
| With a Windows agent, go to agent overview from Endpoints Summary and ensure the Vulnerabilities detection and Office 365 links appear in the agent menu | :black_circle: | :black_circle: | :black_circle: |
| With a Linux agent, go to agent overview …
> Add Vulnerabilities Detection and Office 365 links to agent menu on Endpoints Summary

- CHANGELOG.md
- plugins/main/package.json
- plugins/main/yarn.lock
- plugins/wazuh-check-updates/package.json
- plugins/wazuh-core/package.json
Some vulnerabilities are resolved in follow-redirects >= 1.15.6
This PR adds and updates package.json in the plugins.
- https://github.com/wazuh/internal-devel-requests/issues/1533
- Check-update-plugin
```
node@osd:~/kbn/plugins/wazuh-check-updates$ cat yarn.lock | grep follow
follow-redirects "^1.15.6"
follow-redirects@^1.15.6:
resolved "https://registry.yarnpkg.com/follow-redirects/-/follow-redirects-1.15.6.tgz#[...]"
```
- Core-plugin
```
node@osd:~/kbn/plugins/wazuh-core$ cat yarn.lock | grep follow
follow-redirects "^1.15.6"
follow-redirects@^1.15.6:
resolved "https://registry.yarnpkg.com/follow-redirects/-/follow-redirects-1.15.6.tgz#[...]"
```
- Wazuh-plugin
```
node@osd:~/kbn/plugins/wazuh$ cat yarn.lock | grep follow
follow-redirects "^1.15.0"
follow-redirects "^1.15.6" …
```
> Changed follow redirects versions

- CHANGELOG.md
- plugins/main/public/styles/layout.scss
This PR aims to remove an unnecessary style that truncates the rows in the Discover plugin. As it is a style from the Wazuh plugin, it also makes the wazuh dashboard inconsistent, because if the user refreshes the page inside the Discover plugin, the style is not loaded. 
#6976 
**Before**
**After**
- Navigate to the discover plugin and confirm that the text is not truncated
- Verify that there are no broken pages after this change 
>[!NOTE]
>The text in Discover may be a little bit truncated as it is a problem that [is also present](https://playground.opensearch.org/app/data-explorer/discover#) in OpenSearch.
>[!NOTE]
>The size of the rows in the flyouts may be a little smaller, but the text should be completely legible
> Fix styles that truncates Discover plugin rows

- CHANGELOG.md
- plugins/main/public/components/common/data-grid/use-data-grid.ts
The Events tab has a column selector that shows all available columns. Selected columns appear in this selector, ordered alphabetically. This PR moves the selected columns to the beginning.
Additionally, add functionality to the table so that default columns maintain their position even when they are added or removed.
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6978
- Go to any app with event tabs
- Click on the columns selector and make sure that when a column is selected, it appears before the unselected columns
- Add and remove columns and check that appears first the default columns
> Columns-selector in events show firsts the picked columns

- CHANGELOG.md
- plugins/main/public/components/common/data-source/hooks/use-data-source.ts
- plugins/main/public/components/common/data-source/pattern/pattern-data-source.test.ts
- plugins/main/public/components/common/data-source/pattern/pattern-data-source.ts
- plugins/main/test/types/index.ts
Vulnerability dashboard not working for read-only user
#6985 
1. Create a readonly user following these steps https://documentation.wazuh.com/4.9/user-manual/user-administration/rbac.html
2. Ensure the Vulnerabilities detection in the Wazuh server is enabled and this can connect with the Wazuh indexer
3. Ensure the vulnerabilities states index was created
4. With a user with write permission on the selected tenant, go to Vulnerabilities Detection > Dashboard / Inventory, and it should create the index pattern
5. Login with the readonly user and go to Vulnerabilities Detection > Dashboard / Inventory.
6. The application should not be infinitely loading.
> Vulnerability dashboard error loading for read only user

- CHANGELOG.md
- plugins/main/public/components/endpoints-summary/agent/index.tsx
Style breaks when unpinned an agent in safari
#7011 
- Navigate to endpoint summary
- Click on an agent
- Unpinned the agent
> Style breaks when unpinned an agent in safari

- CHANGELOG.md
- plugins/main/public/controllers/management/components/management/reporting/utils/columns-main.js
- plugins/main/public/react-services/reporting.js
Fix when generating a PDF report, the open report button in safari does not work
#7018 
https://github.com/user-attachments/assets/fe9b1073-f442-489a-8b9c-99dd2244d17c
[Provide instructions to test this PR
- Go to some module
- Click on generate pdf report
- Click on open report button
> Fix when generating a PDF report, the open report button in safari does not work

- CHANGELOG.md
- plugins/wazuh-core/common/constants.ts
This pull request updates the PDF report footer date to the current year.
#7013 
- Generate a PDF report and check the default footer year
> Update PDF report year

- CHANGELOG.md
- plugins/main/public/components/common/search-bar/search-bar.tsx
When filtering by value in the datagrid used in the vulnerability module, the filter goes out of the viewport and cannot be closed.
#7017 
1. Open any application.
2. Apply any filter.
3. Edit the filter value to a longer text.
https://github.com/user-attachments/assets/3015191e-ef20-48de-9e1e-e1e3a5c496ff
> Filter expands outside the viewport and cannot be removed

- CHANGELOG.md
- plugins/main/common/constants.ts
- plugins/wazuh-core/common/constants.ts
This pull request removes the year from the PDF reports footer.
#7013
> Remove PDF report footer year

- CHANGELOG.md
- plugins/main/public/components/common/hocs/withAgentSync.tsx
- plugins/main/public/components/endpoints-summary/agent/index.tsx
This PR add a new hoc to controll the render of no-agent-alert when navigate to a agent-welcome page
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/7020
https://github.com/user-attachments/assets/2d2630b2-0c31-4b89-82e8-d267e5215b3a
When navigating to agent-welcome for the first time, the error appears. Try navigating from the endpoints summary, not just by clicking on the agents, but also using the side options to verify that the 'no agents' alert does not render.
> Fixed no agent alert spawn with selected agent in agent welcome

- CHANGELOG.md
- plugins/main/public/components/common/welcome/welcome.scss
- plugins/main/public/controllers/overview/components/__snapshots__/stats.test.tsx.snap
- plugins/main/public/controllers/overview/components/last-alerts-stat/last-alerts-stat.tsx
Text sizes: We want to increase the font size of the KPI subtitles and the features descriptions.
[#7027](https://github.com/wazuh/wazuh-dashboard-plugins/issues/7027) 
Go to Overview page and check the size of the KPI subtitles and the features descriptions
> Increase the font size of the kpi subtitles and the features descriptions

- CHANGELOG.md
- plugins/main/public/components/security/policies/edit-policy.tsx
The goal of this pull request is to filter deprecated / not listed actions in Wazuh API `/security/actions` endpoint. 
Closes #7031 
- Go to Server management -> Security -> Policies
- Click on the policy that has the `security:revoke` action
- Check it doesn't throw an exception
> Filter deprecated actions

- CHANGELOG.md
- plugins/main/public/components/common/data-grid/use-data-grid.tsx
This pull request fixes the relative index per page. Previously the absolute result index was used and the index was not found in the page array.
#7043
- Add vulnerabilities sample data
- Go to Vulnerabilities / Inventory
- Change between pages
- Verify it works and the information is consistent
> Fix data grid pagination with relative index per page

- CHANGELOG.md
- plugins/main/README.md
- plugins/main/common/wazuh-modules.ts
- plugins/main/public/utils/applications.ts
- Mitre feature: changed its current description by `Explore security alerts mapped to adversary tactics and techniques for better threat understanding.`
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/7027
- Check mitre overview description
> Changed Mitre overview description 

- CHANGELOG.md
- plugins/main/public/components/common/data-grid/data-grid-service.ts
This PR, adds the data sanitation for the export data.
Resolves #7030 
Add data to the vulnerabilities index with the following data:
```
Relative URLs starting with three slashes were incorrectly parsed, and a path-traversal "/../" part in the path could be used to override the specified host. This could contribute to security problems in web sites. This vulnerability affects Firefox < 120, Firefox ESR < 115.5.0, and Thunderbird < 115.5.
```
``` 
dsadsa
newline
```
To do this, we need to edit the Python injector script
- Go to the `Vulnerability Detection` >  `Inventory` tab
- Check if the data with the special characters are shown
- Click con `Export formatted` button
- Open the CSV downloaded in excel
- Check if the columns were correctly formatted. …
> Fix export formatted csv data with special characters from tables 

- CHANGELOG.md
- plugins/main/public/components/agents/fim/inventory.tsx
- plugins/main/public/components/agents/fim/inventory/fileDetail.tsx
- plugins/main/public/components/agents/fim/inventory/registry-table.tsx
- plugins/main/public/components/agents/fim/inventory/table.tsx
This pull request fixes the ability to filter from the FIM inventory details and add some enhancements.
Changes:
- Fix FIM inventory flyout filters for Files and Registry tabs
- Add ability to filter from Last analysis and Last modified fields from
Registry details
- Add ability to select the visible columns in the Files and Registry
tables
- Add to Files table the columns: date (hidden), md5 (hidden), sha1 (hidden), sha256 (hidden)
- Add to Registry table the columns: date (hidden)
- Renamed Last Modified to Last modified in the Files table
#7082
Legend:
| With FIM data in an agent, go to File Integrity …
> Fix ability to filter form FIM details

- CHANGELOG.md
- plugins/main/public/components/agents/syscollector/__snapshots__/inventory.test.tsx.snap
- plugins/main/public/components/agents/syscollector/columns/process-columns.ts
Remove processes state column in macOS agents.
Closes #7121
1. Go to Server Management > Endpoints Summary.
2. Choose a "macOS High Sierra agent."
3. Click on "Inventory Data."
4. Verify that the Processes table does not have a state column.
> Remove processes state column in macOS agents

- CHANGELOG.md
- plugins/main/public/components/overview/overview.tsx
- plugins/main/public/controllers/overview/components/stats.js
This pull request fixes the loading state of the home overview agents visualization.
- #7114 
https://github.com/user-attachments/assets/8319da0d-ad29-4c68-90f8-58a4816e7ccd
- Check agents visualization renders its loading when it's fetching the data
- Check the "No agents" prompt works properly
> Fix agents chart loading state

- CHANGELOG.md
- plugins/main/public/utils/applications.ts
Create an Agents management menu and move sections:
Endpoint Summary -> Change its name to Summary
Endpoint Groups
#7069 
Verify that the new Agent management section exists and that it contains the following sections inside: 
- Summary
- Endpoint Groups
> Create agents management menu and move sections

- CHANGELOG.md
- docker/imposter/wazuh-config.yml
- plugins/main/opensearch_dashboards.json
- plugins/main/package.json
- plugins/main/scripts/release/bump.js
- plugins/wazuh-check-updates/opensearch_dashboards.json
- plugins/wazuh-check-updates/package.json
- plugins/wazuh-core/opensearch_dashboards.json
- plugins/wazuh-core/package.json
This pull request bumps the version to 4.9.2 and revision to 00.
#7125
> Bump 4.9.2 rev 00

- CHANGELOG.md
- plugins/main/public/components/overview/vulnerabilities/dashboards/inventory/inventory.scss
This pull request removes the fixed height in the vulnerabilities inventory table so it can scroll with large pages and it's consistent with the Events table behavior.
- #7127 
- Check the table allows scrolling when the content of the page it's larger than the viewport
- Check that docking the side-nav doesn't cause nested scrolling or weird behaviors
- Check the table full-screen feature works properly and allows to navigate the results without rendering nested scrolls
> Fix vulnerability inventory table scroll

- CHANGELOG.md
- plugins/main/public/controllers/management/components/management/cdblists/views/list-editor.tsx
Added a function in CDB Lists that solve that all keys with multiple colons `:` should end with a quotation mark `"`.
- #7154 
>  When this PR gets code reviewed added lines are 99&100
> With a real manager
Go to Server Management > CDB Lists > `some list`
> Added ending quotes to CDB Lists keys

- CHANGELOG.md
- plugins/main/public/components/common/doc-viewer/doc-viewer.scss
Filters on event flyouts were not appearing in safari 
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/7157
<details><summary>Safari</summary>
</details> 
<details><summary>Firefox</summary>
</details> 
<details><summary>Chrome</summary>
</details> 
1. Navigate to "Threat Hunting"
2. Go to the Events tab
3. Click on the open row details
4. Hover in a row
> Fix filter by value in document details in safari

- CHANGELOG.md
- plugins/main/public/components/common/hooks/use-kbn-loading-indicator.ts
- plugins/main/public/components/wz-updates-notification/__snapshots__/index.test.tsx.snap
- plugins/main/public/components/wz-updates-notification/index.test.tsx
- plugins/main/public/components/wz-updates-notification/wz-updates-notification.tsx
- plugins/main/public/redux/render-with-redux-provider.tsx
- plugins/main/public/redux/store.js
- plugins/wazuh-core/common/constants.ts
This pull request adds the ability to edit the `wazuh.updates.disabled` setting from UI.
Changes:
- Add the ability to edit the `wazuh.updates.disabled` setting from UI.
- Fix a problem when the wazuh.updates.disabled setting was enabled, the UI was displayed
#7152
Legend:
| Go to Dashboard management > App Settings and ensure the wazuh.updates.disabled is displayed and can be configured (try to save both possible values). | :black_circle: | :black_circle: | :black_circle: |
| With wazuh.updates.disabled enabled (true), the UI related to check updates (bottom bar, data in Server APIs) should not appear. | …
> Add ability to edit the wazuh.updates.disabled setting from UI

- CHANGELOG.md
- plugins/main/public/components/endpoints-summary/register-agent/containers/register-agent/register-agent.scss
- plugins/main/public/components/endpoints-summary/register-agent/containers/register-agent/register-agent.tsx
Change the styles of the agent view so it does not look like a modal
- #7071
Navigate to register agent view and check changes
> Change register agent styles

- CHANGELOG.md
- plugins/main/public/components/agents/fim/inventory/fileDetail.tsx
This PR solves the problem when applying a date type filter by clicking on the fields of the FIM details flyout.
This problem only occurred in Firefox and Safari browsers.
Closes #7146
https://github.com/user-attachments/assets/c79b97c9-f2ca-43b9-9285-d700a357ae08
https://github.com/user-attachments/assets/17b90257-eb7c-462d-b0c7-3617071ec664
https://github.com/user-attachments/assets/e3f725ce-2863-475a-bc21-b35a7afd2feb
https://github.com/user-attachments/assets/7a47238f-5eb3-42f3-8347-91f90e782684
1. Go to File Integrity Monitoring > Inventory Tab
2. Select an Agent
3. Click on the File table row
4. Apply the date filter by clicking the add filter button in the header time field
5. Repeat test for Safari, Chrome and Firefox browsers
> Fixed Invalid date filter applied on FIM details flyout

- CHANGELOG.md
- plugins/main/public/utils/applications.ts
Reorder sections and rename endpoint groups
#7148
> Reorder sections and rename endpoint groups

- CHANGELOG.md
- plugins/main/public/components/agents/fim/inventory/fileDetail.tsx
- plugins/main/public/components/agents/fim/inventory/fim-data.tsx
- plugins/main/public/components/agents/fim/inventory/registry-table.tsx
- plugins/main/public/components/agents/fim/inventory/table.tsx
Solve inode not be rendered in FIM inventory view and move some constants to a common file.
- #7082 
> The global changes have affected the order. If a specific order is required, it can be fixed before merging the PR.
> Move fim data values to a common file

- CHANGELOG.md
- plugins/main/server/controllers/wazuh-api.ts
- plugins/main/server/lib/error-response.ts
- plugins/main/server/lib/extract-error-message.ts
This PR  resolves some cases when the wazuh logger receives an unexpected object and cannot log correctly the error message
Closes #7165
https://github.com/user-attachments/assets/a1ac33fc-e60c-400d-8ab3-7dc2b0539eb0
> Fixed error message to prevent pass no strings to the wazuh logger

- docker/README.md
- docker/osd-dev/README.md
- docker/osd-dev/dev.sh
- docker/osd-dev/dev.yml
This issue aims to improve the osd-dev script by adding:
- Take OpenSearch and OpenSearch dashboard versions from packages.json in core-plugin
- Add a flag to the script to manually add OpenSearch and OpenSearch dashboard versions
- Add a manage to imposter version in dev.sh
- Improve terminal response from script
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6962
> Improve dev environment script

- .github/workflows/dev-environment.yml
- .github/workflows/manual-build.yml
- scripts/test-packages/install-plugins.sh
- scripts/test-packages/osd-test-packages.Dockerfile
This pull request fixes the GitHub actions artifacts plugins name so that each plugin has its own name. 
- https://github.com/wazuh/wazuh-dashboard/issues/427
> Fix actions artifact plugins name

- .github/workflows/dev-environment.yml
- .github/workflows/manual-build.yml
- scripts/test-packages/install-plugins.sh
- scripts/test-packages/osd-test-packages.Dockerfile
This pull request adds the unzip package to the test plugins post workflow to fix the `unzip: command not found` error. It also adds support for dev branches that contain `/` in their name.
- https://github.com/wazuh/wazuh-dashboard/issues/430
https://github.com/wazuh/wazuh-dashboard-plugins/actions/runs/12055324147/job/33615734496
- Run the wazuh dashboard package build action and verify there's no error in the output.
> Unzip command not found in package generation action

- CHANGELOG.md
- plugins/main/public/controllers/management/components/management/cdblists/views/list-editor.test.tsx
- plugins/main/public/controllers/management/components/management/cdblists/views/list-editor.tsx
Fixes the rendering of the table as in some cases they were not rendering correctly.
For example: 
- “:key” was not rendering in the table.
And added validations in the inputs.
- #7166
1. Navigate to CDB list
2. Create CDB list with different keys
- `key:`
- `"key":key`
- `"key:":"key:"`
- `key1:"key:" `
3. The table should be rendered accordingly.
4. The keys and values in quotes must be at the beginning and at the end, not in the middle of the value.
> Support for CDB lists beginning with quotes

- CHANGELOG.md
- plugins/main/public/components/common/tables/__snapshots__/table-with-search-bar.test.tsx.snap
- plugins/main/public/components/common/tables/table-with-search-bar.test.tsx
- plugins/main/public/components/common/tables/table-with-search-bar.tsx
- plugins/main/public/components/search-bar/index.tsx
A timestamp has been added to handle when the same filter is added twice.
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/7124
https://github.com/user-attachments/assets/b42cedaf-6cc3-4f66-ba4d-a8db2158c62d
Check that adding a filter through the details flyout, deleting into the search-bar, and adding the same filter again, renders in the input of the search-bar.
> Fixed adding the same filter twice doesn't show it in the search bar.

- .github/workflows/eslint.yml
Ignore specific branches in ESLint workflow and simplify yarn commands
> Ignore specific branches in ESLint workflow and simplify yarn commands

- .eslintrc.js
- .github/actions/comment-test-coverage/README.md
- .github/workflows/codeql.yml
- .github/workflows/cypress-basic.yml
- .github/workflows/cypress-odfe.yml
- .github/workflows/cypress-wzd.yml
- .github/workflows/cypress-xpack.yml
- .github/workflows/dependency-review.yml
- .github/workflows/dev-environment.yml
- .github/workflows/eslint.yml
- .github/workflows/manual-build.yml
- .github/workflows/prettier.yml
- .github/workflows/wazuh-build-push-docker-action.yml
- plugins/main/server/controllers/wazuh-api.ts
- plugins/wazuh-core/common/constants.ts
- plugins/wazuh-core/common/services/settings-validator.ts
- plugins/wazuh-core/public/services/http/constants.ts
- plugins/wazuh-core/server/services/server-api-client.ts
- scripts/test-packages/install-plugins.sh
- scripts/test-packages/osd-test-packages.Dockerfile
This pull request merges 4.10.2 into master.
Manual build passed: https://github.com/wazuh/wazuh-dashboard-plugins/actions/runs/12353182189
Cherry-pick:
- 3186b3a349c6adbb1e3e90ece5e982190f52fa96
- 23b69cdb97f390d9ce9ae0190fba934e2cbb96b4
- 3fcf785aff538e765ab7e0e85c87f75360e5d407
- 3761a5879f059bc0328a19589f5afbfe21358358
#7198
> Merge 4.10.2 into master

- CHANGELOG.md
- plugins/wazuh-check-updates/server/plugin-services.ts
- plugins/wazuh-check-updates/server/services/updates/get-updates.test.ts
- plugins/wazuh-check-updates/server/services/updates/get-updates.ts
- plugins/wazuh-core/server/services/manage-hosts.ts
During https://github.com/wazuh/wazuh/issues/27183, it was found that Wazuh API version shown is not the current one after upgrading from v4.9.2 to v4.10.0-rc1
After cleaning the cache, the error is worse
**Expected behavior**
Wazuh API is v4.10.0
Closes https://github.com/wazuh/wazuh-dashboard/issues/440
1. Navigate to `Dashboard management` » `Server APIs`
2. Open DevTools
3. Go to `Application` » `Session storage`
4. Delete key `checkUpdates`
5. Reload the page
6. Please verify the status of the `Version` column under two scenarios: when everything is correct and when an issue arises.
> [!NOTE]
> Remove `checkUpdates` for each reloaded page.
> Shown Wazuh API version is wrong or empty after upgrade

- CHANGELOG.md
- plugins/main/public/components/common/doc-viewer/doc-viewer.tsx
- plugins/main/server/lib/generate-alerts/sample-data/authentication.js
This pull request adds content to the sample data field `data.win.system.message` and applies a style so it uses the 100% of the space available.
#7204
> Add full width to document detail fields

- CHANGELOG.md
- plugins/main/public/components/common/tables/__snapshots__/table-with-search-bar.test.tsx.snap
- plugins/main/public/controllers/management/components/management/configuration/office365/components/SubscriptionTab/__snapshots__/SubscriptionTab.test.tsx.snap
- plugins/main/public/controllers/management/components/management/configuration/office365/components/api-auth-tab/__snapshots__/api-auth-tab.test.tsx.snap
- plugins/main/public/controllers/management/components/management/configuration/office365/components/general-tab/__snapshots__/general-tab.test.tsx.snap
- plugins/wazuh-check-updates/server/plugin-services.ts
- plugins/wazuh-check-updates/server/services/updates/get-updates.test.ts
- plugins/wazuh-check-updates/server/services/updates/get-updates.ts
- plugins/wazuh-core/server/services/manage-hosts.ts
Merge 4.10.1 into 4.11.0
> [!CAUTION]
> Merge 4.10.1 into 4.11.0

- CHANGELOG.md
- plugins/main/public/components/settings/api/api-table.js
There's a typo in the available updates flyout, it says "Availabe updates" when it should be "available updates".
https://github.com/wazuh/wazuh-dashboard-plugins/issues/7234
1. Navigate to Server API's
2. Click on an API entry with updates in the "eye" button
3. See the fixed
> Fix typo in flyout title for available updates

- docker/osd-dev/dev.sh
Add a `start` command option to mimic the functionality of `docker compose start`
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/7238
```
~/wazuh-dashboard-plugins/docker/osd-dev(master)$ ./dev.sh /home/usuario/wazuh-dashboard-plugins/plugins up
[INFO] OS Version not received via flag, getting the version from ../../plugins/wazuh-core/package.json. Using: 2.18.0
[INFO] OSD Version not received via a flag, getting the version from ../../plugins/wazuh-core/package.json. Using: 2.18.0
[+] Running 14/14
✔ Network os-dev-2.18.0              Created                                                                                                                                                            0.0s 
✔ Volume "os-dev-2180_os_logs"       Created …
```
> Added start command option to dev.sh script

- CHANGELOG.md
- plugins/main/public/components/common/charts/visualizations/legend.tsx
- plugins/main/public/components/common/data-grid/use-data-grid.tsx
- plugins/main/public/components/common/tables/table-wz-api.tsx
- plugins/main/public/components/common/wazuh-data-grid/wz-data-grid.tsx
- plugins/main/public/components/common/wazuh-discover/components/data-grid-additional-controls.tsx
- plugins/main/public/components/common/wazuh-discover/components/visible-columns-selector.tsx
- plugins/main/public/components/common/wazuh-discover/wz-discover.tsx
- plugins/main/public/components/common/welcome/components/vuls_panel/vuls_welcome_panel.tsx
- plugins/main/public/components/management/cluster/components/overview_cards.tsx
- plugins/main/public/components/overview/vulnerabilities/dashboards/inventory/inventory.tsx
- plugins/main/public/components/settings/api/api-table.js
- plugins/main/public/controllers/overview/components/last-alerts-stat/last-alerts-stat.tsx
- plugins/main/public/react-services/format-number.ts
- plugins/main/public/styles/layout.scss
Merge 4.11.0 into 4.12.0
> [!CAUTION]
> Merge 4.11.0 into 4.12.0

- CHANGELOG.md
- plugins/main/package.json
This pull request removes the unused `node_build` property in the package manifest of main plugin.
#5351
> Remove unused node_build field in the package manifest of main plugin

- CHANGELOG.md
- plugins/main/public/components/endpoints-summary/register-agent/containers/steps/steps.tsx
The link to the documentation in the agent password step configuration is not properly defined.
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/7247
Enable the password authentication option by adding the configuration highlighted below to the `<auth>` section of the Wazuh server configuration file `/var/ossec/etc/ossec.conf`:
```
<auth>
<use_password>yes</use_password>
</auth>
```
- Navigate to Agents management > Summary
- Click on Deploy new agent
- The password step renders a documentation link
It must navigate to a correct documentation guide: 
- https://documentation.wazuh.com/4.10/user-manual/agent/agent-enrollment/security-options/using-password-authentication.html
> Repair agent deployment url to documentation

- CHANGELOG.md
- plugins/main/common/api-info/endpoints.json
- plugins/main/common/api-info/security-actions.json
- plugins/main/opensearch_dashboards.json
- plugins/main/package.json
- plugins/wazuh-check-updates/opensearch_dashboards.json
- plugins/wazuh-check-updates/package.json
- plugins/wazuh-core/opensearch_dashboards.json
- plugins/wazuh-core/package.json
This pull requests bumps to 4.11.0 rev 01.
#7260
> Bump 4.11.0 rev 01

- CHANGELOG.md
- plugins/wazuh-core/server/initialization/index-patterns-fields/fields-agent.json
- plugins/wazuh-core/server/initialization/index-patterns-fields/fields-alerts.json
- plugins/wazuh-core/server/initialization/index-patterns-fields/fields-commands.json
- plugins/wazuh-core/server/initialization/index-patterns-fields/fields-fim.json
- plugins/wazuh-core/server/initialization/index-patterns-fields/fields-hardware.json
- plugins/wazuh-core/server/initialization/index-patterns-fields/fields-hotfixes.json
- plugins/wazuh-core/server/initialization/index-patterns-fields/fields-networks.json
- plugins/wazuh-core/server/initialization/index-patterns-fields/fields-packages.json
- plugins/wazuh-core/server/initialization/index-patterns-fields/fields-ports.json
- plugins/wazuh-core/server/initialization/index-patterns-fields/fields-processes.json
- plugins/wazuh-core/server/initialization/index-patterns-fields/fields-scheduled-commands.json
- plugins/wazuh-core/server/initialization/index-patterns-fields/fields-system.json
- plugins/wazuh-core/server/initialization/index-patterns-fields/fields-vulnerabilities.json
- plugins/wazuh-core/server/plugin.ts
- scripts/indices-fields-mapping-to-index-pattern-fields/README.md
- scripts/indices-fields-mapping-to-index-pattern-fields/build-static-files/README.md
- scripts/indices-fields-mapping-to-index-pattern-fields/build-static-files/build-static-files-get-from-wildcard.js
- scripts/indices-fields-mapping-to-index-pattern-fields/build-static-files/build-static-files-transform-templates.js
- scripts/indices-fields-mapping-to-index-pattern-fields/build-static-files/lib.js
- scripts/indices-fields-mapping-to-index-pattern-fields/cli.js
- scripts/indices-fields-mapping-to-index-pattern-fields/map-template-to-index-pattern-fields.js
- scripts/lib/cli/cli.js
- scripts/lib/http.js
This pull request adds a initilization task related to index patterns:
- wazuh-agents*
- wazuh-alerts-5.x-*
- wazuh-commands*
- wazuh-states-fim*
- wazuh-states-inventory-hardware*
- wazuh-states-inventory-hostfixes*
- wazuh-states-inventory-networts
- wazuh-states-inventory-packages*
- wazuh-states-inventory-ports*
- wazuh-states-inventory-processes*
- wazuh-states-inventory-system*
- wazuh-states-vulnerabilities*
Moreover, the CLI gets information about the `.scheduled-commands`, but the index pattern data is not generated due to permissions of the Wazuh dashboard internal user.
Note: The pull request defines some hard-coded values that we should consider to do configurable and defines the initialization task in the same plugin and they could be defined in the related plugin instead. …
> Add tasks to initialize index patterns

- plugins/main/package.json
- plugins/main/yarn.lock
This PR upgrades the `ws` dependency to match the version used in OpenSearch Dashboards.
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/4b8826e7ffa6562825ca8aad676a8d89983c2d70/yarn.lock#L18087-L18090
It also upgrades `micromatch`, to be able to upgrade `braces` to 3.0.3
#7269
> Upgrade dependencies to match OpenSearch Dashboards

- .github/workflows/dev-environment.yml
- .github/workflows/manual-build.yml
- .github/workflows/playground.yml
- .github/workflows/unit-test.yml
- plugins/main/public/directives/wz-logtest/components/logtest.tsx
- plugins/main/scripts/generate-api-data.js
This pull request changes the `master` branch name references to `main`
#7277
> Change master branch references to main

- CHANGELOG.md
- plugins/main/common/services/web_documentation.test.ts
- plugins/main/public/components/agents/prompts/prompt-agent-never-connected.tsx
- plugins/main/public/controllers/management/components/management/configuration/alerts/alerts-labels.js
- plugins/main/public/controllers/management/components/management/configuration/client/client.js
- plugins/main/public/controllers/management/components/management/configuration/registration-service/registration-service.js
- plugins/wazuh-core/common/services/web_documentation.test.ts
This pull request fixes the agent check connection link and the agent labels link.
#7298 
- Add a new agent using the Server management dev tools
- Go to Agents management -> Summary
- Select the never connected agent
- Check the help link works as expected (Keep in mind 4.11 documentation is still not productive, so change the version number to 4.10)
- Go to Server Management -> Settings -> Alerts
- Click on the Labels tab
- Verify the help links work
- Go to Server Management -> Settings -> Registration service
- Click on the Labels tab
- Verify the help links work
> Add agent-management to help links

- .github/actions/comment-test-coverage/README.md
- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
- .github/workflows/dev-environment.yml
- .github/workflows/eslint.yml
- .github/workflows/manual-build.yml
- .github/workflows/prettier.yml
- .github/workflows/wazuh-build-push-docker-action.yml
This pull request updates our GitHub actions to use Ubuntu 24.04 image instead of latest. This is to prevent unexpected changes in the version of the image.
https://github.com/wazuh/wazuh-dashboard/issues/535
Check the actions don't throw any errors.
> Update GitHub actions to use Ubuntu 24.04

- CHANGELOG.md
- docker/imposter/vulnerability/vulnerabilities.json
- plugins/main/public/components/common/wazuh-discover/render-columns.tsx
- plugins/main/public/utils/known-fields.js
- plugins/main/server/lib/generate-alerts/sample-data/vulnerabilities.js
- scripts/vulnerabilities-events-injector/DIS_Template.json
- scripts/vulnerabilities-events-injector/dataInjectScript.py
Update the VD dashboard with the new field
#7300 
- Check the field `vulnerability.id` has a link where the href is the value in the field `vulnerability.scanner.reference`
- Check the field `vulnerability.scanner.reference` is a link in the inventory table and in the document details table
- Check the field `data.vulnerability.cve` has a link where the href is the value in the field `data.vulnerability.scanner.reference`
- Check the field `data.vulnerability.scanner.reference` is a link in the inventory table and in the document details table
> Update the VD dashboard with the new field

- CHANGELOG.md
- plugins/main/public/components/common/hocs/withAgentSync.tsx
- plugins/main/public/components/wz-agent-selector/wz-agent-selector-service.ts
This pull request updates the pinned agent state whenever the agent view initially loads. This ensures that if the agent changes its connection status then the related components show the latest change.
> [!NOTE]
> The agent data only updates the redux state when the agent view loads and then keeps using the redux state to avoid 
spamming requests to the Wazuh API.
#7329 
- Register 2 agents in a Wazuh manager
- Go to Endpoint summary
- Select agent 001 when it's active to enter the agent view
- Verify the agent is displayed as active
- Shut down the agent
- Go to Endpoint summary again
- Wait until the agent is displayed as disconnected
- Click on the previously selected agent to enter the agent view
- Check the agent state is disconnected
> Update pinned agent state

- docs/ref/getting-started/installation.md
This pull request changes in the installation documentation localhost:9200 to 127.0.0.1:9200 in the indexer connection to match the default opensearch_dashboard.yml configuration file.
https://github.com/wazuh/wazuh-dashboard-plugins/issues/7344
> Change localhost to 127.0.0.1

- CHANGELOG.md
This pull request removes the changelog entry for [this fix](https://github.com/wazuh/wazuh-dashboard-plugins/pull/7354) because a new PR has been merged for Wazuh 4.11.2. Therefore, the pull request made for 4.12.0 is no longer relevant.
https://github.com/wazuh/wazuh-dashboard-plugins/issues/7328
> Fix several documentation links - remove 4.12.0 changelog entry

- CHANGELOG.md
- plugins/wazuh-core/common/constants.ts
This pull request fixes the custom branding documentation link located in the App settings section. The documentation link for 4.11.x is:
https://documentation.wazuh.com/4.11/user-manual/wazuh-dashboard/custom-branding.html
#7328
> Fix custom branding documentation link

- CHANGELOG.md
- plugins/main/public/components/settings/about/__snapshots__/appInfo.test.tsx.snap
- plugins/main/public/components/settings/about/appInfo.test.tsx
- plugins/main/public/components/settings/about/appInfo.tsx
- plugins/main/public/components/settings/about/index.tsx
- plugins/main/public/components/settings/settings.tsx
- plugins/main/public/components/settings/types.ts
Remove the revision number from the About page, and adapt the type as the revision is removed.
- https://github.com/wazuh/wazuh-dashboard/issues/602
1. Navigate to About page
2. Check that the revision number does not appear
> Remove revision number from about page

- CHANGELOG.md
- plugins/main/server/start/monitoring/index.ts
This pull request fixes an infinite while loop when the monitoring agents fetching throws an exception.
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/7394
- Force an exception inside the monitoring cronjob while loop
- Check it logs the error in the console and breaks the loop
```console
server    log   [13:54:11.399] [info][listening] Server running at https://0.0.0.0:5601
server    log   [13:54:11.457] [info][server][OpenSearchDashboards][http] http server running at https://0.0.0.0:5601
server    log   [13:54:33.837] [error][monitoring][plugins][wazuh] ApiID: manager, Error request with offset/limit 500/500: test
server    log   [13:55:29.084] [error][monitoring][plugins][wazuh] ApiID: manager. Error: test
server    log   [13:55:29.406] [error][monitoring][plugins][wazuh] …
```
> Break while loop in case of exception

- tools/repository_bumper.sh
Adds an automatic step to update the changelog file when the repository version is bumped. Ensures the changelog accurately reflects the latest version changes.
https://github.com/wazuh/wazuh-dashboard-plugins/issues/7397
https://github.com/wazuh/wazuh-dashboard-plugins/pull/7402
https://github.com/wazuh/wazuh-dashboard-plugins/pull/7402
> Updates changelog during repository bump

- CHANGELOG.md
- plugins/main/public/components/overview/vulnerabilities/dashboards/overview/dashboard_panels.ts
This change improves the readability of the "Vulnerabilities by year of publication" chart in the vulnerability dashboard by changing the X-axis label from "vulnerability.published_at per year" to "Year published."
[#7422](https://github.com/wazuh/wazuh-dashboard-plugins/issues/7422)
To test this PR, follow these steps:
1. To view the visualization with test data, you can use the vulnerabilities events injection script:
```bash
cd scripts/vulnerabilities-events-injector
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
python3 dataInjectScript.py
```
2. Follow the script instructions to inject test data into your Wazuh-Indexer/Opensearch instance.
3. Navigate to the vulnerabilities dashboard and verify that the X-axis label in the "Vulnerabilities by year of …
> Change "Vulnerabilities by year of publication" visualization label - vulnerabilities dashboard

- .github/ISSUE_TEMPLATE/compatibility_request.md
- plugins/main/package.json
- plugins/main/yarn.lock
- plugins/wazuh-check-updates/package.json
- plugins/wazuh-check-updates/yarn.lock
- plugins/wazuh-core/package.json
- plugins/wazuh-core/yarn.lock
This PR upgrades the `cross-spawn` and `dompurify` dependencies to match the versions in Opensearch Dashboards.
#7428
> Upgrade `cross-spawn` and `dompurify`

- .github/workflows/dependency-review.yml
- .github/workflows/eslint.yml
- .github/workflows/prettier.yml
- .github/workflows/unit-test.yml
- CHANGELOG.md
- plugins/main/package.json
- plugins/main/yarn.lock
- plugins/wazuh-check-updates/package.json
- plugins/wazuh-check-updates/yarn.lock
- plugins/wazuh-core/package.json
- plugins/wazuh-core/yarn.lock
This pull request adds the compatibility with OpenSearch Dashboards 2.19.2.
#7411
> Compatibility with opensearch 2.19.2

- CHANGELOG.md
- plugins/main/public/components/endpoints-summary/register-agent/containers/register-agent/register-agent.tsx
This PR implements a navigation button in the agent registration wizard (Deploy new agent) that allows users to return directly to the agent summary view (Endpoints Summary).
Changes:
- Added a button with an arrow icon to the top left of the agent log panel.
- The button always redirects the user to the agent summary view ( /agents-preview ).
- Implemented following the existing design pattern in other sections of the application.
Initially, the issue proposed adding a conditional button that would only appear when at least one agent was registered. However, after discussion with the team, it was decided that the button should always be present and consistently redirect to the agent summary view, regardless of browsing history or the number of registered agents. This provides a more …
> Add back button to endpoints summary

- CHANGELOG.md
- plugins/main/server/lib/sample-data/dataset/shared-utils.js
This pull request fixes the `wazuh.cluster.name` field is not set with the expected value when the server is in manager mode.
#7369
> Fix wazuh.cluster.name field in sample data of IT Hygiene, FIM and vulnerabilites

- CHANGELOG.md
- docker/imposter/api-info/api_info.json
- docker/imposter/wazuh-config.yml
- plugins/main/opensearch_dashboards.json
- plugins/main/package.json
- plugins/wazuh-check-updates/opensearch_dashboards.json
- plugins/wazuh-check-updates/package.json
- plugins/wazuh-core/opensearch_dashboards.json
- plugins/wazuh-core/package.json
This pull request bumps the version to 4.10.3 to support a new Wazuh version.
#7457
> Support wazuh 4.10.3

- CHANGELOG.md
- plugins/main/public/components/common/hocs/with-index-pattern.tsx
- plugins/main/public/components/overview/it-hygiene/common/hocs/validate-system-inventory-index-pattern.tsx
- plugins/main/public/components/overview/it-hygiene/common/saved-vis/generators.ts
- plugins/main/public/components/overview/it-hygiene/dashboards/dashboard-kpi.ts
- plugins/main/public/components/overview/it-hygiene/networks/inventories/interfaces/dashboard.ts
- plugins/main/public/components/overview/it-hygiene/packages/inventories/packages/managed-filters.ts
- plugins/main/public/components/overview/it-hygiene/packages/inventories/packages/table-columns.ts
- plugins/main/public/components/overview/it-hygiene/processes/inventories/processes/dashboard.ts
- plugins/main/public/components/overview/it-hygiene/system/inventories/hardware/inventory.tsx
- plugins/main/public/components/overview/it-hygiene/system/inventories/hardware/managed-filters.ts
This pull request 
- Remove Arhitecture selector from System > Hardware
- Remove `package.architecture` as default column in Packages > Packages
- Replace States viualization ain IT Hygiene > Dashboard and Processes > Processses
- Fix visualization of Global packets loss rate
#7450
Legend:
| Ensure there is no Arhitecture selector in System > Hardware | :black_circle: | :black_circle: | :black_circle: |
| Ensure the package.architecture field is not set as default column in of the table in Packages > Packages | :black_circle: | :black_circle: | :black_circle: |
| Ensure the visualization of Global packets loss …
> Fix some problems related to IT Hygiene

- CHANGELOG.md
- docker/imposter/rules/rules.js
- docker/imposter/rules/rules.json
- docker/imposter/wazuh-config.yml
- plugins/main/public/controllers/management/components/management/ruleset/views/rule-info.tsx
This PR fixes a bug on which the Rule details flyout doesn't show all the compliances. It also adds a new rule in the `/rules` imposter response, which contains all possible compliances (data extracted from a real manager).
#7497
**Before**
**After**
- Navigate to Rules
- Click on a Rule
- Validate that it shows all the compliances
> Fix rule details flyout to show all compliances

- .github/workflows/build.yml
- .github/workflows/dev-environment.yml
- .github/workflows/manual-build.yml
- .github/workflows/unit-test.yml
This pull request restricts GitHub workflow permissions to a minimum. 
- Verify al tests pass
- Verify the package building process works as expected
> Restrict GitHub workflows permission

- .github/workflows/6_builderpackage_on-update-tags.yml
- .github/workflows/6_builderpackage_plugins.yml
- .github/workflows/6_testunit_jest.yml
This pull request fixes a PR write permission in the package building workflow.
https://github.com/wazuh/wazuh-dashboard/actions/runs/15706212470
> Add PR write permission

- .github/workflows/6_builderprecompiled_base-dev-environment.yml
- .github/workflows/dev-environment.yml
- docker/osd-dev/dev.sh
This PR implements automatic version concatenation for development environments and workflows to use Docker images with the combined version format `<Opensearch version>-<Wazuh version>` (e.g., `3.0.0-5.0.0`). This change ensures consistency across different development environments and allows for better version management when working with multiple OpenSearch and Wazuh versions simultaneously.
- **Updated `docker/osd-dev/dev.sh`**: Added automatic version concatenation when no `-d` flag is provided
- Retrieves OpenSearch version from `pluginPlatform.version` in package.json
- Retrieves Wazuh version from `version` in package.json
- Concatenates versions in format: `<Opensearch version>-<Wazuh version>`
- Added proper logging to show the combined version being used
- **Modified GitHub …
> Update development environments to use combined version format <Opensearch version>-<Wazuh version>

- CHANGELOG.md
- docker/imposter/agents/configuration/syscheck-syscheck.json
- plugins/main/public/controllers/management/components/management/configuration/integrity-monitoring/integrity-monitoring-who-data.js
- plugins/main/server/lib/reporting/agent-configuration.ts
Fixed missing `provider` and `queue_size` fields in whodata configuration
- https://github.com/wazuh/wazuh-dashboard/issues/800
1. Go to Endpoints summary > some agent > Configuration
2. Click on Integrity monitoring > Who-data (Windows agents do not have Who-data tab)
3. The provider and queue_size field should appear.
> Missing fields are added to `whodata` configuration

- CHANGELOG.md
- plugins/main/common/constants.ts
- plugins/main/public/components/common/data-source/pattern/fim/data-source-repository.ts
- plugins/main/public/components/common/data-source/pattern/fim/data-source.ts
- plugins/main/public/components/overview/fim/common/hocs/validate-fim-states-index-pattern.tsx
- plugins/main/public/components/overview/fim/inventory/inventories/registry-keys/inventory.tsx
- plugins/main/public/components/overview/fim/inventory/inventories/registry-values/inventory.tsx
- plugins/main/server/lib/sample-data/dataset/states-fim-files/main.js
- plugins/main/server/lib/sample-data/dataset/states-fim-registry-keys/main.js
- plugins/main/server/lib/sample-data/dataset/states-fim-registry-keys/template.json
- plugins/main/server/lib/sample-data/dataset/states-fim-registry-values/main.js
- plugins/main/server/lib/sample-data/dataset/states-fim-registry-values/template.json
- plugins/main/server/lib/sample-data/lib/random.js
This pull request applies changes in the FIM data.
It splits the FIM registry data into 2 index patterns:
- wazuh-states-inventory-registry-keys-*
- wazuh-states-inventory-registry-values-*
Add/remove some fields
- Split the registry index into 2 indices:
- registry-keys
- Add `checksum.hash.sha1`
- Add `registry.permissions`
- Remove `event`
- registry-values
- Add `checksum.hash.sha1`
- Remove `event`
- Remove the managed filter using `event.category` field in Registry
keys and Registry values tabs of File Integrity Monitoring > Inventory
- Adapted the index pattern in File Integrity Monitoring > Inventory > Registry keys and Registry values
to using separate index pattern: wazuh-states-inventory-registry-keys-* and wazuh-states-inventory-registry-values-*
- Change fields in the sample …
> Change fields in FIM indices and split the Registry data into 2 index patterns

- plugins/main/public/components/common/data-source/pattern/system-inventory/data-source-repository.ts
- plugins/main/public/components/overview/it-hygiene/common/hocs/validate-system-inventory-index-pattern.tsx
- This pull request restores code that was mistakenly deleted from the `4.14.0` branch during the scheduled upward merges ([Issue](https://github.com/wazuh/wazuh-dashboard-plugins/issues/7614)).
- Restore code from IT hygiene > network > traffic. This code was part of this [PR](https://github.com/wazuh/wazuh-dashboard-plugins/pull/7588)
https://github.com/wazuh/wazuh-dashboard-plugins/issues/7614
- Verify that the app does not stay blank.
- Go to IT Hygiene > Networks > Traffic and verify that all works properly.
> Fix exports

- CHANGELOG.md
- plugins/main/server/lib/reporting/printer.ts
This PR adds logic to split the long words into several lines, to prevent the table overflowing the page in PDF reports
#7609
Navigate to File Integrity Monitoring, click on "Generate Report", and verify that the long strings in the columns (most likely in the `path`) are split into different lines.
> Prevent column overflow page in PDF reports

- CHANGELOG.md
- docker/imposter/agents/configuration/syscheck-syscheck.json
- plugins/main/public/controllers/management/components/management/configuration/integrity-monitoring/integrity-monitoring-file-limit.js
- plugins/main/public/controllers/management/components/management/configuration/integrity-monitoring/integrity-monitoring-registry-limit.js
This PR resolves terminology confusion in the Integrity monitoring configuration interface by:
- **Registry limit section**: Changed "File limit status" label to "Registry limit status" to avoid confusion with file monitoring
- **Files limit section**: Changed title from "Registry limit" to "Files limit" and updated description to reference "files" instead of "registries"
- **Component names**: Corrected class names to match their actual functionality:
- `WzConfigurationIntegrityMonitoringRegistryLimit` for registry limit configuration
- `WzConfigurationIntegrityMonitoringFileLimit` for file limit configuration
- **Constants**: Updated property names to be more descriptive (`REGISTRY_LIMIT_PROP` vs `FILE_LIMIT_PROP`)
These changes ensure that users can clearly distinguish between file …
>  Fix confusing terms in Integrity monitoring settings and update component names for clarity

- CHANGELOG.md
- plugins/main/common/wazuh-modules.ts
- plugins/main/public/components/add-modules-data/sample-data.tsx
- plugins/main/public/components/common/modules/modules-defaults.tsx
- plugins/main/public/utils/applications.ts
Azure module name changed to Microsoft Graph API
- #7658 
In the sample data, overview and Microsoft Graph API view, the Azure name should have changed to Microsoft Graph API.
> Rename Azure dashboard to Microsoft graph api

- CHANGELOG.md
- plugins/main/public/components/common/reload-cluster-manager-callout.tsx
- plugins/main/public/controllers/management/components/management/configuration/utils/wz-fetch.js
Fix the endpoint path that saves any modifications to the rule set.
The endpoint to reload the rule set changes depending on whether cluster mode is enabled or not.
- Enabled: `PUT cluster/analysisd/reload`
- Disabled: `PUT manager/analysisd/reload`
[reference here](https://github.com/wazuh/wazuh/pull/31459).
https://github.com/wazuh/wazuh-dashboard-plugins/issues/7653
https://github.com/user-attachments/assets/6bf0343a-fff5-419f-b6b2-f4ac7034b303
> Fix endpoint to add reload ruleset button

- CHANGELOG.md
- plugins/main/server/lib/sample-data/dataset/states-inventory-browser-extensions/main.js
- plugins/main/server/lib/sample-data/dataset/states-inventory-browser-extensions/template.json
The Browser extension template is updated according to the [Pull request](https://github.com/wazuh/wazuh/pull/31608), and the sample data is modified according to the template.
- #7627 
Add sample data from IT hygiene, then navigate to the IT hygiene > Browser extensions view, and there should be a package.visible column, package.persmissions should be an array and package.installed should be a date.
> Update Browser extension template and sample data

- CHANGELOG.md
The changelog entry about removing the cluster restart was replaced with an entry about adding a restart button.
https://github.com/wazuh/wazuh-dashboard-plugins/issues/7653
> Fix changelog entries: Add "Reload ruleset" button

- CHANGELOG.md
- plugins/main/public/components/endpoints-summary/services/get-agents-info.test.ts
- plugins/main/public/components/endpoints-summary/services/get-agents-info.ts
This pull request sorts the Top 5 groups by agent count.
https://github.com/wazuh/wazuh-dashboard-plugins/issues/7782
- Create several groups with different amounts of agents assigned
- Verify the Top 5 groups visualization is sorted by agent count
> Sort top 5 groups visualization by agent count

- CHANGELOG.md
- plugins/main/public/components/overview/it-hygiene/users/inventories/users/dashboard.ts
This pull request replaces the Top 5 user auth failures count visualization from the `Identity` > `Users` with the "Top 5 users" visualization.
Closes https://github.com/wazuh/wazuh-dashboard-plugins/issues/7786
- Check "Top 5 user auth failures count visualization" has been replaced with the "Top 5 users" visualization.
> Replace top 5 user auth failures count visualization
