wazuh/wazuh-dashboard-plugins

- public/app.js
- public/less/agents.less
- public/less/common.less
- public/less/kbn.less
- public/less/loader.js
- public/less/main.less
- public/less/manager.less
- public/less/media-queries.less
- public/less/ruleset.less
Also created a `loader` of the `. less` files
> Separating `. less` files to better organize style sheets.

- public/less/common.less
- public/templates/agents-preview.html
- public/templates/groups-preview.html
• Also now we can click in any field of the agent to go to the main agent view.
• Fix sorting by column in agents tab
> Agents and files sortable in groups tab

- public/controllers/common/factories.js
Now you can build new factories based on DataHandler just using a path as bellow:
```js
const groups   = DataHandler => compose(DataHandler,'/agents/groups');
const agents   = DataHandler => compose(DataHandler,'/agents');
const logs     = DataHandler => compose(DataHandler, '/manager/logs');
const rules    = DataHandler => compose(DataHandler, '/rules');
const decoders = DataHandler => compose(DataHandler, '/decoders');
const simple   = DataHandler => new DataHandler();
```
> Optimized factories that are using data handler service

- public/controllers/agentsPreview.js
- public/controllers/common/directives.js
- public/controllers/manager.js
- public/controllers/ruleset.js
- public/kibana-integrations/kibanaDiscoverDirective.js
- public/services/dataHandler.js
- public/services/genericReq.js
- public/templates/agents-preview.html
- public/templates/agents.head
- public/templates/discover.head
- public/templates/groups-preview.html
- public/templates/manager.head
- public/templates/overview.head
- public/templates/ruleset-decoders.html
- public/templates/ruleset-rules.html
- server/initialize.js
Summary:
- Common menu items are now a directive
- Removed some console.log for better performance
- New function in DataHandler to get a filter value from a filter name
- Ruleset template - rules uses getFilter function from DataHandler
- Fixed last agent in agents tab
- Fixed when-scroll directive in multiple tabs
- Fixed "Last registered agent" in Agents tab
> 3.0-dev-ruleset-filters

- public/controllers/manager.js
- public/controllers/overview.js
- public/services/appState.js
- public/templates/manager-status.html
Summary:
- Removed unused methods from appState
- Fix the last agent information on manager - status tab
- In manager - status, don't show keep alive date in last registered agent if it is the manager
> Removed unused appState $cookies

- index.js
- public/app.js
- public/kibana-integrations/kibanaSearchbarDirective.js
- public/kibana-integrations/kibanaVisualizationDirective.js
- public/less/kbn.less
- public/templates/overview-general.html
- New searchbar.
- New visualization directive.
> Kibana integrations rebrand foundation

- public/less/main.less
- public/templates/ruleset-decoders.html
- public/templates/ruleset-rules.html
Changed the style from the Settings tab buttons and the Manager/Ruleset tab buttons.
> Fixed CSS from some buttons

- public/controllers/agentsPreview.js
Agents preview is now faster. Also I noticed a duplicated api call that was inneccessary. Improved way to request data.
> Enhacements in agents loading. Removed unneccessary extra api call

- public/controllers/agents.js
- public/controllers/overview.js
- public/kibana-integrations/kibanaDiscoverDirective.js
- public/services/routes.js
- public/templates/agents-audit.html
- public/templates/agents-fim.html
- public/templates/agents-oscap.html
- public/templates/agents-overview.html
- public/templates/agents-pci.html
- public/templates/agents-pm.html
- public/templates/agents.head
- public/templates/directives/kibana-filterpill-template.html
- public/templates/discover.html
- public/templates/overview-audit.html
- server/integration_files/app_objects_file_alerts.json
- Adapting the agents tab for the new discover directive.
- Fixing redirections and filter creations because of some timing issues with the directives.
> 3.0 new discover agents

- public/less/manager.less
- public/less/wazuh-navbar.less
- public/services/dataHandler.js
- public/templates/ruleset-decoders.html
There was a little problem with the offset of the datahandler when there is an offset bigger than total number of items in the first request, now is fixed. Also fixes some md-chips style issues.
> Fixed ruleset issue with the offset of items. Also fix md-chips

- public/less/buttons.less
- public/less/kbn.less
- public/less/main.less
- public/less/not-used.less
- public/templates/agents.head
* The index selector from our Discover tab doesn't resize oddly.
* The Manager/Ruleset buttons are clearing showing what the current sub-tab is opened.
* The pointer is now default when hovering a metric visualization
* The Panels/Discover buttons now change color correctly according to the hover and current section.
* Fixed the Discover icon not appearing on the Agents/Overview section.
(Sorry about the huge cursor, it's a problem with my 4k display).
> 3.0 several CSS fixes

- public/controllers/agents.js
- public/controllers/overview.js
- public/controllers/settings.js
- public/services/dataHandler.js
- Replaced some angular.forEach loops by native loops
- Better and shorter removeFilter function on datahandler
> Some loops enhacements

- public/less/buttons.less
- public/less/manager.less
- public/templates/manager-osseclog.html
> Manager/Logs CSS bugfixes

- public/controllers/agents.js
- public/kibana-integrations/kibanaDiscoverDirective.js
- public/kibana-integrations/kibanaVisualizationDirective.js
- public/less/kbn.less
- public/less/loader.js
- public/services/routes.js
- public/templates/agents.head
- public/templates/groups-preview.html
- Tooltip color.
- Agent head description show status.
- Unique index-pattern load.
- Proper theming import from Kibana.
...
> Several minor fixes

- public/controllers/agents.js
- public/controllers/agentsPreview.js
- public/controllers/groups.js
- public/templates/settings.html
- Change top menu on settings tab
- Sending only agent id to rootScope from agents and groups tabs
> Settings fix

- public/controllers/ruleset.js
- public/services/routes.js
- public/templates/manager.jade
- public/templates/ruleset-decoders.html
- public/templates/ruleset-rules.html
- public/templates/settings.html
- server/api/wazuh-api.js
- Check if the API is down when starting the app, if the API is down we force the user stay on settings tab and show help messages to handle this situation.
- The error is also catched from back-end to front-end
- This PR also fix the decoders and the rules tables on manager/ruleset
- Added rule level filter on ruleset tab
> Fix API is down situation

- public/less/kbn.less
- public/less/manager.less
- public/less/overview.less
- public/templates/agents-general.html
- public/templates/overview-fim.html
* Fixed width and height of some visualizations
* More width fixes in Manager/FIM
* Fixed Manager/Logs input filter box
> Firefox 57 bugfixes

- package.json
- public/app.js
- public/controllers/agentsPreview.js
- public/controllers/settings.js
- public/kibana-integrations/kibanaDiscoverDirective.js
- public/kibana-integrations/kibanaVisualizationDirective.js
- public/services/appState.js
- public/services/implicitFilters.js
- public/services/routes.js
- public/templates/settings.html
- server/api/wazuh-api.js
- server/api/wazuh-elastic.js
- server/initialize.js
Enhancements:
- Adding the possibility to change the initial index-pattern by using the indexPattern field in the package.json.
- Adding the possibility to dynamically change the index-pattern under settings->pattern.
Minor fixes:
- Apply implicit filters at visualizations startup.
> Enchancement: dynamic index-patterns, plus minor fixes

- public/less/main.less
- public/templates/groups-preview.html
- public/templates/overview-fim.html
This PR fixes the following bugs:
* Events Summary table from Overview/FIM
* Manager/Groups Agents table
* Manager/Logs table header padding
> More bugfixes for Firefox

- public/controllers/agents.js
- public/controllers/groups.js
- public/controllers/manager.js
- public/controllers/osseclog.js
- public/controllers/overview.js
- public/controllers/ruleset.js
- public/services/dataHandler.js
- public/services/routes.js
- public/templates/agents-general.html
- public/templates/manager-osseclog.html
This PR fix the bellow list:
- Logs table are now sortable by all fields except description
- Removed unneccessaries tooltips (redundant information)
- Added `.catch` statement to catch errors in multiple places where were not being catched.
```js
foo()
.then(() => { ... })
.catch(error => notify.error(error.message));
```
> Minor enhacements dev

- public/templates/agents-audit.html
- public/templates/agents-fim.html
- public/templates/agents-general.html
- public/templates/agents-oscap.html
- public/templates/agents-pci.html
- public/templates/agents-pm.html
- public/templates/overview-audit.html
- public/templates/overview-fim.html
- public/templates/overview-general.html
- public/templates/overview-oscap.html
- public/templates/overview-pci.html
- public/templates/overview-pm.html
This PR fixes a very annoying bug in Safari, specially visible on small screens.
> Fixed app viewport in Safari

- public/controllers/agents.js
- public/controllers/groups.js
- public/services/dataHandler.js
- public/templates/agents-general.html
- There is a new card on the agent view to show its group
- Now it's possible to click on the group card from an agent and go to the groups section
- The boolean to check if groups section is loading is now in the right place
- If you come from an agent to groups section, the opened group is the agent group
Hope it helps :+1:
> New logic on groups controller

- server/api/wazuh-elastic.js
- server/initialize.js
- server/monitoring.js
- Upgrading process for Wazuh app.
- From 2.x-5.x
- From 3.x-5.x
> Automatic .wazuh upgrading

- package.json
- public/controllers/settings.js
- public/less/agents.less
- public/less/kbn.less
- public/less/overview.less
- public/templates/agents-audit.html
- public/templates/overview-audit.html
- public/templates/overview-fim.html
- public/templates/overview-general.html
- Metric visualizations changed due to changes in Kibana.
> Adapting for Kibana 6.0.1

- public/controllers/agents.js
- public/templates/agents-overview.html
- Syscheck and Rootcheck dates are now properly handled
- Also checks if a scan is currently in progress
> 2.1 fix syscheck rootcheck

- public/controllers/agents.js
- public/controllers/common/directives.js
- public/controllers/common/factories.js
- public/controllers/ruleset.js
- public/services/dataHandler.js
- public/templates/agents.head
- public/templates/ruleset-decoders.html
- public/templates/ruleset-rules.html
Affected "autocompletes":
- Ruleset/Rules
- Ruleset/Decoders
- Agents
Fixed features:
- Search by any term
- Next page of data when scroll
- Search with lucene syntax (eg. group: syslog)
- Can press "Enter" key to set a filter
> Fix autocomplete

- package.json
- public/kibana-integrations/kibanaDiscoverDirective.js
- public/less/agents.less
- public/less/kbn.less
- public/less/overview.less
- public/templates/agents-audit.html
- public/templates/agents-fim.html
- public/templates/agents-general.html
- public/templates/agents-oscap.html
- public/templates/agents-pci.html
- public/templates/agents-pm.html
- public/templates/directives/kibana-discover-template.html
- public/templates/discover.html
- public/templates/overview-audit.html
- public/templates/overview-fim.html
- public/templates/overview-general.html
- public/templates/overview-oscap.html
- public/templates/overview-pci.html
- public/templates/overview-pm.html
- server/initialize.js
Adapting the Wazuh app plugin for Kibana 6.1.0:
- Now the .kibana index isn't created automatically by Kibana on startup -> we detect if it exists and, if it doesn't, we create it.
- New sizes for metric visualizations -> Kibana has gone back to an older implementation of this visualization type, thus the readjustment.
- New styles to overcome the overflow in the visualizations.
> 3.0 kibana 6.1.0

- server/initialize.js
- server/integration_files/kibana_template.json
Checking when .kibana is not present and, before creating it, inserting a proper template for it.
> Inserting .kibana template when missing

- public/controllers/agentsPreview.js
- public/controllers/settings.js
- server/api/wazuh-api-elastic.js
- Validating form fields when adding a new API (**frontend**)
- Validating form fields when adding a new API (**backend**)
- Fix wrong line getting manager info
> 3.0 Regex validations

- public/controllers/settings.js
This PR makes extensions working again.
There's a known bug in the frontend when you enable/disable extensions and just after that you change to another API from the list. The workaround is to reload the page after selecting the new API.
> Fixed extensions not working

- server/initialize.js
- server/monitoring.js
Changing index-pattern ids for something more semantic.
> Proper index-pattern ids

- public/controllers/settings.js
- public/services/testAPI.js
Summary:
- Solved an error ocurred when you try to connect to the API through `https` and it's not under https
- Removed wrong code and rewritten `checkManager` function code
- More error situations are now properly handled
- Minor JS optimizations
> Some API fixes

- public/controllers/ruleset.js
> Enabled searching by term and press enter

- public/controllers/common/directives.js
- public/controllers/settings.js
- public/less/heights.less
- public/templates/agents/agents-fim.html
- public/templates/agents/agents-general.html
- public/templates/agents/agents-pm.html
- public/templates/directives/menu-top.html
- public/templates/overview/overview-fim.html
- public/templates/overview/overview-general.html
- public/templates/overview/overview-pm.html
This PR:
* Fixes the bug where some charts don't show properly the pagination due to the height of the boxes.
* Adds the currently selected index-pattern on the top menu bar of the app.
> 3.1 minor style bugfixes

- public/controllers/common/directives.js
- server/initialize.js
- App updates wazuh-version information regarding version and revision per initialization. This provides useful data to perform API version checks.
- Using the index-pattern title instead of id when showing data in the upper right corner of the screen while navigating.
> Updating version information on startup and using pattern title in display

- public/controllers/settings.js
- public/kibana-integrations/kibanaVisualizationDirective.js
- public/less/ruleset.less
- public/templates/agents/agents.head
- public/templates/manager/ruleset/ruleset-decoders.html
- public/templates/manager/ruleset/ruleset-rules.html
- Fixes extensions
- Minor error on agents view
- Fixes minor errors on ruleset view
> Multiple fixes

- public/templates/agents/agents-oscap.html
-Reordering splitting sections in Kibana visualizations as they were hindering legend size options.
> Updating visualizations name

- server/api/wazuh-elastic.js
- server/initialize.js
- Better analysis for template resolution.
> Improving template health check

- public/services/routes.js
- public/templates/agents/agents-oscap.html
- server/api/wazuh-elastic.js
- Getting current pattern used from actual visualizations.
> 3.1 fix pattern

- public/less/agents.less
- public/less/buttons.less
- public/less/main.less
- public/less/ruleset.less
- public/templates/overview/overview-audit.html
This pull request fixes some bugs **related to the CSS and the visualizations**, such as:
* Unified colours across the whole app.
* Fix the readability issues with some text.
* Fix the width of some visualizations who doesn't show properly on small screens.
> More CSS bugfixes

- public/controllers/settings.js
- server/api/wazuh-api-elastic.js
- `/^[a-zA-Z0-9]{3,100}$/` is now `/^.{3,100}$/` (any character, min length: 3)
> Regular user expression is now less restrictive

- public/less/agents.less
- public/less/buttons.less
- public/less/main.less
- public/less/ruleset.less
- public/templates/overview/overview-audit.html
This pull request fixes some bugs **related to the CSS and the visualizations**, such as:
* Unified colours across the whole app.
* Fix the readability issues with some text.
* Fix the width of some visualizations who doesn't show properly on small screens.
> (Fixed) More CSS bugfixes

- public/controllers/agents.js
- public/controllers/overview.js
- public/templates/agents/agents-aws.html
- public/templates/overview/overview-aws.html
- server/integration_files/app_objects_file_alerts.json
This PR adds a brand-new extension for the Wazuh App: **Amazon Web Services (AWS)**. This extension shows alerts related with Amazon instances, security groups, and more.
The extension is available in both `Overview` and `Agent` tabs, and can be disabled or enabled just like the other extensions on the `Settings` tab.
> New AWS extension

- public/controllers/agents.js
- public/controllers/overview.js
- public/templates/agents/agents-aws.html
- public/templates/overview/overview-aws.html
- server/integration_files/app_objects_file_alerts.json
This PR modified the first iteration of the AWS tab and removes old visualizations, and add new ones.
> New visualizations overhaul for AWS

- public/controllers/healthCheck.js
- public/services/routes.js
- public/templates/health-check/health-check.html
- Improving heatlh check view.
- Disabling health-check from settings tab.
> Improving health-check and redirections

- public/app.js
- public/controllers/common/directives.js
- public/controllers/settings.js
- public/less/angular-md.less
- public/services/patternHandler.js
- public/services/routes.js
- public/templates/directives/menu-top.html
- public/templates/manager/manager-configuration.html
Hello,
This PR adds **an index-pattern selector** on the upper right corner of the app, next to the `Settings` button.
It works the same as the current selector on the `Settings` page. The app implements now a new Service called `patternHandler`, which will provide the functionality for changing the index-pattern.
In addition, this PR adds `logall_json` to Manager/Configuration.
> New index pattern selector on the navbar

- public/controllers/common/directives.js
- public/controllers/settings.js
- public/services/patternHandler.js
This pull request fixes the following mistakes:
- Pattern handler service because it was not implemented fine due to a wrong use of the promises. 
- Typo on settings.js 
- The menu-top directive is reimplemented in order to work properly with the pattern selector.
> Patch index pattern selector

- public/less/tables.less
- public/templates/manager/groups/groups-preview.html
This PR fixes minor mistakes on groups view.
> Groups patch

- package.json
This PR brings the following features to branch 3.1:
- Adapting Kibana 6.1.3.
> Adapting Kibana 6.1.3

- server/integration_files/app_objects_file_alerts.json
- server/integration_files/objects_file.json
Hi,
This PR modified some visualizations who were not showing the correct information. Mainly, they were FIM metric visualizations, and some old visualizations available at `Visualize`.
> Fixed some FIM and Dashboard visualizations

- CHANGELOG.md
Hello,
This PR modified the `CHANGELOG.md` and adds the release notes for **Wazuh 3.0, 3.1 and 3.2**.
Regards,
Juanjo
> Modified CHANGELOG.md

- public/controllers/blankScreenController.js
- public/controllers/healthCheck.js
- public/services/errorHandler.js
- public/services/prep-error.js
- public/services/routes.js
- public/templates/health-check/health-check.html
- server/api/wazuh-elastic.js
Hi App team! after a first approach of our error handler module, I've been researching more complicated scenarios, after some simulations I catch some situations where a better error handling is needed, with this PR we have a better error hanling module. 
It's mostly focused on Elasticsearch related errors.
Best regards,
Jesús
> Better Elasticsearch error handling

- package.json
- public/controllers/common/directives.js
- public/kibana-integrations/kibanaDiscoverDirective.js
- public/kibana-integrations/kibanaVisualizationDirective.js
- public/less/common.less
- public/templates/directives/menu-top.html
This PR adds the following:
- Improves filter propagation between discover and visualizations.
- Fixes an undefined error in console.
> Improving filter propagation for Kibana 6.2.0

- public/controllers/login.js
- public/services/errorHandler.js
- public/services/routes.js
- public/templates/directives/menu-top.html
- server/api/wazuh-api.js
- Replaces the login route name from `/login` by `/wlogin` to avoid conflict with xpack own login route.
- Shows index pattern selector only if the list length is greater than 1, if it's exactly 1 shows the index pattern without a selector.
> Minor fixes

- public/controllers/login.js
- public/services/errorHandler.js
- public/services/routes.js
- public/templates/directives/menu-top.html
- server/api/wazuh-api.js
- Replaces the login route name from /login by /wlogin to avoid conflict with xpack own login route.
- Shows index pattern selector only if the list length is greater than 1, if it's exactly 1 shows the index pattern without a selector.
> Minor fixes (6.1.x)

- public/controllers/groups.js
- public/controllers/manager.js
- public/controllers/osseclog.js
- public/less/kbn.less
- public/services/routes.js
- public/templates/manager/ruleset/ruleset.head
- Fixes a wrong situation with the visualizations when we refresh on rules/decoders tab
> Rules patch (6.1.x)

- public/controllers/groups.js
- public/controllers/manager.js
- public/controllers/osseclog.js
- public/less/kbn.less
- public/services/routes.js
- public/templates/manager/ruleset/ruleset.head
- Fixes a wrong situation with the visualizations when we refresh on rules/decoders tab
> Rules patch

- public/kibana-integrations/kibanaVisualizationDirective.js
- public/templates/manager/ruleset/ruleset.head
- This PR removes the discover directive from Ruleset tab and modifies a bit the visualization directive to properly loading these visualizations.
> Removed kbn-dis from ruleset and added proper logic on vis directive

- public/controllers/groups.js
- public/controllers/manager.js
- public/directives/wz-table/wz-table.html
- public/services/data-handler.js
- public/templates/manager/groups/groups-preview.html
- public/templates/manager/manager.head
Hello team, this PR fix the following bugs:
- Minor issue with some table fields, now are adjusted
- Click on groups should reload groups view
- Wrong sorting on all tables using wz-table, this was an error since long time ago, but now it works as expected.
> 3.2 minor bugs patch

- public/controllers/agents.js
- public/controllers/overview.js
- public/templates/overview/overview-general.html
This pull request fixes minor bugs from [pull/278](https://github.com/wazuh/wazuh-kibana-app/pull/278)
> Minor bug fixes on overview and agents controllers

- public/app.js
- public/controllers/agents.js
- public/controllers/overview.js
- public/services/wz-metric-service.js
Hello team, this pull request fixes minor bugs related to the new metrics service on overview controller as well agents controller.
> Fixes and modularizes the new metric logic

- public/less/main.less
- public/templates/agents/agents-audit.html
- public/templates/agents/agents-general.html
- public/templates/agents/agents-vuls.html
- public/templates/overview/overview-audit.html
- public/templates/overview/overview-fim.html
- public/templates/overview/overview-general.html
- public/templates/overview/overview-vuls.html
Hello team, this pull request only adjust minor details on the new metrics to be more as "Elastic"
> Minor adjustment to new metrics

- server/integration-files/app-objects-file-alerts.json
Hello team, this pull request fixes four visualizations on the General Audit tab, I was trying the audit component on my Wazuh installation and noticed that they are wrong, this PR fix them, thanks.
> Fix wrong audit visualizations json

- public/controllers/agents.js
- public/controllers/overview.js
- public/kibana-integrations/kibana-discover.js
Hello,
this PR fixes two bugs:
- Metric watcher removal when clicking the panels button.
- Pinned filters removal between agents/overview tabs.
> 3.2 filters watchers

- public/kibana-integrations/kibana-visualization.js
Hello,
this PR fixes the text filters in the visualizations when using Kibana search bar.
> Properly handling text search

- CHANGELOG.md
- public/less/angular-md.less
- public/less/buttons.less
- public/less/common.less
- public/less/kbn.less
- public/less/main.less
- public/less/tables.less
- public/less/wazuh-navbar.less
- public/templates/agents/agents-general.html
Hello everybody,
This PR fixes several bugs reported by @santiago-bassett, such as:
* Adjusted information ribbon in `Agents/General` for large OS names.
* Modified shadow from almost every app component, following Kibana's guidelines.
* Removed bold text from `Discover` tab.
* Some small adjustments to our `Discover` sidebar.
This is one more step towards a more modern, beautiful and useful Wazuh app for Kibana.
Best regards,
Juanjo
> Minor bugfixes and adjustments

- public/kibana-integrations/kibana-visualization.js
Hello team, this pull request only fixes a little bug related to the visualization directive, there is a unsafe array access that could cause troubles if you go directly to ruleset/decoders leaving the visualizations on a weird white box.
> Prevents accesing undefined array position

- CHANGELOG.md
- public/less/manager.less
- public/templates/agents/agents-general.html
- public/templates/manager/groups/groups-preview.html
- public/templates/manager/groups/groups.head
- public/templates/manager/manager-configuration.html
Hello all,
This PR provides the following:
* Removed unused CSS, mainly from `manager.less`.
* Fixed again the information ribbon on `Agents/General`, this time for Windows OS names.
Regards,
Juanjo
> Bugfixes and CSS removal

- public/templates/agents-prev/agents-prev.html
Hello team, this pull request changes the format to show the agents statistics on agents preview.
> Minor redesign on agents tab

- server/integration-files/app-objects-file-alerts.json
Hello, 
this PR adds changes to visualizations in the Wazuh app.
This review has focused on two tasks:
- Limit the number of buckets used (most of the table visualizations were surpassing acceptable limits).
- Check if the visualization makes sense.
Now the app should be faster calculating tables.
Regards.
> Reviewing visualizations

- CHANGELOG.md
- public/templates/manager/manager-configuration.html
- public/templates/settings/settings.html
Hello all,
This PR brings two new changes to the app:
* Recovered the previous state of the redesigned *Manager/Configuration* tab, adapting the HTML code to use the refactored CSS.
* Fixed a misplaced tooltip in the *Settings* tab.
This PR will not be added to the CHANGELOG, since it's part of the refactoring process and there's already a log of the tab redesign itself.
Regards,
Juanjo
> Manager Configuration readjustments

- public/controllers/health-check.js
Hello team, this pull request allows us to have Wazuh App compatible with Wazuh APIs who has different patch number.
> Fix API version check, dismissing patch number

- config.yml
- public/controllers/health-check.js
- public/controllers/settings.js
- public/directives/wz-menu/wz-menu.html
- public/directives/wz-menu/wz-menu.js
- public/services/api-tester.js
- public/services/app-state.js
Hello team, this pull request add the next new feature:
- New option on the config.yml file to set if we should show the index pattern selector on the Wazuh App top menu or not.
_Note: the new option is `ip.selector`, if not present or if it has a `true` value, it will be `true`._
Best regards,
Jesús
> Optional index pattern selector

- public/directives/wz-table/wz-table.less
- public/templates/agents-prev/agents-prev.head
- public/templates/manager/groups/groups.head
- public/templates/manager/manager-osseclog.html
- public/templates/manager/ruleset/ruleset.head
Hello team this pull request only fixes scroll for tables on mozilla.
Best,
Jesús
> Fix tables scroll moz

- public/controllers/agents.js
- public/controllers/overview.js
- public/kibana-integrations/kibana-visualization.js
- public/templates/overview/overview-fim.html
Hello,
this PR fixes an use case where visualizations weren't being destroyed due to ongoing renderization processes. 
Regards.
> Properly destroying visualizations

- server/initialize.js
- server/integration-files/known-fields.js
Hello team, this pull request adds some new features and enhacements related to our back-end:
- The sample alert insertion is not needed anymore
- The known fields are now auto refreshed
- Fields that need to be links, are now auto-formatted
- Real waiting for index pattern creation
- Creation of index pattern if missing
- Minor code refactor
Best regards,
Jesús
> Better initialization

- server/integration-files/monitoring-template.js
- server/monitoring.js
Hello team, this pull request changes the whole `monitoring.js` file:
- We don't need the monitoring template insertion step anymore
- Minor refactor to the whole module
- Regenerate the index patter if it's missing
Best regards,
Jesús
> Monitoring module

- public/services/api-tester.js
- public/services/error-handler.js
Hello team, this small pull request only give more information to the user who is facing problems whenever adds a new API entry, thanks.
Best,
Jesús
> Better API error message on settings

- public/controllers/settings.js
- public/services/pattern-handler.js
- server/initialize.js
Hello team, this pull request fixes mainly 3 things:
- Redirects to blank screen with the proper message whenever index pattern list length is 0
- Overwrite current pattern cookie if it is no longer avalaible
- Ignore index patterns with custom id on the initialization process, instead it uses config.yml default pattern
Best,
Jesús
> Better index pattern list handling

- server/api/wazuh-api.js
- server/api/wazuh-elastic.js
Hi team, this pull request fix two specific things:
- Removed clear API password on checkPattern response ([https://github.com/wazuh/wazuh-kibana-app/issues/336](https://github.com/wazuh/wazuh-kibana-app/issues/336))
- Increased query size when fetching index pattern list ([https://github.com/wazuh/wazuh-kibana-app/issues/338](https://github.com/wazuh/wazuh-kibana-app/issues/338))
Thanks to @JPLachance for your great feedback!
Best regards,
Jesús
> Query size increased, removed clear password

- public/controllers/agents.js
Hello team, this _one line pull request_ only fixes the issue related to multiple agent.id filters whenever go from agents to groups and come back with different agent.
Best,
Jesús
> Fixed multiple agent.id issue

- public/controllers/settings.js
- public/directives/wz-menu/wz-menu.js
Hi team, this pull request fixes the index pattern fetching logic related to the very first time you open the Wazuh App, also it's now moved to the wz-menu directive, now it's clever and better.
Best,
Jesús
> Fix first time pattern

- public/services/error-handler.js
Hi team, this pull request only fixes a little typo on the error handler service. Now it shows better some error messages from elastic-backend requests.
Best,
Jesús
> Fix typo on error handler service

- public/controllers/overview.js
- public/kibana-integrations/kibana-visualization.js
- public/templates/overview/overview-general.html
- server/api/wazuh-elastic.js
Hello team this PR is only to merge two development branchs into single branch.
> Dynamic visualizations seed

- server/initialize.js
Hello team, this PR fixes wrong situation whenever shards value is zero and/or replicas value is zero.
Best,
Jesús
> Fix shards zero-issue

- server/controllers/wazuh-api.js
Hello team, this pull request only replaces some `server.log` statements by nothing because the `server.log` statement is breaking on these places because it's not defined there.
Best,
Jesús
> Server log fix

- public/kibana-integrations/kibana-discover.js
Hello,
this PR fixes an issue with the exist pci_dss filter on PCI tabs in the app.
Regards.
> Fixing PCI DSS filter

- public/controllers/agents.js
- public/kibana-integrations/kibana-discover.js
Hello team, this pull request replaces an if statement on the discover directive by a trace deletion on the agents controller. This way we are reaching the same goal in a cleaner mode, also reduces overload for the discover directive.
Best,
Jesús
> Fix agents autocomplete

- server/controllers/wazuh-elastic.js
- server/initialize.js
- server/lib/elastic-wrapper.js
Same as https://github.com/wazuh/wazuh-kibana-app/pull/401 but master branch.
Regards,
Jesús
> Fix x-pack bug when there is no security enabled

- server/initialize.js
- server/monitoring.js
Hello team,
this pull request fixes https://github.com/wazuh/wazuh-kibana-app/issues/409 for the master branch.
- Checks for wazuh-agent template existence
- Added better log messages while initializing 
Regards,
Jesús
> [master] Fix monitoring no template

- server/initialize.js
- server/monitoring.js
Hello team,
this pull request fixes https://github.com/wazuh/wazuh-kibana-app/issues/409 for the 3.2 branch.
* Checks for wazuh-agent template existence
* Added better log messages while initializing
Regards,
Jesús
> [3.2] Fix monitoring no template

- public/controllers/osseclog.js
- public/directives/wz-search-bar/wz-search-bar.html
- public/directives/wz-search-bar/wz-search-bar.js
- public/templates/manager/manager-osseclog.html
Hello team this pull request implements the request feature from https://github.com/wazuh/wazuh-kibana-app/issues/426.
The code is as simple as parse the filters currently being applied on the data service. The filters are being parsed one time. Once parsed it starts the repetitive interval calling the API.
Regards,
Jesús
> Respect filters on realtime mode on logs tab

- public/services/data-handler.js
Hello team, this pull request comes to fix the last error described on https://github.com/wazuh/wazuh-kibana-app/issues/427. It only makes little modifications on the data-handler factory. In a brief summary:
- Ensuring `this.end` is `false` while we have more items to show.
- Put on busy mode at the begin of search method and disable it once done.
- Also replaces the removeAllFilters logic by an easier one.
Best regards,
Jesús
> Fix minor bugs

- public/controllers/ruleset.js
- public/directives/wz-search-bar/wz-search-bar.html
- public/directives/wz-search-bar/wz-search-bar.js
- public/services/data-handler.js
- public/services/error-handler.js
- public/services/generic-request.js
Hello team, this pull request improves the way we handle multi-requests, timeout, etc.
- Added a 200ms delay when fetching iterables
- Prevents from searching on rules/decoders with a string length <= 1
- Prevents from search if the factory is busy or it's ended
- Properly handling cancelled requests
Best regards,
Jesús
> Fix requests

- public/kibana-integrations/kibana-visualization.js
Hello team, this pull request fixes https://github.com/wazuh/wazuh-kibana-app/issues/479
It's pretty simple to add the missing filter, and the solution works both manager and cluster environment as well.
Regards,
Jesús
> Add specific filter for monitoring

- public/services/data-handler.js
Hello team, this pull request fixes #472 however we shouldn't merge it before the new package is released. It has been tested only under a development environment and the Agents list. It would be better if we await for next test session to verify it.
Regards,
Jesús
> Prevents stop searching if "this.end" is true

- public/controllers/agents.js
- public/controllers/manager.js
- public/directives/wz-table/wz-table.html
- public/templates/agents/agents.head
Hello team, this pull request fixes https://github.com/wazuh/wazuh-kibana-app/issues/489.
__Important__: this pull request must to be reviewed after https://github.com/wazuh/wazuh-kibana-app/pull/490 is merged, otherwise it will add lot of changes.
Regards,
Jesús
> Temporary removed agent 000 from specific sections

- server/controllers/wazuh-api-elastic.js
Hello team, this pull request fixes https://github.com/wazuh/wazuh-kibana-app/issues/494
It replaces API password sent from `getAPIEntries` by `****`.
Regards,
Jesús
> Fix API password replacement

- server/integration-files/known-fields.js
Hello team this pull request fixes https://github.com/wazuh/wazuh-kibana-app/issues/496,
thanks @JuanjiJG for catching them. This should solve it.
> Added two missing fields. Non searchable

- public/controllers/settings.js
- server/controllers/wazuh-api.js
Hello team, this pull request fixes #503 
Brief summary:
- The route checkAPI now accepts a Wazuh API id, this way we can use it to check already stored APIs or new APIs
> Fix check connection feature

- public/controllers/agents.js
- public/controllers/overview.js
- server/controllers/error-response.js
- server/controllers/wazuh-api.js
Hello team, this pull request fixes https://github.com/wazuh/wazuh-kibana-app/issues/514
Regards,
Jesús
> Better error handling for reporting module

- public/controllers/agents.js
- public/controllers/overview.js
- public/factories/vis-handlers.js
- server/controllers/wazuh-api.js
Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/513
Regards,
Jesús
> Added search bar to the report content

- public/controllers/agents-preview.js
- public/controllers/manager.js
- public/templates/agents-prev/agents-prev.html
- public/templates/manager/manager-status.html
Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/506
Regards,
Jesús
> Manager consistency

- public/controllers/overview.js
- public/factories/vis2png.js
Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/523
Regards,
Jesús
> Parallel reporting but it's still on foreground mode

- public/controllers/agents-preview.js
- public/controllers/agents.js
- public/controllers/blank-screen-controller.js
- public/controllers/groups.js
- public/controllers/manager.js
- public/controllers/osseclog.js
- public/controllers/overview.js
- public/controllers/ruleset.js
- public/controllers/settings.js
- public/directives/wz-menu/wz-menu.js
- public/factories/index.js
- public/factories/misc.js
- public/factories/share-agent.js
- public/services/api-tester.js
- public/services/pattern-handler.js
- public/services/resolves/check-timestamp.js
- public/services/resolves/get-ip.js
- public/services/resolves/settings-wizard.js
Hello team, this pull request is a first step for https://github.com/wazuh/wazuh-kibana-app/issues/522
Brief summary:
- Two new factories have been added to replace lot of root scope usage
- Specific cases are now using events
- Removed lot of digest forcing 
Regards,
Jesús
> Sharing data using factories instead root scope

- public/kibana-integrations/kibana-visualization.js
- server/controllers/wazuh-elastic.js
Hello team, this PR fixes #529 
Brief summary:
- Inserting selected pattern while building timelion query
- Applying filters for "Top 5 nodes" pie chart and histogram from specific node
Regards,
Jesús
> Fix vis from cluster monitoring

- public/controllers/agents.js
Hello team, this PR adds a pretty simple control logic to prevent problems regarding to no visualization tabs vs visualization tabs on agents. Same logic will be applied to Overview once the redesign finishes.
- Now we are storing 3 items array which includes 3 last tabs. If A is a visualization tab and B is a no visualization tab and we have A,B,A it means Kibana won't repeat the same search so we can manage that situation like going from discover to panel (local change)
Regards,
Jesús
> Fix agents issue

- public/controllers/agents.js
Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/535. The solution comes from remove a wrong if statement.
Regards,
Jesús
> Fix reloading broken under configuration tab

- public/controllers/agents-preview.js
- public/templates/agents-prev/agents-prev.html
Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/527.
- Added selector to the agents preview including Wazuh agents versions
- Filtering as expected once specific version is selected
- Default is `all`
Regards,
Jesús
> Added filter by agent version to agents preview

- public/controllers/agents-preview.js
- public/templates/agents-prev/agents-prev.html
Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/370
> Added filter by node in agents preview

- server/monitoring.js
Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/539
- The recursive function has been replaced by an async loop.
- The array is cleared whenever the function fails.
- Each API is inserted once the last API has finished.
- The pagination has been increased to 1000 per page
Regards,
Jesús
> Fix monitoring main function

- public/controllers/agents.js
- public/controllers/overview.js
- public/controllers/settings.js
- public/services/app-state.js
- public/services/resolves/settings-wizard.js
- server/controllers/wazuh-api-elastic.js
- server/routes/wazuh-api-elastic.js
Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/541
Regards,
Jesús
> Not updating .wazuh when changing extensions

- public/templates/overview/overview-gdpr.html
- server/controllers/wazuh-api.js
Hello team this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/540
Prevents from parse GDPR requirements if they are not available from the Wazuh API.
Regards,
Jesús
> Checking if GDPR is available from the Wazuh API before parsign

- public/controllers/agents.js
The team just found a little bug when changing agent and going to the same tab regarding to the agent.id filter. This pull request prevents that situation.
Regards,
Jesús
> Fix agent changed condition

- public/controllers/agents-preview.js
- public/services/data-handler.js
- public/templates/agents-prev/agents-prev.html
Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/551
Regards,
Jesús
> Fix OS platform selector

- public/controllers/settings.js
Hello team this PR prevents from change the extensions from the user if click on set default manager.
> Fix set default manager resets extensions

- package.json
Hello team,
This pull request will bump the revision for the 393 release.
Regards,
Juanjo
> Bump app revision for 393 release

- server/controllers/wazuh-api.js
- server/initialize.js
Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/559
Regards,
Jesús
> Added missing header

- server/controllers/wazuh-api.js
- server/logger.js
Hello team, this PR is a possible solution to https://github.com/wazuh/wazuh-kibana-app/issues/562
Regards,
Jesús
> Moved generated data to optimize directory

- server/integration-files/known-fields.js
Hello team this PR fixes #565 
```json
{
"name": "data.vulnerability.package.condition",
"type": "string",
"count": 0,
"scripted": false,
"searchable": true,
"aggregatable": true,
"readFromDocValues": true
}
```
Regards,
Jesús
> Added package condition from vulnerability known fields

- server/integration-files/visualizations/agents/agents-audit.js
- server/integration-files/visualizations/overview/overview-audit.js
After read the audit rules (https://github.com/wazuh/wazuh-ruleset/blob/5faa4b23e6be2b1fff786c0b81237c5a9fb81b84/rules/0365-auditd_rules.xml) slowly and testing them with @vikman90 (thanks man!) and after test them by myself I've concluded we had some wrong visualizations and this "PR" fix all of them from my view.
Regards,
Jesús
> Fix audit visualizations

- public/directives/wz-menu/wz-menu.js
Hello team this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/574
> Fix missing dependency

- package.json
- public/controllers/dev-tools.js
- public/templates/dev-tools/dev-tools.html
Hello team, this pull request fixes #577 , read the issue for more information.
Our dev tool is now able to parse inline queries plus JSON input at the same time. Note that inline queries have precedence to JSON input.
Regards,
Jesús
> Inline queries for dev tools

- public/controllers/agents-preview.js
- server/controllers/wazuh-api.js
- server/routes/wazuh-api.js
Hello team, this PR fixes #578 .
Since this view could has a huge amount of data we concluded to move some of its controller logic to our server side. Once the Wazuh API can provide us a list of unique fields from the data sets we can replace this logic.
Regards,
Jesús
> Agents preview improvement

- public/controllers/settings.js
Hello team, this pull request fixes https://github.com/wazuh/wazuh-kibana-app/issues/590
Regards,
Jesús
> Fix toggleExtension function

- public/directives/wazuh-table/template.html
Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/592
Regards,
Jesús
> Added loading ring, no result box and no result counter

- public/controllers/dev-tools.js
- public/directives/wz-menu/wz-menu.html
- public/less/common.less
- public/templates/dev-tools/dev-tools.html
Hello team, this PR fixes #526 
Regards,
Jesús
> Improvements for the Dev tool

- public/controllers/agents-preview.js
- public/controllers/agents.js
- public/controllers/groups.js
- public/controllers/osseclog.js
- public/controllers/ruleset.js
- public/directives/wazuh-table/controller.js
Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/600
> Restored table filters when building CSV

- package.json
Hello team this pull request fixes https://github.com/wazuh/wazuh-kibana-app/issues/604
> Fix query-string version to avoid uglifyjs related error

- public/app.js
Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/611
Regards,
Jesús
> Added missing provider in load time

- .eslintrc.json
- public/kibana-integrations/index.js
- public/kibana-integrations/kbn-global-timepicker/kbn_global_timepicker.html
- public/kibana-integrations/kbn-global-timepicker/kbn_global_timepicker.js
- public/kibana-integrations/kbn-global-timepicker/time_navigation.js
- public/kibana-integrations/kbn_top_nav/bread_crumbs/bread_crumbs.html
- public/kibana-integrations/kbn_top_nav/bread_crumbs/bread_crumbs.js
- public/kibana-integrations/kbn_top_nav/bread_crumbs/index.js
- public/kibana-integrations/kbn_top_nav/index.js
- public/kibana-integrations/kbn_top_nav/kbn_top_nav.html
- public/kibana-integrations/kbn_top_nav/kbn_top_nav.js
- public/kibana-integrations/kbn_top_nav/kbn_top_nav_controller.js
- public/kibana-integrations/kibana-discover.js
- public/templates/discover/discover.html
- public/templates/kibana-template/kibana-discover-template.html
Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/613 and https://github.com/wazuh/wazuh-kibana-app/issues/614. The changes are mostly related to a small modification/adaptation for kbn-top-nav and kbn-global-timepicker directives.
Regards,
Jesús
> Fix Discover breaking changes from Kibana 6.3.0

- public/controllers/dev-tools.js
Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/622
Now the parameter "pretty" is ignored
Regards,
Jesús
> Ignore pretty in dev tools query parser

- public/templates/agents/agents-ciscat.html
Hello team,
This pull request fixes #625.
Regards,
Juanjo
> Fix visualization names on Agents/CIS-CAT template

- public/controllers/agents.js
- public/templates/agents/agents-ciscat.html
- public/templates/overview/overview-ciscat.html
- public/templates/overview/overview-fim.html
- public/templates/overview/overview-oscap.html
- server/controllers/wazuh-reporting.js
- server/reporting/raw-parser.js
Hello team, this PR adds some reporting minor improvements
- Some kbn-vis from html that had the id located in the wrong place. 
- Adds a validation for the Elastic parser, each row must has same length as columns length
- Adds agent id for reporting
- Fixes some fonts size and margin from generated PDF
Regards,
Jesús
> Reporting minor improvements

- server/initialize.js
- server/lib/elastic-wrapper.js
Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/649, read the issue for more information.
Regards,
Jesús
> New way to update known fields

- public/controllers/health-check.js
- public/controllers/overview.js
- public/controllers/settings.js
- public/directives/wz-menu/wz-menu.js
- public/factories/index.js
- public/factories/wazuh-config.js
- public/services/api-tester.js
- public/services/generic-request.js
- public/services/resolves/get-config.js
- public/services/resolves/index.js
- public/services/resolves/settings-wizard.js
- public/services/routes.js
- public/templates/settings/settings-configuration.html
- public/templates/settings/settings.head
- public/templates/settings/settings.jade
Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/656
- Now we have a new **factory** which stores all the configuration values
- Added a new **resolve** function before each app route, this way we have the configuration always up to date
- Also we are showing the current configuration under settings tab, this was added in https://github.com/wazuh/wazuh-kibana-app/commit/0f8ce068a8f63ccbce6a29e27a93c78a5e0c5330 but could be removed
Regards,
Jesús
> Configuration factory

- public/directives/wazuh-table/controller.js
- public/directives/wazuh-table/template.html
- public/templates/agents/agents-syscollector.html
- public/templates/manager/groups/groups-preview.html
- public/templates/manager/manager-osseclog.html
Hello team, this PR fixes half of https://github.com/wazuh/wazuh-kibana-app/issues/655 (_Truncate long fields, adding a tooltip if needed_)
Regards,
Jesús
> Truncate tables

- package.json
- public/templates/manager/monitoring/disabled.html
- server/logger.js
Reverts wazuh/wazuh-kibana-app#673
> Revert "[3.2-6.2] Logger fix"

- server/integration-files/visualizations/overview/overview-fim.js
Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/693
> Fix visualization

- server/controllers/wazuh-reporting.js
Hello team, this PR fixes #695 
Regards,
Jesús
> Checking if filter is negated

- package.json
Hello team, this PR increases revision to 399 and the Kibana version to 6.3.1
> Bump revision

- server/integration-files/visualizations/overview/overview-fim.js
Same as https://github.com/wazuh/wazuh-kibana-app/pull/694 but 3.2-6.2
> [3.2-6.2] Fix visualization

- server/integration-files/visualizations/overview/overview-fim.js
Same as https://github.com/wazuh/wazuh-kibana-app/pull/694 but 3.3-6.2
> [3.3-6.2] Fix visualization

- server/controllers/wazuh-reporting.js
Same as https://github.com/wazuh/wazuh-kibana-app/pull/696 but 3.2-6.2
> [3.2-6.2] Checking if filter is negated

- server/controllers/wazuh-reporting.js
Same as https://github.com/wazuh/wazuh-kibana-app/pull/696 but 3.3-6.2
> [3.3-6.2] Checking if filter is negated

- public/controllers/agents-preview.js
- public/services/resolves/get-config.js
- server/controllers/wazuh-elastic.js
- server/lib/elastic-wrapper.js
- server/routes/wazuh-elastic.js
Same as https://github.com/wazuh/wazuh-kibana-app/pull/700 but 3.2-6.2
> [3.2-6.2] Searching pattern

- public/controllers/agents-preview.js
- public/services/resolves/get-config.js
- server/controllers/wazuh-elastic.js
- server/lib/elastic-wrapper.js
- server/routes/wazuh-elastic.js
Same as https://github.com/wazuh/wazuh-kibana-app/pull/700 but 3.3-6.2
> [3.3-6.2] Searching pattern 

- public/directives/wazuh-table/controller.js
- server/controllers/wazuh-api.js
- util/csv-key-equivalence.js
Hello team, this PR fixes both https://github.com/wazuh/wazuh-kibana-app/issues/708 and https://github.com/wazuh/wazuh-kibana-app/issues/716 as well.
Regards,
Jesús
> CSV improvements

- public/factories/tab-visualizations.js
- public/templates/agents/agents-fim.html
- server/integration-files/known-fields.js
Hello team, this PR adds missing fields for who data feature. Also it removes groups vis from agents FIM tab.
Regards,
Jesús
> [ 3.4.x >= ] Who data fields

- .eslintrc.json
- public/services/resolves/settings-wizard.js
- server/controllers/wazuh-api.js
Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/734
Regards!
> Fix version mismatch message

- public/controllers/settings.js
Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/730
Regards,
Jesús
> Removing API cookie instead returning a warning if it's the selected API

- package.json
This PR closes https://github.com/wazuh/wazuh-kibana-app/issues/507, problems reagarding to md-autocomplete are not angular related but app itself and it's going to be solved.
Regards!
> Updated angular-material

- public/controllers/agents.js
- public/templates/agents/agents-syscollector.html
- public/templates/agents/agents.head
Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/631
Right now, any agent can go to the inventory tab. In case it has no inventory a proper message is shown and a useful link is shown too.
Regards,
Jesús
> Filtering syscollector output

- public/kibana-integrations/kibana-visualization.js
> Fix specific node vis (cluster.node missing)

- server/integration-files/known-fields.js
> Added missing who data field

- public/controllers/manager.js
- public/less/height.less
- public/templates/manager/manager-configuration.html
- public/utils/xml-beautifier.js
Hello team, this PR adds a new feature to our Management > Configuration section. Now each configuration has its own buttons to show XML raw content or JSON raw content as we can see in the below image:
Regards,
Jesús
> XML / JSON viewers

- public/controllers/agents.js
- public/controllers/overview.js
- public/templates/agents/agents-welcome.html
- public/templates/overview/overview-welcome.html
- server/reporting/tab-description.js
Hello team, this PR fixes few grammar typos and unifies the tab description along the App sections using dynamic values from a description file.
Regards!
> Using dynamic values for description. Grammar fix

- public/controllers/dev-tools.js
Hello team, this PR fixes #776 
Tested using empty lines, comment lines, mixed lines (comments and empty lines) and valid query line.
Regards,
Jesús
> [3.5-6.3] Fix error when first line is a comment or empty

- public/services/resolves/settings-wizard.js
- public/services/routes.js
Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/789
Regards,
Jesús
> [3.5-6.3] Fix api double message + fix previous location

- server/controllers/wazuh-api.js
Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/793
> Check all API entries before throwing error

- public/controllers/health-check.js
- public/services/resolves/settings-wizard.js
- server/controllers/wazuh-api.js
Hello team, this PR finishes the fix done in https://github.com/wazuh/wazuh-kibana-app/pull/794
> Updating API ID

- CHANGELOG.md
- README.md
- package.json
Hello team,
This pull request will update the required files for a new Wazuh app release.
Regards,
Juanjo
> Updated CHANGELOG and package.json for next app release

- server/initialize.js
- server/lib/elastic-wrapper.js
- server/lib/replicas-shards-helper.js
- server/monitoring.js
Hello team, this PR closes https://github.com/wazuh/wazuh-kibana-app/issues/814
Now we can update number of replicas of replicas of existing Wazuh app related indices.
Regards,
Jesús
>  Hot replicas modifying

- public/templates/agents/agents.head
- public/templates/overview/overview.head
Hello team,
This pull request closes #837.
Regards,
Juanjo
> Replace "View Discover" and "View panel" buttons

- server/integration-files/visualizations/overview/overview-virustotal.js
This PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/833
> Fix virustotal vis

- public/templates/settings/settings.head
Closes https://github.com/wazuh/wazuh-kibana-app/issues/824
> Hide extensions if there are no APIs

- public/controllers/settings/index.js
This PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/825
> Fix update wz-menu when last API is removed

- public/controllers/management/status.js
- server/controllers/wazuh-api.js
Hello team,
This PR fixes #826.
Regards,
Juanjo
> Fixed agents coverage percentage when there are no agents

- public/templates/agents/agents-configuration.html
- public/templates/management/configuration.html
Hello team,
This pull request adds new Syscheck configuration items to the current *Management/Agent > Configuration* tabs.
This enhancement is part of #822, so please do not remove the branch when merging this pull request.
Regards,
Juanjo
> Added new syscheck configuration items

- public/app.js
This PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/836
> Restored Kuery auto-complete

- public/controllers/settings/index.js
- public/templates/settings/settings-logs.html
- public/templates/settings/settings.head
Hello team,
This PR closes #834. Now the *Settings > Logs* tab includes a Refresh button, and everytime you click on the *Logs* tab, the logs table will be refreshed.
Regards,
Juanjo
> Implemented Refresh function for Settings/Logs tab

- server/controllers/wazuh-api-elastic.js
- server/lib/elastic-wrapper.js
This PR closes https://github.com/wazuh/wazuh-kibana-app/issues/831
> Fix x-pack updating API using incoming request

- public/controllers/management/rules.js
- server/lib/elastic-wrapper.js
Hello team, this PR fixes #854
> Rule ID fetching rule from Discover

- server/integration-files/known-fields.js
Updated our known fields list for the index pattern. Now we have 567 known fields.
Closes https://github.com/wazuh/wazuh-kibana-app/issues/828
> Updated known fields for Kibana

- public/kibana-integrations/kibana-discover.js
- public/services/common-data.js
Hi team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/876
Regards,
Jesús
> Fix duplicate implicit filters

- CHANGELOG.md
- README.md
- package.json
Hello team,
This pull request will bump the app revision and update the changelog for a new release.
Regards,
Juanjo
> [3.6.1_6.4.0-410] Bump revision and update CHANGELOG.md

- STYLEGUIDE.md
Added STYLEGUIDE.md file, based https://github.com/elastic/kibana/blob/master/STYLEGUIDE.md
> Added STYLEGUIDE.md

- public/templates/overview/overview-fim.html
- server/integration-files/visualizations/overview/overview-fim.js
Hello team, this PR replaces gauge vis by a pie vis for Overview FIM section.
Regards
> Replaced gauge by pie vis, using top 5 agents now

- CHANGELOG.md
- package.json
Hello team,
This PR will update the changelog and bump the revision for a new Wazuh app release.
Regards,
Juanjo
> Update changelog and bump revision 411

- package.json
There are no changes, this Elastic patch version comes with no breaking changes.
Regards
> Updated Elastic version 6.4.1

- public/services/error-handler.js
- server/controllers/wazuh-api.js
Closes https://github.com/wazuh/wazuh-kibana-app/issues/908
> Showing the API error code

- public/controllers/agent/agents.js
- public/controllers/management/groups.js
- public/factories/share-agent.js
- public/templates/agents/agents-general.html
- public/templates/agents/agents-welcome.html
Closes https://github.com/wazuh/wazuh-kibana-app/issues/910
> Multi group

- public/less/layout.less
- public/templates/kibana-template/kibana-filterbar-template.html
Small PR to restore the filterpill align in 6.4.1
> Fix filterpill align

- public/templates/agents/agents-oscap.html
- public/templates/overview/overview-oscap.html
Hello team,
This PR closes #923.
Regards,
Juanjo
> Changed Overview/Agents OpenSCAP visualization titles

- public/controllers/agent/agents.js
- public/templates/management/configuration/welcome.html
Related to https://github.com/wazuh/wazuh/pull/1527
> Added is_sync API call

- public/controllers/agent/agents.js
- public/controllers/overview/index.js
- public/controllers/settings/index.js
- public/templates/agents/agents-welcome.html
- public/templates/agents/agents.head
- public/templates/overview/overview-welcome.html
- public/templates/overview/overview.head
- public/templates/settings/settings-about.html
- public/templates/settings/settings-first-use.html
- public/templates/settings/settings-logs.html
Hi team,
This PR includes several changes and bugfixes found during testing:
- The "Add API form" wasn't showing when pressing the button after updating an API.
- Moved the _Osquery_ extension into a different section.
- Changed date formas on _Settings > Logs_ to make it more _human-readable_.
- Fixed wrong URL to Wazuh core repository on _Settings > About_.
Regards,
Juanjo
> Several 3.7-6.4 testing bugfixes

- public/directives/wz-table/wz-table.js
- public/templates/management/configuration/active-response/active-response.head
- Hide Active response navbar for agents.
- Fix a bug when rule description is an empty string.
Regards,
Juanjo
> More app bugfixes

- public/templates/management/configuration/active-response/active-response.head
- public/templates/management/configuration/active-response/commands.html
- public/templates/management/configuration/agentless/agentless.html
- public/templates/management/configuration/alerts/email-alerts.html
- public/templates/management/configuration/alerts/general-alerts.html
- public/templates/management/configuration/cis-cat/cis-cat.head
- public/templates/management/configuration/cis-cat/ciscat-benchmarks.html
- public/templates/management/configuration/cis-cat/ciscat-general.html
- public/templates/management/configuration/client-buffer/client-buffer.html
- public/templates/management/configuration/client/client.html
- public/templates/management/configuration/global-configuration/global-configuration.head
- public/templates/management/configuration/global-configuration/global.html
- public/templates/management/configuration/integrity-monitoring/integrity-monitoring.head
- public/templates/management/configuration/log-collection/localfile.html
- public/templates/management/configuration/osquery/osquery.html
- public/templates/management/configuration/policy-monitoring/pm-unix.html
- public/templates/management/configuration/welcome.html
- public/utils/tab-names.js
Fix some typos for the config section.
> Fix grammar

- public/controllers/management/monitoring.js
- public/controllers/misc/health-check.js
- public/controllers/settings/index.js
- public/directives/wz-table/lib/click-action.js
- public/directives/wz-table/lib/pagination.js
- public/services/resolves/settings-wizard.js
- public/services/routes.js
- public/templates/management/ruleset/decoders/decoders-detail.html
- public/templates/management/ruleset/rules/rules-detail.html
- public/templates/settings/settings-pattern.html
- server/controllers/wazuh-api.js
- server/integration-files/visualizations/overview/overview-aws.js
Several fixes, related https://github.com/wazuh/wazuh-kibana-app/issues/969
> 3.7 several fixes

- public/kibana-integrations/kibana-discover.js
- public/templates/agents/agents.head
> Fix race condition with the Wazuh filters

- public/controllers/agent/agents.js
- public/controllers/management/monitoring.js
- public/controllers/management/status.js
- public/controllers/overview/index.js
- server/controllers/wazuh-api.js
Hi team, this PR modifies how we are handling some `Promise.all` results. Following our JS style guide.
Regards
> Refactor Promise.all output

- CHANGELOG.md
- public/controllers/management/logs.js
- public/less/layout.less
- public/templates/management/logs.html
Closes https://github.com/wazuh/wazuh-kibana-app/issues/960
> Node selector for Management > Logs

- CHANGELOG.md
- package.json
- public/controllers/agent/agents-preview.js
- public/templates/agents-prev/agents-prev.html
- server/controllers/wazuh-api.js
Closes https://github.com/wazuh/wazuh-kibana-app/issues/993
> Added group selector for the agent list

- package.json
- server/lib/elastic-wrapper.js
Fix X-Pack security `.wazuh` index updating bug.
> Retro-fix updateWazuhIndexDocument for X-Pack

- package.json
- public/services/routes.js
> Fix safari redirect issue when using surrounding documents feature

- package.json
- public/controllers/misc/reporting.js
- public/templates/management/reporting.html
Closes https://github.com/wazuh/wazuh-kibana-app/issues/1011
> Fixed broken report list pagination

- public/templates/agents/agents-syscollector.html
Hi team,
This PR set in 10 the number of visible rows in syscollector packages and processes tables.
Regards
> Increased the number of rows in syscollector packages/processes tables

- public/controllers/agent/agents.js
- public/controllers/management/configuration.js
- public/less/common.less
- public/services/app-state.js
- public/templates/agents/agents.head
- public/templates/management/configuration/client/client.html
- public/templates/management/configuration/configuration.head
- public/templates/management/configuration/welcome.html
Hi team, 
This PR changes some things suggested by @snaow in configuration section (both mangement and agent configuration). It also adds a new fix that saves in the url the path of a opened subtab and loads it when the page is reloaded.
This PR solves #1034 
Regards.
> New Feedbacks and improvements in configuration sections

- public/templates/agents/agents.head
- public/templates/overview/overview.head
> Hide the "Report" button on Discover panel

- server/controllers/wazuh-elastic.js
- server/routes/wazuh-elastic.js
- test/server/wazuh-elastic.js
> Added /elastic/alerts route

- public/controllers/overview/overview.js
- public/templates/overview/overview-aws.html
- public/templates/overview/overview.head
- server/controllers/wazuh-elastic.js
- server/integration-files/visualizations/overview/overview-aws.js
> AWS rework

- public/directives/wz-table/lib/parse-value.js
- public/templates/agents/agents-syscollector.html
- util/csv-key-equivalence.js
- util/process-state-equivalence.js
Closes https://github.com/wazuh/wazuh-kibana-app/issues/991
> Improved syscollector tables

- public/directives/wz-table/wz-table-directive.js
> Fix duplicated rows when resizing tables

- public/services/data-factory.js
> Avoid fetching twice the same data

- server/controllers/wazuh-api-elastic.js
- server/controllers/wazuh-api.js
- server/controllers/wazuh-elastic.js
- server/initialize.js
- server/lib/elastic-wrapper.js
- server/routes/wazuh-api-elastic.js
> Fix updateWazuhIndexDocument method

- public/kibana-integrations/kibana-discover.js
> Removed popularizeField query until kibana/#22426 is solved

- public/directives/wz-tag-filter/wz-tag-filter.js
Hi team,
This PR fix an unhandled casuistic with blankspaces and case sensitive tags in new filters bar.
Regards
> Fix typo new filters bar

- public/directives/wz-tag-filter/wz-tag-filter.js
Hi team,
This PR fix an unhandled casuistic with blankspaces and case sensitive tags in new filters bar.
Regards
> Fix typo autocomplete also

- public/controllers/overview/overview.js
- public/templates/overview/overview-general.html
> Fix missing values when wazuh-monitoring is disabled

- init.js
- server/controllers/wazuh-api.js
- server/lib/api-helper.js
- server/monitoring.js
> Improved wazuh-monitoring module

- public/controllers/agent/agents-preview.js
- public/controllers/agent/agents.js
- public/controllers/management/logs.js
- public/controllers/management/monitoring.js
- public/controllers/management/status.js
- public/controllers/misc/health-check.js
- public/controllers/overview/overview.js
- public/controllers/settings/settings.js
- public/factories/vis-handlers.js
- public/services/api-request.js
- public/services/error-handler.js
- public/services/resolves/settings-wizard.js
- server/controllers/wazuh-api-elastic.js
- server/controllers/wazuh-api.js
- server/controllers/wazuh-elastic.js
- server/controllers/wazuh-reporting.js
- server/initialize.js
- server/monitoring.js
Part of https://github.com/wazuh/wazuh-kibana-app/issues/1050
> Simplify complex if conditions.

- CHANGELOG.md
- public/controllers/dev-tools/dev-tools.js
- public/less/common.less
- public/services/reporting.js
- public/templates/agents-prev/agents-prev.html
- public/templates/dev-tools/dev-tools.html
- public/templates/management/groups/groups.html
- public/templates/management/monitoring/configuration.html
- public/templates/management/monitoring/nodes-detail.html
- public/templates/management/monitoring/nodes-list.html
- public/templates/management/ruleset/decoders/decoders-detail.html
- public/templates/management/ruleset/rules/rules-detail.html
Hi team,
This PR fixes some bugs in dev-tools, enchance the code quality in rules sections, and implements some UI improvements as:
- Back buttons in monitoring section
- Resizable columns by dragging in Dev-tools
- Added new fields to agents table
This PR solves #1050 
Regards
> Some UI improvements and bug fixes

- server/controllers/wazuh-elastic.js
> Fix template checking method for multiple patterns

- public/controllers/agent/agents.js
- public/templates/agents/agents-syscollector.html
- util/csv-key-equivalence.js
Hi team,
This PR adds a new network addresses table for agent inventory data section, in order to show to the user this valuable information.
This PR solves #1109 
Regards.
> Add netaddr table for inventory

- public/controllers/misc/health-check.js
- server/controllers/wazuh-elastic.js
- server/initialize.js
- server/lib/refresh-known-fields.js
- server/monitoring.js
>  Refresh known fields on health check

- public/templates/management/configuration/integrity-monitoring/fim-whodata.html
- public/templates/management/configuration/integrity-monitoring/integrity-monitoring.head
- public/templates/management/configuration/integrity-monitoring/integrity-monitoring.pug
> Added Audit keys configuration

- public/controllers/agent/agents.js
- public/controllers/management/groups.js
- public/directives/wz-table/wz-table-directive.js
- public/less/layout.less
Hi team,
This PR adds some fixes and improvements needed for 3.8-6.5 version release.
Regards
> Some 3.8 fixes

- public/directives/wz-xml-file-editor/wz-xml-file-editor.js
Hi team,
This PR adds some fixes to adapt the XML validation to an Ossec XML file.
Regards
> Fix xml files editor validator

- public/directives/wz-multiple-selector/wz-multiple-selector.html
- public/utils/codemirror/formatting.js
Hi team,
This fix PR add behavior to not breaking the lines until a tag ends in the XML file editor component, and limit to 500 the elimination of agents in multiple agents selector component.
Regards
> Fixes in XML and multiple selector directives

- public/controllers/dev-tools/dev-tools.js
- server/controllers/wazuh-api.js
Hi team,
this PR adds full output to the query result in devtools 
Regards
> Dev Tools. Add full output from Wazuh API

- public/less/common.less
Hi team, the user @crolopez reported that the Wazuh logo is broken on Firefox, this PR aims to solve it modifying a bit the CSS that applies.
Regards
> Fix logo for Firefox

- public/controllers/agent/agents.js
- public/controllers/management/groups.js
- public/directives/wz-table/wz-table-directive.js
- public/directives/wz-table/wz-table.html
- public/templates/agents/agents-welcome.html
- public/templates/management/groups/groups.html
Hi team,
This PR disables the new 3.8 groups management if the user is not an admin.
Regards.
> Groups management with permissions

- public/directives/wz-config-viewer/wz-config-viewer.html
- public/directives/wz-config-viewer/wz-config-viewer.js
- public/utils/config-handler.js
Hi team,
this PR modifies wz-config-viewer directive
closes #1133 
Regards
> Refactor JSON/XML viewer directive

- public/controllers/agent/agents-preview.js
- public/less/common.less
- public/templates/agents-prev/agents-prev.html
Closes https://github.com/wazuh/wazuh-kibana-app/issues/1167
> Added refresh action for agents preview table

- public/controllers/dev-tools/dev-tools.js
- public/templates/dev-tools/dev-tools.html
> Added shift + enter feature. Added "export as JSON".

- public/directives/index.js
- public/directives/wz-config-viewer/wz-config-viewer.html
- public/directives/wz-config-viewer/wz-config-viewer.js
- public/directives/wz-config-viewer/wz-config-viewer.less
Hi team,
this PR fixes an error in wz-config-viewer,
Regards
> Fix config viewer

- public/controllers/agent/agents.js
- public/services/error-handler.js
- public/templates/agents/agents-welcome.html
- public/templates/agents/agents.head
> Changed agent header view

- public/controllers/management/groups.js
- public/directives/wz-table/wz-table-directive.js
- public/directives/wz-table/wz-table.html
> Added an option to edit the group configuration from the groups table

- public/controllers/management/config-ruleset.js
- public/directives/wz-list-manage/wz-list-manage.html
- public/directives/wz-list-manage/wz-list-manage.js
- public/less/common.less
- public/less/layout.less
- public/templates/management/configuration/config-ruleset/config-ruleset.html
Hi team, 
This PR implements the CDB Lists related fixes suggested in #1211 
Regards
> Fixes and improvements cdb lists management

- public/directives/wz-config-viewer/wz-config-viewer.html
- public/templates/management/configuration/active-response/active-response.html
- public/templates/management/configuration/active-response/commands.html
- public/templates/management/configuration/agentless/agentless.html
- public/templates/management/configuration/alerts/email-alerts.html
- public/templates/management/configuration/alerts/reports.html
- public/templates/management/configuration/amazon-s3/amazon-buckets.html
- public/templates/management/configuration/config-ruleset/config-ruleset.html
- public/templates/management/configuration/integrity-monitoring/fim-monitored.html
- public/templates/management/configuration/log-collection/localfile.html
- public/templates/management/configuration/log-collection/socket.html
- public/templates/management/configuration/wazuh-commands/wazuh-commands.html
Hi team,
This PR implements a style fix in order to not to use scroll in a container when it could fill the height of the window.
This PR solves #1219 
Regards
> Expand containers to windows entire height

- public/controllers/management/management.js
- public/directives/wz-list-manage/wz-list-manage.js
- public/directives/wz-xml-file-editor/wz-xml-file-editor.js
Hi team,
This PR improves and fix a wrong behavior in the restart manager/cluster button. Now when we click in any of the restart buttons, the main button is disabled. This PR is related #1210
Regards.
> Fix disable button behavior

- util/api-request-list.js
Hi team,
This PR keep updated the API request list (with new 3.9 calls) for dev-tools autocomplete. This PR solves #1217 
Regards
> Update API request list model

- config.yml
- public/services/resolves/get-config.js
- public/templates/settings/settings-configuration.html
- public/utils/config-equivalences.js
- server/lib/index-date.js
- server/lib/update-configuration.js
- server/monitoring.js
Hi team, this PR adds:
* Support for more than one pattern. Solves #1183 
* Customizable interval for indices creation. Solves #1209 
* Do not check the template if it's a worker or if it's disabled. Solves #1231 
Regards.
> Wazuh monitoring enhancements

- public/templates/agents/agents-welcome.html
> New header for agents

- public/controllers/agent/agents.js
- public/controllers/management/edition.js
- public/controllers/management/monitoring.js
- public/controllers/overview/overview.js
- public/directives/wz-table/wz-table-directive.js
- public/directives/wz-xml-file-editor/wz-xml-file-editor.js
- public/kibana-integrations/kibana-visualization.js
Hi team,
this PR fixes the problems found while testing edit manager/cluster configuration: https://github.com/wazuh/wazuh-kibana-app/issues/1238
Regards,
> Fix edit manager config

- public/templates/agents/agents-welcome.html
- public/templates/management/configuration/config-edition/config-edition.html
- public/templates/management/status.html
- public/templates/overview/overview-general.html
- server/integration-files/visualizations/overview/overview-general.js
Fix _Replace "Most active origins" vis with a "Alerts evolution - Top 5 agents"_, _Do not use "..." in error messages / confirm messages_ from #1249
> Some UI enhancements (01)

- server/integration-files/known-fields.js
> Added syscollector and configuration assessment known fields

- public/directives/wz-table/wz-table.html
Hi team,
This PR fixes the text truncation in order to prevent the tooltip from displaying in a wrong position.
Regards.
> Fix truncate text in tables

- public/directives/wz-config-viewer/wz-config-viewer.html
- public/templates/management/configuration/policy-monitoring/pm-configuration-assessment.html
- public/templates/management/configuration/policy-monitoring/policy-monitoring.head
- public/templates/management/configuration/policy-monitoring/policy-monitoring.pug
- public/templates/management/configuration/welcome.html
Hi team,
This PR shows the applied configuration for the new module `configuration-assessment` in the Agent configuration section.
This solves #1223 
Regards.
> Show "configuration assessment" configuration

- public/templates/settings/settings-extensions.html
Hi team,
This PR fixes a virus total extension switch bug.
Regards
> Fix virus total extension switch

- README.md
Not every system has sudo installed / available so mention a way without sudo as well.
> Add install / update examples without having sudo installed

- public/controllers/management/decoders.js
Hi team, 
Same as #1267  , but with decoders.
Regards.
> Fix decoders save

- index.js
- public/hack-icon-style.js
- public/less/icon-style.less
Hi team,
This PR overwrites a Kibana style to adapt the proportions of the Wazuh App icon to the rest of the icons.
Regards
> Wazuh icon proportions adapted

- public/controllers/management/decoders.js
- public/controllers/management/rules.js
- public/templates/management/ruleset/decoders/decoders-detail.html
- public/templates/management/ruleset/rules/rules-detail.html
Hi team,
This PR adds a fix when refreshing a current rule or current decoder after an edit, in order to show its updated Details. Also allows view details that contain more than one value.
This PR solves #1273
Regards.
> Refresh rules and decoders after editing them

- public/directives/wz-table/wz-table.html
- public/less/layout.less
- public/templates/agents/agents-sca.html
- util/csv-key-equivalence.js
Hi team,
This PR shows new columns in the SCA policies tables, suggested by @wazuh/core.
Regards.
> Added new columns in SCA policies tables

- server/lib/elastic-wrapper.js
The second part of https://github.com/wazuh/wazuh-kibana-app/pull/1276, this time we are adding support for Elasticsearch security in our new cron job.
> Add support for Elasticsearch security

- public/controllers/agent/agents-preview.js
Hi team,
This PR allows filter by agent name adding tag `name` to tags filter bar autocomplete model.
This PR solves part of #1278
Regards
> Add name filter tag

- public/controllers/management/status.js
- public/less/common.less
- public/templates/management/status.html
Hi team,
This PR changes the daemons list design in the manager status section in order to show them all clearly when there are many.
Regards.
> Daemons status design changed

- public/templates/management/configuration/welcome.html
> New design for Management > Configuration, Agent > Configuration

- public/controllers/management/decoders.js
- public/controllers/management/files.js
- public/controllers/management/rules.js
- public/directives/wz-table/wz-table-directive.js
- public/directives/wz-table/wz-table.html
- public/templates/management/management.head
- public/templates/management/ruleset/decoders/decoders-detail.html
- public/templates/management/ruleset/files/files.head
- public/templates/management/ruleset/files/files.html
- public/templates/management/ruleset/rules/rules-detail.html
- public/templates/management/welcome.html
Hi team,
This PR adds the ability to edit a file from the Ruleset > Files tab, changes some labels and fixes an error when a rule/decoder id was modified.
This PR solves part of #1286 
Regards
> Management view UI improvements

- server/integration-files/monitoring-known-fields.js
- server/lib/elastic-wrapper.js
- server/monitoring.js
Hi team, this PR closes https://github.com/wazuh/wazuh-kibana-app/issues/1297
>  Discover and merge dynamic fields for monitoring

- public/controllers/management/logs.js
- public/directives/wz-config-viewer/wz-config-viewer.html
- public/directives/wz-config-viewer/wz-config-viewer.js
- public/directives/wz-config-viewer/wz-config-viewer.less
- public/directives/wz-table/wz-table-directive.js
- public/directives/wz-xml-file-editor/wz-xml-file-editor.js
- public/services/data-factory.js
- public/templates/management/logs.html
Hi team,
This PR changes the logs table for a logs viewer.
This PR solves #1250
Regards.
> Logs viewer

- public/directives/wz-table/lib/init.js
- public/directives/wz-table/wz-table-directive.js
- public/utils/table-col-resizable.js
> Not re-fetch data from tables when resize windows

- public/templates/management/groups/groups.html
Closes https://github.com/wazuh/wazuh-kibana-app/issues/1296 (removed `ng-disabled="currentGroup.name === 'default'"`)
> Add/remove agents even if it's the default group

- public/controllers/agent/agents.js
Hi team,
This PR updates the agent sync status on every sub-section change under the configuration section.
This PR solves #1302 
Regards
> Refresh check agent sync in configuration

- public/controllers/management/edition.js
- public/directives/wz-menu/wz-menu.less
- public/directives/wz-table/lib/click-action.js
- public/directives/wz-table/wz-table-directive.js
- public/directives/wz-tag-filter/wz-tag-filter.less
- public/templates/management/monitoring/nodes-detail.html
- public/templates/management/monitoring/nodes-list.html
- public/templates/management/ruleset/files/files.html
Hi team,
This PR fixes navigation on nodes tables of management > cluster section to be able to see node details if we click on them.
Regards.
> Fixes cluster nodes details

- public/less/common.less
- public/templates/management/configuration/integrity-monitoring/fim-whodata.html
Hi team,
This PRs solves some UI fixes in FIM monitored and who-data configuration.
Regards.
> Some UI fixes

- public/controllers/management/logs.js
- public/directives/wz-config-viewer/wz-config-viewer.js
- public/templates/management/logs.html
Hi team,
This PR shows a 'no results' message when there are no logs to show in the new logs viewer.
Regards
> Show no results message in logs

- CHANGELOG.md
- README.md
- package.json
There are no changes for 6.6.2, I'm just increasing the Kibana version.
Docu: https://github.com/wazuh/wazuh-documentation/pull/1032
Regards
> Bump Kibana version (v6.6.2)

- index.js
- public/app.js
- public/controllers/agent/agents.js
- public/controllers/misc/health-check.js
- public/controllers/misc/reporting.js
- public/directives/wz-menu/wz-menu.html
- public/directives/wz-menu/wz-menu.js
- public/directives/wz-welcome-card/wz-welcome-card.html
- public/less/common.less
- public/services/routes.js
- public/templates/agents/agents-welcome.html
- public/templates/management/reporting.html
- server/lib/elastic-wrapper.js
Hi team,
This PR fixes some wrong behaviors in the app routing system when the basePath is set.
This PR solves #1339 and #1135
Regards.
> Fix app routing with basePath 

- public/templates/management/configuration/agent-configuration.pug
- public/templates/management/configuration/configuration.pug
- public/templates/management/configuration/docker-listener/docker-listener.html
- public/templates/management/configuration/welcome.html
- public/utils/tab-names.js
Part of https://github.com/wazuh/wazuh-kibana-app/issues/1355, here we add the Docker listener settings into our configuration on demand views both for manager and agents as well.
> Added Docker listener settings in config views

- public/directives/wz-tag-filter/wz-tag-filter.js
This PR ports the solution described by @juankaromo in https://github.com/wazuh/wazuh-kibana-app/issues/1353#issuecomment-480877894
> Fix "AND" in agents search bar for the same field

- public/controllers/management/configuration.js
- public/templates/management/configuration/amazon-s3/amazon-s3.head
- public/templates/management/configuration/amazon-s3/amazon-s3.pug
- public/templates/management/configuration/amazon-s3/amazon-services.html
- util/remove-key.js
Hi team, this PR fixes #1392, now it's showing all the services and it's obfuscating the access keys for AWS services too.
Regards
> AWS services config

- public/controllers/management/files.js
- public/directives/wz-config-viewer/wz-config-viewer.html
- public/directives/wz-config-viewer/wz-config-viewer.js
- public/directives/wz-table/wz-table-directive.js
- public/directives/wz-table/wz-table.html
- public/services/ruleset-handler.js
- public/templates/management/ruleset/files/files.html
Hi team,
This PR adds a new feature for being able to view a no-local rule/decoder XML file, since previously only local files were allowed to be accessed.
This PR solves #1370
Regards.
> View no local rules/decoders XML files

- public/controllers/management/edition.js
- public/controllers/management/status.js
- public/templates/agents/agents-welcome.html
- public/templates/management/configuration/config-edition/config-edition.html
- public/templates/management/reporting.html
- public/templates/management/status.html
Hi team,
This PR solves some issues found during testing. Some of the fixes include:
- Disable some Restart buttons when we are not in Admin Mode
- Avoid `Restart false` button label in the config editor
- Fix config restart await, that causes unhandled exceptions.
- Fix pagination in reporting
- Changing some `font awesome` icon for EuiIcon
Regards
> Testing fixes

- public/less/common.less
- public/templates/agents/agents-sca.html
Hi team,
This PR shows the new `file_hash` field in the policies of our agents SCA section. The field has been placed (if exists) under the policy name and as Policy checksum.
This PR solves https://github.com/wazuh/wazuh-kibana-app/issues/1404
Regards.
> Show file_hash field in SCA policies

- package.json
- public/controllers/management/configuration.js
- public/templates/management/configuration/integrations/integrations.html
Hi team,
- Fix some typos (_this_ -> _these_)
- Fix missing scope property that causes Integrations section breaks
Regards
> Fix integrations

- package.json
- public/templates/management/configuration/alerts/labels.html
- public/templates/management/configuration/integrity-monitoring/fim-ignored.html
- public/templates/management/configuration/log-collection/localfile-commands.html
Hi team,
This PR fixes some sections in manager configuration on demand that were shown empty instead of showing a Not configured message.
This PR solves #1410 
Regards
> Empty sections in manager configuration on demand

- package.json
- public/controllers/management/configuration.js
- public/directives/wz-table/wz-table.html
- public/factories/tab-visualizations.js
- public/less/common.less
- public/templates/management/configuration/integrity-monitoring/fim-monitored.html
- public/templates/overview/overview-sca.html
- server/integration-files/visualizations/overview/overview-sca.js
Hi team,
For the incoming 3.9 release, we check for error handler calls that don't have prefixes like "Routes.", we fix cut off checks in the checklist of a check on policy,  the SCA overview dashboard has been reviewed, avoiding giant metrics, and follow_symbolic_link is shown now in the config on demand options.
This PR solves #1413 
Regards
> Check, fix and review

- public/directives/wz-table/wz-table.html
Hi team,
This PR fixes a syscollector tables column width problem due to the resizable columns feature.
This PR solves #1417 
Regards
> Fix table fields in not custom Columns

- CHANGELOG.md
- package.json
- public/services/error-handler.js
- public/services/notifications/global_toast_list.tsx
- public/services/notifications/toasts_service.tsx
Fixes #1418 
Added a new condition so we can customize the lifetime depending on the toaster type:
```js
public render() {
const increaseTime = ((this.state || {}).toasts || []).some(
item => item.color === 'danger'
);
return (
<EuiGlobalToastList
toasts={this.state.toasts}
dismissToast={this.props.dismissToast}
toastLifeTimeMs={increaseTime ? 30000 : 6000}
/>
);
}
```
> Fix toaster time

- public/controllers/dev-tools/dev-tools.js
- public/directives/wz-config-viewer/wz-config-viewer.html
- public/directives/wz-config-viewer/wz-config-viewer.js
- public/directives/wz-list-manage/wz-list-manage.html
- public/directives/wz-xml-file-editor/wz-xml-file-editor.js
- public/less/common.less
- public/templates/management/configuration/cluster/cluster.html
- public/templates/management/configuration/config-edition/config-edition.html
- public/templates/management/groups/groups.html
- public/templates/management/ruleset/decoders/decoders-detail.html
- public/templates/management/ruleset/files/files.html
- public/templates/management/ruleset/rules/rules-detail.html
Instead of having static heights, this PR adds the ability to set the height for certain sections depending on the window height.
> Dynamic heights

- public/controllers/dev-tools/dev-tools.js
- public/controllers/management/logs.js
- public/directives/wz-config-viewer/wz-config-viewer.js
Hi team,
This PR solves some bugs in management logs viewer (wrong dynamic height and continuous scrolling top), and in the dev tools ( weird behavior in resizable columns feature).
Regards.
> Fix logs viewer height and dev-tools resizable

- public/directives/wz-config-viewer/wz-config-viewer.html
- public/directives/wz-config-viewer/wz-config-viewer.js
- public/directives/wz-list-manage/wz-list-manage.html
- public/directives/wz-xml-file-editor/wz-xml-file-editor.html
- public/directives/wz-xml-file-editor/wz-xml-file-editor.js
- public/directives/wz-xml-file-editor/wz-xml-file-editor.less
- public/templates/management/configuration/cluster/cluster.html
- public/templates/management/configuration/config-edition/config-edition.html
- public/templates/management/groups/groups.html
- public/templates/management/ruleset/decoders/decoders-detail.html
- public/templates/management/ruleset/files/files.html
- public/templates/management/ruleset/rules/rules-detail.html
Hi team,
Like in 7.0 app, instead of having static heights, this PR adds the ability to set the height for certain sections depending on the window height, and improve the calculation method to take care when the editor has more than one header.
This PR solves https://github.com/wazuh/wazuh-kibana-app/issues/1439
Regards.
> Improve dynamic height

- public/less/dark_theme/wz_theme_dark.css
Hi team,
This PR prevents map type visualizations from being shown with a dark theme.
Regards.
> Removed dark theme in map visualizations

- package.json
- public/controllers/management/configuration.js
- public/templates/management/configuration/alerts/labels.html
- public/templates/management/configuration/client/client.html
Hi team
This PR fixes some points in agents configuration on demand, like missing fields or empty tables.
This PR solves https://github.com/wazuh/wazuh-kibana-app/issues/1435
Regards
> Minor fixes in agents configuration 

- public/directives/wz-xml-file-editor/wz-xml-file-editor.js
Hi team,
This PR stops filtering by the current path in files configuration validations.
This PR solves #1436 
Regards.
> No filter by path in config validation

- public/controllers/management/logs.js
- public/directives/wz-config-viewer/wz-config-viewer.js
Hi team,
This PR solves a continuous top scrolling bug in new management logs viewer.
Regards.
> Fix logs viewer top scrolling

- public/directives/wz-table/wz-table.html
- public/templates/agents/agents-sca.html
Hi team,
This PR fixes the width of File column and the word-break in Status column.
This PR solves #1472 
Regards.
> Fix SCA result status and file width cells

- public/kibana-integrations/loader/visualize_data_loader.ts
- public/less/common.less
Hi team, 
This PR manages to show the top line of visualizations and not just half of the line as the screenshot below:
This PR solves #1379 
Regards
> Fix covered points in visualizations

- public/controllers/agent/agents-preview.js
- public/directives/wz-tag-filter/wz-tag-filter.js
https://github.com/wazuh/wazuh-kibana-app/issues/1511
> Keep tags filters on agents search reloading

- public/controllers/agent/components/register-agent.js
Hi team,
This PR changes de steps in the agent's registration guide with the aim of letting only the install command.
Regards.
> Change register agent guide messages

- server/controllers/wazuh-reporting.js
> Export group config

- public/controllers/agent/agents.js
Hi team, 
This PR fixes the call to obtain the GDPR requirements on an agent.
This PR solves #1543 
Regards.
> Fix the call to obtain GDPR requirements

- CHANGELOG.md
- package.json
Hi team,
This PR prepares the branch for the release of 3.9.3
Regards.
> 3.9.3 release 

- public/directives/wz-table/wz-table-directive.js
- public/directives/wz-table/wz-table.html
Hi team,
This PR fixes the displaying of some tooltips in tables truncated fields.
This PR solves  #1604 
Regards.
> [6.8] Fix show tootlip in truncated fields

- CHANGELOG.md
- public/controllers/settings/components/api-table.js
Prepares branch to Wazuh 3.9.4
> Changelog 3.9.4

- public/kibana-integrations/kibana-discover.js
Hi team,
This PR solves the casuistic of having pinned agent filters across sections explained here https://github.com/wazuh/wazuh-kibana-app/issues/1626
Regards.
> Fix pinned agent filters

- public/directives/wz-table-eui/components/table.js
- public/directives/wz-table-eui/wz-table-directive.js
Hi team, 
This PR fixes the pagination problem in eui tables when we did a search on a page different to the first one.
This PR solves #1634 
Regards.
> Fix eui tables pagination in searches

- package.json
- public/templates/management/monitoring/main-timelions.html
- public/templates/management/monitoring/main.html
- public/templates/management/monitoring/nodes-detail.html
- server/initialize.js
- server/lib/refresh-known-fields.js
- server/monitoring.js
Thi PR applies some fixes for 3.9.3-7.1.1 version.
> 3.9.3-7.1.1 fixes

- CHANGELOG.md
- README.md
- package.json
- public/kibana-integrations/kibana-discover.js
- public/kibana-integrations/loader/visualize_loader.ts
- public/kibana-integrations/search-bar/filter-generator.tsx
- public/kibana-integrations/search-bar/filter-manager.tsx
- public/kibana-integrations/search-bar/filter-state-manager.tsx
- public/kibana-integrations/search-bar/only_disabled.tsx
- public/kibana-integrations/search-bar/query-filter.ts
- public/kibana-integrations/search-bar/setup.tsx
Bump changes from 3.9-7.3 to 3.10-7.3
> Bump 3.9-7.3 to 3.10-7.3

- public/templates/management/configuration/amazon-s3/amazon-buckets.html
- public/templates/management/configuration/amazon-s3/amazon-services.html
Hi team,
This PR solves #1675 , now we can correctly see AWS-S3 configuration on both Buckets and Services subtabs.
> AWS-S3 configuration is not being shown correctly

- public/factories/tab-visualizations.js
- public/templates/overview/overview-fim.html
- server/integration-files/visualizations/overview/overview-fim.js
As @petersutty commented on #1527 , here is a new table visualization added to Overview > FIM dashboard.
> Added "Alerts summary" table for Overview > FIM

- public/controllers/agent/agents.js
- public/controllers/agent/components/welcome.js
- public/controllers/overview/components/welcome.js
- public/templates/overview/overview.head
Hi team,
This PR fixes de overview and agents welcome card that not was showing HIPAA and NIST options.
> Fix HIPAA and NIST welcome cards in overviews

- public/controllers/agent/agents.js
- public/controllers/overview/overview.js
- public/kibana-integrations/kibana-discover.js
- public/templates/management/monitoring/nodes-detail.html
Hi team,
This PR fixes that the state makes filters disappear in Agent > FIM.
This PR solves #1700 
Regards
> Fix lost of filters in FIM

- public/controllers/agent/agents.js
- public/controllers/agent/components/welcome.js
- public/controllers/management/configuration.js
- public/controllers/management/groups.js
- public/controllers/management/management.js
- public/controllers/overview/components/welcome.js
- public/controllers/overview/overview.js
- public/controllers/settings/settings.js
- public/services/common-data.js
- public/templates/agents/agents.head
- public/templates/management/configuration/active-response/active-response.head
- public/templates/management/configuration/alerts/alerts.head
- public/templates/management/configuration/amazon-s3/amazon-s3.head
- public/templates/management/configuration/cis-cat/cis-cat.head
- public/templates/management/configuration/global-configuration/global-configuration.head
- public/templates/management/configuration/integrity-monitoring/integrity-monitoring.head
- public/templates/management/configuration/log-collection/log-collection.head
- public/templates/management/configuration/open-scap/open-scap.head
- public/templates/management/configuration/policy-monitoring/policy-monitoring.head
- public/templates/management/configuration/vulnerabilities/vulnerabilities.head
- public/templates/management/groups/groups.html
- public/templates/overview/overview.head
- public/templates/settings/settings.head
Hi team,
This PR solves https://github.com/wazuh/wazuh-kibana-app/issues/1707 and, in addition, we performed a refactor to replace the old `md-nav-bar` elements in the dashboards with the new react `Tabs` component in a dynamic load way, avoiding a lot of conditions checks.
Regards
> Improve tabs bars with Tabs component

- public/directives/wz-table/wz-table-directive.js
- util/csv-key-equivalence.js
This PR solves https://github.com/wazuh/wazuh-kibana-app/issues/1710
> Hide attributes in non windows agent FIM files

- public/templates/overview/overview-hipaa.html
- server/integration-files/visualizations/overview/overview-hipaa.js
> Replaced HIPAA panel

- public/templates/management/configuration/welcome.html
Hi team,
This PR solves https://github.com/wazuh/wazuh-kibana-app/issues/1717.
The conditions on the HTML template were bad formatted.
Regards,
> Fix export configuration

- public/templates/dev-tools/dev-tools.html
- server/controllers/wazuh-reporting.js
Hi team, 
This PR solves the duplicated content in the groups reports.
Also, fix the tooltip of the `Export as JSON` icon in the DevTools.
Solves https://github.com/wazuh/wazuh-kibana-app/issues/1721
Regards,
> Fix groups reporting

- server/controllers/wazuh-api.js
- util/csv-key-equivalence.js
Changes:
- Added missing keys for our keys equivalence file: "key", "value", "registerIP". https://github.com/wazuh/wazuh-kibana-app/commit/f2452dac56bf9b766ef2cf363b626b2186932491
- Init the CSV parser with custom fields, using the property `default` as `-` for missing values. https://github.com/wazuh/wazuh-kibana-app/commit/94492b7090d37410da4824ee6913e043f8c5b964
- Fixed agents of a group CSV https://github.com/wazuh/wazuh-kibana-app/commit/94492b7090d37410da4824ee6913e043f8c5b964
- Fixed CDB lists CSV https://github.com/wazuh/wazuh-kibana-app/commit/94492b7090d37410da4824ee6913e043f8c5b964
> Fixes for CSV exporting module

- public/kibana-integrations/search-bar/filter_bar.tsx
Hi team,
This PR is part of https://github.com/wazuh/wazuh-kibana-app/issues/1726 and it fixes https://github.com/wazuh/wazuh-kibana-app/issues/1726#issuecomment-525235932.
> Fix "pin all" feature, not breaking our implicit filters

- public/controllers/management/groups.js
- public/kibana-integrations/kibana-discover.js
- public/templates/management/groups/groups.html
Hi team,
This PR solves some more issues from here https://github.com/wazuh/wazuh-kibana-app/issues/1727
Regards.
> More fixes in 3.10-6.8

- server/controllers/wazuh-api.js
This PR fixes "Removing multiple agents using an object instead of URL query gave me an error, also, the framework team has an unhandled exception that we've just reported them." from https://github.com/wazuh/wazuh-kibana-app/issues/1726.
In addition, we are now handling properly more requests and their parameters that were not being handled as they should be.
> Improve how we handle Wazuh API requests

- public/directives/wz-menu/wz-menu.html
- public/directives/wz-menu/wz-menu.js
- public/less/dark_theme/wz_theme_dark.css
Hi team,
This PR fixes the calculated height of our new position fixed `wz-menu`.
Regards.
> Fix wz-menu calculated height

- public/controllers/dev-tools/dev-tools.js
- public/controllers/management/configuration.js
- public/directives/wz-config-viewer/wz-config-viewer.js
- public/directives/wz-xml-file-editor/wz-xml-file-editor.js
- public/templates/management/configuration/active-response/active-response.html
- public/templates/management/configuration/active-response/agents-active-response.html
- public/templates/management/configuration/active-response/commands.html
- public/templates/management/configuration/alerts/email-alerts.html
- public/templates/management/configuration/alerts/general-alerts.html
- public/templates/management/configuration/alerts/labels.html
- public/templates/management/configuration/alerts/reports.html
- public/templates/management/configuration/alerts/syslog.html
- public/templates/management/configuration/amazon-s3/amazon-s3.head
- public/templates/management/configuration/global-configuration/global.html
- public/templates/management/configuration/global-configuration/remote.html
- public/templates/management/configuration/integrity-monitoring/integrity-monitoring.head
- public/templates/management/configuration/log-collection/localfile-commands.html
- public/templates/management/configuration/log-collection/localfile-logs.html
- public/templates/management/configuration/log-collection/socket.html
- public/templates/management/configuration/wazuh-commands/wazuh-commands.html
- public/utils/dynamic-height.js
Hi team,
This PR adds the capability to calculate dynamically the height of the configuration cards in order to solve the **Dynamic height for some configuration sections is not working as expected (not taking all the available space, reducing the card to a small card with a scroll bar)** point related in this issue https://github.com/wazuh/wazuh-kibana-app/issues/1726.
Also in order to improve this functionality and prevent duplicated code, I've created a class called `DynamicHeight` that can be used in all the controllers which had individual functions to calculate the height. https://github.com/wazuh/wazuh-kibana-app/pull/1743/commits/5732c335d2ee5293c6070c647df76c20a3679825
Regards,
> Calculate dynamically the height of the configuration cards.

- CHANGELOG.md
- package.json
- public/kibana-integrations/kibana-discover.js
Hi team,
This PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/1758, the interval is now working properly for Discover tabs.
Thank you @branchnetconsulting for reporting, your feedback is always welcome and very valuable for us.
Regards,
Jesús
> [6.8] Restored "$state.interval" built-in logic for Discover

- public/controllers/agent/agents-preview.js
- public/controllers/agent/components/register-agent.js
Hi team,
This PR changes the interactive guide to register an agent by a package installation.
Regards,
> Improve commands for register agents guide

- public/directives/wz-table/wz-table-directive.js
Hi team,
The view/edition of ruleset table files was broken due to lens removal.
Regards.
> [6.8] Fix edit files navigation in ruleset

- public/directives/wz-table/wz-table-directive.js
Hi team,
The view/edition of ruleset table files was broken due to lens removal.
Regards.
> Fix edit files navigation in ruleset

- public/directives/wz-menu/wz-menu.less
- public/directives/wz-tag-filter/wz-tag-filter.less
Hi team,
This PR sets the proper background and color to the inputs and select options. 
Regards,
> Fix selects and inputs colors

- public/directives/wz-table-eui/wz-table-directive.js
- util/csv-key-equivalence.js
Changes:
- Replaced "CMD" with "Command"
- Do not show "-" when the value is "0"
> Minor fixes for Inventory tab

- CHANGELOG.md
- package.json
- server/controllers/wazuh-api.js
Hi team,
APIs passwords are now obfuscated in server responses. Also, this PR prepares the 6.8 branch for release.
Regards.
> 3.10 6.8 hide plain passwords

- CHANGELOG.md
- package.json
- server/controllers/wazuh-api.js
Hi team,
This PR hides the secret from the API entry.
Previous response:
```json
{  
"statusCode":200,
"data":{  
"user":"foo",
"secret":"bar",
"url":"http://localhost",
"port":"55000",
"insecure":"true",
"extensions":{  
"audit":true,
"pci":true,
"gdpr":true,
"hipaa":true,
"nist":true,
"oscap":false,
"ciscat":false,
"aws":false,
"virustotal":false,
"osquery":false,
"docker":false
},
"fetched_at":1568105395882,
"password":"****",
"cluster_info":{  
"status":"enabled",
"manager":"master",
"node":"manager_01",
"cluster":"wazuh"
}
},
"idChanged":null
}
```
Current response:
```json
{  
"statusCode":200,
"data":{  
"user":"foo",
"secret":"****",
"url":"http://localhost",
"port":"55000",
"insecure":"true",
"extensions":{  
"audit":true,
"pci":true,
"gdpr":true,
"hipaa":true,
"nist":true, …
```
> Hide API secret

- CHANGELOG.md
- README.md
- package.json
- public/app.js
This PR updates 3.10-7.3 branch with 7.3.2 changes
> Update release 7.3.2

- server/controllers/wazuh-reporting.js
Hi team,
This PR adds info, debug and error logs for the reporting module.
> Added info, debug and error logs for the reporting module

- server/controllers/wazuh-api.js
Hi team,
This PR solves the thrown error when getting a file and its content is empty.
Solves: https://github.com/wazuh/wazuh-kibana-app/issues/1806
Regard,
> Fix when getting an empty file

- public/controllers/management/cdblists.js
- server/controllers/wazuh-api.js
Hi team,
This PR solves the thrown error when getting a file and its content is empty.
Solves: https://github.com/wazuh/wazuh-kibana-app/issues/1806
Regard,
> Fix empty files

- server/controllers/wazuh-api.js
Hi team,
This PR solves #1815 
Regards
> Validate method and path in Requests

- public/controllers/dev-tools/dev-tools.js
- public/directives/wz-menu/wz-menu.html
- public/templates/dev-tools/dev-tools.html
Hi team,
This PR changes the `Tools` section by `Dev tools` in the wazuh menu.
Regards,
> Replace tools by dev tools

- server/controllers/wazuh-api.js
Hi team,
This PR solves https://github.com/wazuh/wazuh-kibana-app/issues/1833
Regards,
> Fix when exporting as csv the files in a group

- public/controllers/management/components/upload-files.js
- public/templates/management/ruleset/cdblists/cdblists-list.html
- public/templates/management/ruleset/files/files.html
Hi team,
This PR solves https://github.com/wazuh/wazuh-kibana-app/issues/1835
Regards,
> Check the admin mode in the upload files component

- server/lib/update-configuration.js
Hi team,
This PR solves: https://github.com/wazuh/wazuh-kibana-app/issues/1838
Regards,
> Fix when checking admin mode

- public/templates/management/configuration/global-configuration/global.html
#1773 
Fix the hidden content in the global configuration section of `management -> configuration`
> Fix the hidden content in management>configuration

- public/controllers/management/components/reporting-table.js
- public/controllers/settings/components/add-api.js
- public/controllers/settings/components/api-is-down.js
- public/controllers/settings/settings.js
- public/less/common.less
Hi team, 
This PR improves the warning message and responsive style.
Regards,
> Improve API messages and styles

- public/templates/management/configuration/integrations/integrations.html
The `custom-[integrations]` don't show up in the
`management -> configuration -> integrations` view
> Fixes hidden integrations in the config view

- public/utils/wz-logo-menu.js
This PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/1871
> Fix logo when reverse proxy is enabled

- public/directives/wz-no-config/wz-no-config.html
> [3.11-7.4] Fix ambiguous message

- public/directives/wz-no-config/wz-no-config.html
> [3.11-6.8] Fix ambiguous message in configuration section

- public/templates/management/configuration/amazon-s3/amazon-s3.head
This PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/1864
> Amazon s3 status fix

- public/directives/wz-no-config/wz-no-config.html
- public/templates/management/configuration/amazon-s3/amazon-s3.head
- public/templates/management/configuration/integrity-monitoring/integrity-monitoring.head
- public/utils/wz-logo-menu.js
Backports from 3.11-7.4 to 3.11-7.2
> 3.11-7.2 backports

- public/controllers/agent/components/agents-table.js
- Set pageIndex to `0` when the search value change
- Delete a comment
- Delete Blanks
> Apply some corrections to the agentsTable component

- server/integration-files/known-fields.js
Backport of the commit 6058d18 from 3.11-7.2 branch
> Add know fields for AWS and Docker 3.11-6.8

- public/controllers/agent/components/register-agent.js
- public/less/common.less
Hi team,
This PR fixes an error in the agent registration guide for macOS.
Some styles have also been fixed.
Regards,
> Fix registration guide

- public/templates/management/ruleset/files/files.html
Backports of https://github.com/wazuh/wazuh-kibana-app/pull/1929 to 3.11-6.8
> Fix decoders file

- public/templates/management/ruleset/files/files.html
Backports of https://github.com/wazuh/wazuh-kibana-app/pull/1929 to 3.11-7.2
> [3.11-7.2] Fix decoders file

- public/controllers/agent/components/register-agent.js
- public/less/common.less
Backports of https://github.com/wazuh/wazuh-kibana-app/pull/1926 to 3.11-7.2
> [3.11-7.2]  Fix registration guide

- public/controllers/agent/components/register-agent.js
- public/less/common.less
Backports of https://github.com/wazuh/wazuh-kibana-app/pull/1926 to 3.11-6.8
> [3.11-6.8] Fix registration guide

- public/components/eui-loader.js
- public/controllers/agent/agents.js
- public/directives/wz-syscheck-table/components/syscheck-table.js
- public/templates/agents/agents-fim.html
Hi team,
Backports of #1941  to 3.11-7.4
> [3.11-7.4] Refactor syscheck table 

- CHANGELOG.md
- README.md
- index.js
Hi team,
This PR solves this issue #1822
Regards!
> Add x-pack integration

- index.js
> Add x-pack integration 7.5.1

- public/controllers/settings/components/api-is-down.js
- public/controllers/settings/settings.js
- public/templates/settings/settings.head
Hi team,
This PR closes #1988.
> Set default API

- server/controllers/wazuh-reporting.js
Backports of https://github.com/wazuh/wazuh-kibana-app/pull/2027
> [3.11-7.5] Add WindowsUpdate table to report

- server/controllers/wazuh-api.js
- server/lib/api-interceptor.js
- wazuh.yml
Hi team!
In this PR, we have revised and modified the check-api function of the BackEnd to work with the new API 4.0.
This PR is part of the issue #2034
> New api/check api

- server/lib/api-interceptor.js
Hi team!
In this PR, we have solved a problem with api-interceptor authentication when updating the wazuh-registry
This PR is part of the issue #1998
> Fix update-registry.json problems

- public/controllers/misc/health-check.js
Hi team!
In this PR, we have revised and modified the health-check class of the FrontEnd to work with the new API 4.0.
This PR is part solves the issue #2036
> Adapt health-check to new API 4.0

- package.json
- server/controllers/wazuh-api.js
- server/lib/api-interceptor.js
Hi team!
In this PR, we have revised and modified api-interceptor to accept payload for the body, and params for the query
This PR is part solves the issue #1998
> Add params and payload to api-interceptor

- public/controllers/management/components/management/ruleset/rule-info.js
The table with the information and details about **ruleset** has been modified and restructured.
_Old table_
**Modifications:**
- The 4 upper panels become 3 panels.
- The columns of PCI, GDPR .... disappear and are unified in a single "Compliance" column.
- Some fix for console errors.
_New table_
> 3.12 7.5 fix compliance

- public/controllers/agent/agents.js
- public/controllers/agent/components/agents-preview.js
- public/controllers/agent/components/agents-table.js
- public/controllers/management/components/management/configuration/configuration-overview.js
- public/controllers/management/components/management/configuration/utils/wz-fetch.js
- server/controllers/wazuh-api.js
- server/controllers/wazuh-reporting.js
Hi team!
In this PR, we have revised and modified the exports PDF function to work with the new API 4.0.
This PR is part of the issue #2073
> New api/exportpdf

- public/react-services/app-state.js
> Fix error when downgrading from 3.12 versions

- public/components/visualize/visualizations.js
- public/kibana-integrations/kibana-vis.js
- public/less/dark_theme/wz_theme_dark.css
- public/templates/discover/discover.html
- server/integration-files/visualizations/overview/overview-aws.js
Hi team,
This PR fixes some errors found when testing all the dashboards of the Wazuh UI after migrating these dashboards to a React component:
- AWS map zoom is now correctly set.
- Vulnerability visualizations width has been fixed.
- Error handling has been added to every visualization
- Dark mode styling fixes
- Removed unused parameters from the visualizations.js file
> Dashboard testing fixes

- README.md
Hi team,
In this PR, we have solved a problem with the upgrade guide of Wazuh UI.
This PR is part of the issue #2118
> Update README for upgrade guide

- package.json
- public/controllers/management/components/management/configuration/edit-configuration/edit-configuration.js
- public/controllers/management/components/management/configuration/utils/wz-fetch.js
Hi team,
In this PR, We have added the details of the errors when editing the configuration.
This PR is part of the issue #2128
> 3.12.0 7.6.1 details errors

- public/components/wz-menu/wz-menu.js
- public/react-services/app-state.js
Hi team,
This PR closes #2143:
- Added a new API selector.
- API / Index pattern selectors are hidden if there are less than 2 items.
- Management popover has been removed.
- Visualize tab has been renamed with Overview.
> Add API selector

- public/components/wz-menu/wz-menu.js
- public/controllers/management/components/management/ruleset/list-editor.js
- public/controllers/management/components/management/ruleset/ruleset-search-bar.js
- Fixed `compliance` in the rules search bar.
- CDB List style modified to add a new list.
> Fix compliance name requirement and change CDB list rule

- public/templates/management/configuration/integrity-monitoring/fim-general.html
- public/templates/management/configuration/integrity-monitoring/fim-synchronization.html
- public/templates/management/configuration/integrity-monitoring/integrity-monitoring.head
- public/templates/management/configuration/integrity-monitoring/integrity-monitoring.pug
Hi team, this PR:
- add new FIM settings
**Issue**: https://github.com/wazuh/wazuh-kibana-app/issues/2147
**Branch**: [3.12-7.6-new-fim-settings-#2147](/wazuh/wazuh-kibana-app/tree/3.12-7.6-new-fim-settings-%232147)
> 3.12-7.6 New fim settings

- package.json
- public/controllers/management/components/management/ruleset/ruleset-search-bar.js
- public/controllers/management/components/management/ruleset/ruleset-table.js
- public/controllers/management/components/management/ruleset/utils/columns.js
Hi team!
In this PR, we have revised and modified the Rules to work with the new API 4.0.
This PR is part of the issue #2167
> New api/new rules

- public/controllers/management/components/management/ruleset/decoder-info.js
- public/controllers/management/components/management/ruleset/rule-info.js
- public/controllers/management/components/management/ruleset/ruleset-search-bar.js
- public/controllers/management/components/management/ruleset/ruleset-table.js
- public/controllers/management/components/management/ruleset/utils/ruleset-handler.js
Hi team!
In this PR, we have revised and modified the Decoders to work with the new API 4.0.
This PR is part of the issue #2168
> New api/new decoders

- public/controllers/management/components/management/ruleset/ruleset-table.js
- public/controllers/management/components/management/ruleset/utils/columns.js
- public/controllers/management/components/management/ruleset/utils/ruleset-handler.js
- server/controllers/wazuh-api.js
Hi team!
In this PR, we have revised and modified the CDB Lists to work with the new API 4.0.
This PR is part of the issue #2177
> New api/new cdblists

- public/templates/agents/agents-syscollector.html
Hi team,
This PR shows all syscollector data stored for a currently disconnected agent instead of showing that the agent has never connected.
This PR solves #1996 
Regards
> Show Inventory data in disconnected agents

- package.json
- public/controllers/management/components/management/groups/actions-buttons-agents.js
- public/controllers/management/components/management/groups/actions-buttons-files.js
- public/controllers/management/components/management/groups/actions-buttons-main.js
- public/controllers/management/components/management/groups/utils/columns-files.js
- public/controllers/management/components/management/groups/utils/columns-main.js
- public/controllers/management/components/management/groups/utils/groups-handler.js
- public/controllers/management/groups.js
- server/controllers/wazuh-api.js
- server/controllers/wazuh-reporting.js
Hi team!
In this PR, we have revised and modified the Management > groups to work with the new API 4.0.
This PR is part of the issue #2179
> New api/new groups

- public/controllers/management/components/management/configuration/edit-configuration/edit-configuration.js
- public/controllers/management/components/management/configuration/util-components/refresh-cluster-info-button.js
- public/controllers/management/components/management/configuration/utils/wz-fetch.js
Hi team!
In this PR, we have revised and modified the Management > configuration to work with the new API 4.0.
This PR is part of the issue #2185
> New api/new configuration section

- public/controllers/management/components/management/mg-logs/logs.js
- public/controllers/management/components/management/status/actions-buttons-main.js
- public/controllers/management/components/management/status/status-overview.js
- public/controllers/management/monitoring.js
Hi team!
In this PR, we have revised and modified the Management > status / cluster / logs / reporting,  to work with the new API 4.0.
This PR is part of the issue #2186
> New api/new status reports

- public/controllers/agent/agents.js
- public/controllers/agent/components/agents-table.js
- public/controllers/management/components/management/configuration/utils/wz-fetch.js
Hi team!
In this PR, we have revised and modified the **Agents**, to work with the new API 4.0.
This PR is part of the issue #2189
> New api/new agents

- public/components/eui-suggest/suggest_input.js
- public/components/wz-menu/wz-menu.js
- public/controllers/misc/health-check.js
- public/controllers/overview/components/stats.js
- public/controllers/settings/settings.js
- public/react-services/generic-request.js
- public/react-services/pattern-handler.js
- public/react-services/saved-objects.js
- public/react-services/wz-api-check.js
- public/react-services/wz-request.js
- public/services/resolves/get-ip.js
- public/services/resolves/settings-wizard.js
- public/templates/health-check/health-check.html
- server/controllers/wazuh-api.js
- server/controllers/wazuh-elastic.js
- server/routes/wazuh-elastic.js
Hi team,
This PR solves:
- **Improve navigation performance** https://github.com/wazuh/wazuh-kibana-app/issues/2200. We were doing some API requests on every navigation, this PR solves these and allows the app to load new pages faster.
- **Migrate IndexPattern management to use the SavedObject APIs** https://github.com/wazuh/wazuh-kibana-app/issues/2197 The `wazuh-alerts-3.x-*` index patter was being created by directly writing into the .kibana index which is not recommended, the app now creates this index pattern in the health check using the Saved Object API (without restarting Kibana) it solves some problems when using Opendistro tenants or Kibana spaces
> Improve index management and performance

- public/components/wz-menu/wz-menu-overview.js
Hi team,
This PR fixes an error when opening the main menu, disabled extensions were being shown for a sec, it is now fixed
> Fix wz-menu extensions

- public/controllers/management/components/management/mg-logs/logs.js
Hi team!
In this PR, we have revised and modified the Management > logs, to work with the new API 4.0.
This PR is part of the issue #2217
> Adapt management > logs to new API 4.0

- public/components/settings/api/add-api.js
- public/components/settings/api/api-is-down.js
- public/components/settings/api/api-table.js
- public/controllers/settings/settings.js
- server/controllers/wazuh-api.js
- server/lib/api-helper.js
- server/lib/initial-wazuh-config.js
- server/lib/manage-hosts.js
- test/server/wazuh-api.js
Hi team!
In this PR, we have revised and modified the Wazuh API Configuration, to work with the new API 4.0.
This PR is part of the issue #2221
> Adapt Wazuh API configuration

- public/components/common/restart-cluster-manager-callout.tsx
- public/controllers/management/components/management/configuration/utils/wz-fetch.js
- public/controllers/management/components/management/ruleset/list-editor.js
- public/controllers/management/components/management/ruleset/ruleset-editor.js
Hi team, this pr resolves:
Add a **warning callout** when create/edit a file in:
- Management/Rules
- Management/Decoders
- Management/CDB List
> 3.13 7.6 - Warning callout in Rules, Decoders and CDB List

- public/components/common/welcome/agents-welcome.js
- public/components/common/welcome/components/mitre_top/index.ts
- public/components/common/welcome/components/mitre_top/lib/get_mitre_counts.ts
- public/components/common/welcome/components/mitre_top/lib/index.ts
- public/components/common/welcome/components/mitre_top/mitre_top.tsx
- server/integration-files/visualizations/agents/agents-welcome.js
Hello team,
With this PR a new component is added, integrates MITRE, in the new `welcome-agent`.
This component shows a top 5 tactics filtered by the agent, if we click on a tactic we will see a top 5 techniques, and clicking on the technique we will see all the information related to it.
> 3.13 7.6 mitre welcome agent

- public/components/agents/fim/inventory/fileDetail.tsx
Hi team,
This PR fixes the button `Inspect in discover` in our FIM flyout:
It has been fixed for both Overview->FIM flyout and Agents Welcome->FIM flyout. 
We can now middle click to open details in a new tab.
> Fix fim redirection

- public/components/agents/fim/inventory/fileDetail.tsx
Hi team,
With this PR we solved a problem that occurred in Safari when filtering by date.
> Fix filter by date in Safari browser

- public/components/agents/sca/inventory.tsx
Hi team,
In this PR, we added the control on non mandatory fields in SCA rules, explained in this issue #2264
Regards,
Alberto
> Add control in non mandatory fields in SCA rules

- public/components/agents/fim/inventory/registry-table.tsx
- public/components/agents/fim/inventory/table.tsx
- public/components/wz-search-bar/lib/suggest-handler.ts
Hey, team!
This PR adds an error message to the Fim tables when the request is rejected. In the other hand, We add some conditions to prevent create filters with an empty value
Regards
> Added error message on rejected request

- public/components/overview/metrics/index.ts
- public/components/overview/metrics/metrics.tsx
- public/components/visualize/agent-visualizations.js
- public/components/visualize/visualizations.js
- public/components/visualize/wz-visualize.js
- public/templates/agents/visualizations.js
Hi team,
This PR replaces our old metrics with a new component that makes a request directly to Elasticsearch to obtain the data more efficiently
> Remove old metrics. Add new component to show metrics

- public/components/overview/compliance-table/compliance-table.tsx
- public/components/overview/compliance-table/components/requirements/requirements.tsx
- public/components/overview/compliance-table/components/subrequirements/subrequirements.tsx
- public/components/overview/mitre/components/tactics/tactics.tsx
- public/components/overview/mitre/components/techniques/techniques.tsx
- public/components/overview/mitre/mitre.tsx
Hi team!
Fixed the update button in the Miter Frame component and the compliance inventory component.
On the other hand, we made changes in the loading animation in both components.
Regards.
> Fixed the refresh button and improved the loading animation

- public/controllers/overview/overview.js
- public/kibana-integrations/kibana-vis.js
Hi team,
This PR adds loading animation to our visualization instead of showing blank visualizations
> Add loading animation to visualizations

- public/components/wz-agent-selector/wz-agent-selector.js
Hi team,
Agent wasn't being correctly switched when doing that from the main menu, this PR fixes it.
> Fix error when switching pinned agent from the main menu

- public/components/overview/metrics/metrics.tsx
Hi team,
Everytime we access to a dashboard we were getting this error:
This PR fixes that error
> Remove error on range filter whne building metrics

- public/controllers/dev-tools/dev-tools.js
Hi team,
With this PR, we have solved a problem in devtools that caused an error when making a query with the admin mode activated.
> 3.13-7.7 fix devtools

- public/components/overview/metrics/metrics.tsx
Hi team,
The new metrics component wasn't showing the loading animation correctly, this PR fixes it
> Fix loading animation on new metrics component

- public/components/wz-search-bar/lib/filters-to-object.ts
- public/controllers/management/components/management/groups/get-agents-filters-values.js
- public/controllers/management/components/management/groups/group-agents-table.js
- public/controllers/management/components/management/groups/group-files-table.js
- public/controllers/management/components/management/groups/groups-table.js
Hi team,
This PR adds the searchbar to our group section and agents/files subtabs;
> Add searchbar to Groups section

- public/components/agents/fim/inventory.tsx
Hi team!
In this PR, we have solved a problem that occurred when exporting in CSV in the FIM table, with filters applied. Now it doesn't happen anymore and it works correctly.
> Fixed export in FIM with filters

- public/components/wz-agent-selector/wz-agent-selector.js
- public/components/wz-menu/wz-menu.js
- public/controllers/agent/agents.js
Hi team,
This PR fixes the error when trying to change the pinned agent from the Agents section.
> Fix error when changing pinned agent

- public/components/common/modules/discover/discover.tsx
- public/components/overview/mitre/lib/elastic-helpers.ts
Hi team,
The hideManagerAlerts setting is supposed to hide alerts from the manager, this wasn't applied in new components like Metrics, Mitre Framework, Compliance Controls or our custom discover.
> Add hideManagerAlerts to missing sections

- public/components/overview/compliance-table/components/requirements/requirements.tsx
- public/components/overview/compliance-table/components/subrequirements/subrequirements.tsx
> Add options menu to Regulatory Compliance component

- public/components/common/modules/main-agent.tsx
- public/components/eui-loader.js
- public/templates/agents/agents-syscollector.html
Hi team!
With this PR, the reporting system for inventory data is added as described in this issue #2313
> Reporting in Inventory data

- public/components/agents/sca/inventory.tsx
Hi team,
This PR adds a new searchbar to the SCA section: 
ONLY 3 fields are being shown as the API isn't working correctly with the others fields: https://github.com/wazuh/wazuh/issues/5312
> Add searchbar to SCA

- public/components/overview/metrics/metrics.tsx
> Adapt metrics to update on searchbar query updates

- public/components/eui-loader.js
- public/controllers/agent/agents.js
- public/directives/wz-eui-prompt/components/wz-eui-prompt.js
- public/templates/agents/agents-syscollector.html
Hi team,
This PR fixes the error when accessing the Syscollector(Inventory Data) section with a never connected agent
> Fix blank page on syscollector with neverconnected agents

- public/controllers/agent/components/agents-preview.js
- public/kibana-integrations/kibana-vis.js
- public/kibana-integrations/kibana-visualization.js
- server/integration-files/visualizations/overview/overview-general.js
> Show timepicker when there are no results in Agents Evolution vis

- public/components/eui-loader.js
- public/controllers/agent/agents.js
- public/controllers/agent/components/agents-preview.js
- public/controllers/agent/components/agents-table.js
- public/controllers/management/components/management/groups/get-agents-filters-values.js
- public/controllers/overview/components/overview-actions/agents-selection-table.js
- public/controllers/overview/components/overview-actions/agents-selector.less
- public/directives/wz-eui-prompt/components/wz-eui-prompt.js
- public/kibana-integrations/kibana-vis.js
- public/kibana-integrations/kibana-visualization.js
- public/templates/agents/agents-syscollector.html
- server/integration-files/visualizations/overview/overview-general.js
- Replace WzFilterBar by WzSearchBar in:
- Agents section
- Agent selector
- Removed CSS `overflow` overwritten property for EuiOverlayMask
> 3.13 7.7 Replace WzFilterBar by WzSearchBar agents

- public/components/common/hocs/index.ts
- public/components/common/hocs/withKibanaContext.tsx
- public/components/common/hooks/index.ts
- public/components/common/hooks/use-filter-manager.ts
- public/components/common/hooks/use-index-pattern.ts
- public/components/common/hooks/use-query.ts
- public/components/common/hooks/use-time-filter.ts
- public/components/common/modules/discover/discover.tsx
- public/components/kbn-search-bar/index.ts
- public/components/kbn-search-bar/kbn-search-bar.tsx
- public/components/kbn-search-bar/lib/index.ts
- public/components/kbn-search-bar/lib/storage.ts
- public/components/overview/compliance-table/compliance-table.tsx
- public/components/overview/mitre/lib/elastic-helpers.ts
- public/components/overview/mitre/mitre.tsx
Hi team!
This PR solves this Issue: https://github.com/wazuh/wazuh-kibana-app/issues/2333
> Refactoring getSearchBar

- public/controllers/management/components/management/ruleset/list-editor.js
- public/controllers/management/components/management/ruleset/ruleset-editor.js
Hi team!
This PR refers to this issue #2347 and we solved a problem by saving the rules with the extension, both in rules, decoders and CDB lists.
Alberto
> 3.13 7.8 error format save rules

- public/components/agents/fim/inventory.tsx
- public/components/agents/fim/inventory/table.tsx
Hi team!
With this PR we fix a problem with the total items of Inventory in FIM, and we also keep the filters when changing agents.
> 3.13 7.8 fix fim inventory

- public/components/wz-menu/wz-menu.js
- public/controllers/misc/health-check.js
- public/react-services/pattern-handler.js
- public/react-services/saved-objects.js
> Create index pattern with the name specified in the wazuh.yml file

- public/components/common/util/grouping-components/grouping-components.less
- public/components/common/util/grouping-components/grouping-components.tsx
- public/components/common/util/grouping-components/hooks/index.ts
- public/components/common/util/grouping-components/hooks/use-parent-width.ts
- public/components/common/util/grouping-components/index.ts
- public/components/common/util/grouping-components/lib/divide-children.ts
- public/components/common/util/grouping-components/lib/index.ts
- public/components/wz-search-bar/components/wz-search-badges/wz-search-badges.tsx
Hi team!
This PR solves this issue: https://github.com/wazuh/wazuh-kibana-app/issues/2350
Regards.
> Created component to grouping others components

- public/components/common/util/grouping-components/lib/divide-children.ts
This fixes the error entered in the PR: #2357
> Fixed the error on WzSearchComponent

- public/components/common/util/grouping-components/lib/divide-children.ts
> Backport/Fixed the error on WzSearchComponent

- public/less/dark_theme/wz_theme_dark.css
Hi team!
With this PR some bugs related to the style are solved when the dark theme is activated.
> Some fix in dark theme

- server/lib/generate-alerts/generate-alerts-script.js
Hi team!
With this PR, we modified the generation of AWS alerts so that they do not have an associated agent. We have also cleaned the code of the alert generation script.
> Review AWS sample alerts

- public/components/overview/compliance-table/components/subrequirements/subrequirements.tsx
- public/components/overview/mitre/components/techniques/techniques.tsx
- public/less/layout.less
This PR fixes the weird behaviour when the alerts count is big
> Fix styling when mouse is over inventory elements

- .github/workflows/backport.yml
This workflow automates the task of generating backports to other branches using `Labels`
> Added backport action

- public/controllers/management/components/management/groups/actions-buttons-main.js
Hi Team!
This PR fixes a visual bug in the new group popover within the group view.
> [Visual bug] Fix new group popover

- public/controllers/management/components/management/configuration/client/client.js
- public/controllers/management/components/management/configuration/utils/utils.js
- Add new settings to Configuration/Communication `<max_retries>` and `<retry_interval>`.
Wazuh PR: https://github.com/wazuh/wazuh/pull/5433
> 3.13.1-7.8.0 new client settings

- server/controllers/wazuh-hosts.js
Whit this Pr fixes the error defined in this issue #2384
> Fix error no valid host in wazuh.yml

- public/components/agents/syscollector/components/syscollector-table.tsx
- public/components/agents/syscollector/inventory.tsx
> Add total items to processes/packages syscollector tables

- .gitignore
- .kibana-plugin-helpers.json
- public/services/resolves/check-timestamp.js
- server/lib/update-registry.js
Hi team,
This PR moves the `wazuh-registry.json` file from the /server path to Kibana's optimize folder. This PR solves #2381 
Regards,
> Move wazuh-registry.json file to optimize folder

- public/components/agents/sca/inventory.tsx
Hi team,
This PR adds new fields to the SCA searchbar.
Closes #2324
> Add new fields to the SCA searchbar

- init.js
- package.json
- public/react-services/saved-objects.js
- public/services/resolves/get-config.js
- public/utils/config-equivalences.js
- scripts/jest.js
- server/lib/cron-scheduler/apiRequest.test.ts
- server/lib/cron-scheduler/apiRequest.ts
- server/lib/cron-scheduler/configured-jobs.ts
- server/lib/cron-scheduler/error-handler.ts
- server/lib/cron-scheduler/index.ts
- server/lib/cron-scheduler/predefined-jobs.ts
- server/lib/cron-scheduler/save-document.test.ts
- server/lib/cron-scheduler/save-document.ts
- server/lib/cron-scheduler/scheduler-handler.test.ts
- server/lib/cron-scheduler/scheduler-handler.ts
- server/lib/cron-scheduler/scheduler-job.test.ts
- server/lib/cron-scheduler/scheduler-job.ts
- server/lib/initial-wazuh-config.js
- test/jest/config.js
Hi team!
This PR adds a new feature to generate schedule tasks. 
Related Issue: https://github.com/wazuh/wazuh-kibana-app/issues/2064
> New cron jobs handler

- public/services/resolves/get-config.js
- server/lib/initial-wazuh-config.js
Change the default value of the "hideManagerAlerts" option to true.
> Set hideManagerAlerts option to true

- init.js
- server/lib/elastic-wrapper.js
closes https://github.com/wazuh/wazuh-kibana-app/issues/2425
Index patterns are not checked every 2 minutes anymore and fields format are not overwritten anymore
> Fix field formats

- server/lib/elastic-wrapper.js
> Update index pattern fetcher service

- public/components/overview/compliance-table/components/subrequirements/subrequirements.tsx
- public/components/overview/mitre/components/techniques/techniques.tsx
- public/components/wz-agent-selector/wz-agent-selector.js
- public/controllers/agent/agents.js
- public/controllers/overview/components/alerts-stats.js
- public/controllers/overview/components/overview-actions/overview-actions.js
- public/controllers/overview/overview.js
- public/kibana-integrations/kibana-discover.js
> Fix filters index pattern

- server/reporting/agent-configuration.js
> Fix disabled values in PDF reports

- public/components/common/hooks/use-kbn-loading-indicator.ts
Hi team!
This PR close this Issue: https://github.com/wazuh/wazuh-kibana-app/issues/2488
Regards.
> fix: The configuration view shows a blank page

- public/components/common/modules/modules-helper.js
- public/kibana-integrations/kibana-discover.js
> Fix filters on inventory section

- public/components/agents/fim/inventory/registry-table.tsx
- public/components/agents/fim/inventory/table.tsx
- public/components/common/modules/discover/discover.tsx
- public/components/common/modules/events.tsx
- public/components/common/welcome/components/fim_events_table/fim_events_table.tsx
- public/components/common/welcome/components/mitre_top/mitre_top.tsx
- public/components/overview/compliance-table/components/subrequirements/subrequirements.tsx
- public/components/overview/mitre/components/techniques/techniques.tsx
- public/components/security/policies/policies.tsx
- public/components/security/roles/roles.tsx
- public/components/security/users/users.tsx
Hi team!
This PR adds the prop "headerZindexLocation" to some "EuiOverlayMask" components to solve a display error.
Closes: https://github.com/wazuh/wazuh-kibana-app/issues/2498
Regards.
> Fix: hidden date range picker

- public/components/common/modules/events-enhance-discover-fields.ts
- public/components/common/modules/events.tsx
- public/components/notifications/modal.tsx
- public/components/security/policies/policies.tsx
- public/components/security/roles/roles.tsx
- public/components/security/users/users.tsx
> Fix events section bugs

- public/components/agents/fim/inventory/filterBar.tsx
- public/components/agents/fim/inventory/lib/getFilterValues.ts
> Fix FIM search bar suggestions

- server/controllers/wazuh-api.js
- server/controllers/wazuh-elastic.js
- server/lib/security-factory/factories/opendistro-factory.ts
> Adapt to ODFE new platform

- public/components/security/policies/edit-policy.tsx
- public/components/security/policies/policies-table.tsx
- public/components/security/policies/policies.tsx
- public/components/security/roles/edit-role-table.tsx
- public/components/security/roles/roles-table.tsx
> Fix security section bugs

- public/components/common/hooks/use-kbn-loading-indicator.ts
This PR fixes an error when editing the configuration from the Wazuh WUI
> Fix error in settings section

- public/components/common/welcome/agents-info.js
- public/components/health-check/health-check.tsx
- public/components/security/policies/edit-policy.tsx
- public/components/security/policies/policies.tsx
- public/components/wz-menu/components/wz-agent-info.js
- public/controllers/agent/agents-preview.js
- public/controllers/agent/components/agents-table.js
- public/controllers/management/monitoring.js
- public/react-services/wz-authentication.ts
- scripts/generate-api-4.0-info/generate-api-4.0-info.js
- server/controllers/wazuh-api.js
- server/lib/api-interceptor.js
- util/api-request-list.json
Hi team,
- Adapted to the JWT payload changes without `rbac_policies` https://github.com/wazuh/wazuh-kibana-app/issues/2523
- Adapted some API endpoints response to new format with `data` https://github.com/wazuh/wazuh-kibana-app/issues/2525
- Updated generate info script and update API endpoints json file
> 4.0-7.9 Adapt jwt changes payload and adapt some endpoints responses

- public/components/security/main.tsx
- public/components/security/roles-mapping/roles-mapping-create.tsx
- public/components/security/roles-mapping/roles-mapping-edit.tsx
- public/components/security/roles-mapping/roles-mapping-table.tsx
- public/components/security/roles-mapping/roles-mapping.tsx
- public/components/security/roles-mapping/rule-editor.tsx
- public/components/wz-menu/wz-menu-security.js
> Add role mapping section

- public/components/management/groups/multiple-agent-selector.tsx
- public/controllers/agent/agents.js
- public/controllers/management/components/management/groups/utils/groups-handler.js
- server/controllers/wazuh-api.js
- server/controllers/wazuh-reporting.js
- util/api-request-list.json
Hi team!
This PR close https://github.com/wazuh/wazuh-kibana-app/issues/2537
> Change parameters name
