public/controllers/agentsPreview.js
public/services/dataHandler.js

Now you can filter agents without os and having no conflict with the API call. The trick was check if is an "Unknown" case, then: 
```js
if(isUnknown){
this.items = this.items.filter(item => typeof item.os === 'undefined');
}
```

Added "Unknown" platform to the agents tab. 

---

public/templates/manager-configuration.html

In the "manager status" tab, the cluster daemon __will appear__ when it is available, in the sense that we make the call to the api `/manager/status` and then iterated on the array obtained.
The configuration of the cluster has been added to the "manager configuration" tab.

Added cluster configuration to the manager configuration tab

---

public/controllers/agents.js
public/less/agents.less
public/less/buttons.less
public/services/dataHandler.js
public/templates/agents-preview.html
public/templates/groups-preview.html

- It's only a `$scope.$digest()` (that only applies current $scope, not the whole app)
- Just noticed that `syscheck` and `rootcheck` minutes, sometimes they are showing and sometimes they aren't so I force to ensure update them when finished.
- Also adds an extra condition in order to prevent wrong offset with datahandler 
- `if(this.offset !== 0 && this.offset >= this.totalItems){ ... }`
- Fixed wrong `hover` in groups tab and agents preview tab,

Ensure syscheck and rootcheck are showing properly

---

public/less/angular-md.less
public/less/common.less

* Fixed colour from active tab in Manager/Groups
* Fixed tooltip text colour:

More CSS tweaks

---

public/less/common.less

This PR changes the Wazuh app typography in order to gain more consistency between the app and the rest of Kibana sections.
This is more noticeable if you look at the Kibana sidebar when on Discover/Visualize and Wazuh.

Fix app typography to gain consistency

---

public/controllers/settings.js
public/services/genericReq.js
public/services/prep-error.js
public/services/testAPI.js

- Errors related to a `timeout` request are handled and showed properly
- Sets the maximum time to finish a request to `4000ms`

Timeout limit on requesting

---

package.json
public/kibana-integrations/kibanaVisualizationDirective.js
public/templates/manager/ruleset/ruleset-decoders.html
public/templates/manager/ruleset/ruleset-rules.html

Adding attribute to the visualization directive:
- specific-time-range: if true, the visualization will be loaded using a specific time range instead of being controlled by the searchbar's time picker.
Modifying ruleset visualizations to use this new attribute.

Visualizations static timerange

---

public/less/heights.less
public/templates/agents/agents-audit.html
public/templates/agents/agents-oscap.html
public/templates/agents/agents-pci.html
public/templates/overview/overview-audit.html
public/templates/overview/overview-oscap.html
public/templates/overview/overview-pci.html

This PR does the following:
* Fix the height of some metric visualizations where the numbers were cut.
* Now all the data table visualizations should not have their pagination cut and the title has been changed to **Alerts summary**.

Small bugfixes

---

public/kibana-integrations/kibanaDiscoverDirective.js
public/kibana-integrations/kibanaVisualizationDirective.js
server/initialize.js

- Considering pending updates while visualizations are rendered (mainly to properly filter pinned filters).
- Visualizations are re-imported in Kibana every time Kibana launches (had to do this because removing the plugin doesn't do that, obviously).

3.1 fix pin import

---

public/less/angular-md.less
public/less/buttons.less
public/less/common.less
public/less/main.less
public/less/manager.less
public/less/wazuh-navbar.less
public/templates/agents/agents-configuration.html

Hi everyone,
This PR removes the old blue colour from some components of the app and uses a new, darker one which is more consistent with the new style of the app for Kibana 6.
On the attached screenshots, we can see an example of components with the modified colour.

Removed old Wazuh App blue color from more app components

---

public/controllers/settings.js

This pull request ensures to only overwrite scope.extensions on settings if there is no current pattern (there is no api)

Prevents overwrite of settings on the scope variable

---

public/templates/manager/manager-osseclog.html
server/integration_files/app_objects_file_alerts.json

This PR provides the following modifications and fixes:
* Changed a **vulnerability-detector** visualization to adapt the latest Wazuh core changes.
* Removed undesired `md-divider` from **Manager/Logs**.
* Adjusted the width of a column in **Manager/Logs** to avoid overflow issues with the text.
Example screenshot of the column width change:

Minor HTML/CSS and visualizations bugfixes (6.2.x)

---

public/templates/manager/manager-osseclog.html
server/integration_files/app_objects_file_alerts.json

This PR provides the following modifications and fixes:
* Changed a **vulnerability-detector** visualization to adapt the latest Wazuh core changes.
* Removed undesired `md-divider` from **Manager/Logs**.
* Adjusted the width of a column in **Manager/Logs** to avoid overflow issues with the text.
Example screenshot of the column width change:

Minor HTML/CSS and visualizations bugfixes (6.1.x)

---

public/controllers/settings.js

This PR fixes the order we are showing the list of stored APIs, now they are sorted by timestamp, the newest is the first now.

Fixes api list wrong sorting

---

public/controllers/blank-screen-controller.js
public/services/error-handler.js
public/templates/error-handler/blank-screen.html
server/api/wazuh-elastic.js

This PR is one more effort to properly handling Elasticsearch related errors. This time the function to get the applied pattern was improved and made it clever.

Better Elasticsearch error handling

---

public/controllers/agents.js

This PR fixes a wrong data flow when go from groups tab to a specific agent and the come back to groups tab. Once you are again on groups tab and go to a different agent it remains the last agent. Now it's working as expected.

Fix wrong agent id parsing when come from groups twice

---

public/kibana-integrations/kibana-visualization.js
public/templates/agents/agents-audit.html
public/templates/agents/agents-fim.html
public/templates/agents/agents-general.html
public/templates/agents/agents-oscap.html
public/templates/agents/agents-pci.html
public/templates/agents/agents-pm.html
public/templates/agents/agents-virustotal.html
public/templates/agents/agents-vuls.html
public/templates/manager/ruleset/ruleset-decoders.html
public/templates/manager/ruleset/ruleset-rules.html
public/templates/overview/overview-audit.html
public/templates/overview/overview-aws.html
public/templates/overview/overview-fim.html
public/templates/overview/overview-general.html
public/templates/overview/overview-oscap.html
public/templates/overview/overview-pci.html
public/templates/overview/overview-pm.html
public/templates/overview/overview-virustotal.html
public/templates/overview/overview-vuls.html

- Hi team this PR makes a little fix on the visualization directive and now it's no longer neccessary the `id` field when using a `kbn-vis` element.
- Also all `kbn-vis` elements have no `id` field now.

No id on kbn-vis

---

CHANGELOG.md
public/controllers/agents.js

Hello all,
This PR will add the **complete JSON output** from the API when requesting the group configuration data. Previously, it only showed the first one, when no filters were applied.
This will help to see if more configuration is available through the JSON viewer until we finally decide the functionality of the `Agent configuration` tab.
Regards,
Juanjo

Added complete group config to JSON viewer

---

config.yml
server/initialize.js

Hello,
this PR adds the possibility to use different shard and replica configuration for both .wazuh and .wazuh-version indices.
This are the options in the config.yml file:
```
#--------------------- Indices configuration ------------------------------------
#
#wazuh.shards              : 1
#wazuh.replicas            : 1
#wazuh-version.shards      : 1
#wazuh-version.replicas    : 1
```
Keep in mind that for it to work, the configuration file must be appropriately edited prior app installation.
Regards.

3.2 internal indices config

---

public/kibana-integrations/kibana-visualization.js

Hello team, this pull request fixes a bug with the kibana visualization directive itself. We were parsing on a wrong way some filters, now the function behind this situation is better and safer and fixes the bug. We need to test it better but it fixes two wrong scenarios:
- Duplicates inside the implicit filter
- False `false` values in some conditional statements
Best,
Jesús

Hotfix to current visualization directive

---

public/less/kbn.less

Hello,
this PR override success and alert toaster colours to match Kibana 6.x ones.
Regards.

Overriding toaster colours

---

public/directives/wz-search-bar/wz-search-bar.html
public/directives/wz-table-header/wz-table-header.html
public/directives/wz-table/wz-table.html
public/kibana-integrations/kibana-visualization.js
public/less/agents.less
public/less/angular-md.less
public/less/common.less
public/less/manager.less
public/less/ruleset.less
public/less/tables.less
public/templates/agents-prev/agents-prev.html
public/templates/manager/groups/groups-preview.html
public/templates/manager/manager-osseclog.html

Hello team, this pull request is a first approach to reinvent the groups tab, also it changes minor things related to the wz-tables.

Groups redesign

---

public/controllers/agents.js
public/kibana-integrations/kibana-discover.js
public/templates/agents/agents.head

Hello team, this pull request prevents double agent.id filter on agents tab. If you go to the agents tab and go into an agent and then change the agent, the agents are accumulated, it's wrong, now it's fixed. Read the code comments bellow for a better understanding.

Query filter patch

---

public/less/kbn.less
public/templates/agents/agents-configuration.html
public/templates/manager/manager-configuration.html

Hello all,
Several weeks ago, a first approach was made to the *Manager/Configuration* tab. This time, I have a **new iteration with a new redesign**, in order to follow even more the Kibana guidelines.
This design uses the ***Monitoring-like* boxes** to show relevant information about every specific Manager configuration. If you place the mouse pointer near the title, a **tooltip** will appear, indicating that you can click to see the complete configuration.
Furthermore, this PR adds two small bugfixes reported by @snaow:
* Fixed missing pointer when hovering the group in the *Agents/Configuration* tab.
* Now the Kibana filter search bar has the same shadow as the rest of app components.
I hope that you like this redesign. Every feedback is appreciated and will be taken into …

New Manager/Configuration redesign

---

public/controllers/agents.js
public/controllers/overview.js
public/directives/wz-table/wz-table.js

Hello team, this pull requests fixes two bugs:
- If you are on Overview and/or Agents and open Discover and then go to another sub tab, the watchers for the metrics were being lost, now it's fixed.
- The rule level on the ruleset tab was wrong whenever it was 0, now it's fixed.

Hotfix minor bugs

---

public/controllers/blank-screen-controller.js
public/controllers/settings.js
public/services/api-tester.js
public/services/app-state.js
public/services/routes.js
public/templates/error-handler/blank-screen.html
server/api/wazuh-elastic.js
server/initialize.js

Hello team, this pull request add some improvments to the Wazuh App:
- Now we have a new field on the `.wazuh-version` index named `lastRestart`, it keeps the last kibana restart date.
- The citated field is used to check if the cookies have consistency with the current sever status. 
- Now the app is clever and take decissions depending on new consistency checks.
It will help to prevent weird situations on our users machines whenever they reinstall the app, reload Kibana, etc. It has been tested on several ways, hope it help us.
Best regards,
Jesús

Better checks

---

CHANGELOG.md
public/controllers/agents.js
public/less/cleaned.less
public/less/loader.js
public/templates/agents-prev/agents-prev.head
public/templates/agents-prev/agents-prev.html
public/templates/agents/agents-configuration.html
public/templates/agents/agents.head
public/templates/manager/manager-configuration.html
public/templates/overview/overview.head
public/templates/settings/settings.html

Hello all,
This PR brings a new redesign to the app. This time is for the **Agents configuration** tab.
This redesign is based on the same made for the **Manager configuration tab**. With this UI revamp, some modifications were made to the side nav cards and were applied to both tabs, providing consistency between them.
For example, the `fa-eye` icon was removed, and replaced by a bold-text active element indicator. When the user hovers the title, the font will turn bold, and also a tooltip will appear, indicating the possible actions.
The current group and sync status indicators were replaced by the new information ribbon, the same that we can see on other app sections.
In addition to this, this PR fixes some minor bugs on the UI, and also removes old CSS classes, continuing with the …

Agents configuration tab redesign

---

CHANGELOG.md
public/less/common.less
public/less/typography.less
public/templates/agents-prev/agents-prev.html
public/templates/agents/agents-configuration.html
public/templates/agents/agents-general.html
public/templates/manager/groups/groups-preview.html
public/templates/manager/manager-configuration.html

Hello everybody!
This PR brings a bunch of minor bugfixes, making the app better with small improvements over the user interface. This is the list of changes that come with this PR:
* Fixed missing shadow on Kibana filter bar.
* Refactored linkable elements with a new CSS class, `wz-text-link` and `wz-text-active`.
* This classes might change in the future.
* Removed all the `fa-eye` icons.
* Adjusted colours for title headings.
* Removed bold text where possible.
* Fixed some space issues on *Agents/General* information ribbon.
* Better truncating of *Name* and *OS* field on *Agents/General* information ribbon, with tooltip incorporated, showing the full text.
* Adjusted line heights on the JSON viewer.
* Increased height between Kibana filter bar and Panels/Discover buttons on …

Several minor bugfixes from feedback

---

public/controllers/settings.js
public/directives/wz-menu/wz-menu.html
public/services/pattern-handler.js
public/services/routes.js
public/templates/settings/settings.html
server/api/wazuh-elastic.js
server/initialize.js

Hello team, this pull request adds several improvements:
- Adds a new route named `/get-list` to fetch the index pattern list
```js
GET /get-list
{
data: [
{ id: 'index-pattern:wazuh-alerts-3.x-*', title: 'wazuh-alerts-3.x-*' },
{ id: 'index-pattern:aaaa-aaaa-aaaa-aaaa', title: 'wazuh*' },
...
]
}
```
- Removed index pattern loop from `settings` controller and `pattern-handler` controller (no longer needed)
- Removed `getAllIp` function from the whole app (no longer needed)
- Modified the function who fetchs an index pattern, now it searches for index pattern `id` instead `title`
```js
{
"query": {
"match": {
"_id":"index-pattern:" + id 
}
}
}
```
Best regards,
Jesús

Several index pattern improvements

---

CHANGELOG.md
public/controllers/agents-preview.js
public/controllers/agents.js
public/controllers/manager.js
public/controllers/settings.js
public/directives/wz-menu/wz-menu.html
public/directives/wz-menu/wz-menu.js
public/directives/wz-menu/wz-menu.less
public/directives/wz-table/wz-table.html
public/directives/wz-table/wz-table.less
public/less/common.less
public/less/layout.less
public/less/typography.less
public/services/routes.js
public/templates/agents-prev/agents-prev.head
public/templates/agents/agents-configuration.html
public/templates/agents/agents.head
public/templates/discover/discover.head
public/templates/manager/manager.head
public/templates/manager/ruleset/ruleset-decoders.html
public/templates/manager/ruleset/ruleset-rules.html
public/templates/overview/overview.head
public/templates/settings/settings.html

Hello all,
This PR brings a new refactor and redesign for the app. This time is for the top nav bar!
This refactoring process cleaned the HTML/CSS code, and reduce the number of needed classes to give style to the bar. Now it uses a `md-toolbar` component instead of a `md-navbar` component, which also fixes several visual bugs.
Also, with this PR, we recover the ability to open new tabs with the mouse wheel when clicking the different navbar buttons. This allows reloading the list of agents on the `Agents` tab, instead of using <kbd>F5</kbd>.
I hope you like this new design, every feedback is really appreciated.
Regards,
Juanjo

Refactored and redesigned top navbar

---

CHANGELOG.md
public/directives/wz-table-header/wz-table-header.html
public/directives/wz-table/wz-table.html
public/directives/wz-table/wz-table.js
public/directives/wz-table/wz-table.less
public/less/layout.less
public/less/typography.less
public/templates/agents/agents-audit.html
public/templates/agents/agents-configuration.html
public/templates/agents/agents-general.html
public/templates/agents/agents-oscap.html
public/templates/agents/agents-virustotal.html
public/templates/agents/agents-vuls.html
public/templates/manager/manager-osseclog.html
public/templates/manager/manager-status.html
public/templates/overview/overview-audit.html
public/templates/overview/overview-aws.html
public/templates/overview/overview-fim.html
public/templates/overview/overview-general.html
public/templates/overview/overview-oscap.html
public/templates/overview/overview-virustotal.html
public/templates/overview/overview-vuls.html
public/templates/settings/settings.html

Greetings,
This pull request adds truncatable text to the app. Specifically, to the metric ribbons and the tables. We've implemented a new CSS class, `wz-text-truncatable`, used for text containers (not the text element itself):
```CSS
.wz-text-truncatable {
overflow: hidden;
white-space: nowrap;
text-overflow: ellipsis;
}
```
In addition, the table from *Manager Logs* is configured to not truncate the **Description** column, so the user won't miss the complete log.
Regards,
Juanjo

Truncated text for tables and metric ribbons

---

public/services/data-handler.js

Hello team, this pull request only adds the `errorHandler` service to our `datahandler` factory.
Best,
Jesús

Added errorHandler service to Datahandler factory

---

public/controllers/settings.js
public/directives/wz-table/wz-table.less
public/less/common.less
public/services/error-handler.js
public/templates/manager/ruleset/ruleset-decoders.html
public/templates/manager/ruleset/ruleset-rules.html

Hello team.
This PR replaces the colour palette used in all the Wazuh app tables. Now uses a much more clearer blue, more relaxing to the eyes. It's the same colour as the used one on the metric ribbons.
Here's an example screenshot:
This PR also provides some CSS cleanup and reordering to the existing stylesheet files.
I hope you like this improvement to the Wazuh app.
Best regards,
Juanjo
**PST**: This PR will be added to the `3.2-xpack-rbac` development branch, which will be later merged into the `3.2` branch.

 Changed colour palette for tables

---

public/controllers/settings.js
public/templates/settings/settings.html

Hello team!
This pull request fixes a weird flickering on the *Settings* tab, due to a situation where the template was loaded before knowing if there were API entries loaded, and after that, hiding again a card.
Best regards,
Juanjo

Fixed flickering on Settings tab

---

CHANGELOG.md
public/controllers/settings.js
server/api/wazuh-api-elastic.js

Hello team this pull request adds the requested feature to accept custom dns on url validation.
```js
const urlRegEx  = new RegExp(/^https?:\/\/[a-zA-Z0-9-.]{1,300}$/)
console.log(urlRegEx.test('http://mydns')); // true
console.log(urlRegEx.test('http://mydns.com')) // true
console.log(urlRegEx.test('http://mydns-mydns')) // true
console.log(urlRegEx.test('http://mydns-mydns.com') // true
console.log(urlRegEx.test('https://mydns')); // true
console.log(urlRegEx.test('https://mydns.com')) // true
console.log(urlRegEx.test('https://mydns-mydns')) // true
console.log(urlRegEx.test('https://mydns-mydns.com')) // true
```
Best,
Jesús

Url regex validation now accepts custom dns

---

public/templates/agents/agents-configuration.html
public/templates/manager/manager-configuration.html

Hello team,
This pull request adds the **Syscollector** tab to both Manager and Agents configuration tabs. Now the user can see in a more friendly way what's the current `syscollector` configuration being applied to a group or the manager.
Best regards,
Juanjo

Added Syscollector to Manager and Agents configuration

---

server/initialize.js

Hello team, reviewing the 2.x to 3.x upgrading process I've catched two minor bugs. This pull request fix two minor bugs related to the recently merged branch, which changes all the server-side. 
- The first fix is related to this line ` const id = config._id;` before the fix, we were missing the `_id` value.
- The second fix is related to ignore the old `wazuh-monitoring` pattern to be refreshed.
- Additionally I've changed the error message `checkWazuhVersionIndex` because the .wazuh-version throws an error whenever it doesn't exists and its right, but not enough to generate an error.
Best,
Jesús

Initialize fix

---

server/vis-deletion-cron.js

Hello team, this pull request fixes the next issue:
- https://github.com/wazuh/wazuh-kibana-app/issues/361
```js
const output = await wzWrapper.deleteVisualizationByDescription(date.getTime(),true);
if(output && output.deleted > 0) log('vis-deletion-cron.js',`Deleted ${output.deleted} visualizations with a timestamp lower than ${date.getTime()}`,'info');
```
Also it logs the number of deleted visualizations when we delete one or more visualizations.
Best,
Jesús

Fix visualizations cron task log message

---

server/controllers/wazuh-elastic.js
server/integration-files/monitoring-template.js
server/monitoring.js

Hello team, this pull request ables the App to store the `cluster.name` property on the monitoring daily index. Assuming the agent from the `/agents` request comes with the field  `{ cluster: { name: 'wazuh-cluster-01' } }` we'll store it as it. If the agent doesn't come with that field, we'll store it as `{ cluster: { name: 'disabled' } }`. On the other hand, whenever we are on a non-cluster environment we'll still able to know it from the `.wazuh` index like on the other app packages.
This PR solves https://github.com/wazuh/wazuh-kibana-app/issues/375
Best,
Jesús

Added cluster.name to monitoring index

---

public/kibana-integrations/kibana-discover.js

Hello team, this pull request only prevents from weird situations where we are comparing some properties without any validation before accessing the properties.
With this addition we are safer whenever we access them:
```js
...
item.meta && item.meta.params && item.meta.params.query &&
filter.meta && filter.meta.params && filter.meta.params.query &&
...
```
Best,
Jesús

Safer access to filter properties

---

public/directives/wz-menu/wz-menu.html
public/less/common.less
public/less/typography.less
public/templates/agents/agents.head
public/templates/manager/groups/groups.head
public/templates/overview/overview.head
public/templates/settings/settings.html

Hello team
This pull request adds a bunch of small minor adjustments to the Wazuh app interface. The main change is that now the navbars don't use all-capitalized letters, so the interface is a bit less aggressive:
In addition to this, the navbar logo has been shrunk and adjusted. Other minor changes to the internal CSS/HTML code have been made.
Regards,
Juanjo

Small minor improvements to user interface

---

server/controllers/wazuh-elastic.js
server/initialize.js
server/lib/elastic-wrapper.js

Hello team, this pull request fixes a known bug (https://github.com/wazuh/wazuh-kibana-app/issues/400) on the Wazuh app related to using X-Pack without credentials which crashes the Wazuh app.
With this pull request we are checking if X-Pack is installed and security is enabled. The modification has been tested on the next environments:
- X-Pack enabled + security
- X-Pack enabled
- X-Pack disabled
- X-Pack enabled + security with no alerts indices
Regards,
Jesús

Fix x-pack bug when there is no security enabled

---

public/controllers/blank-screen-controller.js

Hello team, this pull request parses raw error objects from some scenarios on the blank screen controller, this way we can show the user the exactly message not the raw output. I'm using a try/catch block because this controller needs to be always avalaible, so if the parsing fails we can show the raw any way.
Regards,
Jesús

Added errorHandler service to bs controller, better error parsing

---

server/controllers/wazuh-elastic.js

Hello team, this pull request fixes https://github.com/wazuh/wazuh-kibana-app/issues/414, read it to have a more in deep view about the problem.
Brief summary of the change:
Whenever `allow.hits.total >= 1` it means the user has enough privilege to use that index pattern. This is always true unless there is no indices matching that pattern. If `allow.hits.total === 0` but `!forbiden` the user still has enough privileges to use that pattern but no indices are being matched --> visualizations without results.
Regards,
Jesús

Fix false "not enough privileges" scenario

---

config.yml
server/controllers/wazuh-elastic.js
server/initialize.js

Hello team, this pull request fixes https://github.com/wazuh/wazuh-kibana-app/issues/416, you could read that issue to get a more in deep description. 
Brief summary:
- This change adds a new feature designed to able us to ignore the X-Pack RBAC index pattern filtering capabilities. 
- By default, the filtering is still working like past packages but now we can disable it using the `config.yml` file.
- Also it could be used on next packages for other X-Pack related features.
- Extra: we are now logging the app revision on the internal logs.
Regards,
Jesús

 Added new config for X-Pack index pattern filtering

---

public/templates/agents/agents.head

Hello team, this pull request fixes https://github.com/wazuh/wazuh-kibana-app/issues/418
There is only one change, a `ng-show` statement has been replaced by a `ng-if` statement, this way we are removing the Discover directive from agent / configuration. 
Regards,
Jesús

Disable auto-refresh on configuration tab

---

public/controllers/settings.js

Hello team,
This pull request adds a new message when the user deletes an API entry on the Settings tab:
Now not only the user will know if something went wrong, he'll also confirm that the deletion process was successful.
This PR closes #424.
Regards,
Juanjo

Added message for successful API removal

---

public/controllers/ruleset.js
public/templates/manager/ruleset/decoders/decoders-detail.html
public/templates/manager/ruleset/rules/rules-detail.html
public/templates/manager/ruleset/rules/rules-list.html

Hello team,
This pull request adds even more filters to the Detail view on the *Ruleset* tab.
Now the user can go back to the list and filter by **group**, **PCI**, **path**, **level** or **file** on the *Rules* tab. On the *Decoders* tab, the user can now filter by **file** or **path**.
This pull request closes #430.
In addition to this, this PR includes several bugfixes and enhancements to the related Rules/Decoders table, such as completely hiding it until the loading process is finished.
Regards,
Juanjo

Added more filters to Detail view in Ruleset

---

config.yml
public/controllers/overview.js
public/templates/overview/overview-general.html
server/controllers/wazuh-api.js
server/controllers/wazuh-elastic.js
server/initialize.js
server/lib/get-configuration.js
server/lib/parse-cron.js
server/monitoring.js

Hello team, this pull request adds a new feature to our backend. The feature
has been described on https://github.com/wazuh/wazuh-kibana-app/issues/440 , read it for more information.
Brief summary:
- Configurable frequency for wazuh-monitoring insertions
- Optionally you could disable the wazuh-monitoring insertions
- Added some useful metrics for Overview general if wazuh-monitoring is disabled
- Increases the default frequency from 10 minutes to 1 hour
Best regards,
Jesús

Better wazuh-monitoring management

---

server/initialize.js
server/lib/default-ext.js

Hello team, this pull request fix an inconsistency situation whenever we add a new extension to the App which is enabled by default.
The problem comes for old App packages, whose already have `.wazuh` documents created without the new extension. If the new extension is enabled on the `config.yml` file the App thinks it is disabled. 
With this pull request we are ensuring we have all the .wazuh documents with the proper extensions updated. If the document already had a extension, it is ignored, otherwise we update it adding the new extension using the default value.
To check the extensions the function reads the `config.yml` and compares it with `default-ext.js` extensions. If it's not found con `config.yml`, looks for it on `default-ext.js`. Finally looks if the current `.wazuh` document …

Added check for new extensions

---

public/controllers/agents.js
public/controllers/overview.js
public/kibana-integrations/kibana-discover.js

Hello team, this pull request fix a little non-desired behaviour whenever a user has a custom non-pinned filter on any overview/agent tab and goes to Discover sub tab then come back to Panels sub tab.
The trick here was to add a boolean variable to check if I'm on the same tab but come from Discover or if indeed I'm new for this tab. If `localChange` is true it means we are on that situation, otherwise it'll be false.
Finally, and using `localChange`, we can decide what to do on the right way:
```js
$state.filters = localChange ? $state.filters : [];
```
Best regards,
Jesús

Fix discover to panels preserve extra filters on filter-bar

---

server/controllers/wazuh-elastic.js

Hello team, this pull request removes a useless request to Elasticsearch, which could cause non-desired behaviour whenever the API entry doesn't exists.
Regards,
Jesús

Removed useless Elasticsearch request

---

public/controllers/agents.js

Hello team this pull request prevents from removing visHandlers whenever we only change the current agent on Agents section.
Regards,
Jesús

Fix changing agent not render

---

server/controllers/error-response.js

Hello team, this pull request adds more options while checking the API url whenever you are adding a new API entry.
```
'ENOTFOUND', 'EHOSTUNREACH', 'EINVAL', 'EAI_AGAIN'
```
Regards,
Jesús

Added more options to wrong url parameter checking

---

public/controllers/agents.js
public/controllers/overview.js

Hello team, this pull request checks for different tab whenever we are on sub tab Discover and change the tab, was a missing condition but now it's fixed using a simple boolean variable.
Regards,
Jesús

Check if it's a local change cross tabs or same tab

---

public/controllers/settings.js
public/templates/settings/settings.html

Hello team, this pull request fix a bug related to Settings and the Wazuh API extensions.
- Keeps the current API entry index updated any time you toggle an extension
- Extensions tab is hidden if there are no API entries
- Any case if you are on extensions tab but there are no API entries on the controller, the function returns empty
Regards,
Jesús

Fix extensions wrong situation

---

public/controllers/agents.js
public/controllers/overview.js

Hello team, this pull request fixes https://github.com/wazuh/wazuh-kibana-app/issues/473, now the App uses the right `manager.name` or `cluster.name` filter.
Regards,
Jesús

Fix cluster.name filter

---

public/factories/vis-handlers.js
public/kibana-integrations/kibana-discover.js
public/kibana-integrations/kibana-visualization.js

Hello team, this pull request fixes https://github.com/wazuh/wazuh-kibana-app/issues/475
- Fix empty vis being shown
- Frees two remaining listeners once Discover directive is destroyed.
Regards,
Jesús

Fix empty vis being shown and frees listeners from Discover directive 

---

public/controllers/settings.js

Hello team, this pretty simple pull request fixes https://github.com/wazuh/wazuh-kibana-app/issues/458
It updates the known fields from an index pattern if it's being selected on Settings tab.
Regards,
Jesús

Refreshing known fields on settings while updating index pattern

---

server/controllers/wazuh-api.js

Hello team, this pull request fixes https://github.com/wazuh/wazuh-kibana-app/issues/467
As @jesuslinares said, the Wazuh API route `GET /agents/<id>/key` could be harmful, so we are preventing a bad usage from the Dev tools.
Regards,
Jesús

Prevents get the agent key

---

config.yml
server/monitoring.js

Hello team, this pull request fixes https://github.com/wazuh/wazuh-kibana-app/issues/482
The setting `wazuh.monitoring.enabled` now has three values:
- Any which evaluates `true` and it's not `worker` will ingest data and will show data
- Any which evaluates `false` won't ingest data and won't show data
- If `worker` is given as value, it won't ingest data but will show data
Regards,
Jesús

Allowing to show monitoring data without ingesting information

---

public/kibana-integrations/kibana-visualization.js

Hello team, this pull request fixes https://github.com/wazuh/wazuh-kibana-app/issues/484
We only need to filter Agents status visualization if we are using a cluster, otherwise show all data.
Regards,
Jesús

Fix monitoring non-cluster filter

---

public/kibana-integrations/kibana-discover.js

Hello team, this pull request fixes https://github.com/wazuh/wazuh-kibana-app/issues/487, the solution is to ignore our filter restrictions if we are on the main Discover cause we don't need it and they won't be satisfied never.
Regards,
Jesús

Fix ignoring enter on main Discover

---

public/services/data-handler.js

Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/492. The only one modification is in the data-handler factory. 
> If we are fetching agents, exclude any "000" agent before assign the array
It's useful for the whole app, and after think about it I concluded it's the best place to do the filtering.
Regards,
Jesús

Prevents "000" agents in md-autocomplete

---

public/services/resolves/check-ram.js
public/services/resolves/index.js
public/services/resolves/settings-wizard.js
server/controllers/wazuh-api.js
server/routes/wazuh-api.js

Hello team, this pull request fixes https://github.com/wazuh/wazuh-kibana-app/issues/498
Brief summary:
- Added new route to get the RAM from server side.
- Checking its value at first line of settings-wizard
- Showing warning if `totalRAM < 3072 && totalRAM > 2048`
- Showing error if `totalRAM <= 2048` or an error occurred
Regards,
Jesús

Checking total RAM

---

public/controllers/agents.js

Since we'll have more than one agents tab without visualizations in further packages we've fixed the solution previously merged to be a bit more generic.
Now it only stores last two tabs only if their content includes visualizations. This way we can simply check `arr[0] === arr[1]` to detect if it's a local change.
Regards,
Jesús

Reduced vis tab checking to 2 elements

---

public/controllers/agents.js
public/directives/wazuh-table/controller.js
public/directives/wazuh-table/template.html
public/services/data-factory.js
public/templates/agents-prev/agents-prev.html
public/templates/agents/agents-syscollector.html
public/templates/manager/groups/groups-preview.html
public/templates/manager/manager-osseclog.html
public/templates/manager/ruleset/decoders/decoders-list.html
public/templates/manager/ruleset/rules/rules-list.html

Hello team, this PR fixes #587 
Brief summary:
- Array field such `["gpdr1","gdpr2"]` now looks like `gdpr1, gdpr2`
- Empty array field such `[ ]` now looks like `---`
- Added `Download CSV` to syscollector packages table
- Added optional parameter to `wazuh-table` directive named `rows-per-page`
- Added `elapsed` time to items count from the tables `Eg: 2313 items (0.32 seconds)`
Regards,
Jesús

Improving wazuh-table usage

---

public/templates/manager/ruleset/decoders/decoders-list.html
public/templates/manager/ruleset/rules/rules-list.html

Hello team,
This pull request fixes #609.
Now the Ruleset buttons always take the needed space to not overflow the labels. The search bar and Decoders filter now are also taking the space properly, according to its component type.
Some example screenshots:
Regards,
Juanjo

Fixed flex layout on Ruleset tabs

---

public/directives/wazuh-table/controller.js
public/directives/wazuh-table/template.html

Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/621
Regards,
Jesús

Table directive improvements

---

public/less/common.less
public/less/layout.less
public/templates/agents/agents-configuration.html
public/templates/agents/agents-general.html
public/templates/agents/agents-welcome.html
public/templates/agents/agents.head
public/templates/manager/manager-reporting.html
public/templates/manager/manager-welcome.html
public/templates/manager/ruleset/decoders/decoders-list.html
public/templates/manager/ruleset/rules/rules-list.html
public/templates/overview/overview-welcome.html
public/templates/overview/overview.head
public/templates/settings/settings-extensions.html
public/templates/settings/settings-welcome.html

Hello team,
This pull request fixes a lot of small visual problems on the app:
- Added link to the agents list on the Agents tab breadcrumbs.
- Replaced <kbd>Generate report</kbd> button with a smaller one.
- Redesigned **Management > Ruleset** `md-chips` to look similar to Kibana filter pills.
- Added agent information bar from **Agents > General** to **Agents > Welcome** too.
- Refactored flex layout on **Welcome** tabs to fix a height visual bug.
- Removed duplicated loading rings on the **Agents** tab.
I hope you like these changes for the app.
Regards,
Juanjo

Several small improvements for app UI

---

public/services/routes.js

Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/637
Also it would be nice if we cherry pick this fix to older versions such 6.2.4.
Regards,
Jesús

Resolve getIp before health check is fired

---

public/directives/wazuh-table/controller.js
public/services/data-factory.js
server/controllers/wazuh-api.js
server/monitoring.js

Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/645
Brief summary:
- Monitoring module is now paginating agents by 500 items per request in order to fit new Wazuh API limits (https://github.com/wazuh/wazuh/issues/875)
- Wazuh table directive has been improved:
- Single request has a 500 items limit
- If we are in an empty page, it fetchs 500 more items and so on
- Already fetched items are not re-fetched each time we are requesting data
- Tables works the same way, this modification doesn't modify their behaviour, it only modifies the internal pagination
- Some duplicated code has been placed into a common function
Regards,
Jesús

Pagination improvements

---

package.json
server/logger.js

Hello team, this PR fixes #618 
Brief summary:
- Wait until logs directory is created before try to write a new log entry
- Wait until log rotation finishes before try to write a new log entry
- Updated Winston library from 3.0.0-rc1 to 3.0.0 stable
Regards,
Jesús

Logger fix

---

public/controllers/settings.js
public/directives/wz-menu/wz-menu.js

Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/665
- Using the `wz-menu` event listener to pass new information to the directive.
Regards!

Fix updating API name when checking connection

---

public/controllers/agents-preview.js
public/services/resolves/get-config.js
server/controllers/wazuh-elastic.js
server/lib/elastic-wrapper.js
server/routes/wazuh-elastic.js

Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/699. I've found a wrong function in our server side. That function is currently being used to get the top active agent in Elasticsearch and it had the _wazuh-alerts-3.x-*_ pattern hardcoded. 
The bug was not so harmful but since we are going to use that function with the reporting module in further packages, it must accept dynamic index patterns. 
Regards,
Jesús

Fix searching index pattern

---

public/services/resolves/settings-wizard.js

Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/709
The solution comes from add a new try/catch block because `JSON.parse` throws an exception if it fails, so our logic was just right but that exception was avoiding us to continue our standard execution.
Regards,
Jesús

Added an intended empty catch statement when parsing current API

---

public/controllers/settings.js
public/directives/wazuh-table/controller.js
public/services/api-request.js
public/services/api-tester.js
public/services/app-state.js
public/services/error-handler.js
public/services/generic-request.js
public/services/resolves/get-config.js
public/services/resolves/get-ip.js
public/services/resolves/get-saved-search.js
public/services/resolves/health-check.js
public/services/resolves/settings-wizard.js
public/services/routes.js
public/templates/settings/settings.head

Hello team, this "PR" aims to simplify some of our services. Also fixes small bugs detected from the latest changes. This PR is only Wazuh related, it does not implies Kibana things so it is easy to be tested and should be included before the changelog and revision updates.
Regards,
Jesús

Services improvements

---

public/controllers/monitoring.js
public/templates/manager/monitoring/disabled.html
public/templates/manager/monitoring/monitoring.head

Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/729
Regards,
Jesús

Checking if cluster is enabled and it's running (monitoring tab)

---

public/factories/tab-visualizations.js
public/kibana-integrations/kibana-visualization.js
public/less/common.less
public/templates/manager/monitoring/main-timelions.html
public/templates/overview/overview-fim.html
server/controllers/wazuh-elastic.js
server/integration-files/visualizations/agents/agents-audit.js
server/integration-files/visualizations/agents/agents-ciscat.js
server/integration-files/visualizations/agents/agents-fim.js
server/integration-files/visualizations/agents/agents-gdpr.js
server/integration-files/visualizations/agents/agents-oscap.js
server/integration-files/visualizations/agents/agents-pci.js
server/integration-files/visualizations/agents/agents-pm.js
server/integration-files/visualizations/agents/agents-virustotal.js
server/integration-files/visualizations/agents/agents-vuls.js
server/integration-files/visualizations/overview/overview-audit.js
server/integration-files/visualizations/overview/overview-aws.js
server/integration-files/visualizations/overview/overview-ciscat.js
server/integration-files/visualizations/overview/overview-fim.js
server/integration-files/visualizations/overview/overview-gdpr.js
server/integration-files/visualizations/overview/overview-general.js
server/integration-files/visualizations/overview/overview-oscap.js
server/integration-files/visualizations/overview/overview-pci.js
server/integration-files/visualizations/overview/overview-pm.js
server/integration-files/visualizations/overview/overview-virustotal.js
server/integration-files/visualizations/overview/overview-vuls.js

Hello team, this PR fixes https://github.com/wazuh/wazuh-kibana-app/issues/654
Brief summary:
- All visualizations have been refactored. They are now using filters instead queries.
- The kbn-vis has been refactored. It's now switching between Lucene and Kuery depending on the user input.
- Discover directive doesn't need changes because it's already adapted by the Elastic team.
_Note: this feature is experimental for Kibana, even more for the Wazuh App. It needs lot of testing._
Regards,
Jesús

Accepting Kuery as new query language

---

public/controllers/dev-tools.js

[ Dev tools ] Removed unused deps. Better error handling

---

public/directives/wz-table/wz-table.js

Hello team,
This pull request fixes #781. The bug was caused by a different path on Decoders when the `Only parents` filter was enabled, and it was not triggering the event to open the Detail view.
Regards,
Juanjo

[3.5-6.3] Fixed Decoders detail view when only parents filter enabled

---

config.yml
public/services/resolves/get-config.js
server/lib/elastic-wrapper.js
server/monitoring.js

Hello team, this PR closes https://github.com/wazuh/wazuh-kibana-app/issues/801
Two new parameters have been added to our _config.yml_:
```yaml
wazuh.monitoring.shards: 5
wazuh.monitoring.replicas: 1
```
Just modify them to configure your shards and replicas for _wazuh-monitoring-3.x-*_ indices.
Regards,
Jesús

Configuration for Wazuh monitoring shards and replicas

---

server/controllers/wazuh-api-elastic.js
server/controllers/wazuh-api.js
server/controllers/wazuh-elastic.js

Hello team, this PR closes https://github.com/wazuh/wazuh-kibana-app/issues/810.
Added some logs for specific routes when they fail in a critical way. This means, the log is only written when entering in a `catch(error) { ` block.
Affected routes are:
```
GET /api/wazuh-api/apiEntries
DELETE /api/wazuh-api/apiEntries/{id}
PUT /api/wazuh-api/apiEntries/{id}
PUT /api/wazuh-api/settings
PUT /api/wazuh-api/updateApiHostname/{id}
PUT /api/wazuh-api/update-settings
POST /api/wazuh-api/checkStoredAPI
POST /api/wazuh-api/checkAPI
GET /api/wazuh-elastic/template/{pattern}
GET /api/wazuh-elastic/pattern/{pattern}
GET /api/wazuh-elastic/setup
GET /get-list
GET /refresh-fields/{pattern}
```
Example when trying to save a Wazuh API entry from the app form using wrong port:
```js
// wazuhapp.log
{ …
```

Added logs in critical catch statements

---

public/services/common-data.js
public/services/routes.js

Hello team, this PR prevents from having a global `rule.id` filter if we are in Management > Monitoring
Regards

Remove rule.id filter before entering Management

---

public/kibana-integrations/kibana-visualization.js

Since Kibana fixed its problem related to Discover events, we can use again `loading`, `none` and `ready` statuses as usual.
Regards!

Fix wrong condition

---

public/controllers/management/status.js
public/templates/management/status.html

Hello team, this PR adds a node selector for our _Management > Status_ view. Since Wazuh is now able to be a cluster, it makes sense to have a node selector for checking every node daemons and other useful information. 
This feature is also related to #970 
Regards

Node selector for Management > Status

---

CHANGELOG.md
public/directives/wz-table/lib/data.js
public/directives/wz-table/lib/init.js
public/directives/wz-table/lib/pagination.js
public/directives/wz-table/lib/sort.js
public/directives/wz-table/wz-table-directive.js
public/directives/wz-table/wz-table.html

Closes https://github.com/wazuh/wazuh-kibana-app/issues/959

Aborted request wz-table

---

package.json
public/controllers/agent/agents.js
public/controllers/management/status.js
public/directives/wz-menu/wz-menu.js
public/templates/management/status.html
server/lib/elastic-wrapper.js

Brief summary:
- Removed `this.commonData.getPCI()`, `this.commonData.getGDPR()` from `$onInit` method. Now they are used only in the proper tab.
- Loading _syscollector_ data only once we are in the _Agent > Inventory_ tab because are heavy calls and they are useless in a welcome screen.
- Using `is_sync` only when we are on the configuration tab.
- Method `this.$scope.switchTab` is now `async`.
- Removed _Total rules_ and _Total decoders_ metrics from _Management > Status_ due to perfomance reasons.
- Replaced the Elasticsearch wrapper method at https://github.com/wazuh/wazuh-kibana-app/blob/c7cbbbed8cc2876bf8c4fbbf29fedbfe5be36a7a/server/lib/elastic-wrapper.js#L591 in order to work properly when using X-Pack security features. This __must be fixed__ as soon as possible because it's now …

API calls improved

---

package.json
public/controllers/overview/index.js
public/services/pattern-handler.js
public/services/resolves/get-ip.js
server/controllers/wazuh-elastic.js

Brief summary:
- Saves a few of requests being made in _Overview > Welcome_ tab
- Avoid fetching index pattern list twice in certain views
- Enrich our _selected index pattern <-> template_ matching function.

More optimizations

---

config.yml
public/controllers/agent/agents.js
public/services/resolves/get-config.js
server/controllers/wazuh-api.js

Closes https://github.com/wazuh/wazuh-kibana-app/issues/1003
Hi team, this PR adds the ability to make admin requests to the Wazuh API from the Wazuh App. This means you can make POST, DELETE and PUT requests.
By default it's enabled:
```yml
#admin: true
```
To disable it, edit the `config.yml` file and set `admin: false`.
Regards

Admin mode for the Wazuh API requests

---

public/directives/wz-tag-filter/wz-tag-filter.js

Hi team,
This PR fix a typo in the new tags bar filter when the key typed doesn't exist.
Regards!

Fix typo tags filter bar

---

public/controllers/management/groups.js
public/directives/wz-tag-filter/wz-tag-filter.js

Hi team,
This PR add a fix in tags filter bar to prevent the browser autocomplete from being placed on top of our autocomplete (#1130 ).
Also hides XML editor when clicking in agent's content section.
Regards.

Minor fixes

---

public/controllers/agent/agents.js
public/controllers/dev-tools/dev-tools.js
public/templates/agents/agents-syscollector.html
server/controllers/wazuh-api.js
util/csv-key-equivalence.js

- Added `Process` column for Windows agent on syscollector ports table
- Removed `remote.port` and `remote.ip` from syscollector ports table
- Split `netaddr` and `netiface` calls into separated try/catch blocks
- Forwarding all errors as they are when using Dev tools

Testing 3.8.0 - fixes

---

public/controllers/management/rules.js
public/directives/wz-xml-file-editor/wz-xml-file-editor.html
public/directives/wz-xml-file-editor/wz-xml-file-editor.less
public/less/common.less
public/less/layout.less
public/templates/management/groups/groups.html
public/templates/management/ruleset/rules/rules-detail.html

- Checking the `rule.details` keys length. Showing details only if it has content to show.
- Replaced "agent.conf" by "configuration" when using XML editor
- Minor CSS changes
- Modified JSON viewer for group content. 
- Added edit button for group content.
- Corrected padding for rules detail view.

UI improvements for group management and rules

---

server/controllers/wazuh-api.js
util/api-errors-equivalence.js

Hi team,
This PR adds an equivalence list to avoid showing errors that are too long and do not provide useful information to the user.
This PR solves #1155 
Regards.

Show readable API error response messages

---

public/directives/wz-table/wz-table-directive.js
public/directives/wz-table/wz-table.html
public/templates/management/groups/groups.html

Hi team,
This PR adds the ability to set a custom message for tables that have empty results.
Now, the wz-table-directive receives a new parameter for the custom message:
`=emptyResults`
And it can be used like this example:
`<wazuh-table empty-results="'No agents were added to this group'">`
This PR solves #1154 
Regards.

Customized empty results message in tables directive

---

public/directives/wz-xml-file-editor/wz-xml-file-editor.js

Hi team,
This PR escape certain special characters as `&, <, >, ' , "` in our file editor directive to avoid the XML validation parse error.
This PR solves #1158 
Regards

Escape xml not allowed symbols in validation

---

public/controllers/dev-tools/dev-tools.js

 Allowing the same query multiple times for Dev Tools

---

public/directives/wz-table/wz-table.html
public/less/layout.less
public/templates/management/ruleset/decoders/decoders-list.html

Fix _`wz-table` column selector and gear icon must appear in a new row (like `wz-card-actions` new file bar)_, _Change checkboxes design to adapt it to Kibana's design_ from #1249

Refactor select columns bar

---

public/controllers/management/decoders.js
public/controllers/management/management.js
public/controllers/management/rules.js
public/directives/index.js
public/directives/wz-kbn-switch/wz-kbn-switch.html
public/directives/wz-kbn-switch/wz-kbn-switch.js
public/directives/wz-table/wz-table.html
public/templates/management/ruleset/decoders/decoders-list.html
public/templates/management/ruleset/rules/rules-list.html
public/templates/settings/settings-extensions.html

Fix _Change switches design to adapt it to Kibana's design_, _Allow numbers in new files name_ from #1249

Switches design and other improvements

---

public/directives/wz-table/wz-table-directive.js
public/directives/wz-table/wz-table.html

Hi team,
This PR adds new tooltip behavior in order to show it only in truncated texts (in `wz-table`).
Regards.

Show tooltip only in truncated texts

---

public/controllers/management/rules.js

Hi team,
This PR fixes a bug in the rules editor saving method when the rule isn't a new one.
Regards.

Fix rules save

---

init.js
public/services/routes.js
server/controllers/wazuh-elastic.js
server/index-pattern-cron-job.js
server/lib/elastic-wrapper.js
server/lib/refresh-known-fields.js

Changes:
- The way we refresh an index pattern has been changed. Now we are fetching all the dynamic fields that we may be missing and it merges those fields with our known fields.
- Added a new `cron` task in our server side, it refreshes all valid index patterns every 2 minutes.
- Removed refreshing action per every parent state change.
- Keep the refreshing action for all the index patterns if `kbn-vis` fails due to missing fields*.
- Keep the refreshing action for all the index patterns if the app health check is fired*.
- Keep the refreshing action for the selected pattern only when using the index pattern selector*.
- Wrapped into a double try/catch block, so the server won't be crashed under any error that this feature may throw.
_* Now, the refreshing action is using the merging …

Merge dynamic known fields, added new cron task

---

public/directives/wz-tag-filter/wz-tag-filter.html
public/directives/wz-tag-filter/wz-tag-filter.js
public/directives/wz-tag-filter/wz-tag-filter.less

Hi team,
This PR allows toggling the operators `AND` and `OR` between the tags filters in the agent's search bar. 
This PR solves part of #1278.
Regards

Change the operators between tags

---

CHANGELOG.md
public/services/reporting.js
public/templates/overview/overview-general.html
server/controllers/wazuh-reporting.js

Timezone reporting

---

public/directives/wz-table/wz-table.html

Hi team, 
This PR adds the possibility of removing a single agent from the default group.
Regards

Enable agents remove option in default group

---

public/directives/wz-table/wz-table.html

Hi team, as part of https://github.com/wazuh/wazuh-kibana-app/issues/1361, this PR adds SCA rules for the checks table when a row is clicked so it's expanded, there you can see the rules.

Add SCA rules for checks table

---

public/controllers/agent/agents-preview.js
public/templates/agents-prev/agents-prev.html
server/controllers/wazuh-api.js
server/controllers/wazuh-elastic.js
server/initialize.js

Hi team, this PR makes some changes in our agents preview section.
Summary:
- Exclude agent "000" from the Elasticsearch query we are using for getting the most active agent.
- Do not show it if we have no last registered agent (you can have data in Elasticsearch even if you have no agents)
- Exclude agent "000" from the Wazuh API query we are using for getting the last registered agent.
- Replace the status chart with a meaningful message + docs button for registering agents.
- Reduce font size for the stats being shown in agents preview.
Regards

Fix most active and last registered agents

---

public/templates/management/configuration/global-configuration/global.html
public/templates/management/configuration/welcome.html

Hi team,
This PR show up in our config on-demand global section the mail configuration (if `alerts sent by email`
is enabled). We have appended the output of `/manager/config/mail/global` to the output of the current call. 
This PR solves #1401 
Regards.

Mail configuration on the configuration on demand

---

public/directives/wz-table/wz-table.html
public/less/common.less
public/templates/agents/agents-pm.html
public/templates/agents/agents-sca.html
server/integration-files/known-fields.js

Hi team,
This PR implements the management of all these policies checks that are not applicable. In this case, the result field is changed in favor of status and reason. Now we are showing these new fields properly in the checks tables and SCA charts.
This PR solves #1407 
Regards

Manage not applicable checks in SCA policies

---

CHANGELOG.md
package.json
public/directives/wz-list-manage/wz-list-manage.html
server/controllers/wazuh-api.js
util/csv-key-equivalence.js

The issue:
- The array for the key/values of a CDB list was inside of another array, so we were parsing a matrix instead of a 2D array, this only happens with CDB lists due to its nature.
The fix:
- Added an extra condition (boolean) to know if we are parsing a CDB list.
- Using the element zero from the array.
- Show `-` when has no value.

Fix CDB list export

---

public/less/common.less

Hi team,
This PR solves white background problems in the app discover sections like this:
Regards.

Fix discover background

---

public/services/time-service.js

Hi team
This PR removes Z character in creation dates of reports because when we add the browser timestamp with the new time service, we are adding offset 2 times because this dates sometimes contains this Zulu hour identifier in itself.
Regards

Fix Zulu identifier in reports creation date

---

server/initialize.js
server/lib/refresh-known-fields.js
server/monitoring.js

As we explain in #1464, this PR removes `ansicolors` as a dependency because in Kibana OSS that dependency is not imported so the app installation fails. 
The solution is to replace it with the result the library would generate, it's just `'\u001b[34mwazuh\u001b[39m'` so we don't need the library.
Regards

No longer using "ansicolors" as a dependency

---

public/controllers/dev-tools/dev-tools.js
server/controllers/wazuh-api.js

Hi team,
PUT and POST are the methods that allow body in requests, instead of GET and DELETE that only accept query string.
Regards

Fix DevTools request

---

public/controllers/agent/agents.js
public/controllers/misc/reporting.js
public/services/time-service.js

Hi team,
This PR solves the `Invalid date` problem in some browsers like Internet Explorer and Safari. The problem was that we were removing the Zulu time identifier 'Z' from the date it arrived (to add the timezone of the browser) and that towards it becoming a date format not supported by some browsers. Now we remove this identifier splitting and joining the original data to create a supported formatted one.
This PR solves #1469 
Regards.

Fix time service for IE and Safari Dates

---

public/templates/management/configuration/welcome.html

Hi team,
This PR disables the button to export PDF of the configuration of an agent if it is not active, because if not when ordering the components it gives an error.
This PR solves #1519
Regards

Hide export PDF agents configuration if its not active

---

public/app.js
public/kibana-integrations/field_format.js
server/lib/elastic-wrapper.js

This change restores the `rule.id` the action we miss with Elastic 7, the related issue is https://github.com/wazuh/wazuh-kibana-app/issues/1529 and the solution was overriding a method from Kibana, now it's working again.

 Restore "rule.id" as a clickable field in vis

---

CHANGELOG.md
config.yml
package.json
public/kibana-integrations/kibana-discover.js

Hi team,
This PR fixes #1686. The reason is that for 7.3.0 we missed storing the query in our factory named `discoverPendingUpdates` which we are using for passing data to the search sources of our visualizations.
That's said, the fix is adding the next block in the function `updateQueryAndFetch`:
```js
discoverPendingUpdates.removeAll();
discoverPendingUpdates.addItem($state.query, queryFilter.getFilters());
```
Regards

[Backport-3.9.5-7.3.0] Restored query from search bar in visualizations

---

public/kibana-integrations/kibana-discover.js

Hi team,
This PR fixes #1686. The reason is that for 7.3.0 we missed storing the query in our factory named `discoverPendingUpdates` which we are using for passing data to the search sources of our visualizations.
That's said, the fix is adding the next block in the function `updateQueryAndFetch`:
```js
discoverPendingUpdates.removeAll();
discoverPendingUpdates.addItem($state.query, queryFilter.getFilters());
```
__Note:__ this fix must be backported to https://github.com/wazuh/wazuh-kibana-app/tree/v3.9.4-7.3.0 and https://github.com/wazuh/wazuh-kibana-app/tree/v3.9.5-7.3.0.
Regards

Restored query from search bar in visualizations

---

server/controllers/wazuh-api.js
server/initialize.js

- If the registry file doesn't exist yet, create the registry file. The installation date is just fine.
- For those cases where the registry file already exists, we need to check if it's an app with a different revision, then it means it's a new installation. Now the installation date is being updated properly.
Also, some code was fixed, it was not too clear.

Fix app installation date not being updated properly

---

index.js

Hi team,
This PR implements #1601. Now the Wazuh app is listed as a plugin in the features selector of any Kibana space, allowing the user tho hide/show this plugin for a certain space.
It was tested with the next configurations:
- Kibana 7.3.0 security enabled
- Kibana 7.3.0 security disabled
- Kibana 7.3.0 OSS (it ignores this logic since OSS has no spaces feature)
See ticket #1601 for details.
Regards,
Jesús

Add the app as a "native" plugin for Kibana spaces

---

public/kibana-integrations/kibana-discover.js

This PR just uncomment a line that was commented with no reason in our last Kibana adaptation. It fixes #1702.
```js
//columnActions.removeColumn($scope.state.columns, columnName);
```
to:
```js
columnActions.removeColumn($scope.state.columns, columnName);
```

Restored removing column feature in Discover

---

server/controllers/wazuh-api.js

Hi team, 
**Blocked by**: https://github.com/wazuh/wazuh-api/pull/429 and https://github.com/wazuh/wazuh/pull/3842, please do not merge it until both of them are merged.
With this change, we are reducing the load time for "Agents preview" section. Before this change, it was sending 1 request to our backend, and then it was sending 6 parallel requests from the backend to the Wazuh API. Now it's sending 1 request to our backend and 1 request to the Wazuh API.
Load time has been reduced then about x5 times.
Regards,
Jesús

Reduce "Agents preview" load time

---

public/kibana-integrations/kibana-discover.js

Hi team, 
This PR fixes "Pinned filter in a dashboard, unpinned in Discover, go back to the dashboard, it's still pinned."
The reason was about not updating our internal copy of pinned filters. Now it's fixed.

Fix non removable pinned filters

---

public/kibana-integrations/kibana-discover.js

This PR fixes "Adding a filter of type exists is failing if it's added by hand. E.g: rule.id exists. Not the query bar but the filters."
The reason was we were not safely checking an object property, generating a silent exception ending in not adding the filter.

Safer checking for item key

---

public/app.js
public/services/routes.js

This PR fixes "The very first time you enter the app (with no API entries stored yet), the menu is not being shown. After saving an API entry and refresh the page, it worked." 
The reason was not properly assigning the value to `root.hideWzMenu` variable. Moved to route resolves.

Moved "hideWzMenu" to resolving section

---

public/directives/wz-multiple-selector/wz-multiple-selector.html
public/less/dark_theme/wz_theme_dark.css

Hi team, 
This PR finishes up the problems related with the dark mode on this issue https://github.com/wazuh/wazuh-kibana-app/issues/1726
Solves: 
- Adding agents into a group, makes them appear temporary with a wrong color.
- Adapts the style of the buttons
- Fix when double-clicking on an agent and the background color is not shown.
In addition:
- Consistency in button styles.
Regards,

Minor fixes for Kibana dark mode

---

public/controllers/overview/components/requirement-card.js
public/less/common.less
server/controllers/wazuh-reporting.js

Hi team,
This PR solves the following points related with this issue https://github.com/wazuh/wazuh-kibana-app/issues/1726
- Should be reviewed. If a group has no custom configurations yet, the configuration report with no agents is a bit poor.
In addition:
- Fix the bottom scroll bar in the sections that contain the requirement cards component.
Regards,

Add help message for missing configuration in groups

---

public/less/dark_theme/wz_theme_dark.css

Hi team, 
This PR fixes the autocomplete text color in the dark mode, which was black and hard to see.
Regards

Fix autocomplete text color in dark mode

---

public/controllers/agent/agents.js
public/controllers/overview/overview.js
public/kibana-integrations/kibana-discover.js
public/services/vis-factory-handler.js

This PR fixes _Bug introduced yesterday (8/28/2019). Go to "Overview > Security events", now go to "Overview > FIM", then go back to "Overview > Security events", the FIM filter is still being applied but it's not visible._ from https://github.com/wazuh/wazuh-kibana-app/issues/1726.
The reason was that filters from a tab were being applied to the next tab. Then if you go back to the first tab, the filters from the second tab were being applied to the first tab and so on...

Fix wrong filters history

---

public/controllers/agent/agents.js
public/controllers/overview/overview.js
public/kibana-integrations/kibana-visualization.js
public/templates/overview/overview-audit.html
public/templates/overview/overview-aws.html
public/templates/overview/overview-ciscat.html
public/templates/overview/overview-docker.html
public/templates/overview/overview-fim.html
public/templates/overview/overview-gdpr.html
public/templates/overview/overview-general.html
public/templates/overview/overview-hipaa.html
public/templates/overview/overview-nist.html
public/templates/overview/overview-oscap.html
public/templates/overview/overview-osquery.html
public/templates/overview/overview-pci.html
public/templates/overview/overview-pm.html
public/templates/overview/overview-virustotal.html
public/templates/overview/overview-vuls.html
public/templates/overview/overview.head

This PR completes https://github.com/wazuh/wazuh-kibana-app/pull/1748/ and is part of _Flick between dashboards, once the user is for example in "Overview > Security events" and then the user clicks on "Overview > FIM" a flick is happening, showing empty cards briefly._ from https://github.com/wazuh/wazuh-kibana-app/issues/1726

Fix visualizations rendering

---

public/controllers/agent/agents.js
public/controllers/overview/overview.js
public/factories/tab-visualizations.js
public/kibana-integrations/kibana-visualization.js
public/templates/overview/overview-ciscat.html

There is a certain use case, that was not working properly due to our latest change related to the known fields file (it was removed). If a visualization uses a field that doesn't exist in all the Elasticsearch indices, we try to find it 1 time, if we are on the same situation after trying to fetch it, then it means it doesn't exist. 
When the field doesn't exist, the visualization is marked as dead.

Improve how visualizations are handled

---

public/kibana-integrations/kibana-discover.js

Hi team, 
Due to a problem of no recovery after returning from Syscollector, we decided to remove all filters to recharge them and force data recovery again. With this PR and fix, we are not going to erase the pinned filters so as not to lose them.
Regards.

[6.8] Fix pinned filters in syscollector

---

public/directives/wz-menu/wz-menu.html

Hi team,
This PR hides the index pattern selector if there is only one.
Solves: https://github.com/wazuh/wazuh-kibana-app/issues/1799
Regards,

Hide index pattern selector if there is only one

---

public/templates/management/configuration/alerts/labels.html

Hi team,
Due to this issue: https://github.com/wazuh/wazuh/issues/3429. Labels configuration format has been modified. The `Labels configuration section` is now being shown correctly with this new format. 
Solves #1816.

Adapt Labels configuration section with new format

---

public/templates/management/configuration/integrity-monitoring/integrity-monitoring.head

@Joanes04 Report me a visualization bug in the File integrity monitoring configuration
This commit solved this removed the `d-height` class

Fix hidden overflow in the fim configuration

---

public/kibana-integrations/kibana-discover.js

Hi team,
This PR apply again the pinned filters before a refresh of the page so that they are not lost when returning to load the implicit filters.
Regards.

Add pinned filters after refresh

---

package.json
public/react-services/wz-request.js

Hi team,
This PR creates a new service called WzRequest to use it directly in the react component instead use ApiRequest through the props.
Now from any react component can make the following requests:
- Generic requests
- Requests to the Wazuh API
- Request to generate a CSV
Solves  https://github.com/wazuh/wazuh-kibana-app/issues/1844
Regards,

Requests from react

---

server/integration-files/known-fields.js

Backport of the commit `6058d18` from 3.11-7.2 branch

Add know fields for AWS and Docker 3.11-7.4

---

public/templates/management/ruleset/files/files.html

Hi team,
When we tried to list all the files related to `decoders`, the app was showing only `rules` files, this PR fixes it.

Fix decoders files

---

public/controllers/management/files.js
public/directives/wz-xml-file-editor/wz-xml-file-editor.js

Hi team,
In this PR we have adapted the Wazuh Kibana app so that when we create a file for **rules** or **decoders**, it automatically takes us to edit it, thus eliminating the problem of overwriting files
This PR solves #1896 
Regards!

"New file" editor doesn't allow saving twice #1896

---

public/directives/wz-xml-file-editor/wz-xml-file-editor.js

Hi team!
In this PR we have adapted the Wazuh app for the XML validator error for -- within in comment.
This PR solves #1979 
Regards!

Add validator true to -- within in commentary

---

public/controllers/management/components/upload-files.js

As mentioned in #1947 the limit for uploading a list for the CDB-list capability is too low and the resulting error message contains a typo.
This PR addresses that by increasing the limit to 5MB and fixing the typo.

Increased list filesize limit and fixed typo

---

server/lib/get-configuration.js
server/lib/update-configuration.js

Hi team,
When the configuration is edited multiple times in 10 seconds, the configuration is being duplicated as explained here: https://github.com/wazuh/wazuh-kibana-app/issues/2010

Fix configuration error

---

README.md

The upgrade guide is using a previous version of Wazuh 3.11.1-7.5.2 when the latest version is 3.11.2-7.5.2.

Fix Wazuh version in upgrade guide

---

public/react-services/app-state.js

Hi team,
The format of the CurrentPattern Cookie in previous versions (3.11-) was:
`"index-pattern"`
As the AppState service has been migrated, this format has been changed and this old format causes an error when upgrading, forcing the user to refresh the page in order to make it work. To avoid this, the AppState now detects if the format of the cookie is correct and replace its value with a correct value removing the extra `" "` characters.

Remove previous version format on currentPattern Cookie

---

public/controllers/dev-tools/dev-tools.js
public/services/routes.js

Hi team,
When we start the Wazuh UI for the first time and access the Dev Tools tab, the health check was not being launched and the WzMenu wasn't being shown.
This PR now allows the UI to launch the Health Check even if the first page accessed is DevTools. When opening the DevTools on a new page, the main menu was missing so now it's being checked if the menu is loaded or not, so we can force its load.

Fix missing healthcheck when loading dev-tools

---

server/controllers/wazuh-reporting.js

Hi team,
This PR closes #2024. The `Windows updates` table wasn't being shown in the generated report of Inventory Data, it has now been added to it.

Add WindowsUpdate table to report

---

.kibana-plugin-helpers.json

Now it is not necessary to delete the `wazuh-registry.json` file before running the `yarn build` command

Ignore wazuh-registry.json in package creation

---

server/integration-files/pci-requirements.js

PCI Rules 11.2.1 and 11.2.3 have been added to the requirements.

3.12 7.5 update pci requirements

---

public/controllers/dev-tools/dev-tools.js

Hi team,
This PR adapts the whole Devtools section with all the API endpoints adapted to the new API 4.0, except for the autocomplete

Change devtools method for new API

---

public/app.js
public/controllers/misc/blank-screen-controller.js
public/controllers/misc/health-check.js
public/react-services/app-state.js
public/react-services/generic-request.js
public/react-services/pattern-handler.js
public/react-services/wz-request.js
public/templates/error-handler/blank-screen.html

Hi team,
Some fixes are added in this PR:
- The new AppState service didn't support Kibana spaces and caused an infinite loop freezing the current browser tab, it has been fixed here: https://github.com/wazuh/wazuh-kibana-app/commit/fb147601ca86d5b5368777ef8c17fab7f0b33e41
- When there was an error in the Wazuh UI and the user refreshed the page, we were showing an error page with a `Something went wrong` message. We now check if the error is still happening, in that case, we show the error message (not a generic error message) or if the error has been fixed we redirect to the Overview page. A double-page refresh flick has also been fixed. Fixed here: https://github.com/wazuh/wazuh-kibana-app/commit/cb19c385ceeba19bc32b67245a280b54adbdf1b1
- When a user deletes the `wazuh-alerts*` …

Fix new AppState service

---

public/controllers/misc/health-check.js
public/services/resolves/get-config.js
public/utils/config-equivalences.js

Hi team,
As mentioned in this issue: https://github.com/wazuh/wazuh-kibana-app/issues/1982, this PR adds the possibility to enable/disable the pattern known fields health check (enabled by default).

Allow disabling known fields health check

---

public/react-services/pattern-handler.js

Hi team,
How to reproduce this error:
1. Use an index pattern alias, e.g. `wazuh-alerts`. The Wazuh UI will store that index pattern in the cookie.
2. Remove the index pattern alias and restart Kibana (Kibana will create a new index pattern `wazuh-alerts-3.x-`
3. The App will check if the stored index pattern in our cookies is **INCLUDED** in the new index pattern created, in this case `wazuh-alerts` is included in "**wazuh-alerts**-3.x-" so the app thinks it is a valid index pattern when it's not. 
This produces an infinite loop in our Wazuh UI, this has been fixed by just removing the `include` condition and now it checks if it is the exact same index pattern name. This was just happening when using index pattern aliases.

Fix infinite loop when an index pattern alias is removed

---

public/components/wz-menu/wz-menu.js

Hi team,
This PR fixes:
- Correctly highlight the currently selected tab in the top menu https://github.com/wazuh/wazuh-kibana-app/commit/a754278d2f2042b8aed634a5bede8f12c478712d
-  When restarting Wazuh Cluster, the `Wazuh Not Ready Yet` message was not being shown correctly. https://github.com/wazuh/wazuh-kibana-app/commit/ce19e572663da68db465e62c406c8324d1a9fac9
Regards,

3.12 7.6 menu fixes

---

server/integration-files/visualizations/agents/agents-general.js
server/integration-files/visualizations/overview/overview-general.js

Hi team,
This PR adds the rules group `win_authentication_failed` to the `Authentication failure` metric, both in Overview and Agents.
Regards.

Add rule group win_authentication_failed to metrics

---

public/kibana-integrations/kibana-discover.js
public/kibana-integrations/kibana-visualization.js
public/services/resolves/get-config.js
public/utils/config-equivalences.js
wazuh.yml

This PR solve that issue: **Not showing Wazuh's server alerts on the boards** https://github.com/wazuh/wazuh-kibana-app/issues/2095

Add a new config to hide the manager's alerts

---

public/directives/wz-xml-file-editor/wz-xml-file-editor.js

Hi team,
There was an error in our xml validator when a value was being ended in `\`, for example:
`<tag>C:\</tag>`
or
`<tag>/etc/test/</tag>`

Allow \< in our xml validator

---

public/directives/wz-xml-file-editor/wz-xml-file-editor.js

Hi team,
There was an error in our xml validator when a value was being ended in \, for example:
`<tag>C:\</tag>`
or
`<tag>/etc/test/</tag>`

[3.12-6.8] Allow \< in our xml validator

---

public/directives/wz-xml-file-editor/wz-xml-file-editor.js

Hi team,
There was an error in our xml validator when a value was being ended in \, for example:
`<tag>C:\</tag>`
or
`<tag>/etc/test/</tag>`

[3.12-7.4] Allow \< in our xml validator

---

public/controllers/agent/components/register-agent.js

- fix agent deployment command variables in 3.12
- fix double spaces

3.12 - Fix agent deployment command variables

---

public/controllers/overview/components/stats.js

Hi team!
In this PR, we've added a link from the overview stats to the agents, adding the filter we've clicked.
This PR is part of the issue #2195

Add link to agents in stats

---

public/components/agents/fim/states/fileDetail.tsx
public/components/agents/fim/states/states.less
public/components/common/modules/discover/discover.less
public/components/common/modules/discover/discover.tsx
public/components/common/modules/discover/row-details.tsx
public/controllers/agent/components/agents-table.js

Hi team, as requested this PR adds some fixes to the latest fim section:
1. Discover -> Rules details box: 
- The margins have been fixed and the keys are correctly formatted.
2. Our custom discover should not show all the keys, only `syscheck` related keys are now being shown:
3. Events detail section: 
The link is now working correctly only in States section.
4. sha1_after typo has been fixed.
5. Clicking on changed_attributes caused an error in the app, it has now been fixed:

Add requested fixes

---

public/components/agents/fim/events.tsx

In the events view of the FIM module, when a filter is removed, the link to the detail view disappears.
This PR solved this.

Fix the problem with the missing links

---

public/components/wz-menu/wz-menu-management.js
public/controllers/management/components/management/configuration/edit-configuration/edit-configuration.js
public/controllers/management/components/management/configuration/util-components/code-editor.js
public/controllers/management/components/upload-files.js
public/controllers/management/groups.js
public/directives/wz-multiple-selector/wz-multiple-selector.js
public/templates/management/groups/groups.html

Hi team this, pr resolves (atm):
- Removed **Statistics** of Wazuh menu.
- Added `reload` method to **GroupsController** what was missing, maybe it was removed some commits before (in v3.12 release isn't). Code taken of `v3.10-7.5`. This fixes the filter in **Manage agents** of **Management/Groups** section.
- Upload file size in **UploadFiles** component increased from `5MB` to `10MB`.
- **Font size** in **Management/Configuration** (editors and viewers) incresed from `14px` to `16px`.
- **Height adjustment** in Management/Configuration editor
- **Improved the displayed size** of the **file to be uploaded to largest unit** in UploadFiles React component

3.13-7.6 Fix Management problems

---

server/monitoring.js

Hi team,
In this PR, we have made the changes to check if the creation of a wazuh monitoring index pattern is disabled.
This PR is part of the issue #2100

Check if the creation of a wazuh monitoring index pattern is disabled

---

public/components/common/modules/dashboard.tsx

Hi team,
This PR fixes a bug where the Kibana search bar was not hidden when changing the view to inventory.
Regards,

Hide the kibana search bar in the FIM inventory

---

public/components/agents/fim/inventory/registry-table.tsx

Hi, team!
When the WzSearchBar component was updated the filter builder in the registry table was not updated. 
This PR fixes this.
Regards.

Fixed the FIM registry table

---

public/controllers/management/components/management/ruleset/ruleset-overview.js
public/controllers/management/components/management/ruleset/ruleset-table.js
public/controllers/management/components/management/ruleset/ruleset-total-items.tsx

Hey, team!
This PR adds an arrangement to the list of CBD:
When a new list is imported, the item count of the main title is not updated. This solution obtains the total number of items in the table and sends them to the counting component if the number is greater than the last value, it will be updated.
Regards.

Fix ruleset-overview count

---

public/components/common/welcome/components/sca_scan/sca_scan.tsx

Hi team,
In this PR, we've fixed a problem with displaying the duration of the SCA scan that only happened in Safari.

Fix duration for SCA scan

---

public/components/common/modules/discover/discover.tsx
public/components/overview/mitre/components/techniques/components/flyout-technique/flyout-technique.tsx
public/less/common.less

Hi team!
In this PR, we adjusted the size of the columns for the Discover tables in FIM, MITRE and compliance. With these settings, we give more prominence to the descriptions, and adjust the other fields that are fixed.

Adjust columns for discover tables

---

public/less/common.less

Hi team!
This PR edits the style of the custom discovery component to make your search bar more responsive to window resizing.
Regards.

Make custom discovery more responsive

---

public/components/agents/fim/inventory.tsx

Hi team!
When you change the agent in inventory FIM the component is not reloaded with the data of the new agent.
This PR mounts the component again when a new agent is selected
Regards.

Fixes the error produced when changing agent in FIM

---

public/components/common/modules/discover/discover.tsx
server/controllers/wazuh-elastic.js

Hi team,
This PR fixes the total count shown in our custom discover, it was limited to 10.000, now it shows the real total count of alerts

Fix total hits on custom discover

---

public/components/overview/compliance-table/components/subrequirements/subrequirements.tsx

Hi team,
As requested, the searchbar of the compliance component now also searches on the requirements description, not just on its name.

Compliance inventory. Add search on requirements description

---

public/controllers/management/components/management/configuration/integrity-monitoring/integrity-monitoring-ignored.js
public/controllers/management/components/management/configuration/integrity-monitoring/integrity-monitoring-monitored.js
public/controllers/management/components/management/configuration/integrity-monitoring/integrity-monitoring.js
public/controllers/management/components/management/configuration/policy-monitoring/policy-monitoring-general.js
public/controllers/management/components/management/configuration/util-components/tab-selector.js

- Enable **File limit** tab in `Configuration/Integrity monitoring`. Checked with new API changes.
- Added some missing tables to `Configuration/Integrity monitoring/Ignored` for a Windows agent.
- Removed duplicated `Settings/JSON/XML` selector in `Configuration/Integrity monitoring/Monitored`.
- Renamed `Monitored` to `Monitored registry entries` section in `Configuration/Integrity monitoring/Monitored`.

Fixes in Configuration

---

public/components/wz-search-bar/wz-search-badges.tsx
public/controllers/management/components/management/ruleset/decoder-info.js
public/controllers/management/components/management/ruleset/rule-info.js

- Fix filter links in Rules/Decoders details (related to `filters.map is not a function in Rules/Decoders details` bug described in #2284 )

Fix filter links in Rules/Decoders details

---

public/controllers/management/components/management/ruleset/actions-buttons.js

- an error appear in `Rules/Manage rules files`, with a `search` filter applied, and click **Export formatted** button. Filters changed as these are used in WzSearchBar.
- fix request in `Manage rules/decoders files` for **Export formatted** button. Search bar and Export formmated request were differents.

Export formatted buton in Rules/Decoders

---

public/components/settings/modules/modules.js
public/components/wz-menu/wz-menu-overview.js
server/lib/default-ext.js

Hi team,
With this PR we fixed a bug that, having MITRE by default, did not let us activate it and in a clean installation it never appeared in the menu.

Mitre active by default

---

public/templates/visualize/dashboards.html

Hello team,
With this PR we corrected an error that when moving between Events and Dashboards in some modules 2 spinners were shown loading. Now only one spinner is shown in the loads.

Fix spinner Events to Dashboards tabs

---

public/components/settings/configuration/configuration-table.js
server/controllers/wazuh-utils.js
server/lib/update-configuration.js

Hi team!
Changing the configuration of `hideAlertsManager` requires reloading the page to be applied.
We have added a toast notification with a shortcut button to `location.reload`
Regards.

Added new toast notifiacation to reload page

---

public/components/overview/metrics/metrics.tsx
public/components/visualize/wz-visualize.js

Hi team,
The new Metrics component was only refreshing its data when filters or current time range was modified, not it refreshes its data everytime the dashboard is refreshed

Refresh metrics on dashboard refresh

---

public/controllers/management/components/management/configuration/open-scap/open-scap-evaluations.js
public/controllers/management/components/management/configuration/util-components/code-editor.js
public/controllers/management/components/management/groups/groups-editor.js
public/controllers/management/components/management/ruleset/ruleset-editor.js

- fix Configuration/OpenSCAP/Evaluations is showing anything when configuration is missing
- Rules/Decoders/Groups show when there is a XML error, disable Save button and change the text of this for `XML format error`
- Configuration editor/code viewer font size is 14px

OpenSCAP and errors in Rules/Decoders/Groups editors

---

public/components/visualize/wz-visualize.js

- Sample data callout in Dashboards were showed when no alerts is avaliable for selected time range

Fix sample data callout showing

---

public/controllers/dev-tools/dev-tools.js

Hi team!
With this PR we have modified the output of DevTools when we try to make a request that is not allowed with the admin mode disabled.

Change devtools message when admin mode is disabled

---

package.json

Hi team!
With this PR, we added to our Brace dependencies to make the textmate.js theme work in OpenDistro.

Add brace@0.11.1 to package.json

---

public/components/overview/compliance-table/compliance-table.tsx
public/components/overview/mitre/mitre.tsx

Hi team,
When adding/removing filters in the MITRE/Compliance componentes the results were not being updated. 

Fix refresh on filters update

---

public/components/common/globalBreadcrumb/globalBreadcrumb.less

Hi team!
With this PR, we have solved a design problem in the breadcrumb in Firefox, which showed the name of the wrong agent.

Fix breadcrumb for firefox

---

public/controllers/agent/components/agents-preview.js

Hi team, this PR remove some console errors in:
- AgentsPreview component when it is unmounted, the state try to updated 
Some other errors are shown to belong to Kibana components.

3.13-7.7 Remove console errors

---

public/components/agents/sca/inventory.tsx

- fix SCA/Inventory doesn't update with new agent info after change selected agent using Explore agent

fix SCA/Inventory when change of agent doesn't update with new agent info

---

public/components/overview/mitre/components/tactics/tactics.tsx
public/components/overview/mitre/components/techniques/techniques.tsx
public/components/settings/settings-logs/logs.js
public/controllers/agent/components/agents-table.js
public/controllers/management/components/management/groups/groups-table.js
public/controllers/overview/components/overview-actions/agents-selection-table.js

- fix loading animation position in Mitre techniques
- removed some console warning of React components:
- Tactics
- AgentsTable
- WzGroupsTable
- AgentSelectionTable
- SettingsLogs

Remove components console warnings

---

public/components/common/modules/discover/discover.less
public/components/overview/compliance-table/compliance-table.tsx
public/components/overview/mitre/mitre.tsx
public/less/common.less

Hi team
This PR hide the globalFilterGroup button in the next views:
* Compliances -> controls 
* Mitre -> Framework
Regards.

Hide globalFilterGroup button

---

public/components/wz-search-bar/lib/q-interpreter.ts

- WzSearchBar suggestions aren't working when add the operator in search bar.
This issue doesn't happen in Kibana 7.7.x. It could be due to Typescript parser/compiler.

3.13-7.8 fix regex in QInterpeter of WzSearchBar for Kibana 7.8.x

---

public/components/overview/mitre/components/techniques/components/flyout-technique/flyout-technique.tsx

Hi team!
With this PR we solved a problem that occurred in Safari, which when scrolling to the reference in the MITRE flyout, was not adjusted.

Fix scroll to references in MITRE flyout

---

public/components/common/modules/discover/discover.tsx

Hi team,
This PR adds a new column to our custom discover only when there is no pinned agent.

Add agent column to custom discover if no agent is pinned

---

public/components/common/util/grouping-components/grouping-components.tsx
public/components/common/util/grouping-components/hooks/use-parent-width.ts
public/components/common/util/grouping-components/lib/divide-children.ts
public/components/eui-suggest/suggest_input.js
public/components/wz-search-bar/wz-search-buttons.tsx

This commit fix:
- The WzSearchBar does not break when created with filters.
- Grouping-components do not group components when the width of the parent element is 0.
- WzSearchBar buttons correctly remove or add filters
- When the "+n Filters" button is clicked,
the suggestion popover does not open.

The WzSearchBar breaks when mounted with filters

---

public/components/agents/sca/inventory.tsx

With this PR, the error that occurred when changing agent in SCA "_Inventory_" is fixed, when changing agent the data of the scans was not updated.
**Example**

Fix change agent in SCA

---

server/lib/manage-hosts.js

Hey, team!
This PR modified the creation of the "wazuh.yml" file to restrict read and write permissions to the owner user.
Related Issue: #2402

Restrict the permissions of the wazuh configuration

---

public/components/common/welcome/agents-welcome.js
public/components/common/welcome/components/requirement_vis/components/requitement_body/lib/get_requirement_alerts.ts

Hi team!
This PR solved this Issue: https://github.com/wazuh/wazuh-kibana-app/issues/2398
For the first case, I modified the "VisRequest" component to show an error when the request to Elasticsearch does not return the object of the aggregation.
The second case occurs because the platform name is not defined in the "UnsupportedComponents" object. In this case, we return the list of the "other" key by default.
Regards, 
Jose

Avoid the blanc page in the agent detail view

---

public/components/common/welcome/agents-welcome.js
public/components/common/welcome/components/menu-agent.js
public/controllers/management/components/management/configuration/aws-s3/aws-s3-buckets.js
public/controllers/management/components/management/configuration/aws-s3/aws-s3-services.js
public/controllers/management/components/management/configuration/azure-logs/azure-logs.js
public/controllers/management/components/management/configuration/configuration-settings.js
public/controllers/management/components/management/configuration/configuration-switch.js
public/controllers/management/components/management/configuration/google-cloud-pub-sub/google-cloud-pub-sub.js
public/controllers/management/components/management/configuration/util-components/configuration-setting.js
server/lib/generate-alerts/generate-alerts-script.js

Hi team,
- Added Google Cloud Pub/Sub to Configuration
- `WzConfigurationSetting` component used in Configuration now accepts these falsy values: `0` (number) and `false` (boolean). It continues to ignore the rendering of empty strings.
- Added Amazon S3 to agent menu
- Amazon sample data available for the agents
- Fixes:
- Wrong descriptions for Configuration sections: Amazon S3/Buckets y Azure Logs
- It doesn't render anything in Amazon S3/Services when the response has no `services` key. Same for Amazon S3/Buckets and `buckets` key.
- Pinned modules in the agent menu could be a disabled app module (Settings/Modules). Now update the localstorage with the right ones and remove the disabled ones.

[4.0] Configuration/Google Cloud Pub/Sub, Configuration fixes and and AWS related changes

---

public/components/agents/fim/events.tsx
public/components/agents/fim/inventory/registry-table.tsx
public/components/agents/fim/inventory/table.tsx
public/components/common/modules/mitre-events.tsx
public/components/common/welcome/components/fim_events_table/fim_events_table.tsx
public/components/common/welcome/components/mitre_top/mitre_top.tsx
public/components/overview/compliance-table/components/subrequirements/subrequirements.tsx
public/components/overview/mitre/components/techniques/techniques.tsx
public/components/wz-agent-selector/wz-agent-selector.js

Hi team,
- fix flyouts with the capability to close when clicks out of them
It seems the `@elastic/eui` version that Kibana 7.9 is using, it changed as the `onClink` function of `EuiOverlayMask` component. It doesn't now receive any parameters, while before it was receiving the HTML `event`.

[3.13-7.9] Fix flyouts

---

public/app.js
public/components/index.js
public/components/notifications/modal.tsx
public/components/settings/settings-logs/logs.js
public/controllers/management/components/management/mg-logs/logs.js
public/controllers/management/components/management/statistics/prompt-statistics-disabled.tsx
public/controllers/management/components/management/statistics/prompt-statistics-no-indices.tsx
public/controllers/management/components/management/statistics/statistics-overview.js
public/controllers/management/components/management/status/status-overview.js
public/less/common.less
public/react-services/toast-notifications.tsx
public/redux/actions/appStateActions.js
public/redux/reducers/appStateReducers.js
server/controllers/wazuh-elastic.js
server/lib/elastic-wrapper.js
server/routes/wazuh-elastic.js
util/constants.js

Hi team,
- Added a try/catch block to fetch data method (unhandled promise) in Management/Status https://github.com/wazuh/wazuh-kibana-app/issues/2458
- Set fixed values to `shards` and `replicas` of sample alerts indices configuration https://github.com/wazuh/wazuh-kibana-app/issues/2480
- Fix the horizontal overflow of EuiCodeBlock in Settings/Logs and Management/Logs sections https://github.com/wazuh/wazuh-kibana-app/issues/2479
- Added prompts to Management/Statistics when it is disabled or there are not indices for Statistics https://github.com/wazuh/wazuh-kibana-app/issues/2481
It partially resolves:
- Created the ToastNotifications service and modal to show the expanded information about toasts (with errors) https://github.com/wazuh/wazuh-kibana-app/issues/2487

[4.0] Number of shards and replicas of sample data, overflow EuiCodeBlock in Logs sections, prompts Management/Statistics

---

public/controllers/management/components/management/statistics/prompt-statistics-no-indices.tsx

This PR updates the error prompt shown when there are no wazuh-statistics-* indices

Add wazuh-statistics index to error prompt

---

server/controllers/wazuh-api.js
server/controllers/wazuh-elastic.js
server/lib/security-factory/factories/xpack-factory.ts

Hi team,
- fix the `getCurrentUser` and `getCurrenPlatform` methods for X-Pack (it was migrated to Kibana `newPlatform`)
- improved the error message due to error getting the Wazuh authentication
Issue: #2521

Adapt to X-Pack new platform

---

public/components/security/roles-mapping/roles-mapping.tsx
public/components/security/roles/edit-role-table.tsx
public/components/security/roles/edit-role.tsx

Hi team,
This PR fixes the z-index in the role-mapping section flyouts as it wasn't being shown correctly.
It also orders the list of policies in order of precedence instead of being ordered by name.

Fix Security section

---

public/components/security/roles/roles-table.tsx

Hello team,
- resources spacing in the policy tooltip from Security/roles https://github.com/wazuh/wazuh-kibana-app/issues/2533

Fix resources spacing in the policy tooltip from Security/Roles

---

server/monitoring.js

When the monitoring task of the agent cannot connect to some of the Wazuh APIs, this displays a message telling the user to enter the interface
from the browser and configure it.
It has been updated indicating that he should enter the browser to see more details.
This close: #2544

Updates the API connection error message

---

public/services/resolves/get-config.js
server/controllers/wazuh-api.js
server/lib/initial-wazuh-config.js

Hello team,
- Remove `admin` mode references in `wazuh.yml` initial configuration and cached app configuration #2546 
- Remove commented old `adminMode` logic in `/api/request` endpoint
close #2546

[4.0-7.9] Remove admin mode references

---

public/components/common/modules/events-enhance-discover-fields.ts
public/components/common/modules/events.tsx

Hi team, this PR resolves:  
Fix enhance discover table events:
- `agent.name` link was wrongly generated. The row used information was not corresponding to the event.
- Removed interval function to enhance the cells/fields.
- Added MutationObservers logic to enhance the cell/fields.
close #2551

[4.0-7.9] Fix enhance discover table events

---

public/components/common/buttons/button.tsx
public/components/common/buttons/index.ts
public/components/common/buttons/modal-confirm.tsx
public/components/common/hocs/index.ts
public/components/common/hocs/withButtonOpenOnClick.tsx
public/components/security/policies/policies-table.tsx
public/components/security/roles-mapping/roles-mapping-create.tsx
public/components/security/roles-mapping/roles-mapping-edit.tsx
public/components/security/roles-mapping/roles-mapping-table.tsx
public/components/security/roles-mapping/rule-editor.tsx
public/components/security/roles/roles-table.tsx

Hello team, this PR resolves:
- Created a button component to open modal
- Created a HOC to add logic to open modal/flyout
- Replaced buttons in Security section tables to remove role/policy/role mapping with the component that opens a confirm modal
- Fixes in the Security section:
- Sorting of EuiMemoryTables in Security
- Text in the Role mapping tab
- Removed fixed color in rule panel of Role mapping editor
- Added a space to the link `Learn more` in the Role mapping editor
close #2553

[4.0-7.9] Add modal remove buttons to Security and fixes

---

public/components/agents/prompt-no-active-agent.tsx
public/components/security/users/prompt-no-security-plugin.tsx
public/components/security/users/users.tsx
util/constants.js

Hi team, this PR resolves:  
- Create the prompt component for Security/Users section
- Guard the Security/Users component with the prompt
- Created Security app constants and improved the organization of the file
- Fix text in `prompt-no-active-agent` component
close #2503

[4.0-7.9] Added no security plugin installed prompt

---

server/initialize.js

- Update the registry file when the `revision` fields are different in the `wazuh-registry.json` file and `package.json`
It belongs to https://github.com/wazuh/wazuh-kibana-app/issues/2555

[4.0-7.9] Rebuild the registry when the revision are diferents

---

public/components/common/modules/module.less
public/less/common.less

Hello team, this PR resolves:
- Fix Events search bar z-index visual bug (when opens the suggestions popup which contains previous searches)
closes #2563

[4.0-7.9] Fix visual bug in events search bar when opens the popup

---

public/react-services/saved-objects.js

Hello team!
This PR resolves: 
- The formatedFields are missing from the index-pattern of wazuh-alerts-* 
Closes #2574

[4.0-7.9] [BUGFIX] Fixed formated fields missing in the default index-pattern

---

public/components/health-check/lib/check-kibana-settings.ts

An empty string has been removed from the list of `metafields` that was sent to the Kibana configuration.
This close https://github.com/wazuh/wazuh-kibana-app/issues/2588

Remove the empty string from the metafields settings

---

public/components/overview/metrics/metrics.tsx

Hi team! This resolves: 
- Several calls to the same stats request (esAlerts)
Closes #2586 
Note:
The bug still happens when F5 is pressed, but I assume that is caused by joining AngularJs module life cycle with React component life cycle. However, this will be deprecated soon.

[4.0-7.9] [BUGFIX] Removed unnecessary function call

---

public/controllers/agent/components/register-agent.js

Updated the macOS package URL as the one containing `osx` is no longer valid

updated macOS package URL

---

CHANGELOG.md
public/components/agents/sca/inventory.tsx

Hi team! This resolves
- Search filter in the search bar in Module/SCA wasn't working
Related to #2460

[4.0-7.9] Fixed search filter in search bar in Module/SCA wasn't working

---

CHANGELOG.md
public/components/common/hooks/index.ts
public/components/common/hooks/useResfreshAngularDiscover.ts
public/components/common/modules/discover/discover.tsx
public/components/visualize/components/security-alerts.tsx

Hi team,
- The Discover component uses `/elastic/esAlerts` and supports Private tennant in ODFE. This solves the table in Modules/Security Events.
- Added support when push the Refresh button to refresh the table
It is part of #2639

[Fix] Discover supports private tenant

---

public/components/add-modules-data/guides/audit.js
public/utils/config-equivalences.js

Hi team! This PR solves one type error in Settings>Configuration>Monitoring. The error was that "frecuency" was written instead of "frequency"

Fixed typing error

---

CHANGELOG.md
public/react-services/saved-objects.js
public/utils/known-fields.js

Hi team! This PR fix the problem of creating a new index pattern in the health check when there aren´t any available indices that match with the pattern name.
Fixed [#2620 ](https://github.com/wazuh/wazuh-kibana-app/issues/2620)

Create Index Pattern without available indices

---

CHANGELOG.md
public/components/agents/syscollector/components/syscollector-metrics.tsx
public/components/agents/syscollector/components/syscollector-table.tsx

Hi team!
- When entering Inventory Data for a Solaris agent, the entire view was blank. 
- The necessary validations were carried out, to show all fields correctly, with their data empty.
eg: Solaris agent:
eg: Ubuntu agent:
Issue: #2484

[Fix] Empty inventory data in Solaris agents

---

CHANGELOG.md
public/controllers/management/components/management/management-main.js
public/controllers/management/components/management/ruleset/actions-buttons.js
public/controllers/management/components/management/ruleset/list-editor.js
public/controllers/management/components/management/ruleset/main-ruleset.js
public/controllers/management/components/management/ruleset/ruleset-overview.js
public/controllers/management/components/management/ruleset/ruleset-table.js
public/controllers/management/components/management/ruleset/utils/columns.js
public/controllers/management/components/upload-files.js
public/react-services/wz-user-permissions.test.ts
public/react-services/wz-user-permissions.ts
public/redux/actions/appStateActions.js
public/redux/reducers/appStateReducers.js
server/controllers/wazuh-api.js

Hi team,
This PR resolves:
- Wrong permissions on edit CDB List with Cluster and Manager context configuration server.
- Added action to get context server and status.
- Context server is dynamically added to the CDBList edit button, add new, and delete.
Note: Policy `cluster:status` is necessary to get configuration context `manager` or `cluster`
Issue #2657

[Fix] Wrong permissions on edit CDB

---

CHANGELOG.md
public/react-services/saved-objects.js
public/utils/known-fields.js

Hi team, 
- Add the metafields `_id`, `_index`,  `_score` `_source`, `_type` when refreshing index patterns. Included in the known fields too.

fix(frontend): add the metafields when refreshing the index pattern

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

Hi team! This PR change the form of an agent registration adding the options of selecting the architecture of your OS and enrolling the agent to a group. 
This PR close #2652 and close #2666

Modified agent registration adding groups and arch

---

CHANGELOG.md
public/controllers/management/components/management/ruleset/list-editor.js

Hi team, we resolve the issue #2692 with this steps:
- We change `path` to `relative_dirname` and `filename` (which is the new way to use it) and instead of concatenating name, we pass another filter passing this name to filename

Fixed error due to new use of path in the export of lists

---

CHANGELOG.md
public/components/security/roles-mapping/components/roles-mapping-table.tsx

Hi team, we resolve the bug that wui rules show double tooltip when it have to show only one.
Closes #2723

Fixed Wui rules label should have only one tooltip

---

CHANGELOG.md
public/components/security/roles-mapping/components/roles-mapping-table.tsx
public/react-services/wz-user-permissions.test.ts
public/react-services/wz-user-permissions.ts

- Wui rules label should have only one tooltip
- Fixed permissions to groups view

Merge 4.0 7.9 into cloud/4.0 7.9

---

CHANGELOG.md
public/components/security/roles-mapping/components/roles-mapping-table.tsx
public/react-services/wz-user-permissions.test.ts
public/react-services/wz-user-permissions.ts

Wui rules label should have only one tooltip
Fixed permissions to groups view

Merge 4.0 7.9 into cloud/4.0.1 7.9

---

public/controllers/management/components/files-group-table.js
public/controllers/management/components/management/configuration/configuration-overview.js
public/controllers/management/components/management/groups/actions-buttons-agents.js
public/controllers/management/components/management/groups/actions-buttons-files.js
public/controllers/management/components/management/reporting/reporting-table.js
public/controllers/management/groups.js
public/react-services/reporting.js
public/services/routes.js
server/controllers/wazuh-reporting.ts
server/reporting/syscheck-request.ts
server/routes/wazuh-reporting.ts

- Adapt reporting to new backend endpoints
Closes #2728

4.0 7.10 adapt reports new endpoints

---

server/lib/api-interceptor.ts

- Desestrucutrate the data parameters received by the `buildRequestOptions` method of the ApiInterceptor into:
- `body`
- `headers`
- `params` 
- `rest`
- Use the `rest` if `body` property doesn't exist in the `data` parameter
This should solve the problem with some requests in the `Security` app section.

Fix ApiInterceptor.buildRequestOptions to destructurate data parameters

---

public/kibana-integrations/kibana-discover.js

Hi team this solves the problema that was caused when you changed the Api and the `cluster.name` filter was duplicate. Closes #2743

Fixed duplicate cluster filter when changing API

---

public/components/security/roles-mapping/components/roles-mapping-table.tsx
public/components/security/users/components/users-table.tsx

- Remove calls to an undefined method `ErrorHandler.error`

4.0-7.10 - Fix calls to undefined method ErrorHandler.error

---

common/constants.ts
server/start/initialize/index.ts

- Add a Kibana log if the `<KIBANA_PATH>/data` directory doesn't exist when the plugin is started

4.0-7.10 - Add a Kibana log when the <KIBANA_PATH>/data directory is missing

---

public/react-services/saved-objects.js

- Fix imports of index type constants in `saved-objects.js`

4.0-7.10 - Fix imports of index type constants in saved-objects.js

---

server/controllers/wazuh-hosts.ts
server/start/initialize/index.ts

-  Capture the ENOENT error due to the data directory is missing and returns a response with how to solve the problem in the `/host/apis` endpoint

4.0-7.10 capture the ENOENT error due to the data directory is missing in the /host/apis endpoint

---

public/components/kbn-search-bar/kbn-search-bar.tsx
public/types.ts

- Mitre module crash when tab Framework is opened in Kibana prod
The same fix solve the same problem in PCI DSS , HIPPA , GDPR , TSC , NIST 800-53
Closes #2808

[4.0.4-7.10.0] Fix mitre framework tab crash

---

public/utils/components-os-support.js

- The Vulnerabilities module should not show for agent Solaris.
Closes #2819

[4.0.4-7.10.0] solaris should not show vulnerabilities module

---

public/components/wz-search-bar/lib/q-interpreter.ts

Hi team, this PR fixes:
Search bar filters in Agents view.
Misreading of a regular expression caused misinterpretation o the search input value.
Closes: [#2810](https://github.com/wazuh/wazuh-kibana-app/issues/2810)

Fix Agent Search Bar - Regex Query Interpreter

---

public/react-services/wz-user-permissions.test.ts
public/react-services/wz-user-permissions.ts

- A user is able to see the list of its allowed agents, at first is only able to see agent 001 and by adding permissions to read agent 002 it appears in its list after refreshing.
Issue: https://github.com/wazuh/wazuh-kibana-app/issues/2801#issuecomment-765528832

Fixed permissions to access agents

---

public/react-services/reporting.js

- Add the agent ID to the reports name in Agent Inventory and Modules
Closes https://github.com/wazuh/wazuh-kibana-app/issues/2813

4.0-7.10 - Add agent id to the reports name in Agent Inventory and Modules

---

public/components/overview/metrics/metrics.tsx

- Fix the metrics are not updated after a bad request with a bad query in the search input
Closes #2822

4.0-7.10 - Fix metrics are not updated after a bad request in search input

---

public/controllers/management/components/management/groups/groups-table.js

- Fix searching of groups in Management > Groups
- Reset to 0 the items after search.
- Add loading status.
- Add toast when getting the groups fails.
Closes: #2812

fix(frontend): Fix searching in groups

---

public/controllers/agent/components/agents-table.js

Hello team, we solved a bug that when clicking on the agents table, in the actions column, on the icon that redirects you to configuration, it took you to the dashboard. This has been fixed by excluding onmoussedown from the actions column.
Closes: #2848

Fixed bug in the table on Agents->Table-> Actions->Config icon

---

public/controllers/management/components/management/status/actions-buttons-main.js

- Fix update the agents' information after changing the cluster node selected in Management > Status
Closes #2823

4.0-7.10 - Update agents' info in Management Status after changing cluster node selected

---

server/routes/wazuh-elastic.ts

Hi team, this PR fixes:
**Sample data doesn't use the current manager or cluster name.**
Turns out the endpoint wasn't receiving the payload to use the current manager, but the feature was already developed.
Closes: #2839

Fix body-payload of Sample Alerts POST endpoint

---

CHANGELOG.md
public/components/settings/api/api-is-down.js
server/lib/initial-wazuh-config.ts

- Change the Wazuh API default user to `wazuh-wui`
Closes: #2852

fix: Changed the Wazuh API default user to `wazuh-wui`

---

public/plugin.ts
public/react-services/pattern-handler.js

- Move upper the Wazuh item in the Kibana menu
- Set `wazuh-alerts-*` as the default index pattern when it's created
Solves [#2801 comment](https://github.com/wazuh/wazuh-kibana-app/issues/2801#issuecomment-769988814)

Move upper the Wazuh item in the Kibana menu and default index pattern

---

public/controllers/management/components/management/ruleset/main-ruleset.js

Hi team,
This PR resolve when clicking in the rule details links doesn't add a filter in the Management > Rules search bar when access from Modules/any/Events.
Issue [2877](https://github.com/wazuh/wazuh-kibana-app/issues/2877)

Bugfix filter event rules

---

CHANGELOG.md
server/controllers/wazuh-api.ts

- Invalid token specified: Cannot read property 'replace' of undefined error
Closes #2899

Fixed wrong cookie value validation on getToken

---

CHANGELOG.md
public/controllers/management/components/management/ruleset/list-editor.js
public/controllers/management/components/management/ruleset/utils/columns.js

Hi team,
This PR resolves the wrong labels in CDB lists actions. "Export", "Save" and "Discard" labels.
Issue #2896

Fixed hover texts in CDB lists actions

---

CHANGELOG.md
public/controllers/management/components/management/ruleset/decoder-info.js

- Fix the crash in the decoder details view when the property was an object
Closes: #2888

[4.1-7.10] Fix the decoder details for keys as objects

---

CHANGELOG.md
public/components/visualize/wz-visualize.js

Hi team, this fixes:
**Filters applied to PDF reports.** 
Clears the visualizations list when changing tabs so as to check which filter is applied to the current chart list.
closes #2874

Fix clear visualizations list when changing tabs

---

CHANGELOG.md
public/controllers/agent/components/agents-table.js
public/controllers/overview/components/overview-actions/agents-selection-table.js

Hi team, this fixes:
**Agent view: sort by agent OS doesn't work**
To make the field sortable I had to change the field name to _os.name,os.version_ so as the backend is able to parse it.
Closes #2920

Change agents table field os_name to os.name,os.version to make it sortable

---

CHANGELOG.md
public/components/common/welcome/agents-info.js

- This PR fixed differencies beetween "lastKeepAlive" field in Agents Table and Agents Welcome in Agent detail page.
In Agents Welcome, fields "lastKeepAlive" and "addDate" has been parsed by TimeService.
Closes #2917

Fixed diff parsed datetime between agent detail and agents table

---

CHANGELOG.md
public/controllers/agent/components/agents-preview.js

- Allow access to Agents section with `agent:group` permission
Closes: https://github.com/wazuh/wazuh-kibana-app/issues/2933
How to check:
- Create a group in Management/Group
- Add an agent to the group created
- Create a Role mapping to an Elasticsearch user giving the permission with `agent:group` action and id the name of the group
- Enable `run_as` to use the authentication context.
- Go to check the `Agents` section
- It should be visible the section without showing the prompt

[4.1-7.10] Allow access to agents section with agent:group permission

---

CHANGELOG.md
common/constants.ts
public/components/health-check/health-check.tsx
public/components/health-check/lib/check-max-buckets.ts
public/components/health-check/lib/index.ts
public/services/resolves/get-config.js
public/utils/config-equivalences.js
server/lib/initial-wazuh-config.ts

Hi team! This PR solved the problem that was caused when entering Statistics and executing a query greater than 1 day. 
Closes #2765

Increase the default max buckets

---

CHANGELOG.md
public/components/common/hocs/withKibanaContext.tsx
public/components/common/hooks/use-query.ts

Hi team,
This PR fixed the problem on TSC Is not possible to disable KQL (Lucene)
Closes #2902

Fixed query filter of TSC.

---

public/components/management/groups/multiple-agent-selector.tsx

Hi team,
This PR fixed when you change selections options of right select or left select the options are not unchecked.
- Changed `selectedOptions` for `options`, because after editing the first option in the forEach, it was ignoring a selected option.
Closes: #2889

Bugfix agents are not unchecked

---

public/components/agents/fim/inventory.tsx
public/components/agents/fim/inventory/fileDetail.tsx
public/components/agents/fim/inventory/filterBar.tsx
public/components/agents/fim/inventory/flyout.tsx
public/components/agents/fim/inventory/registry-table.tsx
public/components/agents/fim/inventory/registryValues/index.ts
public/components/agents/fim/inventory/registryValues/registryValues.tsx

Currently, the items for `registry_key` and `registry_value` types in FIM are displayed at the same level (table). But the items with the type `registry_value` should be displayed inside the detail of their corresponding `registry_key` item.

Refactored registry values for FIM

---

CHANGELOG.md
public/utils/components-os-support.js

Hi teams this PR add vulnerabilities module to macOs agents due to it is now supported.
Closes #2965

Add vulnerabilities module to macos agents

---

CHANGELOG.md
public/components/security/roles-mapping/components/rule-editor.tsx

- Fixed disabled switch visual editor button in Rules mapping editor
Closes #2957

Fixed disabled switch visual edit when json is empty

---

server/lib/security-factory/factories/opendistro-factory.ts

When using AWS Elasticsearch 7.9.1 error "bad request" appearing. All works if "path" in OpendistroFactory.getCurrentUser() starts with "/".

fix route in getCurrentUser when AWS Elasticsearch is used

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

This PR Closes #2988 where && was missing from the deployment command

fix missing && from macOS agent deployment command

---

public/controllers/agent/components/export-configuration.js

Hi team,
this fixes the configuration agent view failure to load.
Replaces a hardcoded OS compatibility property to the proper constant which already existed.

Change hardcoded property name to proper OS compatibility constant

---

CHANGELOG.md
public/components/agents/sca/inventory.tsx

- Fixed a bug when an agent has more than 1 SCA policy and select one that is not the first in the SCA inventory table. The data about the first policy was shown in the policy details. The policy checks are working well.
Closes: #3000

Fix SCA selection policy showing information about another policy

---

CHANGELOG.md
public/components/agents/sca/inventory.tsx

- pagination when expanding some row in SCA checks table

Fix pagination in SCA checks table when expanding some row

---

CHANGELOG.md
public/components/agents/sca/inventory.tsx

Hi team,
Tthis PR disables the loading when getting a request failure.
Closes: #3016

Disabled loading inventory

---

CHANGELOG.md
public/components/wz-menu/wz-menu.js
public/components/wz-menu/wz-menu.scss

- Overlay the Wazuh menu to the Kibana menu when it is opened or docked.
Closes: https://github.com/wazuh/wazuh-kibana-app/issues/2994

Overlay Wazuh menu to Kibana menu when is opened or docked

---

CHANGELOG.md
public/components/agents/fim/inventory/fileDetail.tsx
public/components/common/modules/discover/discover.tsx
public/components/overview/compliance-table/components/requirement-flyout/requirement-flyout.tsx
public/components/overview/mitre/components/techniques/components/flyout-technique/flyout-technique.tsx
public/components/visualize/components/security-alerts.tsx
public/kibana-integrations/kibana-discover.js

Hi guys,
We have fixed a bug that caused alerts not to be displayed if you switch from one pinned agent to another in the explore agent submenu.

Fixed that alerts table is empty when switching pinned agents

---

server/integration-files/visualizations/cluster/statistics.ts

Hi team, this resolve:
- Wrong name in TCP sessions visualization when showing TCP sessions average.
- Fix metric Avg TCP sessions to total TCP sessions

fix tcp sessions visualizations

---

CHANGELOG.md
common/constants.ts
public/components/health-check/health-check.tsx

Hi team this PR solves:
- The app redirect to Settings section after the health check 
- If the wazuh-manager service was stopped the button did not appeared.
- Remove some unused code.
To test this PR you have to `stop the manager service` and then try to pass the health check. After that the button should appeared and then you need to `start the manager service` again before clicking on the button. Finally after the health check is passed you should be redirected to `overview` section

Fix redirect to settings after the health check

---

common/api-info/security-actions.json

Hi guys, we have fixed a problem that causes us to not be able to interact with the buttons of manage rules files / decoders and add new rules / decoders file together with the bug of not being able to enter groups having permissions.

Fixed problems with permissions in Rules, Decoders and Groups

---

public/components/health-check/health-check.tsx

- Fix when the API is down not retrying the connection.
Note: this has a temporal fix
- Stop the Wazuh manager service/binary
```
service wazuh-manager stop
```
- Stop the container/down the machine with the Wazuh manager of the used Wazuh API
In both cases, it should allow to retry the connection and it should appear the `Retrying` in the API connection and API version checks

Fix not retrying the API connection in the healthcheck

---

CHANGELOG.md
public/plugin.ts

- Fix the path of the plugin logo in the Kibana menu
- Add the `server.basePath` setting in `kibana.yml`, for example:
```
server.basePath: /wazuh
```
This changes the path to Kibana to `<KIBANA_HOST_IP>:<KIBANA_PORT>:<SERVER_BASE_PATH>`
Check the plugin logo is visible in the Kibana menu.
Closes #3142

Fix the plugin logo path in Kibana menu

---

public/controllers/management/components/management/ruleset/ruleset-editor.js
public/directives/wz-logtest/components/logtest.tsx

This PR resolves:
- Add a prompt with the required permissions (`logtest:run`) for `Tools > Ruleset Test`
- Replace the `Ruleset Test` and `Decoders Test` buttons to require the permissions related to Logtest (`logtest:run`)
*Tools > Ruleset Test**
**Adding a rule**
**Adding a decoder**
Create a user without or denying the `logtest:run` (`*:*:*`) permission and login into Kibana.
- Check the `Tools > Ruleset Test` shows a prompt.
- Check the `Ruleset Test` button,  when adding a rule file, which requires the permissions.
- Check the `Decoders Test` button,  when adding a rule file, which requires the permissions.
Using a user with the `logtest:run` (`*:*:*`) permission as allowed:
- Check the `Tools > Ruleset Test` can be accessed and usable.
- Check the `Ruleset Test` button,  when …

Add permissions control to Logtest

---

CHANGELOG.md
public/controllers/management/components/management/groups/utils/groups-handler.js

- Error creating a new agent group.
Testing:
- Go to `Management/Groups`
- Then create a new group

Fixed error creating a new group

---

public/controllers/agent/components/register-agent.js

Hi team!
This PR checks the new protocol format from API response
Closes #3154

added TCP protocol and check TCP protocol

---

public/components/agents/fim/main.tsx
public/components/agents/sca/main.tsx
public/components/agents/stats/agent-stats.tsx
public/components/agents/vuls/main.tsx
public/components/common/welcome/components/sca_scan/sca_scan.tsx
public/controllers/management/components/management/configuration/configuration-switch.js
public/controllers/management/components/management/groups/group-agents-table.js
public/controllers/management/components/management/status/status-overview.js

- A user with agent groups permission can't see some sections
- SCA
- Integrity Monitoring
- Agent configuration
Closes #3180 
Testing:
With a user with permissions for `agent:read`, `sca:read`, `syscheck:read`  only allowed for `agent:group:xxxx`  
Open the sections: 
- SCA
- Integrity Monitoring
- Agent configuration

Fixed RBAC issue with agent group permissions

---

CHANGELOG.md
common/constants.ts
public/services/resolves/get-config.js
server/lib/initial-wazuh-config.ts
server/start/monitoring/index.ts

This PR resolves:
- Modify in the default app settings the frequency of creation for `monitoring` indices from `daily` to `weekly`.
- Modify in the default app settings the shards for `monitoring` indices from `2` to `1`.
Using a new installation (remove the `wazuh` data directory if needed)
- `wazuh.yml` app configuration file should contain:
```
#wazuh.monitoring.shards: 1
#wazuh.monitoring.replicas: 0
#wazuh.monitoring.creation: w
```
- By default `monitoring` indices should be created weekly instead of daily.
Note: the issue suggests changing the indices `shards` from `2` to `1`. Should we do that change too? I only changed the creation setting to match with the `statistics` indices too.
Closes #3147

Modify the default settings related to monitoring indices creation

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

Hi team, we fix a bug that shows `=` in Wazuh Password instead of `' '` in the new agent command for mac os
closes #3211

Fixing mac os agents add command

---

CHANGELOG.md
public/components/common/welcome/agents-info.js
public/styles/common.scss

Hi team, 
We have fixed that when we have a very large operating system or cluster name, these overlap with the rest of the fields, within the overview of an agent
Closes #3204 
**Steps to test it:**
In `agents-info.js` we modify in line 177, after the if, the variable `agent.node_name`, and we put a long node name and then in line 78 we change `osName` to another super long name, which will change the name of the operating system to display.
Then we go to `/Agents`, we select an agent and the names of both should not overlap.

Fixed fields overlap in the agent summary screen

---

CHANGELOG.md
public/utils/config-equivalences.js

Hi team, this PR fixed a typo error in /Settings/Configuration replacing `Interval creation` for `Index creation`.
Closes #3216

fix index typo settings

---

CHANGELOG.md
public/components/security/policies/create-policy.tsx
public/components/security/policies/edit-policy.tsx
public/components/security/roles-mapping/components/roles-mapping-create.tsx
public/components/security/roles-mapping/components/roles-mapping-edit.tsx
public/components/security/roles/create-role.tsx
public/components/security/roles/edit-role.tsx
public/components/security/users/components/create-user.tsx
public/components/security/users/components/edit-user.tsx
public/controllers/management/components/management/configuration/util-components/configuration-path.js
public/controllers/management/components/management/groups/groups-editor.js
public/controllers/management/components/management/ruleset/ruleset-editor.js

Hi team this PR solves: 
- Form validation on going back doesnt work on new Rules/Decoders files.
Closes #3253 
1. Go to 'Management / Rules' and 'Management / Decoders'
2. Click on create a new file
3. Edit the form/name and go back or navigate from the menu.
4. The message should be displayed.

Add validation form creating new rule/decoder

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

Hi team this PR resolves: 
- TypeError when selecting macOS agent deployment in a Safari Browser.
Closes #3255 
Check if the deploy new agent command for macOS is correct, if you can try it also with Safari 12.

Fix typerror deploy new agent Safari 12

---

CHANGELOG.md
server/controllers/wazuh-api.ts
server/lib/update-registry.ts
server/start/cron-scheduler/save-document.ts
server/start/index.ts
server/start/initialize/index.ts
server/start/monitoring/index.ts
server/start/tryCatchForIndexPermissionError.ts

Hi guys,
In this PR we solve the problem that several records of the same type are shown when starting the app, we improve the message that is shown for the errors of the `Response Error` and `security_exception `type.
To test it, you will have to create an environment, delete the wazuh folder from / kibana / data and see the logs that appear in the app `/Configuration/Logs` section.
The tests must be done with ODFE, X-Pack and without security.
Closes #3209

Fix 3209/improving and removing WUI error logs

---

CHANGELOG.md
public/components/agents/sca/components/rule-text.tsx
public/components/agents/sca/inventory.tsx

This PR resolves the render of each check in an SCA check. before the checks are split by ` -> ` character
- Review the `Checks` within an SCA check
Closes #3261

[SCA] Fix the render of the checks in a SCA check

---

CHANGELOG.md
public/factories/vis-handlers.js

Hi team,
this fixes the property name change in vizdata table in 7.12 with retro-compatibility.
Closes #3319 
To test the PR:
- Go to Security Events (or any other module with alerts summary in the PDF report)
- Generate a PDF report
- Verify the Alerts Summary table is present

Normalize visData table property for 7.12 retro-compatibility

---

CHANGELOG.md
public/services/resolves/get-ip.js

Hi team, this resolves:
- The default index pattern always is set as the selected pattern
Testing:
- Create a new index pattern
- Select it from Menu 
- It should stay selected after the refresh
Related to [#wazuh/wazuh/8776](https://github.com/wazuh/wazuh/issues/8776)

Unable to change selected index pattern from the Wazuh menu

---

CHANGELOG.md
server/lib/reporting/printer.ts

Hi team,
this fixes the _get column width algorithm_ in PDF report tables. 
Closes #3322 
To test it try to reproduce the issue linked

Use the longest value in column to get column width in PDF report tables

---

CHANGELOG.md
public/components/add-modules-data/module-guide.js
public/components/overview/compliance-table/components/requirements/requirements.tsx
public/components/overview/compliance-table/components/subrequirements/subrequirements.tsx
public/components/overview/mitre/components/tactics/tactics.tsx
public/components/overview/mitre/components/techniques/techniques.tsx
public/components/wz-search-bar/components/wz-search-badges/context-menu.tsx
public/controllers/agent/components/register-agent.js
public/factories/vis-handlers.js

Hi team!
this fixes breaking changes in Elastic UI 7.12 upgrade:
- Updated legend and idSelected props of EuiButtonGroup to be required
- Removed EuiPopover's withTitle prop
Closes #3318 
To test:
- Go to Security Events
- Open Browser Dev Tools
- Check there's no EuiButtonGroup's error 
- Go to GDPR -> Controls
- Open Browser Dev Tools
- Check there's no EuiPopover's error

Fix/elastic UI upgrade breaking changes in 7.11 and 7.12 3318

---

CHANGELOG.md
public/kibana-integrations/kibana-vis.js

| Wazuh Version | Kibana Version |
| - | - |
| 4.2 | 7.12 |
closes #3219 
The error message in the issue was caused due short graphs. The Visualization plugin subtracts internally a certain height from certain elements without checking that the result is positive. This means that there is an unspecified minimum when this error starts appearing.
**The fix**
The way the `KibanaVis` component used to hide elements for loading, while still having them present in the `DOM` to inject the graph into them, was to set the height to 0, leading to this error. Simply replacing the hiding condition to display:none avoids the error message.
**Testing**
Visit pages with graphs that use the `KibanaVis` component and check that they still load correctly and without errors.

Fix error due short graphs

---

CHANGELOG.md
public/react-services/error-orchestrator/error-orchestrator-base.ts

Hi team,
This PR changes de log level to lowercase before storing logs in the backend. This prevents the error that happens when passing a wrong level to Winston js library.

Added lowercase levels in storeError

---

public/components/common/error-boundary/error-boundary.tsx
public/kibana-services.ts
public/plugin.ts
public/react-services/error-orchestrator/error-orchestrator-business.ts
public/react-services/error-orchestrator/error-orchestrator.service.ts
public/react-services/error-orchestrator/types.ts
public/react-services/index.ts
public/utils/create-getter-setter.ts

Hi team,
This PR applies the ErrorOrchestratorService enhancement by applying createGetterSetter.
ex: 
```
try {
...........
} catch (error) {
const options = {
level: 'INFO',
severity: 'CRITICAL',
error: error;
};
getErrorOrchestrator().handleError(options);
}
```

feat(error-orchestrator): Improved on createGetterSetter

---

public/components/common/hocs/error-boundary/with-error-boundary.tsx
public/components/common/hocs/utils/utils.tsx
public/controllers/management/index.js

Hi team,
In order to improve the identity of each component and for ErrorBoundary to provide us with more precise information, I suggest the following change (which we should implement in all our hocs) following [Convention: Wrap the Display Name for Easy Debugging](https://reactjs.org/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging).
At the moment since the parent components are rendered from Angular we have to give identity explicitly, as I apply it for Management:
```
WzManagement.displayName = 'WzManagement';
ManagementWelcomeWrapper.displayName = 'ManagementWelcomeWrapper';
WzManagementConfiguration.displayName = 'WzManagementConfiguration';
```
After:
Before:
All hocs with displayName:

Identity components with hocs

---

CHANGELOG.md
package.json
public/components/settings/settings-logs/logs.js
server/lib/logger.ts
server/start/cron-scheduler/error-handler.ts

Hi team, this resolves:
- Avoid huge logs when messages or objects are too long.
Testing:
Turn down the Wazuh API when the cron job for statistics is waiting for the response at  `server/start/cron-scheduler/scheduler-job,ts#run()`
Closes #3388

Avoid huge logs 

---

CHANGELOG.md
public/components/security/policies/create-policy.tsx
public/components/security/policies/edit-policy.tsx
public/components/security/policies/policies-table.tsx
public/components/security/roles-mapping/components/roles-mapping-create.tsx
public/components/security/roles-mapping/components/roles-mapping-edit.tsx
public/components/security/roles-mapping/components/roles-mapping-table.tsx
public/components/security/roles-mapping/helpers/rule-editor.helper.ts
public/components/security/roles-mapping/roles-mapping.tsx
public/components/security/roles/edit-role.tsx
public/components/security/roles/roles-table.tsx
public/components/settings/api/add-api.js
public/components/settings/api/api-is-down.js
public/components/settings/api/api-table.js
public/components/settings/configuration/components/bottom-bar.tsx
public/components/settings/configuration/components/categories/components/category/components/field-form.tsx
public/components/settings/modules/modules.js
public/components/visualize/wz-visualize.js
public/controllers/agent/agents-preview.js
public/controllers/agent/agents.js
public/controllers/agent/components/agents-preview.js
public/controllers/agent/components/agents-table.js
public/controllers/agent/components/checkUpgrade.tsx
public/controllers/agent/components/register-agent.js
public/controllers/management/components/management/mg-logs/logs.js
public/controllers/management/management.js
public/react-services/error-orchestrator/README.md

Hi team,
This PR modifies in all try catch implementations, the way to obtain the context for our orchestrator, adding the name of the class + the name of the method in which the error was caught.

Changed all context value of all try-catch implementations

---

CHANGELOG.md
public/components/overview/compliance-table/compliance-table.tsx
public/components/overview/metrics/metrics.tsx
public/components/overview/mitre/components/tactics/tactics.tsx
public/components/overview/mitre/components/techniques/components/flyout-technique/flyout-technique.tsx
public/components/overview/mitre/components/techniques/techniques.tsx
public/components/overview/mitre/mitre.tsx
public/components/overview/mitre_attack_intelligence/resource.tsx
public/components/overview/mitre_attack_intelligence/resource_detail_references_table.tsx
public/components/overview/mitre_attack_intelligence/resources.tsx

Hi team,
This PR implement our new error handling strategy in Componets/Overview  section
Close #3441

Implement/try catch in Components >  Overview

---

CHANGELOG.md
public/components/wz-menu/__snapshots__/wz-menu.test.tsx.snap
public/components/wz-menu/wz-menu.js
public/components/wz-menu/wz-menu.test.tsx

Hi team, this resolves:
- Adapt API selector when api name is too long
**How to Test:** 
- Register a second API in kibana/data/wazuh/config/wazuh.yml, it doesn't need to be active
- Set the name of the active API (default if no other is set) to a very long name
- The API selector should show full name
Closes [#3334](https://github.com/wazuh/wazuh-kibana-app/issues/3334)

fix size api selector and add basic test

---

CHANGELOG.md
public/components/add-modules-data/sample-data.tsx

Hi team,
This PR implements a new strategy to catch in components/add-modules-data.
Close: #3471

Refactor try-catch components/add-moludes-data

---

public/controllers/dev-tools/dev-tools.ts
public/controllers/misc/blank-screen-controller.js
public/controllers/tools/index.ts
public/controllers/tools/tools.ts
public/directives/wz-logtest/components/logtest.tsx
public/factories/vis2png.js

Hi team,
This PR implements a new strategy to catch and store/show errors in the controllers, directives, and factories front-end side.
Close: #3473

Refactor try-catch strategy on controllers, directives and factories

---

CHANGELOG.md
public/components/common/tables/__snapshots__/table-default.test.tsx.snap
public/components/common/tables/__snapshots__/table-with-search-bar.test.tsx.snap
public/components/common/tables/__snapshots__/table-wz-api.test.tsx.snap
public/components/common/tables/components/__snapshots__/export-table-csv.test.tsx.snap
public/components/common/tables/components/export-table-csv.test.tsx
public/components/common/tables/components/export-table-csv.tsx
public/components/common/tables/table-default.test.tsx
public/components/common/tables/table-default.tsx
public/components/common/tables/table-with-search-bar.test.tsx
public/components/common/tables/table-with-search-bar.tsx
public/components/common/tables/table-wz-api.test.tsx
public/components/common/tables/table-wz-api.tsx

Hi team,
This PR implement our new error handling strategy in `common/table`
Close #3479

Added try-catch stratategy in common/tables

---

CHANGELOG.md
public/components/common/hooks/index.ts
public/components/common/hooks/use-value-suggestions.ts

closes https://github.com/wazuh/wazuh-kibana-app/issues/3500
This hook gets value suggestions for the provided field.
It uses
- `filterField` : The name of the field to get values for
- `type` : either `'string'` or `'boolean'`, the kind of field requested.
It returns:
- `suggestedValues` : array of possible values
- `isLoading` : updates on the loading state
- `setQuery` : Setting the query string will update the `suggestedValues` to match

UseValueSuggestions hook

---

CHANGELOG.md
public/components/common/hocs/withKibanaContext.tsx
public/components/common/hooks/use-es-search.ts
public/components/common/hooks/use-filter-manager.ts
public/components/common/modules/panel/main-panel.tsx
public/components/visualize/components/security-alerts.tsx

The filter manager now handles it's own subscriptions and changes it's own state when filters update, returning an array of filters used globally.
This PR also refactors files that already consumed `useFilterManager` so they use the property `filterManager` of the return object
closes https://github.com/wazuh/wazuh-kibana-app/issues/3512

Moved filter subscription to useFilterManager

---

CHANGELOG.md
public/components/overview/office-panel/config/drilldown-ip-config.tsx
public/components/overview/office-panel/config/drilldown-operations-config.tsx
public/components/overview/office-panel/config/drilldown-rules-config.tsx
public/components/overview/office-panel/config/drilldown-user-config.tsx
public/components/overview/office-panel/config/index.ts
public/components/overview/office-panel/config/main-view-config.tsx
public/components/overview/office-panel/config/module-config.tsx
server/integration-files/visualizations/overview/overview-office.ts

In this PR I am adding 2 new aggregation tables to the Office 365 module, bringing the total up to four.
These new table are:
- **Rules table:** Shows top 5 triggered rules, with a drilldown menu that shows what operations happened for each rule, which users triggered it and where it was triggered from.
- **Operations table:** Shows top 5 operations, with which users performed them, when and where from.
Closes #3511

Added 2 new aggtables to office365 with their drilldowns

---

CHANGELOG.md
public/components/common/custom-search-bar/custom-search-bar.tsx
public/components/common/hooks/use-kbn-loading-indicator.ts
public/components/common/hooks/use-value-suggestions.ts
public/components/overview/github-panel/config/search-bar-config.ts

Hi guys,
In this PR we integrate the dynamic filters and add the filter fields from the GitHub module.
To test it:
We will go to the Github tab, try to enter the tables, and see if the filters are applied correctly when entering the Drilldown tables and if when applying filters both in Github and in the Drilldown tables, the simple filters are modified as well.
Closes #3510

Integrating dynamic filters

---

public/components/agents/fim/inventory/fileDetail.tsx
public/components/agents/vuls/inventory/detail.tsx
public/components/common/modules/discover/discover.tsx
public/components/overview/compliance-table/components/requirement-flyout/requirement-flyout.tsx
public/components/overview/mitre/components/techniques/components/flyout-technique/flyout-technique.tsx
public/components/overview/office-panel/config/drilldown-ip-config.tsx
public/components/overview/office-panel/config/drilldown-operations-config.tsx
public/components/overview/office-panel/config/drilldown-rules-config.tsx
public/components/overview/office-panel/config/drilldown-user-config.tsx
public/components/visualize/components/security-alerts.tsx

This pr closes https://github.com/wazuh/wazuh-kibana-app/issues/3527
On this PR, I have refactored the properties used in the component `Discover` and all the components that use it.
[The first commit](https://github.com/wazuh/wazuh-kibana-app/commit/02f941ef98fb8ac42939fcc433e4fce4ab11d723) simply applies `prettier` to the files that will be modified.
[The second commit](https://github.com/wazuh/wazuh-kibana-app/commit/5c5287e68a3194eaf8b4e673cc50e2af9169c329) changes the behavior of Discover. A brief summary of the changes as intended:
- A new interface is defined within the component:
```
interface ColumnDefinition {
field: string;
label?: string;
}
```
- The prop `initialColumns` is set as an array of `ColumnDefinition` , the prop `initialAgentColumns` is created as optional to be …

Changed props for Discover

---

CHANGELOG.md
public/components/common/custom-search-bar/components/combobox.tsx
public/components/common/custom-search-bar/custom-search-bar.tsx
public/components/common/hooks/index.ts
public/components/common/hooks/use_previous.ts
public/styles/common.scss

Hi team, this resolve: 
- change custom search bar from is to is one of to support multiple values
closes #3529

change filter from is to is one of

---

CHANGELOG.md
public/components/common/modules/discover/discover.tsx

This pr closes https://github.com/wazuh/wazuh-kibana-app/issues/3522
We have added a time subscription to the lifecycle of the component Discover to change it's own timestate.
To test:
1. Go to the Office365 panel
2. Visit any drilldown
3. Change the time range in the search bar
4. See that the event table updates

Added time subscription in discover component

---

public/components/common/welcome/components/agent-sections.ts
public/components/common/welcome/components/menu-agent.js

This PR closes https://github.com/wazuh/wazuh-kibana-app/issues/3550
The office365 section should not appear under the agents sections as it is not applicable. This PR removes it.
To test:
1. Visit an agent panel
2. Click on more
3. See that Office365 is missing

Removed office365 section from agent sections

---

public/components/overview/office-panel/config/drilldown-ip-config.tsx
public/components/overview/office-panel/config/drilldown-operations-config.tsx
public/components/overview/office-panel/config/drilldown-rules-config.tsx
public/components/overview/office-panel/config/drilldown-user-config.tsx

This PR adds the `rule.level` and `rule.id` alert fields to the alerts table in the drills down of the Office 365's Panel.
- Add `rule.level` and `rule.id` fields to the drills down
- Add `rule.description` field to the table that was missing

[Module] [Office365] Add `rule.level` and `rule.id` fields to alerts table of each drill down view

---

CHANGELOG.md
public/components/health-check/components/check-result.tsx
public/components/health-check/container/health-check.container.tsx
public/components/health-check/services/check-setup.service.ts

Hi team, this resolves: 
- Add a link to the upgrade guide when the Wazuh API and the Wazuh App version mismatch. 
To testing, you can easily change in the package.json the version of the app to another than the Wazuh API.
Closes #3591

Added link to upgrade guide when Wazuh API version missmatch

---

CHANGELOG.md
public/components/agents/vuls/inventory/flyout.tsx

Set the implicit filters of the vulnerabilities flyout to be populated dynamically depending on the available data.
closes https://github.com/wazuh/wazuh-kibana-app/issues/3587
1. Set up an environment with vulnerabilty scanner enabled and a windows agent
2. Enable sample data
3. Make sure in the discover tab that the vulnerability `CVE-2020-0678` has alerts for the selected agent
4. See the details in the vulnerability inventory for `CVE-2020-0678` and see that it contains the same alerts as in step 3

Fixed vulnerability flyout

---

CHANGELOG.md
public/components/common/custom-search-bar/components/multi-select.tsx
public/components/common/custom-search-bar/custom-search-bar.tsx
public/components/common/hooks/use-value-suggestion.ts
public/components/overview/github-panel/github-panel.tsx

Hi guys,
In this PR we try to change the simple filters between the vies of Panel and the view of Drilldown Panel (selecting a row in Panel)
To test it, go to GitHub Panel, see the Simple filters allocated there, then select a row and check if the filters have changed. Of course, only some of these rows have to change. Do more than 1 attempt.
Example:
- Panel view:
- Drilldown view:
Closes #3563

Simple filters change between panel and drilldown panel

---

CHANGELOG.md
public/components/common/globalBreadcrumb/globalBreadcrumb.scss
public/components/common/globalBreadcrumb/globalBreadcrumb.tsx
public/components/common/modules/main-overview.tsx

Hi team,
this PR fixes breadcrumb style issues in Kibana 7.14.2
Closes #3667
To test:
- Test in Kibana **7.14.2** & **7.10.2**
- Navigate throughout the app and verify Wazuh and Kibana breadcrumbs look and work well
- Pay special attention when going to **Agents -> _Select agent_ -> _Select module_**

Fixed breadcrumbs style compatibility for Kibana 7.14.2

---

CHANGELOG.md
package.json
public/app.js

Hi team this resolves: 
Remove Wazuh API token on logout with Kibana 7.13 and 7.14
To test:
- login and copy the wz-token and make a curl with this token
- logout and repeat the curl
- the second curl should return 401

Fix remove token on logout kibana 7.13

---

CHANGELOG.md
public/components/agents/sca/inventory.tsx
public/components/common/welcome/management-welcome.js
public/components/common/welcome/overview-welcome.js
public/components/wz-menu/wz-menu-management.js
public/components/wz-menu/wz-menu-settings.js
public/controllers/agent/components/agents-preview.js

In this PR we resolve:
- That the Panels and their titles are properly displayed in the Welcome Overview and in the Management Directory
- That in All the Wazuh menu everything looks good, without titles in gray (disabled)
Closes first 3 error of [this comment](https://github.com/wazuh/wazuh-kibana-app/issues/3310#issuecomment-954609355)

Fixing EuiPannels in Overview Sections and disabled text in WzMenu

---

CHANGELOG.md
public/components/security/users/components/edit-user.tsx
public/controllers/management/components/management/configuration/edit-configuration/edit-configuration.js
public/controllers/management/components/management/groups/groups-editor.js

Hi guys,
With this PR we solve the error when we modify the management configuration or of some group, we save and we give the back button, before it told us that we had not saved, when we had done it
To test it:
- Go to Management/Configuration edit the file, save and try to go back with the button, it doesn't have to ask you about unsaved changes
- Same as before but in Groups/Configuration of one of them
Closes #3671 and first problem of [this comment](https://github.com/wazuh/wazuh-kibana-app/issues/3310#issuecomment-954792529)

Fixed Group Configuration and Management configuration error after trying to going back after you save

---

CHANGELOG.md
common/constants.ts
public/components/settings/configuration/utils/configuration-handler.js
public/react-services/app-state.js
public/react-services/wz-api-check.js
public/services/resolves/get-config.js
public/utils/config-equivalences.js

This PR removes the api selector toggle from the settings menu, since it was not actually affecting the state of the selector in the menu bar.
Closes https://github.com/wazuh/wazuh-kibana-app/issues/3335
- **Given** the browser is in wazuh app
- **When** the user navigates to `settings/configuration`
- **Then** the configuration panel does not show an api selector toggle
Before
After

Removed api selector toggle from the settings menu

---

CHANGELOG.md
public/components/agents/syscollector/columns/packages-columns.ts
public/components/agents/syscollector/columns/ports-columns.ts
public/components/agents/syscollector/columns/process-columns.ts
public/components/agents/syscollector/inventory.tsx

Description
Agent packages with freeBSD were not displayed
Issues Resolved
Wazuh App not showing packages details in FreeBSD agent [#3586](https://github.com/wazuh/wazuh-kibana-app/issues/3586)
Test
To test it you need to have an agent installed in FreeBSD and be in Inventory data, there you can see the packages
1. Go to Inventory Section of an agent
- **Given** the browser is logged in the Wazuh kibana app and you have an FreeBSD active agent
- **When** the user navigate to `Agents` -> click on `FreeBSD agent` -> enter in FreeBSD agent section ->`Inventory Data`
- **Then** Package table will not be empty
Check List

Wazuh app not showing packages details in free bsd agent

---

CHANGELOG.md
public/app.js

Hi team, this resolves 
- Delete wazuh token is called twice
Testing:
- Rollback the changes, add a console.log in [public/react-services/wz-authentication.ts#L151](https://github.com/wazuh/wazuh-kibana-app/blob/e22abcb81e2543d92f00c392785b11e5a981bbc0/public/react-services/wz-authentication.ts#L151)
- Run the logout and see the browser console
**To test it:**
**Precondition 1**: Location: [public/react-services/wz-authentication.ts#L151](https://github.com/wazuh/wazuh-kibana-app/blob/e22abcb81e2543d92f00c392785b11e5a981bbc0/public/react-services/wz-authentication.ts#L151)
1. Go to Inventory Section of an agent
- **Given** the browser is logged in the Wazuh kibana app
- **When** the put a console log in **Precondition 1**
- **And** the user will logged out
- **Then** the console log will …

Delete wazuh token called twice

---

CHANGELOG.md
public/components/health-check/services/check-kibana-settings.service.ts

Hi team this resolves:
- Sometimes on the first health check after an unattended installation the health check returns an error when setting the kibana settings.
This closes #3633 
To testing, I follow the these [comment](https://github.com/wazuh/wazuh-kibana-app/issues/3633#issuecomment-934536008)

Fixed kibana settings conflict on health check

---

CHANGELOG.md
common/semver.ts
public/components/common/modules/events.tsx
public/components/health-check/services/check-index-pattern/check-index-pattern-object.service.ts
public/components/health-check/services/check-index-pattern/check-index-pattern.service.ts
public/components/health-check/services/check-pattern-support.service.ts
public/components/visualize/wz-visualize.js
public/react-services/pattern-handler.js
public/react-services/saved-objects.js

This PR adds compatibility to `Kibana version >= 7.11.x` to manage how the index pattern data is retrieved to check if meets the Wazuh requirements to use.
The index pattern of Wazuh alerts should own a minimum set of fields (`agent.id`, `manager.name`, `rule.groups` and `timestamp`) to be considered usable in the app. 
For Kibana `<7.11.0`, the index pattern fields are stored as the saved object's `attribute.fields` property and these are getting with the next request:
```
GET <KIBANA_PROTOCOL>://<KIBANA_HOST>:<KIBANA_PORT>/api/saved_objects/_find?type=index-pattern&fields=title&fields=fields&per_page=9999
```
but on `Kibana 7.11.x or newer` only the scripted fields are in the `attributes.fields` so is required getting the fields with:
```
GET …
```

[FIX] [Compatibility] Get the valid index patterns to use in the app in Kibana 7.10.2 - 7.13.4

---

CHANGELOG.md
public/components/agents/fim/inventory/fileDetail.tsx
public/components/agents/fim/inventory/table.tsx
public/components/health-check/container/__snapshots__/health-check.container.test.tsx.snap
public/styles/inventory.scss

The information is adapted to the new format
**Issues Resolved**
Format Windows permissions in FIM inventory [#3370](https://github.com/wazuh/wazuh-kibana-app/issues/3370)
**Test**
To test it you need an agent on windows with version 4.3 and enter FIM inventory and enter the details
1. Go to Inventory Section of an agent
- **Given** the browser is logged in the Wazuh kibana app and you have an Windows active agent
- **When** the user navigate to `Integrity Monitoring` -> pin  `Windows agent` -> enter in `Inventory` section -> click in some of the rows available -> `Permissions`
- **Then** the permissions will appear like a JSON correctly
**Check List**

change format permissions in FIM inventory

---

CHANGELOG.md
public/services/resolves/api-count.js

In this PR we solve the bug that caused a blank tab to be shown before even passing the Health-Check, for this we have returned to the state of promises that was used, since when integrating a try catch strategy, we found this failure .
Closes #3699

Fixing blank screen before Health-Check

---

CHANGELOG.md
public/components/agents/fim/inventory/fileDetail.tsx
public/components/agents/fim/inventory/registryValues/registryValues.tsx

It was added to see the ID of the agent that corresponds to the file that you want to see, since the ID of the pinned agent was being taken only
**Issue**
The registry values of are not displayed in FIM - Events [#3677](https://github.com/wazuh/wazuh-kibana-app/issues/3677)
**Test**
_Preconditions_
Without an agent selected.
_Steps_ 
1. Navigate to 'FIM/Events'
2. Click on the `syscheck.path` value of a Windows registry
3. See if the registry value table is not empty.
4. Pin an agent
5. Click on the `syscheck.path` value of a Windows registry
6. See if the registry value table is not empty.
**Check List**
**Screenshots**
_Without an agent selected_
_With an agent selected_

Add id when agent is not pinned

---

CHANGELOG.md
public/controllers/management/components/management/ruleset/decoder-info.js

Hi team,
this PR fixes _Related decoders_ file link error when one clicked on it. 
Closes #3703 
To test it:
- Go to _Managment / Decoders_
- Select the name of a decoder in the table to access **Related decoders table**
- In Related decoders table click on a **file link** and see if it works
- Repeat the procedure with Rules
Test animation

Related decoder link undefined parameters error

---

CHANGELOG.md
public/controllers/management/components/management/ruleset/ruleset-editor.js

Hi team,
This resolves:
- bug when create filename with spaces and throws a bad error
closes #3716

Fixing bug when create filename with spaces and throws a bad error

---

CHANGELOG.md
kibana.json
public/plugin.ts
public/types.ts

This PR hides the `telemetry` banner from UI and saves that the banner was seen to avoid the banner is displayed on the next times.
The status of if the banner was seen/dismissed of `telemetry` banner is stored in a saved object. This is persistent. For new environments, the attribute that controls this is not stored so the banner is displayed, if use the `Dismiss` button, store the flag in the saved objects for next times.
Moreover, the status is saved as a property i the `telemetry` plugin.
- Hide the telemetry banner from UI and set a flag in the saved object that controls if the banner was seen and dismissed
- Changed the `wazuh` `public` `start` method to sync instead of `async` function
- In new environments, the flag in a saved object of the `telemetry` banner is not set, so this …

[FIX] [TELEMETRY] Hide the banner

---

CHANGELOG.md
public/components/health-check/services/check-index-pattern/check-index-pattern-object.service.ts
public/controllers/settings/settings.js
public/react-services/saved-objects.js

This PR fixes the problem in the `Alerts index pattern ` check of the health check caused by `listValidIndexPatterns.find is not a function`. This error could be caused due to a problem when parsing the `attributes.fields` of index pattern data.
- Ensure the `attributes.fields` exists in the index pattern data before parsing it
- Removed returning with error message or error in `SavedObjects.getListOfIndexPatterns` and `SavedObjects.getListOfWazuhValidIndexPatterns`
- The `Alerts index pattern` check shouldn't display the error and the index patterns should be checked and created (if necessary without problems) when the index pattern data has not `attributes.fields`.
*Steps to reproduce*:
1. Create an index pattern through a request to Elasticsearch API:
```
curl -XPOST …
```

[FIX] [HEALH CHECK] Fix `listValidIndexPatterns.find is not a function` error

---

CHANGELOG.md
public/controllers/management/components/management/mg-logs/logs.js

Hi Team, this resolve: 
When you select some daemon filters in the log section, the app throws an error:
The items `'wazuh-modulesd:task-manager'`, `'wazuh-modulesd:agent-upgrade'` not supported by wazuh api as a filter.
Closes #3715

fix wrong deamons in filter list

---

CHANGELOG.md
package.json
public/components/common/util/markdown/markdown.tsx

Hi Team, this resolve:
- Open external links in a new tab browser in Mitre Intelligence interface
closes #3729

add target blank in link table

---

CHANGELOG.md
public/components/common/modules/discover/discover.tsx
public/components/overview/mitre/components/techniques/components/flyout-technique/flyout-technique.tsx
public/components/overview/mitre/components/techniques/techniques.tsx
public/components/overview/mitre_attack_intelligence/all_resources.tsx
public/components/overview/mitre_attack_intelligence/resource.tsx
public/components/overview/mitre_attack_intelligence/resource_detail_references_table.tsx
public/components/overview/mitre_attack_intelligence/resources.tsx
public/controllers/management/components/management/ruleset/rule-info.js

This PR fixes some problems related to the MITRE Att&ck details flyout:
- Can't get the tactics of the technique when opening the flyout from `Modules/MITRE Att&ck/Events` tab and another sections
- Fixed the redirection to show information about some technique or tacts in the `Intelligence` tab (`Modules/MITRE Att&ck`)
- Replaces `references.external_id` by `external_id`. This changed in the response of Wazuh API 
- Removed `openIntelligence` component property in some components and moved the functionality to the component.
- Open MITRE Att&ck details flyouts should render the data correctly.
- The links/buttons that open the details flyouts should work.
- The links of technique/tactic data in the alerts should redirect to `Intelligence` and show a flyout with information about the …

[BUG] [MODULES] [MITRE Att&ck] Bugs in the details flyouts

---

CHANGELOG.md
public/components/common/hooks/use-es-search.ts

…r in the search bar and the data is not updated
- Now uses `useQueryManager` instead of `useQuery`
This PR solves when clearing the query filter in the search bar of `Panel` tab of modules `Office 365` and `GitHub`. See https://github.com/wazuh/wazuh-kibana-app/issues/3713#issue-1075421139
- Replace the `hook` used by `useQueryManager` instead of `useQuery`.
- Add a query filter in the search bar of `Panel` tab of modules `Office 365` and `GitHub` and apply the searching, after clearing the query string and updating the search, the data should be updated.

[Panel] [Office365] [GitHub] Update data when clearing the query filter

---

CHANGELOG.md
server/start/monitoring/index.ts

This PR fixes the problem of only index data of the first `500` agents in the `monitoring` job.
- Fixed the `limit` query param to 500 for each request. This could be improved as described in a comment included in the PR changes but require researching.
- With monitoring job running (and permission to do) and more than `500` agents check the `Evolution` visualization displays more than `500` as the sum of different agent status
Closes #3717

[FIX] [Monitoring] Retrieve data of all agents

---

CHANGELOG.md
public/controllers/management/components/management/ruleset/list-editor.js

This PR fixes an error displayed when exporting the key-value pairs of a CDB List.
- Go to `Management/CDB Lists`, select a list and export the `key-value` pairs to CSV. It should export to the file without problems.
Closes #3712

[FIX] `Maximum call stack size exceeded` error exporting key-value pairs of a CDB List

---

CHANGELOG.md
public/components/common/custom-search-bar/components/multi-select.tsx

Hi team in this PR, I solved the error when navigating to wazuh application in safari browser
Closes #3740

fix regex lookahead and lookbehind for safari

---

CHANGELOG.md
public/components/common/modules/buttons/generate_report.tsx

Hi team,
this PR fixes once a PDF report is generated, when an agent is pinned or unpinned and a NEW report is generated it fails.
Closes #3746 
To test it:
1. Navigate to any Dashboard
2. Click on Generate Report
3. Pin an agent
4. Generate a new report
5. Check both reports were properly created

Dashboards PDF report error when switching pinned agent

---

CHANGELOG.md
public/templates/tools/tools.html

This PR adds styles to contrast the request text of the action buttons.
- Added a background color to the buttons of same color or highlighted request line
Light theme:
Dark theme:
- In Tools/API Console, add a request with long text or reduce the request panel to overlay the action buttons to the request text. The button should have more contrast and should be visible in a better way.
Closes #3770

[FIX] [API Console] Styles of action buttons overlaying the request text

---

CHANGELOG.md
public/components/health-check/services/check-index-pattern/check-index-pattern.service.ts
public/utils/config-equivalences.js
server/lib/initial-wazuh-config.ts

This PR runs the checks related to the alerts index pattern if these are enabled in the app configuration. Add some messages to display when the check is disabled to be skipped or perform some tasks.
The checks when are disabled (value: `false` in the app configuration):
- `checks.pattern`: Some actions run.
- `checks.template`: it is skipped
- `checks.fields`: it is skipped
When the checks are disabled, it appears a message for each one of them.
- The check of template and index pattern known fields now depends on the app configuration (`checks.template` and `checks.fields`).
- Added messages for when the `checks.pattern`, `checks.template` and `checks.fields` are disabled.
- Fixed typo related to the know fields
- Added `checks.fields` to the default app configuration file
- Tests with …

[FIX] [HEALTH CHECK] Run `template` and `fields` checks depends on the app configuration

---

CHANGELOG.md
public/components/common/hooks/use-es-search.ts

This PR fixes the aggregation tables in `Modules/<Module>/Panel` are not updated when the time filter is changed
- Added the `timeFilter` as dependency to update the data
- With alerts data about the module, go to `Modules/<Module>/Panel` (currently only the Office 365 and GitHub modules have this tab) and change the time filter, the displayed data should change according to the time range selected.
Closes #3789

[FIX] [Modules] [Panel] Update aggregation data when the time filter is changed

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

Fixed the rendering component problem of `EuiCodeBlock` when displaying the command to deploy a new Windows agent.
- Set `powershell` as the language that is a valid value for the versions of `@elastic/eui` used by Kibana 7.10.2 (`highlithg.js ^9.18.5`) to Kibana 7.16.2 (`refractor ^3.5.0`)
- Go to deploy new Windows agent and see the command is highlighted and the view is displayed correctly for Kibana 7.10.2-7.16.x
> For Kibana 7.16.x, we should move this change to its development branch
Closes #3752

[FIX] Component rendering of command to deploy new Windows agent

---

CHANGELOG.md
public/controllers/agent/components/agents-preview.scss
public/controllers/agent/components/register-agent.js
public/styles/dark_theme/wz_theme_dark.scss

Hi team, 
this PR enhances the user experience when trying to copy an agent install code block. Also warns the user that the Windows script must be run in a PowerShell terminal.
Closes #3762 
- This should be tested with different browsers.

Enhance agent deployment UI

---

CHANGELOG.md
public/components/add-modules-data/sample-data.tsx
server/controllers/wazuh-elastic.ts

Hi team.
This PR change the user used to manage sample data indexes.
Closes #3611

Changed user for sample data management

---

CHANGELOG.md
public/components/common/hooks/use-value-suggestion.ts
public/react-services/saved-objects.js

Hi team,
this PR fixes multi-select filters failing to get suggested values due to the index pattern not having **attribute.fields** property.
Closes #3779 
To test it: 
- Go to Github and/or Office365 module
- See each multi-select filter suggest values and apply selected filters

Github/Office365 multi-select filters fix to get suggested values

---

CHANGELOG.md
public/components/management/groups/multiple-agent-selector.tsx

Hi team,
this PR fixes the disabled Add agent button when a single agent is selected in `7.16.1`
Closes #3761 
To test it try to add and remove a single agent to a group.

Fix add single agent to group

---

CHANGELOG.md
public/components/common/modules/modules-helper.js

This PR hides the button of filters to remove them from the search bar.
- Use `x.meta.value` as function instead of use the implementation of `toString` when interpolating the value of `x.meta.value`
- Go to `Modules/Office 365/Panel` or `Modules/GitHub/Panel` and access a drill-down view. A new filter will be added with the accessed value, the button to remove the filters should not be visible
Closes #3769

[FIX] [Modules] Avoid the implicit filters can be removables

---

CHANGELOG.md
public/components/common/modules/panel/components/module-side-panel.tsx

Hi team,
this PR fixes styling and the collapsible navbar close button issue when the side panel tab is clicked.
Closes #3768 
To test it:
- Click on the side panel tab
- See a flyout open with additional module information

Fixed Office365/Github module the side panel tab

---

CHANGELOG.md
public/components/overview/mitre_attack_intelligence/resources.tsx

This PR fixes the problem with the wrapping text in the MITRE ATT&CK intelligence table
- Removed the `truncateText` prop of `Descrition` table column.
- Go to `Modules/MITRE ATT&CK/Intelligence and see the `Description` column wraps the text.
Closes #3767

[FIX] [MODULES] [MITRE ATT&CK] [Intelligence] Wrap text in the `Description` column for the resources info table

---

CHANGELOG.md
public/styles/7.9.0/index.dark.scss
public/styles/7.9.0/index.light.scss

Hi team,
This PR fixes visualizations tooltip styles to adjust its width when hovering charts.
Closes #3755 
To test it, try to reproduce the mentioned issue in all main browsers (including Safari).

Fixed visualization echTooltip position

---

CHANGELOG.md
public/controllers/management/components/management/configuration/registration-service/registration-service.js
public/controllers/management/components/management/configuration/util-components/configuration-settings-group.js

This PR adds some settings related to the `auth.force` to the `Registration service` of `Management/Configuration` section
- Go to `Management/Configuration/Registration service and review the new settings are displayed as expected when are defined.
Related to #3597

[FEAT]: Add new options of auth for the Registration service configuration

---

CHANGELOG.md
public/controllers/management/components/management/groups/actions-buttons-main.js
public/controllers/management/components/management/groups/group-agents-table.js

This PR fixes the next things:
- Added a toast message when there is an error creating a new group in `Management/Groups`
- Don't display the remove button in the table of agents for a group
- `default` group:
- another group:
1. Go to `Management/Groups`. Click on the `Add new group` button and write an invalid name. Click on the `Save new group` button and a toast message should be displayed with the error.
2. Go to `Management/Groups`. Click on the `default` group and see the remove button is not displayed for the agent's table. Create a custom group, add some agents and review the agent's table for the group and should have the remove button.
Closes #3802 #3803

[FIX] [GROUPS] Fixes creating a new group with invalid name and no display the remove button in the agents table for the `default` group

---

CHANGELOG.md
kibana.json
package.json
public/assets/custom-style.js

Summary
---------
[This is a feature for Cloud / SaaS]
This PR changes the Home link URL in the navigation drawer with the Wazuh App URL, instead of the Kibana's Home page.
To test
----------
1. Check that the link redirects to `/app/wazuh` and not to `/app/home`.

Override the navigation drawer `Home` link behaviour

---

CHANGELOG.md
package.json
server/lib/security-factory/security-factory.ts

Hi team,
this PR fixes a rejected request to know if x-pack is active. Now it tolerates the internal user not having the resource permission and contemplates this error.
Closes #3829 
To test it
- Setup an internal user in kibana.yml which causes a 403 error in a `GET /_security/user` request 
- Make sure you login without errors
- Go to `Wazuh menu -> Security -> Role mapping` and create a new role mapping without errors
- Go to `Wazuh menu -> Modules -> Security events` and create a PDF report 
- Check the PDF report was properly created

Fix internal xpack user request forbidden

---

CHANGELOG.md
public/controllers/agent/components/register-agent.js

This PR adds a step to the deploy new agent guide to starting the agent on Windows.
- Added the step to start the agent for the Windows guide
- Reduced the vertical space to the info callout of installing the Windows agent
- Review the step to start the agent is displayed for the Windows OS
Closes #3843

[FEAT] [Deploy agent guide] Add step to start the agent on Windows

---

CHANGELOG.md
public/controllers/agent/components/agents-preview.js
public/styles/common.scss

Hi Team,
This PR resolves a wrong width from the agent's details card. 
Because of that, In some resolutions, the agent's evolution visualization is off the screen.
Closes #3837

Fixed agents details card style
